main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

Remove code linked to repository from the processor selection

fix(TESB-21702) Fix route generation

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_process_properties.javajet

https://jira.talendforge.org/browse/TDI-40329
https://jira.talendforge.org/browse/TDI-40329

fix(TDI-40329): Constant String too long due to a large schema

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/MavenGroupIdProjectSettingPageTester.java

missing documentation for user

workitem(TUP-19959):Wrong content for CI project settings on TOS and

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java

TESB-21791:cConfig - Upload Libraries does not work

---

main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_begin.javajet

https://jira.talendforge.org/browse/TDI-36516
After adding quotes to table name, job executes as expected

fix(TDI-36516): add quotes to table name

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobJavaScriptsManager.java

TESB-21799: Fixed cmdline missing beans error with ref project

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java

TESB-21810:Module tab shows the incorrect list of installed jar files

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/JobSettingsView.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java

This reverts commit 889dde20c867ac87667987c3675c3fc9faeb04d7.

Revert "fix(TESB-21830) : fixed deployment tab on Services (#2210)"

---

main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_begin.javajet

For JIRA: https://jira.talendforge.org/browse/TDI-40271

fix(TDI-40271):  tMomInput is not retrieving USR properties and JMS headers from IBM MQSeries

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java

https://jira.talendforge.org/browse/TUP-4096

fix(TUP-4096)[tOracleInput] "Guess schema" uses wrong "Connection type" when using tOracleConnection

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java

Need to merged with 
https://github.com/Talend/tcommon-studio-se/pull/1631
https://github.com/Talend/tcommon-studio-ee/pull/676

upgrade tcompv1 version to 0.0.6

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java

Need to be merged after 
https://github.com/Talend/tdi-studio-se/pull/2220
This PR contains a fix of dynamic values in closed list

integrate enum (closed list) display name

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
main/plugins/org.talend.designer.dbmap/src/main/java/messages.properties
main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/DbMapComponent.java
main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java
main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarOutputZone.java

https://jira.talendforge.org/browse/TUP-19961

fix(TUP-19961): tELTMSSqlInput component does not support the schema with a DB-column name having Degree symbol in it

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java

https://jira.talendforge.org/browse/TUP-19604
Upper the priority display of full matched component family.

fix(TUP-19604)Issue about studio palette

---

main/plugins/org.talend.designer.components.localprovider/components/tMDMBulkLoad/tMDMBulkLoad_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_begin.javajet

TMDM-11954 [Backport] MDM transaction does not commit when multiple tMDMOutput used in same subjob

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModel.java

https://jira.talendforge.org/browse/TUP-20006

fix(TUP-20006): TaCoKit config version is stored in a wrong place

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet

https://jira.talendforge.org/browse/TDI-40318
https://jira.talendforge.org/browse/TDI-40318

fix(TDI-40318): fix FTP permission issue for tFTPPut component sftp mode

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/build/StandardJobOSGiBundleBuildProvider.java

Add tREST component in OSGi build type validation

TESB-21576: Add tREST component in OSGi build type validation

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java

chore: bump Tacokit version to 0.0.9

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java

fix(TUP-19820):The joblet input row issue

---

main/plugins/org.talend.designer.components.localprovider/components/tMomInput/tMomInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_begin.javajet

For JIRA: https://jira.talendforge.org/browse/TDI-39817

feat(TDI-39817):Restrict number of messages in websphere in tMomInput Component

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TUP-19732

Kjwang/fix(tup 19732)joblet not being called after elt components

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/dnd/GenericDragAndDropHandler.java
main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/dnd/JSONDragAndDropHandler.java

https://jira.talendforge.org/browse/TUP-19974

Kjwang/fix(tup 19974)opening a job takes more than half an hour in studio

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/JobSettingsView.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java

deployment tab not shown when a service or its child is selected in the repository
deployment tab is now shown, read only.

fix(TESB-21830) : deployment tab not shown when selecting service

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java

https://jira.talendforge.org/browse/TUP-19974

fix(TUP-19974)Opening a job takes more than half an hour in studio

---

main/plugins/org.talend.designer.components.localprovider/components/tJMSInput/tJMSInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tJMSOutput/tJMSOutput_java.xml

https://jira.talendforge.org/browse/TDI-40451

fix(TDI-40451):remove the default module of tJMSXXX components.

---

main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_main.javajet

https://jira.talendforge.org/browse/TDI-40458

fix(TDI-40458):compile error dynamic schema with identity tsybaseOutput

---

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet

Job compile errors
Revert the commit

TESB-20335: revert for Job compile errors

---

main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/ConnectionManager.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/utils/problems/ProblemsAnalyser.java

https://jira.talendforge.org/browse/TUP-20027

fix(TUP-20027)Error opening job: Unhandled event loop exception (java.lang.StackOverflowError)

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/dialog/MapReducePropertySetDialog.java

streaming jobs
https://jira.talendforge.org/browse/TUP-20041

feat(TUP-20041)Propagate Smart tMap Initative to Spark and Spark

---

main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlBulkExec/tPostgresqlBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlInput/tPostgresqlInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlRow/tPostgresqlRow_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCD/tPostgresqlSCD_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCDELT/tPostgresqlSCDELT_java.xml

https://jira.talendforge.org/browse/TDI-40455
Driver for prior v9 versions was updated to latest version

fix(TDI-40455): change driver for prior v9 versions

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/DirectoryController.java

https://jira.talendforge.org/browse/TUP-18661
https://jira.talendforge.org/browse/TUP-18661

fix(TUP-18661):Errors on component.

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/LibraryField.java

TESB-22034: Fix handling of non-required bean libs in route builds

---

main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_main.javajet

* fixed String value of array in case class attribute is set to array
String representation of array value does not display the content of the array.
Changed String representation of array in case user specified class attribute and set it to array.

fix(TDI-37800): tWriteJsonField handle Arrays

---

main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/AbstractDBInputEnd.javajet

Appeared issue with missing isClosed method in some old drivers.
https://jira.talendforge.org/browse/TDI-36564
Remove isClosed condition.

fix(TDI-36564): remove condition for isClosed

---

main/plugins/org.talend.designer.components.localprovider/components/tNormalize/tNormalize_main.javajet

https://jira.talendforge.org/browse/TDI-33629

fix(TDI-33629): tNormalize support context.

---

main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlBulkExec/tPostgresqlBulkExec_begin.javajet

https://jira.talendforge.org/browse/TDI-40484
FileReader was closed

fix(TDI-40484): FileReader was closed

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet

https://jira.talendforge.org/browse/TDI-40318
https://jira.talendforge.org/browse/TDI-40318

fix(TDI-40318): Talend FTP permission issue

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet

https://jira.talendforge.org/browse/TDI-40488
Check column existance before writing schema.

fix(TDI-40488): Incoming schema enforcer throws NPE when schema is different

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewSalesforceMigrationTask.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewSalesforceMigrationTask.properties

For JIRA: https://jira.talendforge.org/browse/TDI-40443
* set default value true when migration old framework jobs

fix(TDI-40443): add check to control tsalesforceinput bulk mode all return null for empty value

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

fix(TUP-19815)For can't find process

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/language/java/JavaLanguage.java
test/plugins/org.talend.designer.mapper.test/src/org/talend/designer/mapper/language/java/JavaLanguageTest.java

figures+full width underscore
https://jira.talendforge.org/browse/TUP-19999

fix(TUP-19999)column cannot be mapped when column name is Half-width

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet

Not possible to create multiple directories using tFTPPut in SFTP mode
Is possible to create multiple directories using tFTPPut in SFTP mode

fix(TDI-40474): Make it possible to create multiple dirs in tFTPPut SFTP

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java

https://jira.talendforge.org/browse/TBD-6701
ON condition in tELTHiveMap join is working.

fix(TBD-6701): Fix condition left join on for tELTHiveMap

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java

https://jira.talendforge.org/browse/TBD-6701
ON condition in tELTHiveMap join is working.

fix(TBD-6701): Fix condition left join on for tELTHiveMap (#2301)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/MainComposite.java

https://jira.talendforge.org/browse/TUP-20144

fix(TUP-20144): UI:String "Modification" can not show completely even max the window

---

main/features/org.talend.rcp.branding.tos.test.feature/feature.xml
main/plugins/org.talend.designer.xmlmap/src/main/java/org/talend/designer/xmlmap/util/XmlMapConnectionBuilder.java

Only check if can build connection for input tables if the index is big than current one.

fix(TUP-19943):Generated schema miss some fields while import xsd

---

main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/repository/utility/SQLBuilderRepositoryNodeManager.java

https://jira.talendforge.org/browse/TUP-20133

fix(TUP-20133): Edit queries does not display the "SQL Builder" window in some conditions.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeActivateStatusElementCommand.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/Connection.java

fix(TUP-20021):Deactive component will change the execution order

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java

feat(TESB-22105) CI for ESB Services

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericElementParameter.java

https://jira.talendforge.org/browse/TDI-40487

fix(TDI-40487):NPE with Netsuite dev Account.

---

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/handler/GenericRepositoryContentHandler.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizard.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/util/GenericConnectionUtil.java

https://jira.talendforge.org/browse/TUP-20124

fix(TUP-20124): NPE during changing TCOMP component repository value

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendWizardProjectsImportPage.java

https://jira.talendforge.org/browse/TUP-20138
https://jira.talendforge.org/browse/TUP-20138

fix(TUP-20138):Importing projects with "Copy projects into workspace" unchecked copies the project to a temporary folder.

---

main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_finally.javajet
main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_main.javajet

https://jira.talendforge.org/browse/TDI-40512
Fix missing resourse release.

fix(TDI-40512): add release resources for VerticaOutput and JavaDBOutput

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/JobSettingsView.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java

https://jira.talendforge.org/browse/TESB-21830
deployment tab is shown when service is selected, read only.

fix(TESB-21830): deployment tab not shown

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/EscapeQuoterForTNormalize.java

https://jira.talendforge.org/browse/TDI-33629

fix(TDI-33629):Migration Task for tNormalize.

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/MemoryRuntimeComposite.java

https://jira.talendforge.org/browse/TUP-18501

fix(TUP-18501)Modify the confusing message

---

main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_main.javajet

https://jira.talendforge.org/browse/TDI-40522
https://jira.talendforge.org/browse/TDI-40522

fix(TDI-40522): tAS400Output return wrong NB_line with BatchSize

---

main/features/org.talend.tos.components.feature/feature.xml

* split logic of components on definition and runtime

feat(TDI-40477): Split Snowflake components

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

:Fail to build Rest Service job as microservice for NPE
Fixed the NPE

fix(TESB-22267):Fail to build Rest Service job as microservice for NPE

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/EditProcess.java

https://jira.talendforge.org/browse/TUP-20166

fix(TUP-20166): Studio "Attempted to beginRule: F/.Java/src/main/java, does not match outer scope rule" Error

---

test/plugins/org.talend.designer.mapper.test/src/org/talend/designer/mapper/utils/problems/ProblemsAnalyserTest.java
test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/ui/ProcessErrorUtilTest.java

org.talend.designer.mapper.utils.problems.ProblemsAnalyserTest.testCheckLookupTablesKeyProblems
org.talend.designer.mapper.utils.problems.ProblemsAnalyserTest.testGetLookupTableProblem
org.talend.designer.runprocess.ui.ProcessErrorUtilTest.testGetAllErrorMess

fix junit failure

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/OpenExistVersionProcessWizard.java

link: https://jira.talendforge.org/browse/TMDM-12082
Throwing "java.lang.ClassCastException" while open and create another version MDM Object from MDM repository view
Create MDM Object wither new version successfully.

TMDM-12082  Error while creating new version and open

---

main/plugins/org.talend.designer.components.localprovider/components/tXMLMap/tXMLMap_begin.inc.javajet
main/plugins/org.talend.designer.components.localprovider/components/tXMLMapOut/tXMLMapOut_begin.javajet

https://jira.talendforge.org/browse/TDI-39874
https://jira.talendforge.org/browse/TDI-39874

fix(TDI-39874): Numeric.sequence increments by 2 instead of  1 in tXMLMap

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

fix(TESB-22267):Add binary setting as build for micrsoervice

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

TESB-22085:Dynamic schema column type is always String in Runtime

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/ConnectionManager.java

https://jira.talendforge.org/browse/TUP-20199

TUP-20199 Studio is way too slow when branching 2 ways with if condition

---

main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/batchExecute.javajet

https://jira.talendforge.org/browse/TDI-40522
https://jira.talendforge.org/browse/TDI-40522

fix(TDI-40522):reuse the common batch execute javajet

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_main_odata.javajet

https://jira.talendforge.org/browse/TDI-40521
We can send a byte[] into a Edm/String. It will be encoded to base 64

fix(TDI-40521) : Encode to base64 byte[]->String (#2346)

---

main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/SetQueryName.javajet

https://jira.talendforge.org/browse/TBD-6923
Error does not appear

fix(TBD-6923): Fix hive.query.name param for Hive components

---

main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/SetQueryName.javajet

https://jira.talendforge.org/browse/TBD-6923

fix(TBD-6923): Fix using hive query name

---

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsProviderManager.java
main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsService.java

module protobuf-java-2.6.1.jar

fix(TUP-20210):Strange behavior on component tNLPModel for required

---

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsProviderManager.java
main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsService.java

Reverts Talend/tdi-studio-se#2384

Revert "fix(TUP-20210):Strange behavior on component tNLPModel for required"

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/TableEntriesManager.java
main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/managers/TableEntriesManager.java

https://jira.talendforge.org/browse/TUP-20156

fix(TUP-20156): Cannot open the tMap component, throwing 'An SWT error has occured'.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java

job
https://jira.talendforge.org/browse/TUP-19603

fix(TUP-19603)Suffix number is not proper when drag DB connection to a

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractValueSelectionController.java

adds Abstract controller for value selection widgets. This controller may be extended by multiple concrete controllers (like FileController, FolderController etc). This controller is needed for TacokitValueSelectionController
https://jira.talendforge.org/browse/TCOMP-842

feat(TCOMP-842): implement AbstractValueSelectionController

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModel.java

Fix NPE during testing connection in DragAndDropHandler
https://jira.talendforge.org/browse/TCOMP-865

fix(TCOMP-865): fix NPE when not Tacokit connection is checked

---

test/plugins/org.talend.designer.mapper.test/src/org/talend/designer/mapper/utils/problems/ProblemsAnalyserTest.java
test/plugins/org.talend.designer.scd.test/src/main/java/org/talend/designer/scd/ScdComponentServiceTest.java

solve some junit failure

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java

revert fix(TUP-19603)Suffix number is not proper when drag DB connection

---

main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/actions/GenerateDocAsHTMLAction.java

fix(TUP-20258):"Generate Doc As HTML" Item Does not Exist for BD

---

main/plugins/org.talend.libraries.custom/build.properties

https://jira.talendforge.org/browse/TDI-40162
https://jira.talendforge.org/browse/TDI-40162

fix(TDI-40162): remove the plugin.xml include statement

---

main/plugins/org.talend.libraries.custom/build.properties
main/plugins/org.talend.libraries.custom/plugin.xml

https://jira.talendforge.org/browse/TDI-40162
https://jira.talendforge.org/browse/TDI-40162

Revert "fix(TDI-40162): remove the unnecessary talend-codegen-utils.jar register for runtime(#2002)"

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml

https://jira.talendforge.org/browse/TDI-40460
Version of slf4j was corrected.

fix(TDI-40460): change slf4j version

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java

https://jira.talendforge.org/browse/TUP-20053

fix(TUP-20053): Cannot run MapR 6.0 DI job with tSqoopImportAllTables

---

main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/MainComposite.java

name in JobletView
https://jira.talendforge.org/browse/TUP-20231

fix(TUP-20231)Update Detection won't popup after updating it's joblet

---

main/plugins/org.talend.sbi.engines.client/plugin.xml
main/plugins/org.talend.sbi.engines.client/src/messages.properties
main/plugins/org.talend.sbi.engines.client/src/org/talend/sbi/engines/client/ui/preferences/SpagoBiPreferencePage.java
main/plugins/org.talend.spagic.engines.client/plugin.xml
main/plugins/org.talend.spagic.engines.client/src/main/java/org/talend/spagic/engines/client/ui/preferences/SpagicPreferencePage.java

feat(TUP-20277):Deprecated items on 7.1

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/ImportProjectAsWizardPage.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendWizardProjectsImportPage.java

https://jira.talendforge.org/browse/TUP-20303

fix(TUP-20303)project folder name not correct in workspace after import using "Import an existing project"

---

main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet

https://jira.talendforge.org/browse/TDI-40645

fix(TDI-40645): driver name was uppercased

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/build/StandardJobStandaloneBuildProvider.java
main/plugins/org.talend.repository/src/main/java/messages.properties
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/extrachecker/LimitRESTRequestJobChecker.java

TESB-22487:OSGI Bundle should be exported when using ESB components

---

main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/snowflake/unifier.json

* registered tSnowflakeOutputBulkExec as unified tDbOutputBulkExec
Need to register new component in unifier
New component is added to appropriate unifier

feat(TDI-40427): Duplicate of tSnowflakeOutput

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java

TESB-22106:CI for ESB - Data Services and Routes - On Prem - Part 2

---

main/plugins/org.talend.designer.components.localprovider/components/tSortIn/tSortIn_begin.javajet

https://jira.talendforge.org/browse/TDI-30055
https://jira.talendforge.org/browse/TDI-30055

fix(TDI-30055): Clear memory for tSort asap

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/OpenExistVersionProcessWizard.java

fix(TUP-20261):Routine editor mixed the code

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

TUP-20346:Preview in Metadata File fails with NullPointerException

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/NodeQueryCheckUtil.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/properties/NodeQueryCheckUtilTest.java

https://jira.talendforge.org/browse/TUP-20312
https://jira.talendforge.org/browse/TUP-20312

fix(TUP-20312):java.lang.StackOverflowError in 6.5.1 studio.

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

https://jira.talendforge.org/browse/TUP-20319

fix(TUP-20319): Cloud Studio can't retrieve any project from TMC

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

lost many mappings due to name change
https://jira.talendforge.org/browse/TUP-20333

fix(TUP-20333)When upgrading from Talend v5.6.1 to v6.4.1, the tmap has

---

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java

https://jira.talendforge.org/browse/TUP-20309

TUP-20309 - integrate after group code part for tacokit

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java

https://jira.talendforge.org/browse/TUP-20292

feat(TUP-20292): Support hive metastore HA (wizard)

---

main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_main.javajet

https://jira.talendforge.org/browse/TCOMP-897

fix(TCOMP-897) : fix guess schema with bulk logic for processors

---

main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRListInstances/tAmazonEMRListInstances_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRResize/tAmazonEMRResize_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/tSQSConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageChangeVisibility/tSQSMessageChangeVisibility_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageDelete/tSQSMessageDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueCreate/tSQSQueueCreate_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueDelete/tSQSQueueDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueList/tSQSQueueList_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSQSQueuePurge/tSQSQueuePurge_java.xml

https://jira.talendforge.org/browse/TDI-40679
https://jira.talendforge.org/browse/TDI-40679

fix(TDI-40679): align to httpclient-4.5.5,httpfluent-4.5.5 and httpcore-4.4.9

---

main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutputBulk/tVerticaOutputBulk_main.javajet

https://jira.talendforge.org/browse/TDI-40688
https://jira.talendforge.org/browse/TDI-40688

fix(TDI-40688): tVerticaOutput in Copy mode: Nullable Float-values are rounded to the nearest integer

---

main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastLoad/tTeradataFastLoad_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastLoad/tTeradataFastLoad_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastLoad/tTeradataFastLoad_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastLoadUtility/tTeradataFastLoadUtility_main.javajet
main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddDbMappingTTeradataFastLoadMigrationTask.java

* Add db type to tTeradataFastLoad
* Add Date,Timestamp and Time handling to tTeradataFastLoad
* Fix tTeradataFastLoadUtility

fix(TDI-40641): tTeradataFastLoad select DB Type

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet

https://jira.talendforge.org/browse/TDI-40546
FileNames checked correctly

fix(TDI-40546): Fix String comparing

---

main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_main.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_process_data_begin.javajet
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/AbstractConnectorCreator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/ProcessorConnectorCreator.java

https://jira.talendforge.org/browse/TUP-20352

TUP-20352 : handle condional outputs for tacokit components

---

main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet

https://jira.talendforge.org/browse/TDI-34091
To config file cid was added

fix(TDI-34091): add cid to name of config file

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModel.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/command/AsyncAction.java

https://jira.talendforge.org/browse/TUP-20402

fix(TUP-20402): fix TaCoKit drag&drop problem, and dialog popup position problem

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml

get by build job which not check "Items" also can not run

TDQ-15215:standard job tRulesurvivorship can not run on TIC, zip file

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml

TDQ-15215:standard job tRulesurvivorship can not run on TIC, zip file get by build job which not check "Items" also can not run

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java

TUP-20407 : update tacokit version to 1.0.2-SNAPSHOT

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UnifyPasswordEncryption4ContextMigrationTask.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UnifyPasswordEncryption4DBConnectionMigrationTask.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UnifyPasswordEncryption4ItemMigrationTask.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UnifyPasswordEncryption4ParametersInJobMigrationTask.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UnifyPasswordEncryption4ProjectSettingsMigrationTask.java

https://jira.talendforge.org/browse/TUP-20391

fix(TUP-20391): Migration tasks are re-executed and encrypting passwords

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java

https://jira.talendforge.org/browse/TCOMP-904

TCOMP-904 : fix job classpath for tacokit components

---

main/plugins/org.talend.designer.codegen/jet_stub/subprocess_header.javajet

TDQ-15455 Compile error after refactoring job (#2433)

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

TESB-22602:CI for ESB - Data Services and Routes - Part 3

---

main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/SetQueryName.javajet

Duplicate variable error.
No compile error.

fix(TBD-7296): Fix duplicate variable (#2499)

---

main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/SetQueryName.javajet

Duplicate variable error.
No compile error.

fix(TBD-7296): Fix duplicate variable

---

main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_begin.javajet

Need to be merged after https://github.com/Talend/component-runtime/pull/270

TCOMP-903 : remove unused attributes

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/StatLogsAndImplicitcontextTreeViewPage.java

https://jira.talendforge.org/browse/TUP-20140

fix(TUP-20140)Checked status of items listed in Project Settings

---

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_java.xml
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

https://jira.talendforge.org/browse/TUP-20385

fix(TUP-20385)Run job with using dynamic tRunJob throw compile error

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

See TUP-20433
- [ X] Bugfix
- [ X] No

TUP-20433 - tHMap throw npe when connect to output but haven't config it

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java

https://jira.talendforge.org/browse/TUP-20091
https://jira.talendforge.org/browse/TUP-20091

fix(TUP-20091):teltmssqlmap: show alias for columns from a middle table.

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java

https://jira.talendforge.org/browse/TUP-20364
https://jira.talendforge.org/browse/TUP-20364

fix(TUP-20364):Audit can't set database "H2 Local","H2 Remote" when studio logon on git remote mode.

---

main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHBulkExec/tSQLDWHBulkExec_begin.javajet

feat(TDI-40559): Fix appName parameter in jdbc url

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobJavaScriptsWSManager.java

fix(TUP-20438) fix export with war for tdm

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/audit/AuditManager.java

https://jira.talendforge.org/browse/TUP-20361
https://jira.talendforge.org/browse/TUP-20361

fix(TUP-20361):the report path is not correct.

---

main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_main.javajet

fix(TBD7343): tHiveRow compile error

---

main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_begin.javajet
main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_main.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
main/plugins/org.talend.sdk.component.studio-integration/messages.properties
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/AbstractConnectorCreator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/TaCoKitNodeConnector.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java

Fix guess schema (force maxbatchSize to 1) and handle null values
Fix multischema connector creation
To be merged adter https://github.com/Talend/component-runtime/pull/272
https://jira.talendforge.org/browse/TUP-20427

TUP-20427 : integrate maxBatchSize from component model

---

main/plugins/org.talend.designer.components.localprovider/components/tMysqlClose/tMysqlClose_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlCommit/tMysqlCommit_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlInput/tMysqlInput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlRollback/tMysqlRollback_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/AbstractDBInputBegin.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/AbstractDBOutputFinally.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet

https://jira.talendforge.org/browse/TDI-40760
https://jira.talendforge.org/browse/TDI-40760

fix(TDI-40760): Error Connecting Aurora database using existing connection

---

main/plugins/org.talend.designer.components.localprovider/components/tJMSInput/tJMSInput_finally.javajet

https://jira.talendforge.org/browse/TDI-40757
https://jira.talendforge.org/browse/TDI-40757

fix(TDI-40757): Fix Job compilation error related to tJMSInput component

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/imports/ImportItemUtil.java

https://jira.talendforge.org/browse/TUP-20448

TUP-20448 exception show in error log when i export a job contain connection then import it again

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java

chore: bump tacokit version to 1.0.3

---

main/plugins/org.talend.designer.components.localprovider/components/tJMSOutput/tJMSOutput_finally.javajet

https://jira.talendforge.org/browse/TDI-40757
https://jira.talendforge.org/browse/TDI-40757

fix(TDI-40757): fix the tjmsoutput

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/CheckElementParameter.java

* Convert Object to boolean for CheckElementParameter on update

fix(TCOMP-921): boolean fields in tables

---

main/plugins/org.talend.designer.components.localprovider/components/tMysqlClose/tMysqlClose_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlCommit/tMysqlCommit_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlInput/tMysqlInput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlRollback/tMysqlRollback_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/AbstractDBInputBegin.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/AbstractDBOutputFinally.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet

https://jira.talendforge.org/browse/TDI-40760
https://jira.talendforge.org/browse/TDI-40760

fix(TDI-40760): add more condition to fix the stats and logs issue

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJobUtil.java

Tests fails because of NPE 
Tests passes

fix(TESB-22628): fixed NPE during test execution

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizardPage.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/dnd/GenericDragAndDropHandler.java

getting "UNEXPECTED_EXCEPTION" upon selecting the same connection
created.

fix(TUP-20492):When doing extract as context for a tsalesforceinput,

---

main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet

https://jira.talendforge.org/browse/TDI-39567
Improve formatting

fix(TDI-39567): add tabs / improve code redability

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/DebouncedParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/Metadatas.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActionParametersUpdater.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/PropertyValidator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ValidationListener.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/SuggestionsResolver.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/ValidationResolver.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/listener/ValidationListenerTest.java

This work still having issue with Tables
https://jira.talendforge.org/browse/TUP-20482

TUP-20482 : active if with new legth strategy for comparing values.

---

main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/snowflake/unifier.json

* registered new components in unifier
New components must be registered as unified DB components.
New components are registered in unifier.

feat(TDI-40574): tSnowflakeOB and tSnowflakeBE

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_process_data_begin.javajet

* all tcomp v0 components with reject should have same issue.
For JIRA: https://jira.talendforge.org/browse/TDI-40815

fix(TDI-40815): Compilation issue with tSalesforceOutput component with reject link

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/SuggestionsResolver.java

Default value is set to Suggestions action parameter
https://jira.talendforge.org/browse/TCOMP-961

fix(TCOMP-961): set default value to SuggestionsAction parameters

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/JavaProcessUtilTest.java

Additional libraries defined for CMessagingEndpoint components can be set as part of the bundle classpath, i.e. physically included, or as OSGi dependency. This fix ensures that these libraries are no longer physically included if not set as part of the bundle classpath.
TESB-22826 - additional libs are always added physically to bundle causing class loading issues under OSGi.
Additional libs are handled correctly as OSGi dependencies when they are not marked as part of the bundle classpath.
If this PR contains a breaking change, please …

fix(TESB-22826): Handling of cMessagingEndpoint additional libraries in OSGi.

---

main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/HTMLDocGenerator.java

missing in other than English
https://jira.talendforge.org/browse/TUP-20369

fix(TUP-20369)Mapper/Metadata tables for tMap in HTML document are

---

main/plugins/org.talend.designer.components.localprovider/components/tSCPFileExists/tSCPFileExists_main.javajet

https://jira.talendforge.org/browse/TDI-40833?
https://jira.talendforge.org/browse/TDI-40833?

fix(TDI-40833): tSCPFileExists not working with wildcard

---

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/util/GenericContextUtil.java

https://jira.talendforge.org/browse/TUP-20512
https://jira.talendforge.org/browse/TUP-20512

fix(TUP-20512)Metadata JDBC DB Connections Bug with context variables

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java

fix(TESB-22825): Compile source before compute the manifest

---

main/plugins/org.talend.designer.components.localprovider/components/tELTMap/tELTMap_messages.properties

For https://jira.talendforge.org/browse/TDI-40840

fix(TDI-40840):Remove "JDBC" from parameter "ELT JDBC Map Editor" in tELTMap

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/SetupProcessDependenciesRoutinesAction.java

Enable "Edit routine dependencies" popup menu for routes.

[TESB-22901] cMap with user defined code routine failing in ESB runtime

---

main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_main.javajet

https://jira.talendforge.org/browse/TDI-34861
Wrong counter value for nb_line
Fix with proposed solution in jira and retest it.

fix(TDI34861): fix nb_line counter

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/ActionParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/Metadatas.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/SuggestionsResolver.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/resolver/SuggestionsResolverTest.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/test/TestComponent.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/resources/suggestions.json

Suggestions action parameters were mapped to ElementParameter without respect to order in method declaration, which cause bugs in some cases.
Suggestions action parameters were mapped to ElementParameter with respect to order in method declaration
https://jira.talendforge.org/browse/TCOMP-960

fix(TCOMP-960): fix suggestions parameters mapping

---

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml

https://jira.talendforge.org/browse/TDI-40722

fix(TDI-40722):restore the origin logic of import xstream.jar

---

main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml

https://jira.talendforge.org/browse/TDI-40806
https://jira.talendforge.org/browse/TDI-40806

fix(TDI-40806): use mulit copy only when file larger than 5gb

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/src/main/java/org/talend/database/exasol/imp/EXABulkUtil.java
main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_begin.javajet

https://jira.talendforge.org/browse/TDI-34814
Wrong behaviour of number formatter
Fix hasGroups functionality

fix(TDI-34814): improve number formatter in exa

---

main/plugins/org.talend.designer.components.localprovider/components/tServiceNowInput/tServiceNowInput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tServiceNowInput/tServiceNowInput_main.javajet

https://jira.talendforge.org/browse/TDI-40825

fix(TDI-40825):Provide clear errorMessage for tServiceNow.

---

main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet

https://jira.talendforge.org/browse/TDI-39279
commitCounter_<%=cid%> variable was updated.
I reproduced bug, and test it locally. Works good.

fix(TDI-39279): update commitCounter for end part

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/OutgoingDynamicSchemaEnforcer.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
main/plugins/org.talend.libraries.custom/pom.xml

https://jira.talendforge.org/browse/TDI-40858
https://jira.talendforge.org/browse/TDI-40858

fix(TDI-40858): fix the tcompv0 dynamic type performance issue with studio

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/OutgoingDynamicSchemaEnforcer.java

https://jira.talendforge.org/browse/TDI-40858
https://jira.talendforge.org/browse/TDI-40858

fix(TDI-40858): fix the unstable format as different OS(different row separator) and fix the format for the java file

---

main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_begin.javajet

https://community.talend.com/t5/Troubleshooting-Internal/How-to-use-a-proxy-when-using-quot-Google-Storage-quot/ta-p/116965
proxy workaround for tGSConnection after  TBD-5415
make proxy workaround can work as before.

fix(TDI-40854): tGSConnection proxy workaround can't work from 7.0.1

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

gchore: upgrade tacokit version to 1.0.5-SNAPSHOT

---

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml

https://jira.talendforge.org/browse/TDI-40775
Change version of commons-lang3 jar

fix(TDI-40775): version of commons-lang3 now 3.7

---

main/plugins/org.talend.designer.oas/.classpath
main/plugins/org.talend.designer.oas/.project
main/plugins/org.talend.designer.oas/META-INF/MANIFEST.MF
main/plugins/org.talend.designer.oas/build.properties
main/plugins/org.talend.designer.oas/plugin.properties
main/plugins/org.talend.designer.oas/plugin.xml
main/plugins/org.talend.designer.oas/pom.xml
main/plugins/org.talend.designer.oas/schema/org.talend.designer.oas.OASDecoder.exsd
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/WsToolsExtensionsPlugin.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/EESBMediaType.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/ETranslationStatus.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/IOASDecoder.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/OASDecoderFactory.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/RestAPIMapping.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/TranslationException.java

New plugin adding an extension point to provide OAS swagger 2.0 decoders.
- [X ] Feature
- [X ] No

TESB-22605 Moving OAS tools from tesb projects to tdi projects

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml

Version of CXF 3.2.4
Newest version of CXF 3.2.6

feat(TDI-40828): upgrade cxf library to newest one

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

fix(TESB-23217):MicSvc pom for REST type is generated wrong when

---

main/plugins/org.talend.designer.components.localprovider/components/tSetKeystore/tSetKeystore_main.javajet

HostNameVerifier interface was implemented for new JSSE
Catch old implementation to prevent runtime error.

feat(TDI-40829): fix hostname verifier interface

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java

fixing tacokit module compilation

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

https://github.com/Talend/tdi-studio-se/pull/2593

fix(TBD-7495): Add checkbox to transform date type in timestamp (#2593)

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddSchemaDatePatternUseForImpalaTask.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

https://github.com/Talend/tdi-studio-se/pull/2593

fix(TBD-7495): Add checkbox to transform date type in timestamp (#2593) 

---

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/CamelEndpointBuilder.java

TESB-21633:The URI of the cREST component is not correct

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/pom.xml
main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_java.xml

https://jira.talendforge.org/browse/TDI-40917
Version of EXABulkUtil was updated

 fix(TDI-40917): update version of EXABulkUtil

---

main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_messages.properties

https://jira.talendforge.org/browse/TDI-40806
https://jira.talendforge.org/browse/TDI-40806

fix(TDI-40806): adjust the ui label and exception information to make it more clear

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java

very bad performances on cConfig component : https://jira.talendforge.org/browse/TESB-22547
performances back to usual, only when modules are not installed there is still a little delay due to git fetch. 

fix(TESB-22547): call saveCustomMavenURIMap only once.

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

fix(TUP-20661):Cannot create preview delimited file for NPE

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/condition/ConditionGroup.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListenerTest.java

Conditional fields using tacokit are always using a "AND" operator between conditions
OR operator is supported

[TCOMP-1013] starting to wire the new condition API

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/IncomingSchemaEnforcerTest.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
main/plugins/org.talend.libraries.custom/plugin.xml
main/plugins/org.talend.libraries.custom/pom.xml

* Fix timezone problems for date fields
* Bump version

fix(TDI-40868): incorrect dates inserted Snowflake

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/Lookups.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/debounce/DebounceManager.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/debounce/DebouncedAction.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListenerTest.java

[TCOMP-1029] adding contains as strategy for conditional rendering

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-httputil/pom.xml

fix(TBD-7422): upgrade tDataPrepRun jar Studio 7.0

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-httputil/pom.xml

fix(TBD-7422): upgrade tDataPrepRun jar

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java

artifact in reference project
Add fully esb components in the list

fix(TESB-22874):Fix to genreate bundle resources for OSGi bundle type

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

fix(TBD-7596): Migrate to Timestamp format instead of Date

---

main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForBulk.javajet
main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/saphana/unifier.json

https://jira.talendforge.org/browse/TDI-40745
https://jira.talendforge.org/browse/TDI-40745

fix(TDI-40745): fix the table exists issue

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

fix(TBD-7596): Migrate to Timestamp format instead of Date (#2656)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java

fix(TUP-20511)Need to limit the number of entry on the

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractValueSelectionController.java

allows to configure Text control editability in common parent Controller class
https://jira.talendforge.org/browse/TCOMP-1047

fix(TCOMP-1047): allow to configure Value Selection Text control

---

main/plugins/org.talend.designer.xmlmap/src/main/java/org/talend/designer/xmlmap/MapperComponentDocumentation.java

fix(TUP-20570):Documentation for tXMLMap does not show the mapping

---

main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/actions/OpenNewEditorAction.java
main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLBuilderDialog.java

Null pointer exception when trying to edit query by double-clicking query in Repository View
https://jira.talendforge.org/browse/TUP-20634

fix(TUP-20634)Null pointer exception when trying to edit query by double-clicking query in Repository View

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/OutgoingSchemaEnforcer.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/OutgoingDynamicSchemaEnforcerTest.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/OutgoingSchemaEnforcerTest.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
main/plugins/org.talend.libraries.custom/plugin.xml
main/plugins/org.talend.libraries.custom/pom.xml

* Fix Date conversion in IncomingSchemaEnforcer
* Fix tests
* Bump talend-codegen-utils lib version

fix(TDI-40994): SnowflakeInput incorrect date

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml

fix(TESB-23376):Runtime cannot install REST artifact because redundant '-bundle' in features

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

fix(TBD-7670): Remove DQ components from migration task

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

fix(TBD-7678): Migrate tMatchModel (#2682)

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet

no info about studio version in tcomp components
added information about studio version to global map

feat(TDI-40535): track application in snowflake

---

main/plugins/org.talend.repository/src/main/java/messages.properties
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java

https://jira.talendforge.org/browse/TUP-20678

feat(TUP-20678): Add APAC datacenter to the list on the studio (license / connection)

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
main/plugins/org.talend.libraries.custom/plugin.xml
main/plugins/org.talend.libraries.custom/pom.xml

https://jira.talendforge.org/browse/TDI-40875

feat(TDI-40875): bumped codegen-utils to 0.25.3

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet

Compile error in tFTPPut when use `create dir if not exist`
No compile error in tFTPPut when use `create dir if not exist`

fix(TDI-40965): Fix compile error in tFTPPut

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet

Code generates for SOCKS proxy when existing connection used
No code generates for SOCKS proxy when existing connection used

fix(TDI-40963): Disable codegen for unused socks proxy

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

feat(TDQ-15611) Add tDataShuffling/tMatchPairing/tMatchPredict/tMatchModel to this migration

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java

feat(TDQ-15611) Add tDataShuffling to this migration

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet

https://jira.talendforge.org/browse/TDI-40875
cast as Object for primitive boxing

fix(TDI-40875): cast as Object for primitive boxing

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/HealthCheckResolver.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/GuessSchemaSelectionAdapter.java

CSV was used to comminicate the schema
JSON is used

guess schema now uses json in tacokit

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet

Full file info is not working for SFTP
Full file info is working for SFTP

fix(TDI-41043): SFTP tFTPFileList full file info fix

---

main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_begin_for_processor.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_inputs.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_outputs.javajet
main/plugins/org.talend.sdk.component.studio-integration/pom.xml

**DO NOT MERGE BEFORE IVAN REVIEW** 
https://jira.talendforge.org/browse/TCOMP-1063

TCOMP-1063 : integrate Record API from tacokit to the studio

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java

console incorrectly displaying ESB endpoint if using absolute url
url correctly displayed

fix(TESB-23560) : display correct url in console for ESB implementations

---

main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_begin.javajet

https://jira.talendforge.org/browse/TDI-40790
https://jira.talendforge.org/browse/TDI-40790
improve the performance a lot especially for large file

fix(TDI-40790): improve the s3 get performance and retry way

---

main/plugins/org.talend.designer.components.localprovider/components/tELTMap/tELTMap_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet

https://jira.talendforge.org/browse/TDI-40720
https://jira.talendforge.org/browse/TDI-40720

fix(TDI-40720): support tSAPHanaConnection work with tELTMap

---

main/plugins/org.talend.designer.components.localprovider/components/tHiveIn/tHiveIn_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_main.javajet

Adding more detailed information like job name, tags etc. for qubole hive job.
Components included:
- tHiveInput
- tHiveRow
Relates to
https://github.com/Talend/tbd-studio-se/pull/867
https://github.com/Talend/tbd-studio-ee/pull/639

feat(TBD-7591) Add job name & tags for qubole hive components

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/HealthCheckResolver.java

https://jira.talendforge.org/browse/TCOMP-1082

fix(TCOMP-1082): fix ActionParameter conversion issue for HealthCheck

---

main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_messages.properties
main/plugins/org.talend.libraries.excel/.classpath
main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
main/plugins/org.talend.libraries.excel/lib/.gitignore
main/plugins/org.talend.libraries.excel/pom.xml

For https://jira.talendforge.org/browse/TDI-39059
add a new checkbox "Include phonetic runs"

feat(TDI-39059):tFileInputExcel support includePhoneticRuns configurable

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java

Launcher
bat & sh are exported to zip if I select Unix for Shell Launcher
when I select Unix for Shell Launcher
just sh is exported
- [* ] Bugfix
- [* ] No

bugfix(TUP-7208):bat & sh are exported to zip if I select Unix for Shell

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java

It excludes schema parameter from the list of possible roots in metadata persisted configuration
https://jira.talendforge.org/browse/TCOMP-1104

fix(TCOMP-1104): fix drad and drop issue

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/command/AsyncAction.java

ensure a shell is passed to the openinfo/openerror

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java

TESB-23695
URL does not contains multiple backslash anymore

fix(TESB-23695) : filter multiple backslash in url

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml

https://jira.talendforge.org/browse/TDI-41119
Fix condition for requiring edtftpj library.

fix(TDI-41119): add more condition to use edtftpj library

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java

exclude schema parameter from persistance
https://jira.talendforge.org/browse/TCOMP-1105

fix(TCOMP-1105): do not persist schema parameter

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java

resource dependency only
https://jira.talendforge.org/browse/TUP-20789

feat(TUP-20789)Remove the dependencies page and use context view for

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

chore: upgrade Tacokit version to 1.1.0 release

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ArtifactRepositoryShareSettingPage.java

https://jira.talendforge.org/browse/TUP-20854

fix(TUP-20854): NPE show in error log when add reference project

---

main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveOutputBulkExec/tSalesforceWaveOutputBulkExec_java.xml

https://jira.talendforge.org/browse/TDI-40958
- update jars to 44.0
- update default endpoint to 43.0 (44.0 can't be test at present)

feat(TDI-40958): update salesforce api to 43.0

---

main/plugins/org.talend.designer.components.localprovider/components/tIterateToFlow/tIterateToFlow_java.xml

Useless default value was set (without cid)
No default value set

fix(TDI-31285): Remove needless default value

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml

Missing fix on Studio 7.0
Backport fix of https://jira.talendforge.org/browse/TDI-41119

fix(TDI-41119): add more condition to use edtftpj library (#2748)

---

main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet

https://jira.talendforge.org/browse/TDI-41063
Counting logic was changed

fix(TDI-41063): change count NB lines logic

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

fix(TUP-20799):vaidation rule do not work for mssql and oracle

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java

https://jira.talendforge.org/browse/TUP-20796

fix(TUP-20796): [bug] there are errors after click Property Type: repository button to choose db

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

fix(TUP-20716):Could not find or load main class while running a big job

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java

bugfix(TUP-20711)Cannot "Guess schema" with tSQLDWHInput

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java

bugfix(TUP-20711)Cannot "Guess schema" with tSQLDWHInput (#2780)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/DesignerCoreService.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java

https://jira.talendforge.org/browse/TUP-20284

fix(TUP-20284)Import Items throw errors

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java

wrong sql
right sql
- [* ] Bugfix
- [ *] No

bugfix(TUP-20479):ELT Maps generate incorrect SQL

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java

used for any column in the source table
wrong sql query
right sql query
- [* ] Bugfix

bugfix(TUP-20739):tELTHiveMap generates wrong query when the operator is

---

main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveOutputBulkExec/tSalesforceWaveOutputBulkExec_java.xml

https://jira.talendforge.org/browse/TDI-40958
default endpoint version to 44.0

feat(TDI-40958): update salesforce default endpoint to 44.0

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

upgrade tacokit to 1.1.1

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java

https://jira.talendforge.org/browse/TUP-20522
https://jira.talendforge.org/browse/TUP-20522

fix(TUP-20522):Cannot use 'Generate Audit Report' on Ubuntu.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/ProjectSettingManager.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/ImplicitContextLoadHelper.java

settings_Implicit context load_ From database
https://jira.talendforge.org/browse/TUP-20805

fix(TUP-20805)NPE thrown when click Project settings_Job

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java

https://jira.talendforge.org/browse/TUP-20910
Value is set only if index is available

fix(TUP-20910) : Set value only if index is acceptable

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/update/TaCoKitCarFeature.java

https://jira.talendforge.org/browse/TUP-20875

fix(TUP-20875): Components Manager: errors when do cancel the install patch/components

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ProjectRefSettingPage.java

https://jira.talendforge.org/browse/TUP-20887

Fix (TUP-20887) Sub-reference project is listed in Reference Project

---

main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml

https://jira.talendforge.org/browse/TDI-41177

fix(TDI-41177): Remove SSO condition for redshift component

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java

https://jira.talendforge.org/browse/TUP-20919
https://jira.talendforge.org/browse/TUP-20919

fix(TUP-20919):The inprogress bar do not show correctly when we do generate audit report.

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet

fix(TDI-41043): SFTP tFTPFileList full file info fix Backport to 7.0

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet

fix(TDI-41043): SFTP tFTPFileList full file info fix Backport to 6.4

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet

fix(TDI-41043): SFTP tFTPFileList full file info fix/Backport to 6.3

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet

fix(TDI-41043): SFTP tFTPFileList full file info fix (#2723)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

fix(TUP-20799):Oracle Invalid Character with tSchemaComplianceCheck

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java

https://jira.talendforge.org/browse/TUP-20981

Fix : TUP-20981 Build job will pop up LifecyclePhaseNotFoundException using installer on windows 10

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractGuessSchemaProcess.java

https://jira.talendforge.org/browse/TUP-20980
https://jira.talendforge.org/browse/TUP-20980

fix(TUP-20980):tMysqlInput --> "Guess schema" not show the warning message.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java

fix(TBD-7781): Support retrieving node from SparkConfiguration

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet

feat(TBD-7689): support Standard SQL in BigQueryUtil

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ProjectRefSettingPage.java

https://jira.talendforge.org/browse/TUP-20887

Revert "Fix (TUP-20887) Sub-reference project is listed in Reference Project

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml

fix(TESB-23792): Build data service failed in studio

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java

fix(TUP-21010):Jar name on classpath should be based on mvn uri

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java

* fix(TUP-21010):Jar name on classpath should be based on mvn uri
* fix(TUP-21010):Jar name on classpath should be based on mvn uri

fix(TUP-21010):Jar name on classpath should be based on mvn uri (#2832)

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java

fix(TESB-23721):ESB Conductor can not pick artifacts by CI for ESB

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java

messages checking
https://jira.talendforge.org/browse/TUP-20927

fix(TUP-20927)Automatic scrolling in execution console prevent upper log

---

main/plugins/org.talend.sdk.component.studio-integration/.classpath

chore: resolve tacokit sdk plugin compile error in eclipse

---

main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/ui/wizards/NewRouteResourceWizardPage.java

https://jira.talendforge.org/browse/TUP-20905

bugfix(TUP-20905)Edit resource wizard show "Ok" when open the page.

---

main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/ui/wizards/NewRouteResourceWizardPage.java

Reverts Talend/tdi-studio-se#2851

Revert "bugfix(TUP-20905)Edit resource wizard show "Ok" when open the page."

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java

https://jira.talendforge.org/browse/TUP-21039

fix(TUP-21039): "Apply context to children jobs" does not work for "grand son" job if Studio not restarted

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java

getting applied to the jobs
https://jira.talendforge.org/browse/TUP-20778

fix(TUP-20778)Reference  Project - New context group variable not

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java

generated code error
generated code 
- [* ] Bugfix
- [ *] No

bugfix(TUP-20693):Table selection widget - wrong generated code

---

main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton

SQL Time with Java date can't be null 
SQL Time with Java date can be null 

fix(TDI-41276): Use correct SQLType for null Time

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet

https://jira.talendforge.org/browse/TDI-41162
If File detail is checked CURRENT_FILEPATH global variable don't hold details now. 

fix(TDI-41162): correct file detail for FTP and FTPs mode

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java

bugfix(TUP-20693):Table selection widget - wrong generated code
- [ *] Bugfix
- [* ] No

bugfix(TUP-20693):Table selection widget - wrong generated code (#2818)

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java

fix(TUP-21005)In studio Java Debugging of Routes fails

---

main/plugins/org.talend.designer.components.localprovider/components/tLogRow/tLogRow_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tLogRow/tLogRow_main.javajet

https://jira.talendforge.org/browse/TDI-32967

fix(TDI-32967):tLogRow length do not support context

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml

fix(TPS-2771)Correct survivorship rules path

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/dnd/GenericDragAndDropHandler.java
main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/dnd/JSONDragAndDropHandler.java

studio (#2232)
* fix(TUP-19974)Opening a job takes more than half an hour in studio
https://jira.talendforge.org/browse/TUP-19974
* fix(TUP-19974)Opening a job takes more than half an hour in studio
https://jira.talendforge.org/browse/TUP-19974
Conflicts:
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/dnd/GenericDragAndDropHandler.java
If this PR contains a breaking change, …

Kjwang/fix(tup 19974)opening a job takes more than half an hour in

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/dnd/GenericDragAndDropHandler.java

* bugfix(TUP-20837):Job containing saleforce components takes too much
time to open
- [* ] Bugfix
- [* ] No

Hwang/tup 20837 master (#2859)

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java

fix(TUP-21005)In studio Java Debugging of Routes fails (#2869)

---

main/plugins/org.talend.repository/src/main/java/messages.properties
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/ConfigExternalJarPage.java

https://jira.talendforge.org/browse/TUP-20413
Remove the button of reload the library

fix(TUP-20413)Reload the library will throw NPE in import external jar.

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

fix(TUP-20765)"Web-app Url" is read-only and empty after clicking "+";

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

fix(TUP-20675)"Web-app Url" is read-only and empty after clicking "+";

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaActionParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaElementParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java

* Add schema action parameter
* Add schema element parameter
* Set schema name equal to parameter name
* Set connection type as tagged value

fix(TUP-21026): empty schema in suggestable method

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java

https://jira.talendforge.org/browse/TUP-21054
https://jira.talendforge.org/browse/TUP-21054

fix(TUP-21054):Jars from db wizard not synchronized with component.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateDetectionDialog.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java

bugfix(TUP-21030):Components don't change to Built-in mode

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateDetectionDialog.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java

* bugfix(TUP-21030):Components don't change to Built-in mode
- [* ] Bugfix
- [ *] No

bugfix(TUP-21030):Components don't change to Built-in mode (#2879)

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/tabs/TabFolderEditors.java

https://jira.talendforge.org/browse/TUP-21075

fix(TUP-21075)Problem of display in the tMap with Mojave

---

main/plugins/org.talend.designer.runprocess/plugin.properties
main/plugins/org.talend.designer.runprocess/src/main/java/messages.properties

fix(TUP-21022)Project Setting->Shell Setting ->Ps1: unfriendly (#2904)

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/tabs/TabFolderEditors.java

* fix(TUP-21075)Problem of display in the tMap with Mojave
https://jira.talendforge.org/browse/TUP-21075
* fix(TUP-21075)use duplicate name for jdbc connection, no error show
https://jira.talendforge.org/browse/TUP-21075
* fix(TUP-21075)Problem of display in the tMap with Mojave
https://jira.talendforge.org/browse/TUP-21075

fix(TUP-21075)Problem of display in the tMap with Mojave (#2900)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UseOracle11VersionInsteadOfRemoved.java

Error appear for tCreateTable with existing connection

fix(TDI-41320): Fix oracle 11 migration task use existing connection

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/migration/TaCoKitMigrationManager.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitService.java

https://jira.talendforge.org/browse/TUP-21055

fix(TUP-21055)Migration check executed at each start of studio

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java

https://jira.talendforge.org/browse/TUP-20514
https://jira.talendforge.org/browse/TUP-20514

fix(TUP-20514):Project setting-Aduit can not save the db info if switch to another type of db.

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/build/TestProcessor.java

JOB_GN_SFDC_LANCEUR_FLUX_DELTA_REG14.

fix(TUP-20979):OutOfMemoryError error when do build job

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java

https://jira.talendforge.org/browse/TUP-21054
https://jira.talendforge.org/browse/TUP-21054

fix(TUP-21054):backport to 7.1

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UseOracle11VersionInsteadOfRemoved.java

Backport https://github.com/Talend/tdi-studio-se/pull/2902

fix(TDI-41320): Backport Fix oracle 11 migration task use existing connection

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java

bugfix(TUP-21058):Snowflake ELTJDBCInput/Output

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
main/plugins/org.talend.designer.codegen/jet_stub/header.javajet

TESB-24093
context parameter overriding is now working correctly

TESB-24093 : context values can be overriten by MS.

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/DiSchemaConstants.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/OutgoingSchemaEnforcer.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/OutgoingDynamicSchemaEnforcerTest.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/OutgoingSchemaEnforcerTest.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
main/plugins/org.talend.libraries.custom/plugin.xml
main/plugins/org.talend.libraries.custom/pom.xml

https://jira.talendforge.org/browse/TDI-41188
https://jira.talendforge.org/browse/TDI-41188

fix(TDI-41188): map Snowflake Time type to Talend Date instead of Talend Integer

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

fix(TESB-22833): Compile route before generate manifest

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ConnectionUtil.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/ConnectionUtilTest.java

https://jira.talendforge.org/browse/TUP-21044
https://jira.talendforge.org/browse/TUP-21044

fix(TUP-21044);JDBC driver changed when load JDBC-Mysql8 to "Project Setting ---> Job setting ---> Stats&Logs".

---

main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/component/DelegateComponent.java

Japanese(just DelegateComponent fixed)

fix(TUP-21049)can't find other database in default list with Chinese and

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/dnd/CompleteDropTargetTableListener.java

https://jira.talendforge.org/browse/TUP-21075

fix(TUP-21075)Problem of display in the tMap with Mojave (#2943)

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java

the top when the gap is too small
https://jira.talendforge.org/browse/TUP-21161

Fix(TUP-21161)can't use the up-arrow button or scroll bar to locate at

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

fix(TESB-22833): Fixed packages not allowed: java.util" problem

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java

https://jira.talendforge.org/browse/TDI-31797

fix(TDI-31797):Basic Run button donnot work

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
main/plugins/org.talend.designer.codegen/jet_stub/header.javajet

TESB-24093 : context values can be overriten by MS. 

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet

THIS PR IS CREATED TO SIMPLIFY REVIEW OF https://github.com/Talend/tdi-studio-se/pull/2914

fix(TUP-20926): add Input schema value to Configuration in runtime

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

https://jira.talendforge.org/browse/TUP-21148

fix(TUP-21148)Can't save the changes of Connections

---

main/features/org.talend.repository.feature/feature.xml

https://jira.talendforge.org/browse/TUP-21137

Fix : TUP-21137 Security: jtds-1.3.1-patch.jar ntlmauth loaded from a path variable

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/StatsAndLogsManager.java

https://jira.talendforge.org/browse/TUP-21160

fix(TUP-21160):JDBC connection will not commit even if autocommit i set to True.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/StatsAndLogsManager.java

https://jira.talendforge.org/browse/TUP-21160

fix(TUP-21160):JDBC connection will not commit even if autocommit is set to True

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/StandAloneTalendJavaEditor.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/SaveAsRoutineWizard.java

https://jira.talendforge.org/browse/TUP-21064

fix(TUP-21064)NPE happens when 'save as' routine

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/StandAloneTalendJavaEditor.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/SaveAsRoutineWizard.java

fix(TUP-21064)NPE happens when 'save as' routine
https://jira.talendforge.org/browse/TUP-21064

fix(TUP-21064)NPE happens when 'save as' routine (#2934)

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java

Map components and is not separated with string concat from SQL code
- [* ] Bugfix
- [ *] No

bugfix(TUP-21164):Context is not recognized as context variable in ELT

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/CodeView.java

job editor closed
- [ *] Bugfix
- [ *] No

bugfix(TUP-21118):Code view/test case still link last component even all

---

main/plugins/org.talend.designer.xmlmap/src/main/java/org/talend/designer/xmlmap/XmlMapService.java
main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep1Form.java
main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep2Form.java

fix(TUP-21145)use equals instead

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/service/GenericService.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ComponentListController.java
test/plugins/org.talend.designer.core.generic.test/src/main/java/org/talend/designer/core/generic/service/GenericServiceTest.java

* bugfix(TUP-21105):tDBConnection(Snowflake) issue within joblet.
* bugfix(TUP-21105):tDBConnection(Snowflake) issue within joblet.
- [* ] Bugfix
- [ *] No

Hwang/tup 21105 t db connection (#2953)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java

fix(TUP-21094)Job can not be run after the first time I set tELTMap and

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTestHelper.java

* bugfix(TUP-21164):Context is not recognized as context variable in ELT
Map components and is not separated with string concat from SQL code
- [ *] Bugfix
- [ *] No

Hwang/tup 21164 (#3004)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

fix(TESB-22833):CI builder NoClassDefFoundError error with routelet

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

https://jira.talendforge.org/browse/TUP-21149

feat: upgrade Tacokit runtime to 1.1.2

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

modification in the main job in the same component

fix(TUP-21252):tMap losing all links in testcase when we do some

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java

https://jira.talendforge.org/browse/TUP-21216

bugfix(TUP-21216):Audit:Generate Report:NPE when do refresh

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java

https://jira.talendforge.org/browse/TUP-21109

feat(TUP-21109): Deprecate build of sources from Build job menu

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java

https://jira.talendforge.org/browse/TUP-21126

fix(TUP-21126)Not able to use routines from Reference project

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/StatsAndLogsManager.java

https://jira.talendforge.org/browse/TUP-21160
https://jira.talendforge.org/browse/TUP-21160

fix(TUP-21160):refix JDBC connection will not commit even if autocommit is set to True.

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/service/GenericService.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java

bugfix(TUP-21105):tDBConnection(Snowflake) issue within joblet.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateContextParameterCommand.java

https://jira.talendforge.org/browse/TUP-21042
https://jira.talendforge.org/browse/TUP-21042

fix(TUP-21042):Edit and update the used context group, will show double value and context view vanish

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/StatsAndLogsManager.java

https://jira.talendforge.org/browse/TUP-21160
https://jira.talendforge.org/browse/TUP-21160

fix(TUP-21160):refix JDBC connection will not commit even if autocommit is set to True

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java

fix(TUP-21326)Guess Schema has error if use existing connection in Joblet

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewJDBCConnectionMigrationTask.java

6.4.1 to 7.1.1
https://jira.talendforge.org/browse/TUP-21245

fix(TUP-21245)faile to check JDBC connection with context Migrate from

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ListPropertyNode.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyDefinitionDecorator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java

Normally no behavior change but ensure we have a list for everything layout related instead of a Set which can easily break some logic relying on that

layout should rather use list than set, ensure it is typed on the code

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtilTest.java

if its name contains uppercase letter
https://jira.talendforge.org/browse/TUP-21138

fix(TUP-21138)Ubuntu18: Resources: Job which uses Resources run failed

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeJobsettingDBversionForMssqlMigrationTask.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdateELTComponentMigrationTask.java

bugfix(TUP-21134):"Throw an error if the file already exist" is ticked

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/BigDataJobUtil.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java

when spark job launched from standard job by jobserver
https://jira.talendforge.org/browse/TUP-21356?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

bugfix(TUP-21356):"talend-bigdata-launcher-1.2.0-20170410.jar" not found

---

main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/src/main/java/org/talend/archive/IntegrityUtil.java
main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
main/plugins/org.talend.libraries.custom/pom.xml

* Use apache commons compress in checkArchive lib

fix(TDI-41469): tFileUnarchive zip64 format error

---

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionControllerTest.java

add junit for(TUP-2136)

---

main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PerformancePreferencePage.java

https://jira.talendforge.org/browse/TUP-21321
https://jira.talendforge.org/browse/TUP-21321

fix(TUP-21167):Install Additional Packages has no available modules.

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/ConfigExternalJarPage.java

https://jira.talendforge.org/browse/TUP-21461

fix(TUP-21461): Routine libraries can't be updated to pom.xml of routine in special case

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java

switch different job on job editor
https://jira.talendforge.org/browse/TUP-21336

bugfix(TUP-21336): Run view console result is not synchronized when I

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java

fix(TUP-21396)keeping popup for running a job after adding a var in CONEXT GROUP

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java

fix(TUP-21396)keeping popup for running a job after adding a var in context group

---

main/features/org.talend.rcp.branding.tos.test.feature/feature.xml

https://jira.talendforge.org/browse/TUP-21119

feat(TUP-21119): Cleanup features, each plugin must be in one unique feature

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/BigDataJobUtil.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java

"talend-bigdata-launcher-1.2.0-20170410.jar" not found when spark job
launched from standard job by jobserver (TBD-7933)
https://jira.talendforge.org/browse/TPS-2794

fix(TPS-2794):[7.0.1][20181221]

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml

fix(TBD-8144): fix for 404 error in tBigQueryInput

---

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/DataNodeTest.java

https://jira.talendforge.org/browse/TUP-21333

fix(TUP-21333)OnSubJob Links Not Working

---

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/DataNodeTest.java

https://jira.talendforge.org/browse/TUP-21333

fix(TUP-21333)OnSubJob Links Not Working (#3079)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateNodeParameterCommand.java

incorrectly to any following component
Change to repository schema used in tMap propagated incorrectly to any following component
- [* ] Bugfix
- [* ] No

bugfix(TUP-21330):Change to repository schema used in tMap propagated

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java

default even without activating in the Project Setting
- [* ] Bugfix
- [ *] No

bugfix(TUP-20663):tAccessOutputBulkExec/tAccessBulkExec are visible at

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java

https://jira.talendforge.org/browse/TUP-21474

fix(TUP-21474): Facing issue while accessing joblet present on job in main project

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java

Reverts Talend/tdi-studio-se#3094

Revert "bugfix(TUP-21330):Change to repository schema used in tMap propagated"

---

main/plugins/org.talend.designer.runprocess/src/main/java/messages.properties
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/ShadowProcess.java

fix(TUP-21439)Preview error. Some settings must be changed

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TUP-21425

fix(TUP-21425)Job built in 7.0.1 not working in 7.1.1

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TUP-21425

fix(TUP-21425)Job built in 7.0.1 not working in 7.1.1 (#3106)

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/sdk/WsdlTokenManager.java
main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/ui/edit/Schema2XMLLinker.java
main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToXPathLinker.java

https://jira.talendforge.org/browse/TUP-21263

TUP-21263 Consider setting the secure processing feature on XPathFactory instances

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet

https://jira.talendforge.org/browse/TDI-31569

fix(TDI-31569):specify identity column don't work for dynamic

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/dialog/ListStringValueDialog.java

showing complete view
https://jira.talendforge.org/browse/TUP-21564

bugfix(TUP-21564):tMap settings - the "Options" window pop-up not

---

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_begin.javajet

https://jira.talendforge.org/browse/TDI-41556
Backport to 7.1

fix(TDI-41556): Redshift driver name was changed (Backport to 7.1) (#3096)

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

Upgrade tacokit runtime to 1.1.4

feat: upgrade Tacokit version to 1.1.4

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java

GIT mode
https://jira.talendforge.org/browse/TUP-19978

fix(TUP-19978)It is very slow to delete many items at the same time on

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java

propagated
- [* ] Bugfix
- [ *] No

bugfix(TUP-21331):Change between repository schemas for tMap output not

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java

https://jira.talendforge.org/browse/TUP-19463

fix(TUP-19463)extend display of groupId in job > deployment sub-tab

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java

https://jira.talendforge.org/browse/TUP-21648
https://jira.talendforge.org/browse/TUP-21648

fix(TUP-21648):tJDBCSCDELT table list cannot be retrieved.

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet

https://jira.talendforge.org/browse/TDI-31569

fix(TDI-31569):keep the old behavior of tMssqloutput

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java

https://jira.talendforge.org/browse/TUP-20508
https://jira.talendforge.org/browse/TUP-20508

fix(TUP-20508):Audit: Generating cannot be finished and canceled after 30 mins.

---

main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_begin.javajet

* Fix problem when check zip integrity and die on error are both checked

fix(TDI-41469): check zip integrity die on error

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AbstractVersionManagementProjectSettingPage.java

settings-version management/status management.
- [* ] Bugfix
- [* ] No

bugfix(TUP-17933):Errors when select testcase in project

---

main/plugins/org.talend.designer.components.libs/libs_src/soap/src/main/java/org/talend/soap/SOAPUtil.java

https://jira.talendforge.org/browse/TUP-21251

workItem(TUP-21251):Replace com.sun.org.apache.xerces.internal.jaxp

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/SetupProcessDependenciesRoutinesAction.java

dependencies are not generated)
- [* ] Bugfix
- [* ] No

bugfix(TUP-20768):Test Case's build failed (user defined routine

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_main.javajet

no transaction management
transaction management has been added

feat(TDI-41405): add transaction management

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java

TESB-24596:Docker Support for Microservice - Publish to Docker Registry
Route and REST for MS docker image

TESB-24596:Docker Support for Microservice - Publish to Docker Registry

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet

…put with int type not nullable

fix(TBD-8242): Compilation error for tFileInputDelimited/tFixedFlowInput with int type not nullable

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

Missing commits from patch/7.1.1_TESB-24058 to patch/7.1.1 
fix patch branch

Merging missing fix from old patch branch

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

characters for the password
https://jira.talendforge.org/browse/TUP-2382

fix(TUP-2382):The Connection Window should NOT show the exact number of

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

https://jira.talendforge.org/browse/TUP-21143

workItem(TUP-21143):Generate random value for null password hiding code

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_main.javajet

feat(TDI-41405): add transaction management (#3177). Revert

---

main/plugins/org.talend.repository.ftp/src/org/talend/repository/ftp/ui/wizards/forms/FTPForm.java
main/plugins/org.talend.repository.ftp/src/org/talend/repository/ftp/ui/wizards/pags/FTPPage.java

fix(TUP-21836)Display of SFTP Metadata

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/SqlMemoController.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SetContextModeForQueryMigrationTask.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

Ttao/work item/tup 21143 generate random value for null password hiding code

---

main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/pom.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
main/plugins/org.talend.designer.components.localprovider/pom.xml

fix(TDI-41678): Upgrade custom lib version to avoid compile error

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/MavenVersionManagementProjectSettingPage.java

with testcase.
- [* ] Bugfix
- [ *] No

bugfix(TUP-18054):Deployment Version:array icon should be moved for job

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericElementParameter.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericTableUtils.java
main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/DBDynamicComposite.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/DynamicComposite.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizardPage.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericDialog.java

fix(TUP-21505)be able to save jdbc connection even test fail

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java

is used in MSSQL Connection in Studio
- [* ] Bugfix
- [ *] No

bugfix(TUP-21711):Incorrect DataType retrieved when guess schema option

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java

Ttao/backport 7.0/tup 20927 automatic scrolling in execution console log

---

main/plugins/org.talend.repository.ftp/src/org/talend/repository/ftp/ui/wizards/forms/FTPForm.java
main/plugins/org.talend.repository.ftp/src/org/talend/repository/ftp/ui/wizards/pags/FTPPage.java

fix(TUP-21836)Display of SFTP Metadata (#3201)

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8260): compile error for tBigQueryOutput

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/BigDataJobUtil.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java

"talend-bigdata-launcher-1.2.0-20170410.jar" not found when spark job launched from standard job by jobserver

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet

fix(TBD-8301) : Use Regional Location for BigQuery datasets

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet

fix(TBD-8301) : Use Regional Location for BigQuery datasets (#3228)

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

Error was fixed for one component, but still present when multiple
components were used.
Changed the <%cid%> to <%=cid%>

fix(TBD-8299): Compile error on BigQuery Component

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AutoUpdateRelationsMigrationTask.java

https://jira.talendforge.org/browse/TUP-21888
https://jira.talendforge.org/browse/TUP-21888

fix(TUP-21888):NPE when importing job.

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericTableUtils.java

opening job migrated 6.4.1 to 7.1.1 (job using tJDBCInput)
- [* ] Bugfix
- [ *] No

bugfix(TUP-21895):An error has occurred. UNEXPECTED_EXCEPTION when

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/extrachecker/LimitESBConsumerJobChecker.java

https://jira.talendforge.org/browse/TESB-24959
None

TESB-24959:Error message when building Data Service as Docker Image with tRESTClient component

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

fix(TUP-21958)No Warning sign on different 'Nullable' checkbox state

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UseOracle11VersionInsteadOfRemoved.java

for patch https://jira.talendforge.org/browse/TPS-2903

fix(TDI-41320): Fix oracle 11 migration task use existing connection (#2902) (#2933)

---

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/model/migration/NewSalesforceWizardMigrationTask.java

fix(TUP-21849)Salesforce name was changed while it is being edited for spec

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

fix(TUP-21994)error occurred when open a job from di side

---

main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton

https://jira.talendforge.org/browse/TDI-41517
Teradata manager was updated with new types and now sets to PreparedStament AsciiStream for CLOB and BinaryStream for BLOB

fix(TDI-41517): Manager was updated with Object type

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

https://jira.talendforge.org/browse/TESB-25024

TESB-25024:cTalendJob with job could not be build as OSGi bundle

---

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/DBDynamicComposite.java

fix(TUP-21998)JDBC Connection doesn't work well

---

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizard.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/common/GenericWizardPage.java

fix(TUP-5535)rename salesforce connection,the new name can't be reload

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

token will all open the same url.
https://jira.talendforge.org/browse/TUP-22063

fix(TUP-22063)[bug] when use different cloud type,click ... to fetch

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java

fix(TUP-22066)Font color in Run console is black, it should be blue

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/java/TalendJavaSourceViewer.java

fix(TUP-22062)Error pops up when typing tJava in job editor

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

fix(TUP-22103): Fixed joblet running error with default processor

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet

fix(TBD-8356): tBigqueryOutput handles empty strings as null

---

main/plugins/org.talend.rcp.branding.tos/plugin.xml

fix(TUP-21733)Fix Help About string missing

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java

component
- [* ] Bugfix
- [ *] No

bugfix(TUP-21944):Problem with globalMap.get in tELTOracleOutput

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

fix(TUP-21983): fixed Compile failed for MSESB_IMAGE type

---

main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tOracleInput/tOracleInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_java.xml
main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
main/plugins/org.talend.designer.components.localprovider/components/templates/slowly_change_dimension.skeleton

feat(TDI-41807): add rules for oracle 12/18

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java

Endpoint displayed in console when running a route in Studio is sometimes wrong (when using context variables for example).
Now code replaces context variables with appropriate values and add default endpoint URI if missing. The displayed endpoint in console is more reliable.

fix(TESB-24920) (#3286)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java

https://jira.talendforge.org/browse/TUP-21777
https://jira.talendforge.org/browse/TUP-21777

fix(TUP-21777):[7.0.1] Metadata Wizard with SSL cannot retrieve cluster settings.

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java

bugfix(TUP-21944):Problem with globalMap.get in tELTOracleOutput #3261

---

main/plugins/org.talend.designer.components.localprovider/components/tNetezzaNzLoad/tNetezzaNzLoad_begin.javajet

When `show command` is selected - password is printed as clear text
Password in console replaced with asterisks

fix(TDI-41808): Fix showing pass as clear text NZLoad

---

main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendProcessJavaProject.java

https://jira.talendforge.org/browse/TUP-21920

fix(TUP-21920) Nullpointer on build job

---

main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendProcessJavaProject.java

fix(TUP-21920) Nullpointer on build job (#3266)

---

main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_main.javajet

Compile error when 2 tELTOracleOutput in one job
No compile error

fix(TDI-41897): Fix compile error on generated code

---

main/plugins/org.talend.repository/src/main/java/messages.properties
main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/sandboxProject/CreateSandboxProjectDialog.java

https://jira.talendforge.org/browse/TUP-21495
https://jira.talendforge.org/browse/TUP-21495

feat(TUP-21495):Support MFA on studio for the Cloud. (#3253)

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RedshiftLogFileMigrationTask.java

https://jira.talendforge.org/browse/TDI-41789

fix(TDI-41789): Redshift change migration logic

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/DataProcessTest.java

group variable set for connection type Oauth.
https://jira.talendforge.org/browse/TUP-21903

fix(TUP-21903):tSalesForceConnection JWT flow does not work with Context

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet

Reverts Talend/tdi-studio-se#3277

Revert "fix(TBD-8356): tBigqueryOutput handles empty strings as null"

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TUP-21903

kjwang/Fix-TUP-21903 tSalesForceConnection fix junit

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TUP-21903

kjwang/Fix-TUP-21903 tSalesForceConnection fix junit (#3314)

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-httputil/pom.xml

fix(TDI-41896): Upgrade jackson-databind version

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

fix(TESB-25116):Build microservice jar with ctalendjob is only 2kb

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml

https://jira.talendforge.org/browse/TDI-41894
https://jira.talendforge.org/browse/TDI-41894

fix(TDI-41894): Randomly the job fails with "java.security.SignatureException: Invalid encoding for signature" error.

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/DiSchemaConstants.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/OutgoingSchemaEnforcer.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/OutgoingSchemaEnforcerTest.java
main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
main/plugins/org.talend.libraries.custom/plugin.xml
main/plugins/org.talend.libraries.custom/pom.xml

https://jira.talendforge.org/browse/TDI-42013
https://jira.talendforge.org/browse/TDI-42013

fix(TDI-41188): map Snowflake Time type to Talend Date instead of Talend Integer (#2945)

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8496): field separator for service account bigquery

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionCreateCommand.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/Connection.java

TESB-24784 Propagation of Connection extra properties is added

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

fix(TESB-25116): Fixed JUnit error for NPE

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet

fix(TBD-7153): Fixed missing mappings for BigQuery (#3291)

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8496): field separator for service account bigquery (#3329)

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java

Endpoint displayed in console when running a route in Studio is sometimes wrong (when using context variables for example).
Now code replaces context variables with appropriate values and add default endpoint URI if missing. The displayed endpoint in console is more reliable.

TESB-24920 Backport fix to patch/7.1

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/java/TalendJavaSourceViewer.java

fix(TUP-22334)Error pops up when clicking if link

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java

https://jira.talendforge.org/browse/TDI-41898
https://jira.talendforge.org/browse/TDI-41898

fix(TDI-41898): Comment in the query in tJDBCInput component does not work if the job is migrated from 6.2.1 to 7.1.1

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/imports/ImportItemWizardPage.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importproject/ImportProjectHelper.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/AbstractWizardProjectsImportPage.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendWizardProjectsImportPage.java

fix(TUP-22410)Can't import item which locate at root of disk after eclipse upgrade

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet

No up to RFC standards 
PBSZ executing before PROT up to RFC

fix(TDI-42024): Change execProt and execPBSZ order

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml

feat(TDI-41787): Upgrade to CXF 3.3.1

---

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/WebServiceUI.java
main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/dialog/WebServiceDialog.java

https://jira.talendforge.org/browse/TUP-22269

fix(TUP-22269)Twebservice throwing Null Pointer Exception

---

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/WebServiceUI.java
main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/dialog/WebServiceDialog.java

https://jira.talendforge.org/browse/TUP-22269

fix(TUP-22269)Twebservice throwing Null Pointer Exception (#3349)

---

main/plugins/org.talend.designer.components.libs/libs_src/TalendSAX/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/TalendSAX/src/main/java/org/talend/xml/sax/ComplexSAXLooper.java
main/plugins/org.talend.designer.components.libs/libs_src/TalendSAX/src/main/java/org/talend/xml/sax/simpleparser/SimpleSAXLooper.java
main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSXML/tFileInputMSXML_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_java.xml
main/plugins/org.talend.libraries.xml/pom.xml

fix(TDI-42046): error DOCTYPE is disallowed

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/mvn/Mvn.java

TCOMP-1353 ensure tcomp does not conflict with components

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFixedFlowInput/tFixedFlowInput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSocketInput/tSocketInput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSocketOutput/tSocketOutput_main.javajet

https://jira.talendforge.org/browse/TDI-41944
https://jira.talendforge.org/browse/TDI-41944

fix(TDI-41944): [Java 11] Replace usage of sun.misc.Base64 to java.util.Base64

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFixedFlowInput/tFixedFlowInput_begin.javajet

https://jira.talendforge.org/browse/TDI-41944
https://jira.talendforge.org/browse/TDI-41944

fix(TDI-41944): fix the code generate issue

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java

https://jira.talendforge.org/browse/TUP-22470

fix(TUP-22470): NPE shows after opening edit in conflict page and resolving the conflict

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TUP-22342

fix(TUP-22342)Joblet referring to objects that do not exist

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TUP-22342

fix(TUP-22342)Joblet referring to objects that do not exist (#3355)

---

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet

https://jira.talendforge.org/browse/TDI-42072
https://jira.talendforge.org/browse/TDI-42072

fix(TDI-42072): NullPointerException when using the tDie component in the child job and execute the job from the parent job.

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

fix(TESB-25116): Fixed NPE for data viewer

---

main/plugins/org.talend.repository/src/main/java/messages.properties
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java

fix(TUP-22395)Shouldn't be overwrite button for creating unexist directory for build job

---

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/WebServiceUI.java

https://jira.talendforge.org/browse/TUP-22269

fix(TUP-22269)Twebservice throwing Null Pointer Exception (#3364)

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java

https://jira.talendforge.org/browse/TUP-21920
Loop dependency classpath issue caused main class not found

fix(TUP-21920)Nullpointer on build job

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

https://jira.talendforge.org/browse/TESB-25438
Fix the issue.
- [] Yes

TESB-25438:SAM/Locator not work when tRestClient job deploy to Runtime

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java

https://jira.talendforge.org/browse/TUP-21920
Loop dependency classpath issue caused main class not found

fix(TUP-21920)Nullpointer on build job (#3336)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/java/TalendJavaSourceViewer.java

fix(TUP-22201)Cannot show suggestion of methods in tJava

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java

https://jira.talendforge.org/browse/TUP-22521
https://jira.talendforge.org/browse/TUP-22521

fix(TUP-22521):tHiveMap- Unexpected SQL syntax for 'case when ...then....else' condition.

---

main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml

fix(TBD-8343): NoSuchMethodError when Having tGSConnection and tS3Connection Components Within one Job

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ServerManagerTest.java

Talend Component Kit 1.1.9-SNAPSHOT base is used
IMPORTANT: tcommon-studio-se must get the upgrade too
Guess Schema works, Record model is supported

preparing talend component kit 1.1.9 upgrade

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java

https://jira.talendforge.org/browse/TDI-29956
https://jira.talendforge.org/browse/TDI-29956

fix(TDI-29956): Lookup from tRESTClient ClassNotFoundException

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/MigrateTDataMaskingGuiTDQ16376.java

feat(TDQ-16376): add migration task for tDataMasking UI changes

---

main/plugins/org.talend.designer.components.localprovider/components/tHttpRequest/tHttpRequest_main.javajet

https://jira.talendforge.org/browse/TDI-42126
https://jira.talendforge.org/browse/TDI-42126

fix(TDI-42126): tHttpRequest cannot correctly handle multi-byte characters

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/ConnectionManager.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/ConnectionManagerTest.java

job in studio
https://jira.talendforge.org/browse/TUP-22620

fix(TUP-22620)java.lang.StackOverflowError exception when opening the

---

main/plugins/org.talend.designer.components.localprovider/components/tReplaceList/tReplaceList_begin.javajet

https://jira.talendforge.org/browse/TDI-42141
https://jira.talendforge.org/browse/TDI-42141

fix(TDI-42141): tReplacelist not replacing in order

---

main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml

TESB-25479 Switching to activemq 5.15.5

---

main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml

https://jira.talendforge.org/browse/TDI-42142
https://jira.talendforge.org/browse/TDI-42142

fix(TDI-42142): Switching to activemq 5.15.5 

---

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/UpgradeElementHelperTest.java

compilation error "row1 cannot be resolved to a variable"
- [ *] Bugfix
- [* ] No

bugfix(TUP-22426):[6.5.1]Test Case generation on tRunJob gives

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8570): correct error message handling

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java

https://jira.talendforge.org/browse/TUP-22587
https://jira.talendforge.org/browse/TUP-22587

fix(TUP-22587):NameNode URI fields changes to default value after changing the HDP version.

---

main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml

https://jira.talendforge.org/browse/TDI-42071
https://jira.talendforge.org/browse/TDI-42071

fix(TDI-42172): not import activemq jar for ESB runtime

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java

bugfix(TUP-22435):tMap lost look-up details

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet

fix(TBD-8573): correct parsing date values from BigQuery

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/MigrateTDataMaskingGuiTDQ16376.java

feat(TDQ-16376): no need to migrate if CATEGORY field is present

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java

fix wrong setup

---

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/UpgradeElementHelperTest.java

compilation error "row1 cannot be resolved to a variable"
- [* ] Bugfix
- [* ] No

bugfix(TUP-22426):6.5.1]Test Case generation on tRunJob gives

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java

https://jira.talendforge.org/browse/TUP-21546

feat(TUP-21546): Add commit mode on the studio

---

main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml

https://jira.talendforge.org/browse/TDI-42100
https://jira.talendforge.org/browse/TDI-42100

fix(TDI-42100): Upgrade to ActiveMQ 5.15.9 in tMom/tSAP components

---

main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml

https://jira.talendforge.org/browse/TDI-42223
https://jira.talendforge.org/browse/TDI-42223

fix(TDI-42223): twebservice not works in java 11

---

main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_main.javajet

Only add the log.info if log4j is enabled

fix(TBD-8603): tHiveRow compile error

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet

fix(TBD-8587) : Compiler error when di job use hbase components

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet

https://jira.talendforge.org/browse/TDI-42186
https://jira.talendforge.org/browse/TDI-42186

fix(TDI-42186): sure to close the stream

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/hive/HiveGenerationManager.java

fix(TBD-8566): correct context var replacement in subqueries

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java

https://jira.talendforge.org/browse/TUP-22804

fix(TUP-22804)Job with component tSAPIDOCOutput not getting built

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java

show as a Tag
https://jira.talendforge.org/browse/TUP-22681

fix(TUP-22681)Job in CI Builder gets generated and deployed, but doesn't

---

main/plugins/org.talend.designer.runprocess/resources/templates/Job_run_template.bat
main/plugins/org.talend.designer.runprocess/resources/templates/Job_run_template.sh
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ProcessorConstants.java

bugfix(TUP-22744):711 built batch job doesn't run fine

---

main/plugins/org.talend.designer.codegen/jet_stub/header.javajet

https://jira.talendforge.org/browse/TDI-42239
https://jira.talendforge.org/browse/TDI-42239

fix(TDI-42239): tLogCatcher and tAssertCatcher cause compilation error when used together

---

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tELTSybaseOutput/tELTSybaseOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseBulkExec/tSybaseBulkExec_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseConnection/tSybaseConnection_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseIQBulkExec/tSybaseIQBulkExec_begin_Insert_Location.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseIQBulkExec/tSybaseIQBulkExec_begin_Load.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseInput/tSybaseInput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseRow/tSybaseRow_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseSCD/tSybaseSCD_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseSCDELT/tSybaseSCDELT_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSybaseSP/tSybaseSP_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/HelpClass/HelpClass.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/HelpClass.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/HelpClass.javajet

https://jira.talendforge.org/browse/TDI-42241
https://jira.talendforge.org/browse/TDI-42241

fix(TDI-42241): make sybase components work in java 11 too

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java

fix(TUP-22484)Random issue: Compile error for simple job sometimes

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/utils/DataMapExpressionParserTest.java

* bugfix(TUP-22649):tELTOracleMap : wrong Generated SQL Select query after
patch TPS-2944
- [* ] Bugfix
- [* ] No

Hwang/tup 22649 (#3413)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

TESB-25671:Build DemoREST as MS Jar with maven script

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java

fix(TUP-22147)There is a NPE error when closing studio

---

main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_begin.javajet

https://jira.talendforge.org/browse/TDI-42100
https://jira.talendforge.org/browse/TDI-42100

fix(TDI-42100): disable hostname check for ssl

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/InputDataMapTableView.java

16.04
https://jira.talendforge.org/browse/TUP-22783

fix(TUP-22783)TELTPOSTGRESQL MAP Join Operator not working in Ubuntu

---

main/plugins/org.talend.designer.codegen/src/main/java/messages.properties
main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java

https://jira.talendforge.org/browse/TUP-22713

fix(TUP-22713): Possible thread lock during git update operation

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/hive/HiveGenerationManager.java

fix(TBD-8566): correct context var replacement in subqueries (#3420)

---

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/RepositoryWebService.java

* Remove legacy ssl configuration

fix(TUP-21896): replace internal sun classes

---

main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet

https://jira.talendforge.org/browse/TDI-42300

Fix(TDI-42300):Make variable name unique

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet

fix(TBD-8573): correct parsing date values from BigQuery (#3429)

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/TalendBorderItemRectilinearRouter.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java

fix(TUP-22520)tDBConnection is not used in the tDB components Joblet issue

---

main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml

https://jira.talendforge.org/browse/TDI-42251
Fix the same issue that the WSDL URL is invalid.

Fix(TDI-42251):Fix the invalid WSDL URL.

---

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/DataNodeTest.java

https://jira.talendforge.org/browse/TUP-22906

fix(TUP-22906): Job working in 6.3.1 fails to generate in 7.1.1 : Failed to generate code. 

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet

ensure TACOKIT_SUGGESTABLE_TABLE leads to valid configuration

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/update/UpdateResolver.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/action/update/UpdateResolverTest.java

ensure activeif is respected for update button

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

https://jira.talendforge.org/browse/TESB-23808
Fix the issue

TESB-23808:Cannot build osgi bundle correctly with checking "Add maven script"

---

main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_main.javajet

* fix(TBD-8603): tHiveRow compile error
Only add the log.info if log4j is enabled
* fix(TBD-8603): tHiveRow compile error
Only add the log.info if log4j is enabled

fix(TBD-8603): tHiveRow compile error (#3425)

---

main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/dnd/JSONToSchemaDragAndDropHandler.java
main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToXPathLinker.java

trying to set "Fields to extract" Column name in Metadata -> File XML
https://jira.talendforge.org/browse/TUP-22908

fix(TUP-22908)Talend Studio Mac OS Mojave 10.14 : Hangs or Crashes when

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/CleanCustomerMatcherField.java

https://jira.talendforge.org/browse/TDQ-16872
Add a migration for tMatchGroup component when the source version is less than 7.2.0

fix(TDQ-16872): Migration for correctly "Custom Matcher" parameter on tmatchGroup component

---

main/plugins/org.talend.designer.codegen/src/main/java/messages.properties
main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java

fix(TUP-22713): Possible thread lock during git update operation
https://jira.talendforge.org/browse/TUP-22713

fix(TUP-22713): Possible thread lock during git update operation (#3449)

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java

Avoid NPE when java.coordinates property is not set

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java

exception handling

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/dialog/PropertySetDialog.java

fix(TUP-20851)Tmap with Die on error uncheck doesn't create ErrorReject Output

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

https://jira.talendforge.org/browse/TUP-23098

item(TUP-23098): Upgrade tacokit to release version of 1.1.9

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/OpenExistVersionProcessWizard.java
main/plugins/org.talend.designer.rowgenerator/src/main/java/org/talend/designer/rowgenerator/RowGeneratorComponent.java

fix(TUP-22980)After create another version for a job, when add another schema for trowgenerator, it will not saved

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

fix(TESB-25692): Set to jave 1.8 in manifest after Java11 compiled

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java

fix(TUP-23123): fix indent between component properties for Windows

---

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/MapperUI.java
main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java

https://jira.talendforge.org/browse/TUP-22701

fix(TUP-22701)[MacOS] tMap - Can't save field in expression

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

bugfix(TUP-22887):sorting schema order cause a tMatchgroup regression

---

main/plugins/org.talend.repository.resource/plugin.xml
main/plugins/org.talend.repository.resource/src/messages.properties
main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/ui/wizards/NewRouteResourceWizardPage.java

https://jira.talendforge.org/browse/TUP-22117
https://jira.talendforge.org/browse/TUP-22117

fix(TUP-22117):Create resource item message contains "route"

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8708): tBigqueryOutput - some enhancement

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java

* fix(TUP-22147)There is a NPE error when closing studio
* fix(TUP-22147)There is a NPE error when closing studio

fix(TUP-22147)There is a NPE error when closing studio (#3443)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java

TESB-25922:Docker pubish: No progress bar in publish route dialog

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java

fix(TUP-22955):java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java

https://jira.talendforge.org/browse/TUP-22237

fix(TUP-22237)tFixedflowinput converting string to garbage value

---

main/plugins/org.talend.libraries.custom/pom.xml

Fix(TDI-42321):Change pom.xml in org.talend.libraries.custom(save

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java

fix(TUP-22198)CommandLine : get error when execute/build job for a job using nested joblets

---

main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton

https://jira.talendforge.org/browse/TDI-41947
https://jira.talendforge.org/browse/TDI-41947

fix(TDI-41947): process the null for UUID db type

---

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet

https://jira.talendforge.org/browse/TDI-42407

Fix(TDI-42407):Fix the issue which causes missing data while use tFileInputExcel

---

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
main/plugins/org.talend.libraries.excel/pom.xml

https://jira.talendforge.org/browse/TDI-42433
close the stream like before we use poi 3.16

fix(TDI-42433): close the stream like before, we need to keep the old action for the old job

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml

https://jira.talendforge.org/browse/TDI-42223
https://jira.talendforge.org/browse/TDI-42223

fix(TDI-42223): update woodstox-core jar

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/views/ProcessView.java
main/plugins/org.talend.designer.runtime.visualization.tools/src/org/talend/designer/runtime/visualization/internal/tools/IConstants.java
main/plugins/org.talend.designer.runtime.visualization.tools/src/org/talend/designer/runtime/visualization/internal/tools/JvmAttachHandler.java
main/plugins/org.talend.designer.runtime.visualization.tools/src/org/talend/designer/runtime/visualization/internal/tools/Tools.java

https://jira.talendforge.org/browse/TUP-23244

Fix TUP-23244 Studio continuously throw "Attach is not supported for target JVM" after memory run

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8708): fix action on data for service account

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/MultipleThreadDynamicComposite.java

https://jira.talendforge.org/browse/TUP-23325
Check for the position to be null or not. 
Behave as previously in case the position is not null otherwise do not calulate the position as this is not needed

fix(TUP-23325): fix blank Panel in case a group is not visible

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java

build/publish Job
https://jira.talendforge.org/browse/TUP-22833

feat(TUP-22833)Remove the addition of context parameters during the

---

main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinBulkExec/tSalesforceEinsteinBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinOutputBulkExec/tSalesforceEinsteinOutputBulkExec_java.xml

for feature: https://jira.talendforge.org/browse/TDI-41141

 feat(TDI-41141):Update SalesForce API to 45.0

---

main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleInput/tAmazonOracleInput_begin.javajet

This reverts commit f7cbeabea2ac4ed60f9b65a07318c5e8c2dbbd8d.

Revert "Fix(TDI-30725):Make username to uppercase in log4j. (#3456)"

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java

https://jira.talendforge.org/browse/TUP-20054
https://jira.talendforge.org/browse/TUP-20054

fix(TUP-20054):lose the focus on the field.

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java

https://jira.talendforge.org/browse/TUP-20938
https://jira.talendforge.org/browse/TUP-20938

fix(TUP-20938):[Layout] Test connection button appears on advanced form.

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessContextComposite.java

fix(TUP-22198)CommandLine : get error when execute/build job for a job

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractSchemaController.java

bugfix(TUP-23228):The order of schema changed when ticked "used column"

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameTCOMPCouchbaseMigrationTask.java

feat(TDI-42393): Add a migration task for renaming Couchbase

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java

https://jira.talendforge.org/browse/TUP-22359

fix(TUP-22359)Broken Data Schema UI

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java

https://jira.talendforge.org/browse/TESB-26058
Fix the issue

TESB-26058:Docker - Build Job Dialog - Remove DI / BD Docker Option when it is an ESB Artifact

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/pom.xml
main/plugins/org.talend.libraries.excel/.classpath

https://jira.talendforge.org/browse/TDI-42464
https://jira.talendforge.org/browse/TDI-42464

fix(TDI-42464): Update tcomp in studio to 0.27.0 / daikon to 0.31.6

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/MainComposite.java

to release repository
- [ *] Bugfix
- [ *] No

bugfix(TUP-23322):context value doesn't update after publishing the job

---

main/plugins/org.talend.designer.codegen/src/main/java/messages.properties

bug(TDQ-17136) : add Data Privacy Family

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml

TESB-25939
route/jobs contexts are now correctly bundled after update

TESB-25939 : fix context update when building route and job

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/pom.xml

https://jira.talendforge.org/browse/TDI-42483
https://jira.talendforge.org/browse/TDI-42483

fix(TDI-42483): DEBUG or INFO display in studio console while should not

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitService.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java

fix(TUP-23285): Problem with deleting dataset/datastore https://jira.talendforge.org/browse/TUP-23285

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitRepositoryContentHandler.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java

https://jira.talendforge.org/browse/TUP-23285

fix(TUP-23285): Problem with deleting dataset/datastore

---

main/plugins/org.talend.designer.components.localprovider/components/tAS400Connection/tAS400Connection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAS400Input/tAS400Input_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAS400Row/tAS400Row_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java

https://jira.talendforge.org/browse/TDI-41636
https://jira.talendforge.org/browse/TDI-41636

fix(TDI-41636): adjust the maven path to use the one in maven center

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModel.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java

https://jira.talendforge.org/browse/TUP-23157
https://jira.talendforge.org/browse/TUP-23157

fix(TUP-23157):datastore values are not prefilled when creating a dataset.

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/action/CreateTaCoKitConfigurationAction.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitCreateWizard.java

https://jira.talendforge.org/browse/TUP-23282

fix(TUP-23282): Display of Tacokit Metadata is not homogeneous with other metadata

---

main/plugins/org.talend.libraries.excel/.classpath
main/plugins/org.talend.libraries.excel/lib/.gitignore

chore: resolve compile error in eclipse

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java

chore: temp fix to remove unused jars

---

main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/soap/src/main/java/org/talend/soap/SOAPUtil.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/sdk/DeviceIdManager.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/sdk/WsdlTokenManager.java
main/plugins/org.talend.designer.components.localprovider/components/tDTDValidator/tDTDValidator_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
main/plugins/org.talend.designer.components.localprovider/pom.xml
main/plugins/org.talend.libraries.crm/pom.xml

https://jira.talendforge.org/browse/TDI-41573
https://jira.talendforge.org/browse/TDI-41573

fix(TDI-41573): Enable secure processing + disallow doctypes for DocumentBuilderFactory instances

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8787): set allow quoted new lines to true

---

main/plugins/org.talend.designer.core/plugin.xml
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GenerateCryptoFileController.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/generator/GenerateCryptoFileControllerGenerator.java

feat(TDQ-16495): add controller for crypto file generation

---

main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/actions/AbstractPublishJobAction.java

https://jira.talendforge.org/browse/TESB-26145
Context is added to published Job

TESB-26145 Including context to published Job

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodecontainer/NodeContainerFigure.java

https://jira.talendforge.org/browse/TUP-22936

fix(TUP-22936)No description for component red/yellow signs

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java

Reverts Talend/tdi-studio-se#3539

Revert "fix(TUP-22198)CommandLine : get error when execute/build job for a job"

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java

Reverts Talend/tdi-studio-se#3515

Revert "fix(TUP-22198)CommandLine : get error when execute/build job for a job using nested joblets"

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java

https://jira.talendforge.org/browse/TUP-23431

fix(TUP-23431): java heap OutOfMemoryError when logon project while running auto tests using oracleJDK11.0.3

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8708): create only if create table option is checked for service account (BigQuery)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitService.java

https://jira.talendforge.org/browse/TUP-23432

fix(TUP-23432): NPE when single selecting build job

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java

https://jira.talendforge.org/browse/TESB-26160
Fixed the bug

TESB-26160:When build docker image, the offline mode will not switch to online mode automatically

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

fix(TBD-8708): code enhancement

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml

context not correctly updated in final route bundles
Context is correctly updated

TESB-25939 : fix context update

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModel.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java

https://jira.talendforge.org/browse/TUP-23460

fix(TUP-23460):[TaCoKit] Empty widget has null value as string.

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

TESB-26208:Cannot build route kar when Studio path contains space

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java

https://jira.talendforge.org/browse/TDI-42382
https://jira.talendforge.org/browse/TDI-42382

fix(TDI-42382): Class path contains multiple SLF4J bindings

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-httputil/pom.xml

fix(TDI-42396): Bump httputils lib version

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml

https://jira.talendforge.org/browse/TDI-40979
https://jira.talendforge.org/browse/TDI-40979

fix(TDI-40979): fix the regression

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java

https://jira.talendforge.org/browse/TUP-22955

TUP-22955 java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver (Fix can't guess query problem)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

TESB-26211:[Docker] Docker Build option is shown in ESB Entry level product

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java

https://jira.talendforge.org/browse/TUP-23465

fix(TUP-23465): Performance issue when open a job and save a job and import in items.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java

https://jira.talendforge.org/browse/TUP-22955

TUP-22955 java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver (Fix can't guess query problem) (#3607)

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java

https://jira.talendforge.org/browse/TUP-22955

TUP-22955 java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver (Fix can't guess query problem))

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java

bugfix(TUP-23510):There is compile error job in TDI demo project
