- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TextController.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/Lookups.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TextElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ValidationLabel.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/PropertyValidator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ValidationListener.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/HealthCheckResolver.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/problemmanager/ColorfulProblemManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/problemmanager/ComponentViewProblemManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/problemmanager/IProblemManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/problemmanager/ProblemManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/problemmanager/WizardProblemManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitConfigurationRuntimeData.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitConfigurationWizard.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
https://jira.talendforge.org/browse/TUP-20054
> fix(TUP-20054): Due to checking fields it is hard to type credentials/data from the keyboard

- i18n/plugins/org.talend.designer.runprocess.nl/src/main/java/messages_fr.properties
fix a pattern used to display job status
> fix(): typo in a pattern

- i18n/plugins/org.talend.designer.runprocess.nl/src/main/java/messages_fr.properties
fix a pattern used to display job status
> fix: typo in a pattern

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
Reverts Talend/tdi-studio-se#3619
> Revert "Jding/tup 23482 should avoid multi version slf4j log4j jars"

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
sapjco3.jar with a newer version 3.0.14.
https://jira.talendforge.org/browse/TUP-23506
> fix(TUP-23506)Job use tsapconnection component run fail when use the

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
> fix(TUP-21827)MVN package fail with testcase use olderversion from 651

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> patch(TBD-8649): tBigQueryInput component doesn't contain field Result Size for service account

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java
> fix(TUP-23389)tMap - cannot edit schema

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/ConnectionManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
merged
- [ *] Bugfix
- [ *] No
> bugfix(TUP-22734):lookup will come after OnSubjobOK then subjobs will be

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
https://jira.talendforge.org/browse/TUP-23594
> fix(TUP-23594): NullPointerException when using the build job wizard.

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> fix(TBD-8853): removed too small total timeout for service account

- main/plugins/org.talend.designer.components.localprovider/components/tContextLoad/tContextLoad_end.javajet
https://jira.talendforge.org/browse/TDI-42021
> Fix(TDI-42021):Change the log level when using implicit context load

- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_end.javajet
- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_end.javajet
https://jira.talendforge.org/browse/TDI-42531
Add logic to close resources on end block.
> fix(TDI-42531): close resources in end block

- main/plugins/org.talend.designer.components.localprovider/components/tContextLoad/tContextLoad_main.javajet
https://jira.talendforge.org/browse/TDI-42534
> fix(TDI-42534):tContextLoad compile error on resource type

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> TESB-26293 Duplicated libraries in private & import packages of the build manifest file

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
> fix(TUP-23371)[GIT] Studio will dead when TAC accidentally disconnected

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-23264
> fix(TUP-23264):Studio can't find dependencies for tacokit components.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
Reverts Talend/tdi-studio-se#3665
> Revert "fix(TUP-23371)[GIT] Studio will dead when TAC accidentally disconnected"

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/processor/QueryTypeProcessor.java
https://jira.talendforge.org/browse/TUP-23550
> fix(TUP-23550):Select query for DBInput component page will list Couchbase.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
- [] Tests for the changes have been added (for bug fixes / features)
> fix(TUP-23371)Studio_will_dead_when_TAC_accidentally_disconnected

- main/plugins/org.talend.designer.fileoutputxml/src/main/java/messages.properties
- main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/action/ImportTreeFromXMLAction.java
- main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/i18n/Messages.java
indexOutOfBoundsException
https://jira.talendforge.org/browse/TUP-22200
> fix(TUP-22200)Import XML tree from xsd file throw

- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusConnection/tPostgresPlusConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusInput/tPostgresPlusInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_java.xml
fix(TUP-23363)'save the property' to metadata get error
> fix(TUP-23363)'save the property' to metadata get error

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-23264
https://jira.talendforge.org/browse/TUP-23264
> fix(TUP-23264):fix problems for guess schema and trun job.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ColumnListController.java
> feat(TDQ-16419) Add a filter by the column data type

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeActivateStatusElementCommand.java
- test/plugins/org.talend.designer.core.test/src/core/ui/editor/cmd/ChangeActivateStatusElementCommandTest.java
unexpectedly when using tMSXMLInput component
https://jira.talendforge.org/browse/TUP-23663
> fix(TUP-23663)The connection row between components is getting activated

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-23790
https://jira.talendforge.org/browse/TUP-23790
> fix(TUP-23790):Can't guess schema for metadata item(delimited/positional/regex/excel/ldif/ldap)

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-23790
https://jira.talendforge.org/browse/TUP-23790
> fix(TUP-23790):Can't guess schema for metadata

- main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
the process is not stopped when parent thread is stopped
the process is stopped when parent thread is stopped
> Tdi 42570 stop process when thread stops

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
https://jira.talendforge.org/browse/TDI-42423
https://jira.talendforge.org/browse/TDI-42423
> fix（TDI-42423）：fix(TDI-42423): fix the tcreatetable for teradata with jdbc parameters

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> task(TBD-8950): Change redundant code appearance in tBigQueryBulkExec

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddEncodingTypeForDQComponentsTask.java
https://jira.talendforge.org/browse/TDQ-16777
added new combo list all the four kinds of DQ component
> feat(TDQ-16777 TDQ-17239): added one migration for added encoding type of combo list.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-23743
> fix(TUP-23743):ERROR when Job in MDM project calling Job in Reference DI project:import routines.DataQuality cannot be resolved.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-23743
> fix(TUP-23743):ERROR when Job in MDM project calling Job in Reference DI project routines cannot be resolved.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TDQ-17069
remove unused code
> chor(TDQ-17069): remove unused code

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TDQ-17069
remove unused code
> chor(TDQ-17069): back port on 7.1

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> fix(TBD-8951): skeap header for Service Account

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
https://jira.talendforge.org/browse/TUP-23809
> Fix TUP-23809 [Studio] changes in column order are not saved (no propagate changes dialog)

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
https://jira.talendforge.org/browse/TUP-23841
> TUP-23841 Build job with 'OSGI Bundle For ESB' get error pop-up

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/MemoryRuntimeComposite.java
https://jira.talendforge.org/browse/TUP-23508
TOS has bug in memory run
Fix the bug of memory run in TOS
> fix(TUP-23508): TOS can't use memory run

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> Patch(TPS-3225): removed too small total timeout for service account

- main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/pom.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_java.xml
https://jira.talendforge.org/browse/TDI-42572
> fix(TDI-42572):upgrade EXAUtil version

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
the component does not extract nested into multipart body attachments
the component extracts nested into multipart body attachments
> fix(TDI-42634): get attachments recursively

- main/plugins/org.talend.designer.runprocess/resources/templates/Job_run_template.ps1
Generated Powershell scripts, is wrong.
> bugfix(TDI-42364): When building a Standalone job.

- main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
When directory name not finish with separator, the last directory name is mix with filename.
directory name and file name are clearly separate.
> TDI-42679 : use new File(rep, file) constructor

- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
https://jira.talendforge.org/browse/TDI-42674
> fix(TDI-42674):Redshift missing jar for SSO

- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/HelpClass/HelpClass.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jDBConnUtil.javajet
> TESB-24900 Undeploying a Data Service causes "Exception in opening zip file" error

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/maven/listener/ProcessChangeListenerTest.java
7.1.1
https://jira.talendforge.org/browse/TUP-23789
> fix(TUP-23789)Pom files are not generated sometimes for the jobs in

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
> TESB-24597:Docker Support for Microservice - CI Part

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> TESB-24730 Services no longer accessible ( NPE) after route deployment

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractTextAreaSelectionController.java
- main/plugins/org.talend.sdk.component.studio-integration/plugin.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TextAreaSelectionParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/WidgetTypeMapper.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/controller/TaCoKitTextAreaSelectionController.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/controller/TaCoKitValueSelectionController.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/controller/ValueSelectionDialog.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/generator/TaCoKitTextAreaSelectionGenerator.java
https://jira.talendforge.org/browse/TUP-20928
> fix(TUP-20928):Suggestable doesn't work for TextArea in Studio

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModel.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ValueConverter.java
- test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModelTest.java
https://jira.talendforge.org/browse/TUP-21687
https://jira.talendforge.org/browse/TUP-21687
> fix(TUP-21687):Table value is not visible after filling component properties from metadata.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtilTest.java
project;
https://jira.talendforge.org/browse/TUP-22880
> fix(TUP-22880)Resources: Job cannot use resources from reference

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
Resources
https://jira.talendforge.org/browse/TUP-22943
> fix(TUP-22943)checkbox with empty item name display on window Save

- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTestHelper.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/demo/imports/MdmEeDemoImportTest.java
> bugfix(TUP-23894):Fix all failed junit for both java 8 and 11

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
> bugfix(TUP-23967):Studio can't run jobs when path has spaces, Windows 10

- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTestHelper.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/demo/imports/MdmEeDemoImportTest.java
> bugfix(TUP-23894):Fix all failed junit for both java 8 and 11 #3761

- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
https://jira.talendforge.org/browse/TUP-20943
> fix(TUP-20943): Code generates with an error when Pattern check fails if contain back slash

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ComponentModelTest.java
https://jira.talendforge.org/browse/TUP-23626
> fix(TUP-23626):tacokit problem with drag and drop variables from Outline.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java
https://jira.talendforge.org/browse/TUP-23514
> fix(TUP-23514): NPE shows in errorlog view when Selecting Repository in Basic settings

- main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
https://jira.talendforge.org/browse/TDI-41662
fix missing import
> fix TalendExcel imports

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/seeker/TaCoKitMetadataRepoViewSeeker.java
https://jira.talendforge.org/browse/TUP-23515
https://jira.talendforge.org/browse/TUP-23515
> fix(TUP-23515):tacokit dataset won't pop up after clicking OK on "Edit parameters using repository".

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/SqlMemoController.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/properties/controllers/SqlMemoControllerTest.java
https://jira.talendforge.org/browse/TUP-23513
https://jira.talendforge.org/browse/TUP-23513
> fix(TUP-23513):NPE shows in errorlog view when clicking [...] button next to SQL Query.

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/model/parameter/InputSchemaParameterTest.java
- test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameterTest.java
- test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameterTest.java
https://jira.talendforge.org/browse/TUP-20951
> fix(TUP-20951): Validation parameters need to be removed from serialization

- main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet
https://jira.talendforge.org/browse/TDI-42687
https://jira.talendforge.org/browse/TDI-42687
> fix(TDI-42687): Enable AWS ECS role for S3 component

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/DesignerCoreService.java
https://jira.talendforge.org/browse/TUP-20372
> fix(TUP-20372)Use Project Settings is not checked as default for job

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractTextAreaSelectionController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractValueSelectionController.java
https://jira.talendforge.org/browse/TUP-21027
https://jira.talendforge.org/browse/TUP-21027
> fix(TUP-21027):Suggestable widgets not save edited values (if not use custom value).

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileOutputStep1Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep1Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep2Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep3Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/action/ImportTreeFromJSONAction.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/util/JSONUtil.java
https://jira.talendforge.org/browse/TUP-23914
> fix(TUP-23914): JSON with accented characters is not being recognized when creating a new JSON file in Metadata.

- main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
> TESB-26174:Error on Job with multiple tRunJob calling Call another Child job with tESBConsumer component

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactoryTest.java
> TESB-24597 Docker Support for Microservice - CI Part

- main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_main.javajet
> fix(TDI-42495): unexpected behaviour of tArchive

- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/converter/TypeConverter.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
- main/plugins/org.talend.libraries.custom/plugin.xml
- main/plugins/org.talend.libraries.custom/pom.xml
https://jira.talendforge.org/browse/TDI-42747
https://jira.talendforge.org/browse/TDI-42747
> fix(TDI-42747): fix the issue for tjdbcinput with dynamic column and inside talend object type like for database type blob

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactoryTest.java
> Docker_Support_for_Microservice_CI_Part_72

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
https://jira.talendforge.org/browse/TUP-20933
> fix(TUP-20933):tStatCatcher Statistics property is not shown in Advanced tab of Tacokit components

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ExternalNodeChangeCommand.java
repository when changes are made in the map
> fix(TUP-24034)tETLoutput schema getting changed to Built-in from

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToXPathLinker.java
https://jira.talendforge.org/browse/TUP-24159
> fix(TUP-24159)XML metadata wizard showing inconsistent view on V711 comparing with V6 Studio

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddEncodingTypeForDQComponentsTask.java
> feat(TDQ-17366)Remove migration for tRuleSurvivorship

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddRAWFlowTPatternMasking.java
https://jira.talendforge.org/browse/TDQ-17177
add a new output flow 
> feat(TDQ-17177): support "RAW" output flow for tPatternMasking component

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
When route is built, it shows twice an error dialog.
Do not display dialog on error check
> TESB-26300: disable message dialog when checking build errors

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToXPathLinker.java
https://jira.talendforge.org/browse/TUP-24159
> fix(TUP-24159)XML metadata wizard showing inconsistent view on V711comparing with V6 Studio

- main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/pom.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_java.xml
https://jira.talendforge.org/browse/TDI-42725
> fix(TDI-42725):change the groupID for Exa jar

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/changeDBVersionForMapROJAIOutputMigrationTask.java
> fix(TBD-9121): new migration task to change tMapROjaiOutput component dbVersion 

- main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_messages.properties
> fix(TDI-42836): Add milis elaboration to properties labels

- main/plugins/org.talend.designer.components.localprovider/components/tSetProxy/tSetProxy_messages.properties
https://jira.talendforge.org/browse/TDI-42374
> Fix(TDI-42374):"None Proxy Hosts" rename to "No Proxy for"

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/actions/RunProcessAction.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
https://jira.talendforge.org/browse/TUP-23160
> fix(TUP-23160)Error popup during build father job after modified sun job and do not open father job

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/TracesConnectionUtils.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
> bugfix(TUP-23583):Unable to see all tables in AS400 Connection

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/java/TalendJavaSourceViewer.java
- main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/VirtualRowGeneratorNode.java
- test/plugins/org.talend.expressionbuilder.test/.classpath
- test/plugins/org.talend.expressionbuilder.test/.project
- test/plugins/org.talend.expressionbuilder.test/META-INF/MANIFEST.MF
- test/plugins/org.talend.expressionbuilder.test/build.properties
- test/plugins/org.talend.expressionbuilder.test/pom.xml
- test/plugins/org.talend.expressionbuilder.test/src/org/talend/expressionbuilder/test/shadow/VirtualRowGeneratorNodeTest.java
https://jira.talendforge.org/browse/TUP-24109
> fix(TUP-24109)unable to test Expression Builder of tMap

- main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/src/main/java/org/talend/ftp/SSLSessionReuseFTPSClient.java
- main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
- main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-42862
https://jira.talendforge.org/browse/TDI-42862
> fix(TDI-42862): fix the ftps for java 11

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TUP-20936
https://jira.talendforge.org/browse/TUP-20936
> fix(TUP-20936):No properties validation for tcomp components in compile time.

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
https://jira.talendforge.org/browse/TDI-42034
Driver was updated from 1.2.20.1043 to 1.2.32.1056
> fix(TDI-42034): update Redshift jar to 1.2.32.1056

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
scripts in 7.1.1.
https://jira.talendforge.org/browse/TUP-24129
> fix(TUP-24129)Security vulnerabilities in Job building and contexts

- main/plugins/org.talend.designer.components.localprovider/components/tDotNETInstantiate/tDotNETInstantiate_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDotNETRow/tDotNETRow_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMSAXInput/tMSAXInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMSAXOutput/tMSAXOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOleDbInput/tOleDbInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOleDbOutput/tOleDbOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOleDbRow/tOleDbRow_java.xml
> feat(TDI-42473): change janet-java version to 1.2

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/changeDBVersionForMapROJAIOutputMigrationTask.java
> fix(TBD-9121): migration task for tmaprojaioutput 

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/changeDBVersionForMapROJAIOutputMigrationTask.java
> fix(TBD-9121): migration task for tmaprojaioutput

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
osgi-exclude.properties resource fileis included in org.talend.repository bundle and by this cannot be updated. In some rare case, user need to add an exclusion entry.
This dev adds the opportunity to externalise osgi-exclude.properties
resource file from org.talend.repository bundle better than using the
one included in org.talend.repository budle jar file.
> TESB-26772 Adding a way to externalise osgi-exclude.properties file

- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_end.javajet
https://jira.talendforge.org/browse/TDI-42819
Correct behavior when use log file
> fix(TDI-42819): correct behavior whe use log file

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
https://jira.talendforge.org/browse/TUP-22646
> fix(TUP-22646)Path in Textbox of "To archive file" is incomplete when building job

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToXPathLinker.java
> bugfix(TUP-24249):Added the column but not reflected to json metadata

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
> TESB-26609:Building a route microservice docker with wrong host details

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
> TESB-26824:Fail to deploy cMap route and tHmap job to runtime

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ColumnListController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/controller/SuggestableTableController.java
https://jira.talendforge.org/browse/TUP-21759
> fix(TUP-21759):BuiltInSuggestable table should remove value, when corresponding schema column was removed.

- main/plugins/org.talend.designer.components.localprovider/components/tOracleSP/tOracleSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOracleSP/tOracleSP_main.javajet
https://jira.talendforge.org/browse/TDI-42493
(confusion between DATE & TIMESTAMP)
Correct, separate DATE and TIMESTAMP
> TDI-42493 : add DBType in mapping

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ButtonController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
https://jira.talendforge.org/browse/TUP-24392
> fix(TUP-24392)JDBCInput component not working as expected when values as provided using context

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
Reverts Talend/tdi-studio-se#3822
> Revert "fix(TUP-20936):No properties validation for tcomp components in compile time."

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/DirectoryController.java
> fix(TUP-23077)left border of text of component tFileCopy does not show

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/update/TaCoKitCarFeature.java
https://jira.talendforge.org/browse/TUP-23435
> fix(TUP-23435):Studio path contain a space can't install car file in local patches file.

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONWizard.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToJsonPathLinker.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToXPathLinker.java
different as when created
- [ *] Bugfix
- [* ] No
> bugfix(TUP-24248):when edit the metadata, the display content is

- main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
> fix(TESB-26174): Backport to 7.2 for tRunJob with tESBConsumer

- main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
> fix(TESB-26174): Backport to 7.1 for tRunJob with tESBConsumer

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/EmptyContext.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/contexts/ContextsView.java
- main/plugins/org.talend.designer.rowgenerator/src/main/java/org/talend/designer/rowgenerator/shadow/RowGenContextManager.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToDelimitedProcess.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToXmlProcess.java
https://jira.talendforge.org/browse/TUP-24411
> fix(TUP-24411)Error message: unable to update task config if the Context parameters have same values but different case

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-42522
https://jira.talendforge.org/browse/TDI-42522
> fix(TDI-42522): avoid 65535 issue (#3636)

- main/plugins/org.talend.designer.components.localprovider/components/tCloudStart/tCloudStart_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tCloudStop/tCloudStop_java.xml
https://jira.talendforge.org/browse/TDI-42560
jaxb-api dependency was added (it was excluded from java 9)
> fix(TDI-42560): add jaxb dependency to support java 11

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddRAWFlowTPatternMasking.java
> feat(TDQ-17372): update migration to support batch/streaming job

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/changeDBVersionForMapROJAIOutputMigrationTask.java
> migration task from TBD-9121

- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
https://jira.talendforge.org/browse/TUP-22459
> fix(TUP-22459):TaCoKit component runtime doesn't work until initialize all hidden enums.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorModel.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableToolbarEditorView.java
https://jira.talendforge.org/browse/TUP-20949
> fix(TUP-20949):Property change event is not triggered when user adds/removes column in Table widget.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/TRunjobUtil.java
> bugfix(TUP-23100):Add warning in the tRunjob for recursive jobs

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddEncodingTypeForDQComponentsTask.java
> feat(TDQ-17246) update the migration to update spark job

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_end.javajet
> fix(TBD-9137) : tBigQueryInput does not support backtick in query in

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewComponentFrameworkMigrationTask.java
components
- [ *] Bugfix
- [ *] No
> bugfix(TUP-24326):keyword "__TABLE__" not working for tJDBCxxxx

- main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_begin.javajet
https://jira.talendforge.org/browse/TDI-34818
https://jira.talendforge.org/browse/TDI-34818
> fix(TDI-34818): tEXAOutput doesn't work when use a shared DB connection

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddRAWFlowTDataMasking.java
> Feat     TDQ-17176 Retrieve records "rejected" by the tDataMasking DI

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
https://jira.talendforge.org/browse/TUP-23158
> fix(TUP-23158):Some layouts for Tacokit component isn't correct.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
> feat(TUP-24028)Add Azure datacenter part of the studio connection

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
> bugfix(TUP-24495):columns' order is incorrect if I use 'Used Column'

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
> bugfix(TUP-24311):jvm arguments not reflected on build job

- main/plugins/org.talend.sdk.component.studio-integration/plugin.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitService.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/startup/TacokitLoadComponentsStatusStartup.java
https://jira.talendforge.org/browse/TUP-23217
> fix(TUP-23217):Install a wrong car will make all the car file installed can not work.

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_end.javajet
> Fix(TBD-9137) : 7.2 Cherry pick

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_end.javajet
> fix(TBD-9137) : tBigQueryInput does not support backtick in query

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/TRunjobUtil.java
> bugfix(TUP-24631):There is error when open job with tRunJob in TOS

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
https://jira.talendforge.org/browse/TUP-24084
> fix(TUP-24084):Change the display of the new Couchbase component names.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> fix(TESB-27030): Avoid to add activemq-all lib in OSGi bundle

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddRAWFlowTDataMasking.java
component DI
-change the migration task
> Feat     TDQ-17348 Retrieve records "rejected" by the tDataUnmasking

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importproject/ImportProjectHelper.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/AfterImportProjectUtil.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/ImportProjectAsWizard.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/ImportProjectAsWizardPage.java
https://jira.talendforge.org/browse/TUP-22677
> fix(TUP-22677)import a existing project from Login dialog, the temp folder is not deleted

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
https://jira.talendforge.org/browse/TUP-24084
> fix(TUP-24084):Change the display of the new Couchbase component names. (#3934)

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
> fix(TESB-27046): Job run failed with pure DI license in studio

- main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
> fix(TDI-42061): fix zip4j module name

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessErrorUtil.java
> fix(TUP-24607)Not able to see the component error in the Studio Designer

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java
and enable by system property
https://jira.talendforge.org/browse/TUP-24444
> feat(TUP-24444)Add choice between log4j and log4j2 in project settings

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddRAWFlowTPatternMasking.java
Retrieve records "rejected" by the tPatternUnMasking component in DI job
> Feat    TDQ-17291

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
> TESB-27079:Data Service Micro-service is failing from TMC

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/postgres/PostgresGenerationManager.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTestHelper.java
variable as a parameter
https://jira.talendforge.org/browse/TUP-22361
> fix(TUP-22361)ELTMap bug in column expression while using context

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/ReconcilerStyledText.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/java/TalendJavaSourceViewer.java
https://jira.talendforge.org/browse/TUP-23229
There is issue in Eclipse4.10 CursorLinePainter#paint
CursorLinePainter#updateHighlightLine, the update action is based on
lines in the whole document rather than the visible document, so there
will be issue with new line in VisibleRegion
> fix(TUP-23229): IllegalArgumentException when press enter for tLibraryLoad->Advanced settings->Import

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/JavaProcessUtilTest.java
org.slf4j.spi.LocationAwareLogger.log
https://jira.talendforge.org/browse/TUP-24540
> fix(TUP-24540)java.lang.NoSuchMethodError:

- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
Backport Jira: https://jira.talendforge.org/browse/TDI-43044
Main Jira: https://jira.talendforge.org/browse/TDI-42969
Change logic to retrieve detailed filename
> fix(TDI-42969): change logic to retrieve detailed filename

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> TESB-26951 Dependencies from SubJob are added to manifest of ParentJob

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
> bugfix(TUP-24577):Spark job can't run if it uses a spark joblet

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/JavaProcessUtilTest.java
org.slf4j.spi.LocationAwareLogger.log
https://jira.talendforge.org/browse/TUP-24540
> fix(TUP-24540)java.lang.NoSuchMethodError: (#3978)

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/context/TaCoKitContextProvider.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/toc/TaCoKitTocProvider.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
- test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtilTest.java
https://jira.talendforge.org/browse/TUP-24708
> fix(TUP-24708):Tacokit: Help Content isn't right when select tCouchbaseInput and press F1.

- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
https://jira.talendforge.org/browse/TDI-43020
> fix(TDI-43020):S3 multipart upload minimun value.

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/DebugProcessTosComposite.java
https://jira.talendforge.org/browse/TUP-24740
> fix(TUP-24704)TOS 7.3.1: after import a 7.2.1 project context disappears in Java Debug

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddMissingContextMigrationTask.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/model/migration/AddMissingContextMigrationTaskTest.java
> fix(TUP-24680)Context variable type disappears after changing default

- main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
https://jira.talendforge.org/browse/TDI-43053
> fix(TDI-43053):unify mvn uri

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TUP-24800
> fix(TUP-24800):Upgrade tacokit to release version of 1.1.13

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateContextParameterCommand.java
https://jira.talendforge.org/browse/TUP-24748
> kjwang/Fix TUP-24748 CLONE - Modification in Context Variables is not propagating to all jobs

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java
https://jira.talendforge.org/browse/TUP-24809
> fix(TUP-24809)log4j2 should not be selected an enable when log4j is inactive in project setting

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/hive/HiveGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java
>    fix(TBD-9366): tELTHiveMap doesn't pass context variable properly

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/hive/HiveGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java
Reverts Talend/tdi-studio-se#4013
> Revert "   fix(TBD-9366): tELTHiveMap doesn't pass context variable properly"

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
org.slf4j.spi.LocationAwareLogger.log
https://jira.talendforge.org/browse/TUP-24540
> fix(TUP-24540)java.lang.NoSuchMethodError: (#4018)

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-24784
> fix(TUP-24784):Build error with tRunJob on a spark job.

- main/plugins/org.talend.designer.runprocess/src/main/java/messages.properties
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/DebugProcessTosComposite.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
Language is French
- [ *] Bugfix
- [ *] No
> bugfix(TUP-24728):Date and Time is not displaying when the Preferred

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-24784
> fix(TUP-24784):Build error with tRunJob on a spark job. 

- main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/ProxyCreds.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/ProxyHolder.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/TalendProxyAuthenticator.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/TalendProxySelector.java
> Add talend proxy library

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/LibraryField.java
> fix(TUP-24613)routine section does not allow user to edit required

- main/plugins/org.talend.repository/META-INF/MANIFEST.MF
kjwang/Fix a compile error for TUP-21518
> kjwang/Fix a compile error for TUP-21518

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
https://jira.talendforge.org/browse/TUP-24148
> fix(TUP-24148): tNetsuiteInput throws cast error when switching from use tNetsuiteConnection to use this component

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> fix(TESB-27030): Exclude jms library when it is used from tRunJob

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TUP-24917
> fix(TUP-24917):Upgrade tacokit to 1.1.14.

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
> TESB-27139:"Could not find the context Default" is shown in runtime when

- main/plugins/org.talend.designer.components.localprovider/components/tSetProxy/tSetProxy_main.javajet
> fix(TDI-40977): Fix https proxy usage for custom mode

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java
https://jira.talendforge.org/browse/TUP-24885
> fix(TUP-24885):tELTTeradataMap: Output table : Expression & Column set to blank if you add a Column without Expression.

- test/plugins/org.talend.repository.test/src/org/talend/repository/model/migration/UpgradePasswordEncryptionAlg4ItemMigrationTaskTest.java
https://jira.talendforge.org/browse/TUP-24212
> kjwang/Fix TUP-24212 Create migration for CryptoHelper to AES upgrading

- main/plugins/org.talend.repository/plugin.xml
https://jira.talendforge.org/browse/TDI-42493 
(versions corrections)
> TDI-42493 : correct versions

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/AbstractProcessProvider.java
> bugfix(TUP-24884):Spark Joblets cannot be built within Parent DI job

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
> fix (TESB-25283): backport docker esb fixes to master

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
https://jira.talendforge.org/browse/TBD-9366
> fix(TBD-9366): tELTHiveMap doesn't pass context variable properly

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/context/TaCoKitContextProvider.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/toc/TaCoKitTocProvider.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
https://jira.talendforge.org/browse/TUP-24708
> fix(TUP-24708): improve for Tacokit exists Help Content .

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
> TESB-27123:Context does not transmit to Job called by route in the second call in runtime

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
> fix(TBD-9372): methods added to know if tMap can work in dataset or not

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/java/JavaProcessorUtilitiesTest.java
Conflicts:
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
> fix(TUP-21596):exclude tLibraryLoad jars for independent subjob. (#3148)

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
> fix(TBD-9372): fix code generation error when tMap has only one input

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
> fix(TBD-9372): refacto of condition

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
main class" when imported the project export from 6.3 to 7.2
https://jira.talendforge.org/browse/TUP-24786
> fix(TUP-24786)Jobs are failing with the error "Cannot find or load the

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/studio/process/TaCoKitNode.java
https://jira.talendforge.org/browse/TUP-24625
> fix(TUP-24625):Configuration migration doesn't work for tacokit components.

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/table/InputTable.java
> bugfix(TUP-24937):Propagate changes in tELTInput schema to tELTMap

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
> upgrade tacokit 1.1.14

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
https://jira.talendforge.org/browse/TUP-20939
> fix(TUP-20939): Actions are called twice due 2 sets of ElementParameters

- test/plugins/org.talend.repository.test/src/org/talend/repository/model/migration/UpgradePasswordEncryptionAlg4ItemMigrationTaskTest.java
https://jira.talendforge.org/browse/TUP-24221
> kjwang/Fix TUP-24221 Fix a junit

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
> fix(TBD-9492):fix condition that broke graphical build of nodes

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/CheckLogManamger.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobJavaScriptsManager.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/ui/utils/UpdateLog4jJarUtilsTest.java
https://jira.talendforge.org/browse/TUP-24894
> feat(TUP-24894)Automatically review / changes slf4j/log4j dependencies

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendJavaEditor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/TRunjobUtil.java
> Jding/tup 24732 studio code tab doesn't show error

- main/plugins/org.talend.designer.components.localprovider/components/tMap/tMap_main.inc.javajet
https://jira.talendforge.org/browse/TDI-43105
> fix(TDI-43105):tmap jdbc join timestamp

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
> TESB-27309:During the publishing with CI feature we got an error of

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
> commons-logging.jar need not to remove

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendJavaEditor.java
https://jira.talendforge.org/browse/TUP-24732
> fix(TUP-24732) Studio Code tab doesn't generate code/show errors in Job

- main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml
https://jira.talendforge.org/browse/TDI-43167
https://jira.talendforge.org/browse/TDI-43167
> fix(TDI-43167): add back slf4j bridge for special components for the unactive log4j case.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpgradePasswordEncryptionAlg4ItemMigrationTask.java
https://jira.talendforge.org/browse/TUP-25101
> TUP-25101 The key store password missing of component "tSetKeyStore" when import into studio

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
> feat(TUP-24894) add back some jars to the end classpath list.

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
> fix(TBD-9542): support tMap with dummyMaps

- main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet
https://jira.talendforge.org/browse/TDI-43058
> fix(TDI-43058):tFileFetch apply trustStore

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/table/InputTable.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java
https://jira.talendforge.org/browse/TPS-3542
> TPS-3542 : [7.2.1] ELTMap / Teradata connexion fixes

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-24842
> Fix TUP-24842 Switch jobscript and run job get error : NoClassDefFoundError: org/talend/daikon/crypto/Encryption

- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/snowflake/unifier.json
No Component tSnowflakeCommit / tSnowflakeRollback.
https://jira.talendforge.org/browse/TDI-41954
Put tSnowflakeCommit / tSnowflakeRollback under tDBCommit & tDBRollback family
> feat(TDI-41954): add commit and rollback to unified

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/AbstractJSONFileStepForm.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileOutputStep1Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep1Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep2Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep3Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/action/ImportTreeFromJSONAction.java
https://jira.talendforge.org/browse/TUP-25052
> fix(TUP-25052): File json miss source schema when after do export to context.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
https://jira.talendforge.org/browse/TUP-25109
Guess table schema of redshift database by executing sql query.
> bugfix(TUP-25109) redshift guess schema by executing query.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-25099
> fix(TUP-25099):NPE when using joblets from reference Projects.

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/tabs/TabFolderEditors.java
https://jira.talendforge.org/browse/TUP-25218
> fix(TUP-25218):tELTXXXMap: Output table : Expression & Column set to blank if you add a Column without Expression on Mac OS X.

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/tabs/TabFolderEditors.java
https://jira.talendforge.org/browse/TUP-25218
> fix(TUP-25218):tELTXXXMap: Output table : Expression & Column set to blank if you add a Column without Expression on Mac OS X

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> fix(TBD-9578): option to skip header is added for csv in tBigQueryBulkExec

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> fix(TBD-9578): csv option were not called

- main/plugins/org.talend.designer.components.libs/libs_src/talend_DB_mssqlUtil/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend_DB_mssqlUtil/src/main/java/org/talend/designer/components/util/mssql/MSSqlGenerateTimestampUtil.java
- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlInput/tMSSqlInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHInput/tSQLDWHInput_java.xml
- main/plugins/org.talend.libraries.custom/pom.xml
https://jira.talendforge.org/browse/TDI-43174
https://jira.talendforge.org/browse/TDI-43174
> fix(TDI-43174): tMSSqlinput process datetimeoffset data type failed when use DST timezone as localtime

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-25099
> fix(TUP-25099):NPE when using joblets from reference Projects. (#4132)

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> fix(TBD-9578): cherry pick

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> backport(TBD-8951): backport skip header for BigQueryBulkExec

- main/plugins/org.talend.designer.components.localprovider/components/tAS400Connection/tAS400Connection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAccessConnection/tAccessConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonAuroraConnection/tAmazonAuroraConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlConnection/tAmazonMysqlConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleConnection/tAmazonOracleConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleConnection/tAmazonOracleConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Connection/tDB2Connection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAConnection/tEXAConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFirebirdConnection/tFirebirdConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tGreenplumConnection/tGreenplumConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tInformixConnection/tInformixConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tIngresConnection/tIngresConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tInterbaseConnection/tInterbaseConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMysqlConnection/tMysqlConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tNetezzaConnection/tNetezzaConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tParAccelConnection/tParAccelConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusConnection/tPostgresPlusConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHConnection/tSQLDWHConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQLiteConnection/tSQLiteConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseConnection/tSybaseConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tTeradataConnection/tTeradataConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseConnection/tVectorWiseConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaConnection/tVerticaConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/HelpClass/HelpClass.javajet
wwang-talend/TDI-43211
wwang-talend/TDI-43211
> fix(TDI-43211): SharedDBConnectionLog4j use log4j1 api, should use slf4j

- main/plugins/org.talend.designer.components.libs/libs_src/talend-ws/pom.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
- main/plugins/org.talend.designer.components.localprovider/pom.xml
> feat(TDI-43088): Update cxf deps for msCRM and webservice components

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/TRunjobUtil.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
https://jira.talendforge.org/browse/TUP-24732
> fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job

- main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
> fix(TDI-41651): Add where clause support for update query

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UpgradeParameterHelper.java
https://jira.talendforge.org/browse/TUP-25186
Revert code changes
> bugfix(TUP-25186) Revert previous changes

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-24749
> fix(TUP-24749): [7.2.1] issue to download component jar via https proxy

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet
https://jira.talendforge.org/browse/TDI-43296
https://jira.talendforge.org/browse/TDI-43296
> fix(TDI-43296): Generate a sample logging file for runtime lineage cause compile error

- main/plugins/org.talend.designer.core/plugin.xml
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/FillTRunJobReferenceParametersMigrationTask.java
https://jira.talendforge.org/browse/TUP-25257
Set back jobid for trunjob
> backport72(TUP-25257) Fix missing jobid for trunjob

- main/plugins/org.talend.designer.core/plugin.xml
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/FillTRunJobReferenceParametersMigrationTask.java
https://jira.talendforge.org/browse/TUP-25257
Set back jobid for trunjob
> backport71(TUP-25257) Fix missing jobid for trunjob

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> patch(tps-3592): cherry pick

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> backport(TPS-3600):  tBigQueryBulkExec get error when run with big file

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
https://jira.talendforge.org/browse/TUP-25344
> fix(TUP-25344): can't logon project after change workspace if set log4j2

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TUP-25227
> fix(TUP-25227):Changing the joblet name is not reflected properly.

- main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_messages.properties
https://jira.talendforge.org/browse/TDI-43264
> Fix(TDI-43264):Fix issues.

- main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldIn/tWriteXMLFieldIn_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldIn/tWriteXMLFieldIn_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_main.javajet
https://jira.talendforge.org/browse/TDI-43266
https://jira.talendforge.org/browse/TDI-43266
> fix(TDI-43266): Studio returns exit code 0 when OutOfMemoryError in routine occurs

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
until you deselect component
https://jira.talendforge.org/browse/TUP-25350
> bugfix(TUP-25350)Show if for opened list: active values are not updated

- main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml
> fix(TBD-8343):fix version of jars for tGSConnection

- main/plugins/org.talend.repository.generic/src/main/java/messages.properties
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizardPage.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/context/ContextComposite.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/httpsProxy/HttpsProxyComposite.java
> feat(TUP-24382)Enable HTTPS with authentication

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dnd/CompleteDropTargetListener.java
https://jira.talendforge.org/browse/TUP-25218
> fix(TUP-25218):tELTXXXMap: Output table : Expression & Column set to blank on Mac OS X

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java
https://jira.talendforge.org/browse/TUP-25406
> fix(TUP-25460)schema hardcoded in guess query in tDBInput component

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
- main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/src/main/java/org/talend/job/audit/JobAuditLogger.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/src/main/java/org/talend/job/audit/JobContextBuilder.java
https://jira.talendforge.org/browse/TDI-43101
https://jira.talendforge.org/browse/TDI-43101
> fix(TDI-43101): revert it as only a poc research topic, should not merge

- main/plugins/org.talend.designer.runprocess/resources/log/log4j2.properties_template
> fix(TUP-25453)color setting for log4j2

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/AbstractJavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-25343
> Kjwang/ tup 25343 database can not dataview

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
https://jira.talendforge.org/browse/TUP-25457
> fix(TUP-25457)Harden RunTrace deserialization

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
https://jira.talendforge.org/browse/TUP-25237
Clear modules per job before generating pom
> backport(TUP-25237) javax.mail cannot be resolved to a type at Studio Runtime

- main/plugins/org.talend.repository/resources/osgi-exclude.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> fix(TESB-27266):Exclude tdm-lib-di from REST DS, but keep package info

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
sure rules file can be contain when publish.
> fix(TPS-3611): backport a commit from TDQ-15215 on patch/7.0.1 to make

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/TableEntriesManager.java
generate an incorrect dsiplay
- [ *] Bugfix
- [ *] No
> bugfix(TUP-25106):when creating an onsubjobOk link with tELTMap, this

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
> fix(TBD-9677)under the log4j2, Run some job with spark 2.4 local get

- test/plugins/org.talend.repository.test/src/org/talend/repository/handler/BuildJobHandlerTest.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/ui/utils/UpdateLog4jJarUtilsTest.java
> fix log4j failed junits

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/Log4jPrefsSettingManager.java
https://jira.talendforge.org/browse/TUP-25504
> fix(TUP-25504)Active log4j by default

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
> fix(TUP-25530)Log4j error when execute a job on datatabricks

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java
> bugfix(TUP-25278):Issues about delete columns in tELTMap with alias

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/postgres/PostgresGenerationManager.java
https://jira.talendforge.org/browse/TUP-25411
> fix(TUP-25411):Table name and field should in double quotes in tELTPostgresqlMap.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
> fix(TUP-25541)tMap TUJs are broken for the ClassNotFound

- main/plugins/org.talend.designer.runprocess/resources/log/log4j2.properties_template
> fix(TUP-25483)color default setting not work on ubuntu

- main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
https://jira.talendforge.org/browse/TDI-43396
https://jira.talendforge.org/browse/TDI-43396
> fix(TDI-43396): Compile error for S3 and tFileFetch TUJs when log4j is not enabled at default

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/DbTableController.java
* Add usage of alternate schema during table selection
> feat(TUP-25053): use alternate schema in DB Output

- main/plugins/org.talend.designer.components.localprovider/components/tGPGDecrypt/tGPGDecrypt_messages.properties
https://jira.talendforge.org/browse/TDI-42408
> Fix(TDI-42408):rename for tGPGDecrypt.

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TUP-25575
> fix(TUP-25575):Upgrade tacokit to 1.1.15.

- main/plugins/org.talend.designer.components.localprovider/components/tNormalize/tNormalize_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tNormalize/tNormalize_main.javajet
https://jira.talendforge.org/browse/TDI-43323
> Fix(TDI-43323):Fix issue of duplicated variables.

- main/plugins/org.talend.sdk.component.studio-integration/META-INF/MANIFEST.MF
- main/plugins/org.talend.sdk.component.studio-integration/build.properties
- main/plugins/org.talend.sdk.component.studio-integration/plugin.properties
https://jira.talendforge.org/browse/TUP-25502
> fix(TUP-25502): import dialog i18n error

- main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/RoutineImportHandler.java
> bugfix(TUP-22500):jars already existed on nexus still try to upload

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeCDCTypeForOracle18TDI43319.java
* Add migration task for old jobs with OracleCDC component
> fix(TDI-43319): CDC Oracle wrong settings

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/ProjectSettingManager.java
file) uses a hardcoded encoding of ISO-8859-15
> bugfix(TUP-25035)Implicit tContextLoad feature (with selection from

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java
https://jira.talendforge.org/browse/TUP-25409
When CI builder to generate source code for items, now generate for main job only, does not generate source code for children jobs. 
> bugfix(TUP-25409) Improve building speed of CI builder

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java
https://jira.talendforge.org/browse/TUP-24905
> fix(TUP-24905): Studio automatically set password when set up multiple login connections

- main/plugins/org.talend.designer.components.localprovider/components/tHadoopConfManager/tHadoopConfManager_begin.javajet
parameter in the Hadoop conf wizard
https://jira.talendforge.org/browse/TUP-25226
> feat(TUP-25226): Make the hadoop conf jar path a contextualizable

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/context/TaCoKitContextProvider.java
https://jira.talendforge.org/browse/TUP-24727
> fix(TUP-24727):Use shortcut F1 to search help document on component then throw errors

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/StatsAndLogsManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/ProjectSettingManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/StatsAndLogsHelper.java
https://jira.talendforge.org/browse/TUP-24405
> fix(TUP-24405):stats/logs database ui is not right when choose teradata database

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> bugfix(TUP-21691):Run job fail after drag it out from a folder.

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor4Component.java
https://jira.talendforge.org/browse/TUP-23672
> fix(TUP-23672):Check connection button for tacokit integration to Studio

- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
customer artifact repository
https://jira.talendforge.org/browse/TUP-24057
> feat(TUP-24057)There is no error message when studio can't connect to

- main/plugins/org.talend.repository.ftp/src/messages.properties
- main/plugins/org.talend.repository.ftp/src/org/talend/repository/ftp/ui/wizards/forms/FTPForm.java
bugfix(TUP-24029):[FTP] Connection wizard add timeout property
- [ *] Bugfix
- [ *] No
> bugfix(TUP-24029):[FTP] Connection wizard add timeout property (#3864)

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/controller/TaCoKitValueSelectionController.java
https://jira.talendforge.org/browse/TUP-25382
> fix(TUP-25382):More than one dialog pop up when quickly click the button more than once.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java
> fix(TUP-25524)issue for TOS Log4j

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/DesignerCoreService.java
- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/ui/utils/UpdateLog4jJarUtilsTest.java
pop up let me download or browse in.
https://jira.talendforge.org/browse/TUP-25338
> fix(TUP-25338)Run job use sap miss jar slf4j-api-1.7.16 and there is no

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
> fix(TUP-25572) improve the performance of import job

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
"org.slf4j.impl.StaticLoggerBinder"
> fix(TUP-21660)SLF4J: Failed to load class

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
https://jira.talendforge.org/browse/TUP-25229
> fix(TUP-25229):Some TCOMPV0's components should not has "Use this Component" in Connection Component

- main/plugins/org.talend.sdk.component.studio-integration/META-INF/MANIFEST.MF
org.talend.sdk.component.studio-integration
> fix(TUP-21660)add slf4j-simple.jar to Bundle-ClassPath in the plugin

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java
stats&logs
- [* ] Bugfix
- [* ] No
> bugfix(TUP-24510):Studio can't use JDBC connection to trace job

- main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/editors/RouteResourceEditor.java
> bugfix(TUP-24413):The tab name of resource is changed

- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDataprocManage/tGoogleDataprocManage_java.xml
> fix(TDI-42875): Add missing log4j to component deps

- test/plugins/org.talend.designer.mapper.test/src/org/talend/designer/components/tisprovider/ReplaceParallelizationNodeForTMapTest.java
getting inserted as NULLs
https://jira.talendforge.org/browse/TUP-25650
> fix(TUP-25650)On enabling Parallelization on tDBInput, the data is

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
https://jira.talendforge.org/browse/TUP-25707
- Set Left to Right text direction for destionation combo
> bugfix(TUP-25707) Set correct text direction for destination combo

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
> change back log4j version to 2.12.1

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
https://jira.talendforge.org/browse/TUP-25820
> fix(TUP-25820)TMC: error show in error log when logon TMC project

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
https://jira.talendforge.org/browse/TUP-25727
> fix(TUP-25727):Dataviewer for hdfs schema failed if it's checked webHDFS encryption

- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinBulkExec/tSalesforceEinsteinBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinOutputBulkExec/tSalesforceEinsteinOutputBulkExec_java.xml
for jira: https://jira.talendforge.org/browse/TDI-43516
update api to 47.0
> feat(TDI-43516):Salesforce api update to 47.0

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
https://jira.talendforge.org/browse/TDI-43509
https://jira.talendforge.org/browse/TDI-43509
> fix(TDI-43509): Upgrade redshift driver for 7.3.1

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
> fix(TESB-27912):[CI]Cannot skip docker for DemoRESTConsumer

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java
https://jira.talendforge.org/browse/TUP-25862
> fix(TUP-25862)Change client ip of SDK server from localhost to 127.0.0.1

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-25649
> fix(TUP-25649):ERROR when Job in MDM project calling Job in Reference DI project:import routines.DataQuality cannot be resolved.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java
https://jira.talendforge.org/browse/TUP-25427
> fix(TUP-25427)active or deactivate log4j2 need to reopen the child job

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/ui/ComponentsPreferencePage.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ComponentsHelpUtil.java
https://jira.talendforge.org/browse/TUP-25786
> feat(TUP-25786): Enable online help

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
> fix(TESB-27583): Maven nature is added to child Job for OSGI build

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/debug/JobLaunchConfigurationDelegate.java
project
https://jira.talendforge.org/browse/TUP-21555
> fix(TUP-21555)Error pops up if run job during opening another job in git

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
https://jira.talendforge.org/browse/TUP-25533
> fix(TUP-25533):Talend Component Kit Components cannot be renamed in Studio.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
store path contain space
- [ *] Bugfix
- [ *] No
> bugfix(TUP-25768):Ubuntu:Switch to a new workspace not work if Studio

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/studio/process/TaCoKitNode.java
https://jira.talendforge.org/browse/TUP-25545
> fix(TUP-25545): tWorkdayInput --> `Mode` and `WQL Query` can't edit when use metadata

- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java
created project after 7.3.1.
https://jira.talendforge.org/browse/TUP-25843
> fix(TUP-25843)Hide log4j/log4j2 combox when it is not enabled for new

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/TaCoKitGenericProvider.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/ComponentService.java
https://jira.talendforge.org/browse/TUP-25152
> fix(TUP-25152): component does not display in palette, after deployed to the studio 7.2.1

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
error log list if Studio store path contain space
- [ *] Bugfix
- [ *] No
> bugfix(TUP-25764):Win:Cannot load component "tImpalaOutput" error in

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-25649
> fix(TUP-25649):ERROR when Job in MDM project calling Job in Reference project:import routines.DataQuality cannot be resolved.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java
Close"
https://jira.talendforge.org/browse/TUP-25910
> fix(TUP-25910)NPE error shows in ErrorLog view after clicking "Apply And

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-25784
> fix(TUP-25784): Couchbase guess schema failed

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ComponentsHelpUtil.java
> workItem(TUP-25786)add snapshot

- main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
> fix(TDI-43583): Do not set error code if not fail on child error

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputPositional/tFileOutputPositional_begin.javajet
https://jira.talendforge.org/browse/TDI-43484
Check if related tSetDynamic guess schema from file, if yes throw RuntimeException
> fix(TDI-43484): tSetDynamic schema cant work with tFile***Positional

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ComponentsHelpUtil.java
https://jira.talendforge.org/browse/TUP-25786
> Fix TUP-25786 Enable online help (Remove temporary hard code version)

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java
> feat(TUP-25834)Upgrade postgres to support v12

- main/plugins/org.talend.designer.components.localprovider/components/tHiveConnection/tHiveConnection_java.xml
> fix(TBD-9886): lib conflict with tS3Connection

- main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml
https://jira.talendforge.org/browse/TDI-43089
https://jira.talendforge.org/browse/TDI-43089
> fix(TDI-43089): Upgrade to ActiveMQ 5.15.10 in tMom/tSAP components

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> fix(TUP-25951)Syncing of project and pom files doesnt happen initally

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
component
- [ *] Bugfix
- [ *] No
> bugfix(TUP-25864):Too many required jars for tVerticaConnection

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/imports/ZipToFileUtil.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/ZipToFile.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JarBuilder.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/utils/ZipFileUtils.java
https://jira.talendforge.org/browse/TUP-24536
Validate unzip file path, error out if any file pathes not contained inside target directory.
> bugfix(TUP-24536) Studio is vulnerable to "Zip Slip" style attacks

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ComponentsHelpUtil.java
https://jira.talendforge.org/browse/TUP-25985
> TUP-25985 TOS: No need to pop up install plugin page when switch from online help to offline help.

- main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_main.javajet
https://jira.talendforge.org/browse/TDI-43231
Logging order were changed
> fix(TDI-43231): change logging order

- main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/SQSClient.javajet
https://jira.talendforge.org/browse/TDI-43409
https://jira.talendforge.org/browse/TDI-43409
> fix(TDI-43409): Enable AWS ECS role for tSQS component

- main/plugins/org.talend.designer.components.localprovider/components/templates/Amazon/CredentialsProvider.javajet
https://jira.talendforge.org/browse/TDI-43410
https://jira.talendforge.org/browse/TDI-43410
> fix(TDI-43410): Enable AWS ECS role for tAmazonEMR component

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/migration/ChangeMysqlVersionForProjectSetting.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeMysqlJarReference4MysqlComponents.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdateJobSettingsForMysqlMigrationTask.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/audit/SupportDBVersions.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/ConnectionUtilTest.java
> workItem(TUP-25915)Upgrade MySQL driver

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> remove synchronized

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> backpot72(TUP-25951)Syncing of project and pom files doesnt happen

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> backport71(TUP-25951)Syncing of project and pom files doesnt happen

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> backport70(TUP-25951)Syncing of project and pom files doesnt happen

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/ActivateSubjobOneComponentAction.java
> workItem(TUP-21195)replace all forms of subjob with subJob

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
https://jira.talendforge.org/browse/TUP-25856
> fix(TUP-25856):Error msg show under error log list when try to check couchbase help doc

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java
> bugfix(TUP-25990):Support MariaDB 10.X

- main/plugins/org.talend.designer.components.localprovider/components/tXSDValidator/tXSDValidator_main.javajet
> fix(TDI-43611): include all columns to reject row

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/SqlMemoController.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/actions/ContextModeAction.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/AbstractSQLEditorComposite.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLBuilderDialog.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLBuilderEditorComposite.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLBuilderTabComposite.java
https://jira.talendforge.org/browse/TUP-25519
> fix(TUP-25519): SQL builder in Enterprise studio context mode works differently to Talend Open studio

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
> fix(TDi-43605): Fix adding tcompv0 components into tRest globalMap copy

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ComponentsHelpUtil.java
https://jira.talendforge.org/browse/TUP-26023
> fix(TUP-26023):Studio should open online help based on language

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpgradePasswordEncryptionAlg4ItemMigrationTask.java
created from 721
- [ *] Bugfix
- [ *] No
> bugfix(TUP-26031):Cannot connect successfully for mongDB which is

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-25943
> Fix: TUP-25943 tELTMap generated query has extra symbols generated

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/JavaRoutineSynchronizer.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/StandAloneTalendJavaEditor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/routine/SetupProcessDependenciesRoutinesDialog.java
- main/plugins/org.talend.designer.rowgenerator/src/main/java/org/talend/designer/rowgenerator/shadow/RowGenProcess.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/ExportProcessorHelper.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToDelimitedProcess.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToXmlProcess.java
- main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/AnyIntoLogRowProcess.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/MavenDeploymentConfigurationProjectSettingPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/ConfigRoutineLibraryAction.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/RefreshAction.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/metadata/DetecteViewImpactAction.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobJavaScriptsManager.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobPerlScriptsManager.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/routines/NewRoutineWizardPage.java
https://jira.talendforge.org/browse/TUP-25986
remove pigudf related
> fix(TUP-25986)Can't import attached job

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
https://jira.talendforge.org/browse/TUP-25271
> fix(TUP-25271):display error/warin message on tacokit component .

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/postgres/PostgresGenerationManager.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/postgres/PostgresGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-25777
> Kjwang/fix tup 25777 interger values are read as string (#4403)

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-25943
> Fix: TUP-25943 tELTMap generated query has extra symbols generated 

- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/postgres/PostgresGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-26060
> Fix TUP-26060 Add junit for TUP-25777 and TUP-25943

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/DbInfo.java
> bugfix(TUP-25859):Upgrade vertica support to 9.3 - metadata

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
> fix(TBD-9884) : Missing log42 conf on Yarn side

- main/plugins/org.talend.rcp.branding.tos/plugin.properties
- main/plugins/org.talend.rcp.branding.tos/resources/license.txt
https://jira.talendforge.org/browse/TUP-26123
Update copyright date to 2020
> bugfix(TUP-26123) Update copyright date

- main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_begin.javajet
https://jira.talendforge.org/browse/TBD-9823
Fixed
> fix(TBD-9823): tBigQuerySQLRow can't generate code

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
https://jira.talendforge.org/browse/TUP-25777
> kjwang/Fix TUP-25777 Interger values are read as string after applying TPS-3637 (Fix failed tuj)

- main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_main.javajet
https://jira.talendforge.org/browse/TDI-43670
https://jira.talendforge.org/browse/TDI-43670
> fix(TDI-43670): tSSH component hangs if Command takes time to complete

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemovePigudfModulesMigrationTask.java
remote project from old version to 731
https://jira.talendforge.org/browse/TUP-26113
> fix(TUP-26113)Can't generate by CI due to remove pigudf after migrate a

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/assembly_job_template.xml
> TESB-28192 Dataservice Microservice built ZIP has wrong structure

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
> TESB-28209 DemoServiceConsumer build fails when build type is "Standalone Job"

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
> fix(TESB-27578): fix feature.xml is missing in nexus

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
> fix(TUP-26167)Log4j2: confirm message pop up when build job if activate log4j2 for TOS

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
https://jira.talendforge.org/browse/TUP-25777
> kjwang/Fix TUP-25777 Interger values are read as string after applyingg 

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
> fix(TESB-28240): Use final name for osgi bundle build pom

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
> fix(TESB-28247): consumer job is missing feature.xml by CI

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
https://jira.talendforge.org/browse/TUP-25229
> fix(TUP-25229):revert the fix of "Use this Component"

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java
> fix(TUP-26192)supply choice of log4j1 / 2

- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/actions/EditQueriesAction.java
> bugfix(TUP-26018):No Edit queries in Offline Mode

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
> bugfix(TUP-26160):NullPointerException when logon git project

- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-25777
> Fix TUP-25777 Interger values are read as string after applying TPS-3637 (Improve the junit)

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/odata/DynamicsCRMClient.java
* Update libraries versions
* Create required methods
> feat(TDI-43423): Azure Dynamics 365 CRM component

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameELTJDBCComponentsMigrationTask.java
> bugfix(TUP-25959):Incorrect message is observed in the tWarn component

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/ui/ComponentsPreferencePage.java
https://jira.talendforge.org/browse/TUP-26146
> TUP-26146 Online Help: Cancle not work if uncheck "Enable online help for components" at Perference page

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/java/JavaProcessorTest.java
https://jira.talendforge.org/browse/TUP-26223
If there are multiple version of same artifacts in the classpath, this fix will remove all of lower version of jars, keep only one maxum version jar.
> bugfix(TUP-26223) Remove lower version artifacts from classpath

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep2Form.java
Preview' for Json with context mode
> bugfix(TUP-26207):The tip message is not proper when use 'Refresh

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/shadow/JSONShadowProcessHelper.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep2Form.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/util/JSONConnectionContextUtils.java
> bugfix(TUP-26206):'Refresh Preview' can not work for Json with context

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
> fix(TESB-28166): [CI] Missig fieature.xml in esb consumer and service

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/odata/DynamicsCRMClient.java
* Add cleaning of links to delete
* Deprecate method
* Add new method to process delete navigation links separately
> fix(TDI-43796): Azure empty lookup problems

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-26264
> Kjwang/fix tup 26264 t elt map generated query has extra symbols (#4489)

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-26189
> fix(TUP-26189): [7.2.1] snowflake metadata connection with proxy failure

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/PropertyTypeController.java
https://jira.talendforge.org/browse/TUP-26156
> fix(TUP-26156)tCreateTable change DBType and Property Type not work

- main/plugins/org.talend.repository/resources/osgi-exclude.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> fix(TESB-28255): Solve reference error for java ws and mdm lib in java 8

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbMapSqlConstants.java
https://jira.talendforge.org/browse/TPS-3715
> TPS-3715 : tELTJDBC** generating wrong sql (TUP-25672)

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
> Set logger level in org.talend.designer.codegen

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
> fix(TUP-23956)createTable should not use Redshiftsso connection

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateDatesPatternAccordingToDeletedTimestampOption.java
> fix(TBD-10158): fix migration task

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/BigQuery/BigQueryHelper_ServiceAccount.javajet
Error when REPEATED value type in big query result (multi value)
Ok with REPEATED values.
- x ] Bugfix
> fix(TDI-43785) - big query repeated value managed

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
https://jira.talendforge.org/browse/TUP-26193
> fix(TUP-26193):Can`t find the connection by the key.

- main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_java.xml
> Fix(TDI-31017): Added short UUID in filename pattern.

- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
Use setNString method for NVARCHAR and NCHAR columns only for MS driver
tdboutput for MsSQL uses the setNString method for ncahr and nvarcher columns
setNString method is used only when the driver is MS
- [X ] Bugfix
- [X ] No
> TDI-43764 : MsSQL NVARCHAR

- main/plugins/org.talend.repository/resources/osgi-exclude.properties
> fix(TESB-28385): Revert to use Saxon-HE in studio but exclude in runtime

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
> TESB-28130:Duplicate dependencies in POM.xml for routes lead to compile issues

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
> TESB-28130:Duplicate dependencies in POM.xml for routes lead to compile

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/GEFPasteAction.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/MultiplePasteCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/NodesPasteCommand.java
https://jira.talendforge.org/browse/TUP-26399
> Fix TUP-26399 Items in Studio get deleted and cannot be recovered, even if items are locked

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
https://jira.talendforge.org/browse/TDI-43851
> fix(TDI-43851): hide csvSchema in metadata editor

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
> TESB-25377:CI-Builder generates bad job's jar if job's build type is Standalone

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java
This PR is to prevent the 'Standalone' type to show up as Deployment option for Jobs with tRouteInput
> TESB-28446 preventing the 'Standalone' type to show up as Deployment option for Jobs with tRouteInput

- main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForOutput.javajet
> Fix(TDI-30526): Fix logger message for listed DB .

- main/plugins/org.talend.designer.components.libs/libs_src/azure-utils/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/azure-utils/src/main/java/org/talend/components/azure/runtime/token/AzureActiveDirectoryTokenGetter.java
> feat(TDI-43218): Extract token-retrieve to the utils lib

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/ManageResourcePanel.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/service/ResourcesDependenciesService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtilTest.java
https://jira.talendforge.org/browse/TUP-26231
> fix(TUP-26231)Relative path not working in Talend v721

- main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/ui/FOXUI.java
> fix column names are same

- main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/ui/FOXUI.java
> fix column names are same (#4551)

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
artifact repository set in administrator
https://jira.talendforge.org/browse/TUP-26576
> fix(TUP-26576):Warning pops up cannot connect to the user libraries

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/ManageResourcePanel.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/service/ResourcesDependenciesService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtilTest.java
* fix(TUP-26231)Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
* fix(TUP-26231)Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
* fix(TUP-26231)Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
* fix(TUP-26231):Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
Conflicts:
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
**Please check if the PR …
> fix(TUP-26231)Relative path not working in Talend v721 (#4530)

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
https://jira.talendforge.org/browse/TDI-32442
Fix read real values issue after fixing Date
Launched tuj run on ttp-dev. Build №9694
> fix(TDI-32442): add missing else block

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
> Temp tps 3845

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
Reverts Talend/tdi-studio-se#4565
> Revert "Temp tps 3845"

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-25963
> fix(TUP-25963)Spark jobs - LOG4J_RUN_LEVEL not available in item

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
https://jira.talendforge.org/browse/TUP-26580
> fix(TUP-26580):DI job with Big Data components fail when using the custom hadoop conf file location feature.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ProjectRefSettingPage.java
reference job even after we delete it from the main job
> bugfix(TUP-26475):Job is referring to the joblet present in the

- main/plugins/org.talend.designer.dbmap/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.dbmap/model/dbmap.ecore
- main/plugins/org.talend.designer.dbmap/model/dbmap.genmodel
- main/plugins/org.talend.designer.dbmap/plugin.xml
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/AbstractDBDataMapTable.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DBMapData.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DBMapperTableEntry.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DbmapFactory.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DbmapPackage.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/FilterEntry.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/InputTable.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/OutputTable.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/AbstaceDBInOutTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/AbstractDBDataMapTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DBMapDataImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DBMapperTableEntryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DbmapFactoryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DbmapPackageImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/FilterEntryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/InputTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/OutputTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/VarTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/util/DbmapResourceFactoryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/util/DbmapSwitch.java
> fix(TUP-26476)tELTMap Group By in Where Clause

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
https://jira.talendforge.org/browse/TPS-3909
> TPS-3909:[7.3.1] DI job with Big Data components fail when using the custom hadoop conf file location feature(TUP-26580)

- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_main.javajet
Transform json object to string.
Keep object level.
> fix(TDI-43408) : not a string if content

- main/plugins/org.talend.designer.dbmap/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.dbmap/model/dbmap.ecore
- main/plugins/org.talend.designer.dbmap/model/dbmap.genmodel
- main/plugins/org.talend.designer.dbmap/plugin.xml
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/AbstractDBDataMapTable.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DBMapData.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DBMapperTableEntry.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DbmapFactory.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DbmapPackage.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/FilterEntry.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/InputTable.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/OutputTable.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/AbstaceDBInOutTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/AbstractDBDataMapTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DBMapDataImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DBMapperTableEntryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DbmapFactoryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DbmapPackageImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/FilterEntryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/InputTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/OutputTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/VarTableImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/util/DbmapResourceFactoryImpl.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/util/DbmapSwitch.java
Reverts Talend/tdi-studio-se#4542
> Revert "fix(TUP-26476)tELTMap Group By in Where Clause"

- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_main.javajet
https://jira.talendforge.org/browse/TDI-43918
https://jira.talendforge.org/browse/TDI-43918
> fix(TDI-43918): fix the risk of drop table if exception appear

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
> chore(TDI-43933): update axis2 version

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
https://jira.talendforge.org/browse/TPS-3921
> TPS-3921: tELTHiveMap doesn't pass context variable properly (TUP-24955)

- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_finally.javajet
* Handle error and quick exit with catch-finally block
but child thread proceed working so wait for it end
> fix(TDI-37349): Join thread in the finally block

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/service/GenericService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentParameter.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentParameterValue.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleGenricComponentManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobContextLoadComponent.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
> fix(TUP-26388)Amazon Redshift Driver class not working with Implicit

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/ManageResourcePanel.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/service/ResourcesDependenciesService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtilTest.java
* fix(TUP-26231)Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
* fix(TUP-26231)Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
* fix(TUP-26231)Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
* fix(TUP-26231):Relative path not working in Talend v721
https://jira.talendforge.org/browse/TUP-26231
Conflicts:
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
**Please check if the PR …
> fix(TUP-26231)Relative path not working in Talend v721 (#4530) (#4549)

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
> TUP-26388  fix SQL script's syntax issue

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
* TUP-26388  fix SQL script's syntax issue
* TUP-26388  fix SQL script's syntax issue
> TUP-26388  fix SQL script's syntax issue (#4603)

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateDatesPatternAccordingToDeletedTimestampOption.java
> chore(TPS-3890): backport fix migration task (#4510)

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/FilterEntryImpl.java
> Tup-26476 fix missing filterKind issue

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/InputDataMapTableView.java
https://jira.talendforge.org/browse/TUP-26679
> fix(TUP-26679):tMap editor was freezed

- main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_java.xml
> patch(TPS-3862): Apply fix for related issue

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameELTJDBCComponentsMigrationTask.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameSQLDWHMigrationTask.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameSalesforceWaveMigrationTask.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameTCOMPCouchbaseMigrationTask.java
> bugfix(TUP-26439):Need to fix other rename components Migration task

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/GEFPasteAction.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/MultiplePasteCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/NodesPasteCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/ManageResourcePanel.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/service/ResourcesDependenciesService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ProjectRefSettingPage.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtilTest.java
> Temp patch tps 3844

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
> bugfix(TUP-26758):[7.2.1] Wrong column order when using Schema from

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentConnection.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentItem.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobContextLoadComponent.java
> TUP-26388 fix missing DB context value

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentConnection.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentItem.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobContextLoadComponent.java
* TUP-26388 fix missing DB context value
* fix missing db value issue
* remove useless isTcompv0
> TUP-26388 fix missing DB context value (#4614)

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTTableNameMigrationTask.java
https://jira.talendforge.org/browse/TUP-26750
> fix(TUP-26750):Table name in eltinput component, the default table is taken into consideration

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/PropertyTypeController.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
> Patch/7.3.1 TPS-3839 monthly patch backport

- main/plugins/org.talend.designer.components.localprovider/components/tAS400Connection/tAS400Connection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlConnection/tAmazonMysqlConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleConnection/tAmazonOracleConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Connection/tDB2Connection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tEXAConnection/tEXAConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFirebirdConnection/tFirebirdConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGreenplumConnection/tGreenplumConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tInformixConnection/tInformixConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tIngresConnection/tIngresConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tInterbaseConnection/tInterbaseConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMysqlConnection/tMysqlConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tNetezzaConnection/tNetezzaConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tParAccelConnection/tParAccelConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusConnection/tPostgresPlusConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQLiteConnection/tSQLiteConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseConnection/tSybaseConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tTeradataConnection/tTeradataConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseConnection/tVectorWiseConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaConnection/tVerticaConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/HelpClass/HelpClass.javajet
> Fix(TDI-31598): Don't add "connection" into globalMap for all dbConnection components - always duplicate.

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTTableNameMigrationTask.java
https://jira.talendforge.org/browse/TPS-3953
> TPS-3953:[7.2.1] Table name in eltinput component, the default table is taken into consideration (TUP-26750)

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
when switch back from Jobscript to Designer
> bugfix(TUP-26796):Error "Can't find filed of null" show in error log

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JavaScriptForESBWithMavenManager.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
- main/plugins/org.talend.sdk.component.studio-integration/plugin.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/provider/TacokitExportDependenciesProvider.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitDependencyService.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
https://jira.talendforge.org/browse/TCOMP-1681
Export TaCoKit compliant resources for using components in Talend-Runtime.
> feat(TCOMP-1681): manage tacokit components in OSGi/Microservice job export

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/util/GenericContextUtil.java
- test/plugins/org.talend.repository.generic.test/src/main/java/org/talend/repository/generic/util/GenericContextUtilTest.java
connections
https://jira.talendforge.org/browse/TUP-26639
> fix(TUP-26639):Talend Cloud studio Issues - Group context and

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/util/GenericContextUtil.java
- test/plugins/org.talend.repository.generic.test/src/main/java/org/talend/repository/generic/util/GenericContextUtilTest.java
* fix(TUP-26639):Talend Cloud studio Issues - Group context and
connections
https://jira.talendforge.org/browse/TUP-26639
* fix(TUP-26639):Talend Cloud studio Issues - Group context and
connections
https://jira.talendforge.org/browse/TUP-26639
> fix(TUP-26639):Talend Cloud studio Issues - Group context and (#4634)

- main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/HTMLDocGenerator.java
https://jira.talendforge.org/browse/TUP-26683
> fix(TUP-26683): Inputs label in documentation not the same as FlowDiagram

- main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/VirtualRowGeneratorNode.java
https://jira.talendforge.org/browse/TUP-26939
> fix(TUP-26939:Tmap shows null values when using Expression Builder.

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet
https://jira.talendforge.org/browse/TPS-3956
> fix(TDI-44051):add the real value to the db name (#4621)

- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet
https://jira.talendforge.org/browse/TDI-44130
> fix(TDI-44130):move log to finally

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
> fix(TDI-44074): Fix performance for date mssql

- main/plugins/org.talend.designer.dbmap/plugin.xml
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/operator/DbOperator.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/operator/IDbOperator.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/teradata/TeradataDbOperatorValues.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/migration/DbOperatorMigrationTask.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/teradata/TeradataDbOperatorValuesTest.java
> bugfix(TUP-26186):Use of the operators =, <=, <, >=, >, <> instead of

- main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/VirtualRowGeneratorNode.java
https://jira.talendforge.org/browse/TUP-27066
> fix(TUP-27066)test failed in "Expression Builder" dialog

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionReconnectCommand.java
> bugfix(TUP-26958):Test case: possible to remove input / output node

- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet
https://jira.talendforge.org/browse/TDI-44130
> fix(TDI-44130):move log to finally (#4652)

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/processor/RepositoryTypeProcessor.java
https://jira.talendforge.org/browse/TUP-27000
> fix(TUP-27000):Talend Salesforce Einstein connector Repository connection issue in Talend 7.3

- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/java/JavaProcessorTest.java
https://jira.talendforge.org/browse/TUP-27053
test case should not validate commandline arguments by hardcoded index
> fix(TUP-27053): fix junit test case

- main/plugins/org.talend.designer.components.localprovider/components/tELTSybaseOutput/tELTSybaseOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseBulkExec/tSybaseBulkExec_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseConnection/tSybaseConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseIQBulkExec/tSybaseIQBulkExec_begin_Load.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseInput/tSybaseInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseRow/tSybaseRow_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseSCD/tSybaseSCD_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseSCDELT/tSybaseSCDELT_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseSP/tSybaseSP_begin.javajet
https://jira.talendforge.org/browse/TDI-44159
https://jira.talendforge.org/browse/TDI-44159
> fix(TDI-44159): Sybase not works with jdbc properties

- main/plugins/org.talend.designer.components.localprovider/components/tHadoopConfManager/tHadoopConfManager_begin.javajet
> fix(TBD-10454): with TMC strip timestamp to get hadoop conf

- main/plugins/org.talend.designer.components.localprovider/components/tHadoopConfManager/tHadoopConfManager_begin.javajet
> fix(TBD-10454): with TMC strip timestamp to get hadoop conf (#4679)

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdatetPersonatorOutputSchemaTask.java
> feat(TDQ-17831) update tPersonator component with new fields IPAddress

- main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_end.javajet
> Fix(TDI-30698): Remove lines of spaces between elements in output XML.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ExternalNodeChangeCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/CopyMetadataTableUtil.java
> bugfix(TUP-26002):Reject Schema is original schema, not changed schema

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/EInternalTemplate.java
> TESB-27806:Expose Talend Microservices Metrics in a monitoring system like Prometheus

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.repository/resources/job-rest-template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> feat(TESB-24998): Add context support for data services and routes

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
https://jira.talendforge.org/browse/TUP-16067
ESB route was allowed drag into a Job and run fail.
Don't allow drag ESB route & routelet into job.
> TUP-16067 Don't allow drag route to job.

- main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.javajet
> Fix(TDI-44173): Fix for inner element creation in Loop element.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
https://jira.talendforge.org/browse/TUP-26924
> fix(TUP-26924):tELTXXX: link name won't be updated after updating "default table name" in tELTInput.

- main/plugins/org.talend.repository/resources/job-rest-template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/utils/EmfModelUtils.java
> feat(TESB-24998): Interpret context variable at endpoint for Data Services and Routes

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ParallelExecutionUtils.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/ParallelExecutionUtilsTest.java
https://jira.talendforge.org/browse/TUP-27179
> fix(TUP-27179):Studio freezes on job importing/loading

- main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml
https://jira.talendforge.org/browse/TDI-44104
xmlrpc-common lib was updated to the latest version because of CVE
> fix(TDI-44105): CVE update xmlrpc-common version

- main/plugins/org.talend.designer.components.localprovider/components/tEXistConnection/tEXistConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistDelete/tEXistDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistGet/tEXistGet_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistList/tEXistList_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistPut/tEXistPut_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistXQuery/tEXistXQuery_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistXUpdate/tEXistXUpdate_java.xml
https://jira.talendforge.org/browse/TDI-44104
xmlrpc-common lib was updated to the latest version because of CVE
> fix(TDI-44104): update xmlrpc-common version

- main/plugins/org.talend.designer.components.localprovider/components/tEXistConnection/tEXistConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistDelete/tEXistDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistGet/tEXistGet_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistList/tEXistList_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistPut/tEXistPut_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistXQuery/tEXistXQuery_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXistXUpdate/tEXistXUpdate_java.xml
https://jira.talendforge.org/browse/TDI-44115
xmlrpc-client lib was updated to the latest version because of CVE
> fix(TDI-44115): update xmlrpc-client version

- main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml
https://jira.talendforge.org/browse/TDI-44169
xmlrpc-common lib was updated to the latest version because of CVE
> fix(TDI-44169): update xmlrpc-client version

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
https://jira.talendforge.org/browse/TPS-3953
> fix(TUP-26924):tELTXXX: link name won't be updated after updating "default table name" in tELTInput

- main/plugins/org.talend.repository/resources/job-rest-template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/utils/EmfModelUtils.java
> feat(TESB-24998): Add context bean for tRESTReuest

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
> TESB-29112 Earlier TPS-3797 was provided, but that broke TPS-2787

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
* bugfix(TUP-27199):DB version of sybase isn't hide for other database
on
tCreateTable
Conflicts:
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
> Hwang/tup 27199 (#4692)

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
> bugfix(TUP-26848):Unsaved icon * still show on job after click save

- main/plugins/org.talend.repository/plugin.xml
Fix_TUP-26288 remove error commit in commit/8e53443f645440484e298d8b08e977fefce2049a#diff-9d5aeb4ed64e4c20c7804c64e2bb1bd6R3332-R3339
> Fix_TUP-26288 remove error commit

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContextManager.java
fix tup 26288 directly run job can't update context var name
https://jira.talendforge.org/browse/TUP-26288
> Fix TUP-26288 Directly run job can't update context var name

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/provider/TacokitExportDependenciesProvider.java
pb when using windows with paths...
> fix(TCOMP-1681): fix Windows path case

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-43833
https://jira.talendforge.org/browse/TDI-43833
> fix(TDI-43833): tDBBulkExec bug when using PostGress driver

- main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAccessOutput/tAccessOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFirebirdOutput/tFirebirdOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tHSQLDbOutput/tHSQLDbOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tInformixOutput/tInformixOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tIngresOutput/tIngresOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tInterbaseOutput/tInterbaseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMaxDBOutput/tMaxDBOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tNetezzaOutput/tNetezzaOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tParAccelOutput/tParAccelOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQLiteOutput/tSQLiteOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tTeradataOutput/tTeradataOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseOutput/tVectorWiseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/DBOutputEndGlobalVars.javajet
> Fix(TDI-30505): Do not log if no autocommit.

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitService.java
https://jira.talendforge.org/browse/TUP-26569
> feat(TUP-26569): merge known conflicts automatically

- main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileDelete/tFileDelete_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
> fix(TDI-44269): Set Outline ERROR_MESSAGE values.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
> fix(TBD-10285):Add contains predicate to expressions

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/NodesPasteCommand.java
> bugfix(TUP-25171):Issue when using components inside Joblet

- main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/HTMLDocGenerator.java
https://jira.talendforge.org/browse/TUP-26683
> fix(TUP-26683): Inputs label in documentation not the same as FlowDiagram.

- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/java/JavaProcessorTest.java
https://jira.talendforge.org/browse/TUP-27361
Does not validate hardcode commandline argument
> bugfix(TUP-27361) Fix test case

- main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAccessOutput/tAccessOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFirebirdOutput/tFirebirdOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tHSQLDbOutput/tHSQLDbOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tInformixOutput/tInformixOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tIngresOutput/tIngresOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tInterbaseOutput/tInterbaseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMaxDBOutput/tMaxDBOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tNetezzaOutput/tNetezzaOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tParAccelOutput/tParAccelOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQLiteOutput/tSQLiteOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tTeradataOutput/tTeradataOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseOutput/tVectorWiseOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/DBOutputEndGlobalVars.javajet
Backport of https://github.com/Talend/tdi-studio-se/pull/4629 into "maintenance/7.3" branch.
> fix(TDI-30505): Backport fix from "master"

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java
https://jira.talendforge.org/browse/TUP-26347
> fix(TUP-26347):Bug in tMap component using Talend Studio on Mac

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-27053
Insert -Dtalend.component.manager.m2.repository before -cp
> fix(TUP-27053): backport

- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/java/JavaProcessorTest.java
https://jira.talendforge.org/browse/TUP-27361
Fix test cases
> fix(TUP-27053): fix junit test case (#4676)

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-44216
> feat(TDI-44216):Redshift partner tracker

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet
* Get location from jobreference for OAuth 2.0 authentication mode
> fix(TDI-44247): tBigQueryInput illegal operation

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet
* Get location from jobreference for OAuth 2.0 authentication mode
Co-authored-by: Dmytro Chmyga <dmytro.chmyga@synapse.com>
> fix(TDI-44247): tBigQueryInput illegal operation (#4722)

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet
https://jira.talendforge.org/browse/TDI-44196
> fix(TDI-44196):Jdbc use origin name for dynamic

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mssql/MssqlGenerationManagerTest.java
> TUP-27070  fix cross join cases

- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/AbstractLoginActionPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionsDialog.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionsListComposite.java
> feat(TUP-16546)Prompt users for new password in Studio Connection when AD or LDAP credentials change in TAC

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeMSSQLDBDefaultVersionMigrationTask.java
…in Metadata (#4736)
* feat(TUP-27259)Change default driver to Microsoft official for MSSql in
Metadata
https://jira.talendforge.org/browse/TUP-27259
* Update plugin.xml
* feat(TUP-27259)Change default driver to Microsoft official for MSSql in
Metadata
https://jira.talendforge.org/browse/TUP-27259
* feat(TUP-27259)Change default driver to Microsoft official for MSSql in
Metadata
> feat(TUP-27259)Change default driver to Microsoft official for MSSql

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java
update all jobs"
https://jira.talendforge.org/browse/TUP-27509
> fix(TUP-27509):[bug] testcase listed everytime when click "Detect and

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-44380
https://jira.talendforge.org/browse/TDI-44380
> fix(TDI-44380): Imported JDBC job has compile error : extra quotes around table name

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/CreateContextLinkMigrationTask.java
https://jira.talendforge.org/browse/TUP-26699
> TUP-26699 Enhance context propagation over reference project - Resolve link conflict with Git

- main/plugins/org.talend.designer.components.localprovider/components/tHadoopConfManager/tHadoopConfManager_begin.javajet
> fix(TBD-10454): fix hadoop conf in context with TMC

- main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/VirtualRowGeneratorNode.java
https://jira.talendforge.org/browse/TPS-4061
> TPS-4061: Tmap shows null values when using Expression Builder {TUP-26939}

- main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_messages.properties
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/DbMapComponent.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/mssql/MssqlGenerationManager.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mssql/MssqlGenerationManagerTest.java
> Hengzhao/backport patch721/tup 27070

- main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_main.javajet
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/DbMapComponent.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/mssql/MssqlGenerationManager.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mssql/MssqlGenerationManagerTest.java
backport to 7.2 and fix conflicts
> Tup-27070 (#4734)

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-27053
normailize spaces of job startup script
> fix(TUP-27053): backport (#4767)

- CONTRIBUTORS.md
> fix(TDI-44355): Updated CONTRIBUTORS.md

- CONTRIBUTORS.md
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
Backport of https://github.com/Talend/tdi-studio-se/pull/2534 and https://github.com/Talend/tdi-studio-se/pull/4843 into 'maintenance/7.3' branch
> fix(TDI-44355): Backport to 'maintenance/7.3' branch

- main/plugins/org.talend.designer.components.localprovider/components/tGPGDecrypt/tGPGDecrypt_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSystem/tSystem_begin.javajet
> Fix(TDI-44021): Replaced join(10000) with join();

- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mssql/MssqlGenerationManagerTest.java
> tup-27070 fix junit failed on patch 7.2.1

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
https://jira.talendforge.org/browse/TUP-27497
> fix(TUP-27497): [7.3.1] tPreJob with tHDFSConnection with kerberized cluster fails with simple authentication error

- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/DataProcessTest.java
cluster fails with simple authentication error
https://jira.talendforge.org/browse/TUP-27497
> fix(TUP-27497): [7.3.1] tPreJob with tHDFSConnection with kerberized

- main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/HTMLDocGenerator.java
> chore: fix compile error

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-44378
tSybaseOutput can't create table with character data type
New changes allow properly work tSybaseOutput
> fix(TDI-44378): add correct generation of create table sql for Sybase

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
Backport of #4815 to master.
Fix in master.
> fix(TDI-44378): add correct generation of create table sql for Sybase (#4815)

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRSSInput/tRSSInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
https://jira.talendforge.org/browse/TDI-44063
xercesImpl lib was updated to 2.12.0 version
Don't merge before xercesImpl will uploaded to https://talend-update.talend.com/
> fix(TDI-44063): update xercesImpl dependency

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/HealthCheckResolver.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitConfigurationWizard.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitPageBuildHelper.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ServerManagerTest.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameterTest.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitPageBuildHelperTest.java
Exception when active if has its target on different form
https://jira.talendforge.org/browse/TDI-44320
ok with that
> Clesaec/tdi 44320 active if form 7.3

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/HealthCheckResolver.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitConfigurationWizard.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitPageBuildHelper.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ServerManagerTest.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameterTest.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitPageBuildHelperTest.java
Exception when active if has its target on different form 
https://jira.talendforge.org/browse/TDI-44320
ok with that.
> fix(TDI-44320) : change page creation method

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
https://jira.talendforge.org/browse/TUP-27607
> fix(TUP-27607)Metadata Database connection with special characters(double quote) in the password

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ParallelExecutionUtils.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/ParallelExecutionUtilsTest.java
* fix(TUP-27179):Studio freezes on job importing/loading
https://jira.talendforge.org/browse/TUP-27179
* fix(TUP-27179):Studio freezes on job importing/loading
https://jira.talendforge.org/browse/TUP-27179
* fix(TUP-27179):Studio freezes on job importing/loading
https://jira.talendforge.org/browse/TUP-27179
> fix(TUP-27179):Studio freezes on job importing/loading (#4682)

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TCOMP-1733
> tuj - integration

- main/plugins/org.talend.designer.components.libs/libs_src/mdm_transaction/src/main/java/com/talend/mdm/transaction/client/MDMTransactionClient.java
https://jira.talendforge.org/browse/TMDM-14504
- If username/password contains special characters, like `userü@talend.com/äöüß€&éà?`, tMDMConnection & tMDMCommit not working normally
- `userü@talend.com/äöüß€&éà?`, working normally
> TMDM-14504 tMDMConnection not working normally if username/password contains special characters

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
https://jira.talendforge.org/browse/TUP-27697
> fix(TUP-27697)Studio throw NPE error when drag json item to job

- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet
Backport of https://github.com/Talend/tdi-studio-se/pull/4858 into "master" branch.
> fix(TDI-44412): Implemented optional component fail when no files found by mask.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GenerateCryptoFileController.java
https://jira.talendforge.org/browse/TDQ-17180
check parameter before create a new command
> fix(TDQ-17180): check paramter before start a command

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
> tup-27447  backport to patch721

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java
* bugfix(TUP-26059):tELTPostgresqlMap lost its "DB Type" column for which
the value should be "BPCHAR"
> Hwang/tup 26059 (#4436)

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
Co-authored-by: Dmytro Chmyga <dmytro.chmyga@synapse.com>
> fix(TDI-44384): set csv options (#4821)

- CONTRIBUTORS.md
> Add contributor's real name.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/Connection.java
https://jira.talendforge.org/browse/TUP-27352
> fix(TUP-27352):Traces enabled by default when using Memory Run

- main/plugins/org.talend.repository/plugin.xml
https://jira.talendforge.org/browse/TDI-44284
> feat(TDI-44284): change the migration version on master

- test/plugins/org.talend.designer.unifiedcomponent.test/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommandTest.java
> add junit caused by TDI-44284

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
https://jira.talendforge.org/browse/TUP-27680
> feat(TUP-27680)Can't use the database "MAPPING" parameter to decide the component UI if show

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
TU not activate, generate warning, and TUJ can't build
https://jira.talendforge.org/browse/TDI-44455
TU run, TUJ run
> fix(TDI-44455) : log dependencies for studio-integration module

- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_messages_en.properties
- main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForBulk.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/createTableFromDynamicInBulkExec.javajet
https://jira.talendforge.org/browse/TDI-44215
> feat(TDI-44215): Dynamic Schema for Vertica Bulk - Integrate in Studio monthly release of July

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
Error when active unit test
https://jira.talendforge.org/browse/TDI-44455
TU activate and studio build & TUJ pass
> fix(TDI-44455) : log deps pb

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateNodeParameterCommand.java
https://jira.talendforge.org/browse/TUP-27545
> Fix: TUP-27545 Update context var name for jdbc drivers can not be updated to job automatically.

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-44506
https://jira.talendforge.org/browse/TDI-44506
> fix(TDI-44506): Failed to build job on TOS

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-44506
https://jira.talendforge.org/browse/TDI-44506
> fix(TDI-44506): Failed to build job on TOS (#4900)

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
https://jira.talendforge.org/browse/TDI-44300
> fix(TDI-44300):skip bom to fix issue

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_main.javajet
https://jira.talendforge.org/browse/TDI-44342
Fixed in maintenance/7.3
This PR for master
> TDI-44342 : Ignore microseconds in BigQuery datetime (#4798)

- main/features/org.talend.tos.libraries.feature/feature.xml
> tup-27154 update feature

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TDI-44548
https://jira.talendforge.org/browse/TDI-44548
> fix(TDI-44548): tacokit components can't be loaded

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java
> feat(TESB-28826) Secure Password - Publish job with Password

- main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.inc.javajet
for https://jira.talendforge.org/browse/TDI-44453
> fix(TDI-44453):tAdvancedFileOutputXML issue after upgrading to 7.3.1

- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/common_scd_pattern1.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/common_scd_pattern2.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/databricks_delta_lake.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/db2.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/mysql.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/oracle.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/postgres.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/postgresplus.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/sap_hana.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/sybase.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/tJDBCSCDELT_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/teradata.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/vertica.javajet
https://jira.talendforge.org/browse/TDI-44558
> fix(TDI-44558):fix tJDBCSCDELT 65535 issue

- main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
https://jira.talendforge.org/browse/TDI-44482
https://jira.talendforge.org/browse/TDI-44482
> fix(TDI-44482): CVE: org.apache.ant:ant:1.10.1

- main/plugins/org.talend.designer.components.libs/libs_src/mdm_transaction/src/main/java/com/talend/mdm/transaction/client/MDMTransaction.java
- main/plugins/org.talend.designer.components.libs/libs_src/mdm_transaction/src/main/java/com/talend/mdm/transaction/client/MDMTransactionClient.java
https://jira.talendforge.org/browse/TMDM-14504
- If username/password contains special characters, like `userü@talend.com/äöüß€&éà?`, tMDMConnection & tMDMCommit not working normally if check "Use client side transaction id"
- `userü@talend.com/äöüß€&éà?`, working normally
> TMDM-14504 Fix "Use client side transaction id"

- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_main.javajet
https://jira.talendforge.org/browse/TDI-44561
compile error was fixed
> fix(TDI-44561): fix compile error when dieOnError is checked

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
Backport of #4780 to master.
Fix in master.
> fix(TDI-44202): tCreateTable add support of Sybase (#4780)

- main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/main/java/org/talend/gs/util/GSObjectUtil.java
- main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/java/util/GSObjectUtilTest.java
https://jira.talendforge.org/browse/TDI-44562
google-storage-util lib was updated
> fix(TDI-44562): replace all backslashes in GS path

- main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/main/java/org/talend/gs/util/GSObjectUtil.java
- main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/java/util/GSObjectUtilTest.java
https://jira.talendforge.org/browse/TDI-44562
backport to 7.4.1
> fix(TDI-44562): replace all backslashes in GS path (#4949)

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> TESB-29664 Reverting changes

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/NodesPasteCommand.java
https://jira.talendforge.org/browse/TUP-27601
> fix(TUP-27601):NPE when try to copy-paste database component inside the job

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
> TESB-29647 Bundle version for Jobs is corrected

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
> TESB-29647 Bundle version for Jobs is corrected 

- main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/test/java/net/sf/json/AbstractJSONObjectStaticBuildersTestCase.java
- main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/test/java/net/sf/json/TestJSONObject.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-ws/build.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-ws/pom.xml
- main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMondrianInput/tMondrianInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinBulkExec/tSalesforceEinsteinBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_java.xml
https://jira.talendforge.org/browse/TDI-44481
https://jira.talendforge.org/browse/TDI-44481
> fix(TDI-44481): CVE: commons-beanutils:commons-beanutils:1.9.3

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/context/ComponentContextPropertyValueEvaluator.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java
https://jira.talendforge.org/browse/TUP-25171
> fix(TUP-25171):Issue when using components inside Joblet.

- main/plugins/org.talend.repository.json/plugin.xml
> fix json xpath issue

- main/plugins/org.talend.repository.json/plugin.xml
> fix json xpath issue (#4980)

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml
https://jira.talendforge.org/browse/TDI-44400
NPE for empty table schema
Updated google-cloud-bigquery to the version with fix
Now it is possible to get empty table from BigQuery
> fix(TDI-44400): update google-cloud-bigquery version

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml
Backport of #4860 to master.
Fix in master.
> fix(TDI-44400): update google-cloud-bigquery (#4860)

- main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
PR: master
https://jira.talendforge.org/browse/TUP-27851
upgraed xstream to 1.4.12
workitem
> TUP-27851 upgrade xstream to 1.4.12.

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/GenericDbGenerationManager.java
> patch(TPS-4193): remove localprovider, make it compatible with javajet modifications

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/TalendEditorPaletteFactoryTest.java
matches to the top
https://jira.talendforge.org/browse/TUP-19440
> fix(TUP-19440)Search for new tDB* components are not bringing best

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddSchemaDatePatternUseForImpalaTask.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UseSqlDateTypeInDataframesTask.java
> fix(TPS-4279): Add checkbox to transform date type in timestamp

- main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
https://jira.talendforge.org/browse/TDI-44622
> fix(TDI-44622):Correct Bonita mvn URL

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/CreateContextLinkMigrationTask.java
https://jira.talendforge.org/browse/TUP-27879
Improve the code fix a spelling errors
> Kjwang/fix tup 27879 library data.index (#4935)

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/VersionManagementPage.java
https://jira.talendforge.org/browse/TUP-28009
Save relationship index after version changes
> fix(TUP-28009): Save relationship index after version change

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
Adding org.dom4j to the Import-Package of the MANIFEST. This PR fixes issue, which described in last comment here https://jira.talendforge.org/browse/TESB-29133
> TESB-29133 Update dom4j to 2.1.3

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
The reason of this issue is that one of the generated in Studio methods has too much code.
I found this commit https://github.com/Talend/tdi-studio-se/commit/839af2e2f8f0b126fb85a0a708b967b344edd9ef in maintenance/7.2 branch, which helps to reduce amount of generated code
(and therefore fixes this issue), but it wasn't commited to 7.2 patch branch.
So this PR is just to cherry-pick code to 7.2 patch branch.
> TESB-29656 tESBProvider giving exceeding 65535 bytes limit error

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletContainer.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TUP-27953
> fix(TUP-27953): tSalesforceInput component displays in-job tSalesforceConnection incorrectly

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tHiveConnection/tHiveConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tJavaDBInput/tJavaDBInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tJavaDBRow/tJavaDBRow_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMondrianInput/tMondrianInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/plugin.xml
> TUP-27991 remove uripath

- main/plugins/org.talend.designer.components.localprovider/components/tWaitForSqlData/tWaitForSqlData_begin.javajet
https://jira.talendforge.org/browse/TDI-44643
https://jira.talendforge.org/browse/TDI-44643
> fix(TDI-44643): NPE exception on tWaitForSQLData with snowflake connection

- main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
Reverts Talend/tdi-studio-se#4895
Cause compilation issue, all the DI job won't compile after this, because of other missing change on JobStructureCatcherUtils
Please review with DI team if needed
> Revert "TESB-29656 tESBProvider giving exceeding 65535 bytes limit error"

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
> TESB-29071 Bean in route gives wrong output on running in studio

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java
> feat(TUP-27862)Add possibility to customize pattern for dates when

- main/plugins/org.talend.designer.components.libs/libs_src/StewardshipTask/build.xml
- main/plugins/org.talend.designer.components.libs/libs_src/mdm_stewardshipTask/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talendsap/pom.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEDIFACTtoXML/tEDIFACTtoXML_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tExtractXMLField/tExtractXMLField_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSXML/tFileInputMSXML_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputXML/tFileOutputXML_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOpenbravoERPInput/tOpenbravoERPInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOpenbravoERPOutput/tOpenbravoERPOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRSSInput/tRSSInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRSSOutput/tRSSOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tXMLMap/tXMLMap_java.xml
https://jira.talendforge.org/browse/TDI-44192
https://jira.talendforge.org/browse/TDI-44192
> fix(TDI-44192): Update dom4j to 2.1.3

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
> fix(TESB-29210): Build type not updated for consumer job

- main/plugins/org.talend.designer.components.libs/libs_src/mdm_transaction/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-webservice-input/pom.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/pom.xml
> chore(TDI-44362): CVE. Remove commons logging

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/prefs/RunProcessPreferenceInitializer.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/utils/JobVMArgumentsUtil.java
https://jira.talendforge.org/browse/TUP-27374
Get default vm arguments from hard coded value instead of UI plugin preference. 
> bugfix(TUP-27374) Commandline doesn''t pick up the correct JVM arguments

- test/plugins/org.talend.repository.test/src/org/talend/repository/handler/BuildJobHandlerTest.java
> try fix junit to download jar

- main/plugins/org.talend.designer.components.localprovider/components/tSAPBWInput/tSAPBWInput_java.xml
https://jira.talendforge.org/browse/TDI-44648
> fix(TDI-44648): Derepcate tSAPBWInput

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateSeparatorAndEscapeForDatasetAPI.java
> fix(TBD-11052): fix dataset migration for csv value

- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/utils/JobVMArgumentsUtilTest.java
https://jira.talendforge.org/browse/TUP-27374
Fix test case failure
> fix(TUP-27374): Fix test case
