Talend/tdi-studio-se

test/plugins/org.talend.repository.test/src/org/talend/repository/handler/BuildJobHandlerTest.java
Reverts Talend/tdi-studio-se#5025
=> Revert "try fix junit to download jar"

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
Co-authored-by: Maksym Sheverda <maksym.sheverda@synapse.com>
=> TESB-29133 Update dom4j to 2.1.3 (#5000)

test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/utils/JobVMArgumentsUtilTest.java
https://jira.talendforge.org/browse/TUP-27374
Return default jvm arguments always
=> fix(TUP-27374): Fix test case (#5055)

main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java
=> Csun/tesb 29322/microservice monitoring expose camel metrics m73

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
"Exclude deleted items" and delete to recycle bin
https://jira.talendforge.org/browse/TUP-28180
=> fix(TUP-28180):[bug]Only latest version deleted from root pom when check

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_main.javajet
https://jira.talendforge.org/browse/TDI-42668
=> feat(TDI-42668):update jar of tssh component branch 7.3

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/RefactoDeltaMergeOption.java
=> feat(TBD-10769): delta Features for R08

main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
=> fix(TESB-29957):CI Fail to publish Microservice with Prometheus param

CONTRIBUTORS.md
=> feat(TDI-44045): Add contributor to the list

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
https://jira.talendforge.org/browse/TUP-28295
=> fix(TUP-28295): UI Problem of TCOMPV0 in the recent 741NB and 731 Release + Aug. Nightly Build Patch

main/plugins/org.talend.designer.core/META-INF/MANIFEST.MF, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/proposal/TalendCompletionProposalComputer.java, main/plugins/org.talend.designer.dbmap/META-INF/MANIFEST.MF, main/plugins/org.talend.designer.dbmap/src/main/java/messages.properties, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/EltExpressionComposite.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/ExpressionBuilderDialogForElt.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/ExpressionComposite.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/proposal/expression/ExpressionProposalProvider.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/DataMapTableView.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/OutputDataMapTableView.java
* bugfix(TUP-25103):tELTMap - ctrl+space shortcut is not working to
retrieve easily job context
* TUP-25103
* Tup-25103
* tup-25103  use styleText
* tup-25103 add exception handler
* remove comments
* solve issues
* add doit false to avoid new line
* try replace "\r\n" to " " in tELTMssqlMap_main.javajet
* fix edit expression builder but sql tab not refresh
* remove comments and format
* improve code
* to fix other eltmap about multi-line expression  and import/export
expression from file
* remove javajet and remove buttons
* remove expressionbuilder
Co-authored-by: hwang <hwang@talend.com>
**What kind of change does this PR …
=> Hengzhao/backport73/tup 25103 (#5033)

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/RefactoDeltaMergeOption.java
=> feat(TBD-10769): delta Features for R08 (#5067)

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
=> fix(TESB-29676): Job with deployment type Microservice don't compile if password context parameter added directly to job

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateSeparatorAndEscapeForDatasetAPI.java
=> fix(TBD-11052): fix dataset migration for csv value (#5051)

main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
=> fix(TESB-29957): Added properties for metrics

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
* fix(TUP-28338):[7.3.1] configuring Implicit tContextLoad in the job Goes
on error after installing the patch 07_2020
https://jira.talendforge.org/browse/TUP-28338
* fix(TUP-28338):[7.3.1] configuring Implicit tContextLoad in the job Goes
on error after installing the patch 07_2020
https://jira.talendforge.org/browse/TUP-28338
* fix(TUP-28338):[7.3.1] configuring Implicit tContextLoad in the job Goes
on error after installing the patch 07_2020
https://jira.talendforge.org/browse/TUP-28338
If this PR contains a breaking change, please …
=> Jding/tup 28338 implicit context issue (#5097)

main/plugins/org.talend.designer.components.localprovider/components/tHiveIn/tHiveIn_main.javajet
=> fix(TBD-11119): tHiveInput with DataProc 1.4 in DI: no rows retrieved

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/jobsettings/JobSettingsManagerTest.java
on error after installing the patch 07_2020
https://jira.talendforge.org/browse/TUP-28338
=> fix(TUP-28338):[7.3.1] configuring Implicit tContextLoad in the job Goes

main/plugins/org.talend.repository/plugin.xml
=> fix(TBD-11052): Update plugin.xml

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveMetadataInPomsFolder.java
https://jira.talendforge.org/browse/TUP-28078
=> fix(TUP-28078)metadata folder generated under .../poms/jobs when create new connection in remote project

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
=> fix(TESB-29963) MQ Dependency issues in Runtime

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/palettesettings/ComponentPaletteItem.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
https://jira.talendforge.org/browse/TUP-28134
=> fix(TUP-28134):TCK Components shown as hidden by default in the palette settings

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendProcessJavaProject.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
https://jira.talendforge.org/browse/TUP-28308
If job contains multiple version of joblets, studio will build job in a single thread.
=> bugfix(TUP-28308) build error and joblet maven xml file has incorrect values and Couldn't parse data error message

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
https://jira.talendforge.org/browse/TUP-28308
Build job in a single thread if aggregator pom contains multiple version of joblets
=> fix(TUP-28308): build error and joblet maven xml file has incorrect values and Couldn't parse data error message

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/CheckAzureBlobStorageKeepRemoteDirJavajetToTCOMPv0.java
=> fix(TDI-44394): Fix migration tcomp for javajet

main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
https://jira.talendforge.org/browse/TDI-44063
We receive an exception:
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
This one will be fixed with new jar.
=> fix(TDI-44063): add transitive xml-apis lib

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TPS-4101
=> patch(TPS-4101): bump component-runtime to 1.1.15.2

main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tRSSInput/tRSSInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-44063
Backport to 7.4
=> fix(TDI-44063): update xercesImpl dependency (#5004)

main/plugins/org.talend.designer.codegen/jet_stub/iterate_subprocess_header.javajet
=> Add test suffix for test case support

main/plugins/org.talend.designer.codegen/jet_stub/iterate_subprocess_header.javajet
=> Mverrilli patch 7.3.1 iterate test fix

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
=> fix change metadata table ,column list wrong order.

main/plugins/org.talend.designer.components.localprovider/plugin.xml
studio
https://jira.talendforge.org/browse/TUP-28085
=> fix(TUP-28085):Error while compiling a Kafka component with Big Data

main/plugins/org.talend.designer.codegen/jet_stub/iterate_subprocess_header.javajet
* Add test suffix for test case support (#5136)
Co-authored-by: Michael Verrilli <mverrilli@talend.com>
* Mverrilli patch 7.3.1 iterate test fix (#5137)
* Add test suffix for test case support
* Fixed missing reference to className
* Update iterate_subprocess_header.javajet
Co-authored-by: Michael Verrilli <mverrilli@talend.com>
Co-authored-by: Michael Verrilli <mverrilli@talend.com>
=> fix(TUP-28440):iterate subprocess generator does not take into account test cases entirely

main/plugins/org.talend.designer.components.libs/libs_src/adal4j/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/servicenow/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-ws/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-ws/readme.txt, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputLDIF/tFileOutputLDIF_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFuzzyMatch/tFuzzyMatch_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGoogleDataprocManage/tGoogleDataprocManage_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMondrianInput/tMondrianInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSAPBWInput/tSAPBWInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tServiceNowInput/tServiceNowInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml, main/plugins/org.talend.libraries.crm/pom.xml
* update commons-codec to 1.14 version in libraries
* update commons-codec to 1.14 version in javajet
https://jira.talendforge.org/browse/TDI-44145
=> chore(TDI-44145): update commons-codec:1.14

main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
=> fix(TDI-44074): Fix performance for date mssql (#4638)

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
Old driver.
Use the latest Snowflake driver:
https://mvnrepository.com/artifact/net.snowflake/snowflake-jdbc/3.12.11
=> feat(TDI-44730): snowflake driver

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
Backport of https://github.com/Talend/tdi-studio-se/pull/5150
=> feat(TDI-44730): upgrade snowflake driver to latest (#5150)

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
for issue: https://jira.talendforge.org/browse/TDI-44748
=> fix(TDI-44748):Error in method "add" for the component tFileOutputMSXML

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/pom.xml
Backport of https://github.com/Talend/tdi-studio-se/pull/5132 into "master" branch.
=> fix(TDI-44743): backport to "master" branch

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-44743
=> TalendExcel: read password protected files.

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizardPage.java
=> fix(TESB-29819): Studio doesn't select model beans during exporting

main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
=> fix(TDI-30522): extra '(' removed.

main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
=> fix(TDI-30522): extra '(' removed

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java
https://jira.talendforge.org/browse/TUP-27438
Add studio-utils to jet classpath
=> fix(TUP-27438): Add new plugin to codegen classpath

main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/src/main/java/org/talend/ftp/SSLSessionReuseFTPSClient.java, main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
* throw NPE when the SSL session was re-initialized.
* avoid throwing the NullPointerException when the SSL session was re-initialized.
* print info message instead of NPE
=> fix(TDI-44654): fixed NPE for tFTP

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/GuessSchemaSelectionAdapter.java
https://jira.talendforge.org/browse/TCOMP-1759
=> (TCOMP-1759): fix random order for columns in guessSchema in Studio

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/GuessSchemaSelectionAdapter.java
https://jira.talendforge.org/browse/TCOMP-1759
=> fix(TCOMP-1759): fix random order for columns in guessSchema in Studio

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java
https://jira.talendforge.org/browse/TUP-28258
=> fix(TUP-28258):tETLInput and tETLMap does not show datatypes for Snowflake DB on Import Metadata

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java
https://jira.talendforge.org/browse/TUP-28258
=> fix(TUP-28258):tETLInput and tETLMap does not show datatypes for Snowflake DB on Import Metadata。

main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_begin.javajet
https://jira.talendforge.org/browse/TDI-44760
https://jira.talendforge.org/browse/TDI-44760
=> fix(TDI-44760): TMomOutput not changing the value of the queue

main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_begin.javajet
https://jira.talendforge.org/browse/TDI-44760
https://jira.talendforge.org/browse/TDI-44760
=> fix(TDI-44760): TMomOutput not changing the value of the queue (#5145)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/build/StandardJobOSGiBundleBuildProvider.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/build/StandardJobStandaloneBuildProvider.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java
=> TESB-30188:CI builder doesn't publish feature folders for some artifacts

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml
https://jira.talendforge.org/browse/TDI-44765
=> chore(TDI-44765): remove guava:13.0

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/pom.xml
Dynamic Columns handling in Studio : https://jira.talendforge.org/browse/TCOMP-1651
Master backport
**Related PRs:**
- https://github.com/Talend/studio-full-master/pull/432
- https://github.com/Talend/tcommon-studio-ee/pull/1507
- https://github.com/Talend/tcommon-studio-se/pull/3621
- https://github.com/Talend/tdi-studio-ee/pull/1459
- https://github.com/Talend/tdi-studio-se/pull/5180
=> feat(TCOMP-1651): backport to master

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
https://jira.talendforge.org/browse/TDI-44803
=> fix(TDI-44803):attachment issue in tfileinputmail.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
https://jira.talendforge.org/browse/TDI-44803
=> fix(TDI-44803):attachment issue in tfileinputmail. (#5176)

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_main.javajet
https://jira.talendforge.org/browse/TDI-44846
=> fix(TDI-44846):fix the compliation error.

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetGlobalTimestampOptionForPreviousVersions.java
=> fix(TBD-10885): refacto date and timestamp handling with dataset (#5149)

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_main.javajet
https://jira.talendforge.org/browse/TDI-44856
=> fix(TDI-44855):tSSH append new line in the result

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TCOMP-1770
https://jira.talendforge.org/browse/TDI-44874
**Related PR**
- https://github.com/Talend/tcommon-studio-ee/pull/1523
- https://github.com/Talend/tcommon-studio-se/pull/3638
- https://github.com/Talend/tdi-studio-se/pull/5202
=> feat(TCOMP-1770): backport to master

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/RuntimeLineageTreeViewPage.java
https://jira.talendforge.org/browse/TUP-28635
=> fix(TUP-28635):[bug] output path always be changed when path contains \

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_main.javajet
https://jira.talendforge.org/browse/TDI-44855
=> fix(TDI-44855):fix index out of bound error

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
https://jira.talendforge.org/browse/TUP-28628
Add NPE check and log messages
=> bugfix(TUP-28628) Detection of update of project blocked in case of wrong item

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/service/GenericService.java
https://jira.talendforge.org/browse/TUP-26413
=> fix(TUP-26413): Be able to compare metadata connection conflicts

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/service/GenericService.java
https://jira.talendforge.org/browse/TUP-26413
=> fix(TUP-26413): Be able to compare metadata connection conflicts (#5222)

main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
https://jira.talendforge.org/browse/TDI-44806
https://jira.talendforge.org/browse/TDI-44806
=> fix(TDI-44806): Observability: Add customization for event frequency

main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/pom.xml
https://jira.talendforge.org/browse/TDI-44824
https://jira.talendforge.org/browse/TDI-44824
=> fix(TDI-44824): Observability: Update daikon-audit library version

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java
https://jira.talendforge.org/browse/TUP-27654
=> feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
=> fix(TUP-28576):Reference projects routine POM file is modified and can't be committed to GIT

main/features/org.talend.tos.libraries.feature/feature.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
remove org.talend.libraries.apache.google plugin
https://jira.talendforge.org/browse/TUP-28519
=> fix(TUP-28519):Update org.talend.libraries.apache.google jars

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
https://jira.talendforge.org/browse/TDI-44568
=> fix(TDI-44568): Update TalendExcel library.

main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/src/main/java/org/talend/msg/utils/MsgMailUtil.java
=> fix(TDI-44568): Update talendMsgMailUtil library

main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DataBufferCache.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/EnoughDataException.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
=> fix(TDI-44568): Update simpleexcel library

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
=> fix(TDI-44568): Update Apache POI version in components

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
Reverts Talend/tdi-studio-se#5043
=> Revert "fix(TDI-44568): Update Apache POI version in components"

main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.excel/build.properties, main/plugins/org.talend.libraries.excel/pom.xml
Reverts Talend/tdi-studio-se#5042
=> Revert "fix(TDI-44568): Update org.talend.libraries.excel plugin"

main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DataBufferCache.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/EnoughDataException.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
Reverts Talend/tdi-studio-se#5041
=> Revert "fix(TDI-44568): Update simpleexcel library"

main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/src/main/java/org/talend/msg/utils/MsgMailUtil.java
Reverts Talend/tdi-studio-se#5040
=> Revert "fix(TDI-44568): Update talendMsgMailUtil library"

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
Reverts Talend/tdi-studio-se#5001
=> Revert "fix(TDI-44568): Update TalendExcel library."

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
https://jira.talendforge.org/browse/TCOMP-1772
=> fix(TCOMP-1772): fix MEMO_X type in configuration.javajet

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizardPage.java
=> TESB-30423:Install Patch_20200925_R2020-09_v1-7.3.1 with TDI.license,

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericComponent.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/IUnifiedComponentService.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/UnifiedJDBCBean.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/ComponentSettingsView.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java, main/plugins/org.talend.designer.unifiedcomponent/plugin.xml, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/UnifiedComponentService.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/component/DelegateComponent.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/component/UnifiedObject.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommand.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/manager/UnifiedComponentsManager.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/jdbc/IDynamicJDBCUnifier.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/jdbc/JDBCComponentsUnifier.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/DBDynamicComposite.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/dialog/RepositoryReviewDialog.java
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
Signed-off-by: …
=> feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE (#5078)

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
https://jira.talendforge.org/browse/TDI-44908
https://jira.talendforge.org/browse/TDI-44908
=> fix(TDI-44908): pass TMC function jar for trunjob independent process case and dynamic job case

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizardPage.java
=> Bugfix/maintenance/7.3/tesb 30423 7.3.1 patch

main/plugins/org.talend.repository/resources/osgi-exclude.properties
=> fix(TESB-30136) exclude the jakarta.activation

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
https://jira.talendforge.org/browse/TDI-44911
=> fix(TDI-44911):tFileInputExcel has malposition header when enabling

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
=> fix(TDI-44771): Fix error code for prejob in multithread run (#5208)

main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/xpath.javajet
https://jira.talendforge.org/browse/TDI-44883
=> fix(TDI-44883): set value of ERROR_MESSAGE in tFileInputJSON component

main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/xpath.javajet
https://jira.talendforge.org/browse/TDI-44883
Backport of https://github.com/Talend/tdi-studio-se/pull/5216 into "master" branch
=> fix(TDI-44883): set value of ERROR_MESSAGE

main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java, main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml, main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-32442
=> chore: TDI-32442 revert

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
https://jira.talendforge.org/browse/TDI-44880
=> fix(TDI-44880): Add ERROR_MESSAGE in components.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
https://jira.talendforge.org/browse/TDI-44880
Backport of https://github.com/Talend/tdi-studio-se/pull/5207 into "maintenance/7.1" branch.
=> fix(TDI-44880): backport fix to "maintenance/7.1" branch.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
https://jira.talendforge.org/browse/TDI-44880
Backport of https://github.com/Talend/tdi-studio-se/pull/5207 into "maintenance/7.2" branch
=> fix(TDI-44880): backport fix to "maintenance/7.2" branch.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
https://jira.talendforge.org/browse/TDI-44880
Backport of https://github.com/Talend/tdi-studio-se/pull/5207 into "master" branch.
=> fix(TDI-44880): backport fix into "master" branch.

main/plugins/org.talend.designer.core/src/main/java/messages.properties, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/NodeBreakpointAction.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/NodeConditionalBreakpointAction.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorContextMenuProvider.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodecontainer/NodeContainerFigure.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/NodeErrorEditPart.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/NodeFigure.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/ComponentSettingsView.java, main/plugins/org.talend.designer.runprocess/schema/debugprocess_view_helper.exsd, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/EDebugProcessType.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/views/DefaultDebugviewHelper.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/views/IDebugViewHelper.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/views/ProcessView.java
=> feat(TESB-29271): Route debuging feature

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
=> fix(TESB-29271): Fix for headless issue

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/EDebugProcessType.java
=> fix(TESB-29271): Fix for Spack job debug type

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/EDebugProcessType.java
=> fix(TESB-29271): Fix NPE for Spack job debug type

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
https://jira.talendforge.org/browse/TESB-30623 - Data service job bundles built via CI contain empty routines library jar.
The internal jar "lib/routines.jar" contains the expected routine classes.
=> TESB-30623 Ensure routine classes are compiled before the routines library is created.

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/BigDataJobUtil.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
=> tup-27447  backport to patch721 (#4822)

main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/soap/src/main/java/org/talend/soap/SOAPUtil.java, main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
* fix(TDI-44893): upgrade libraries, update code, remove old libs
* fix(TDI-44893): update local provider pom with newest version
Backport to master
=> fix(TDI-44893): upgrade libraries, update code, remove old libs (#5229)

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitUpdateService.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/update/TaCoKitCarFeature.java
kjwang/Feat_TUP-27762_new_version_of_ci
https://github.com/Talend/tdi-studio-se/pull/new/kjwang/Feat_TUP-27762_new_version_of_ci_m
=> kjwang/Feat_TUP-27762_new_version_of_ci (#5248)

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet
https://jira.talendforge.org/browse/TDI-44957
=> fix(TDI-44957): tSSH timeouts use

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet
https://jira.talendforge.org/browse/TDI-44957
Backport of https://github.com/Talend/tdi-studio-se/pull/5303 into "master" branch
=> fix(TDI-44957): Backport - tSSH timeouts use

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/metadata/RepositoryObjectHelper.java
https://jira.talendforge.org/browse/TUP-28618
=> fix(TUP-28618):[Bug] db type dont show Delta in impact page.

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveSnapshotJarMigrationTask.java
https://jira.talendforge.org/browse/TUP-28659
Regnerate poms if snapshot jars were removed
=> fix(TUP-28659): migrate jobs because remove snapshot jars

main/plugins/org.talend.repository/resources/osgi-exclude.properties
=> fix(TESB-30136) javax.activation.UnsupportedDataTypeException

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/TaCoKitGuessSchemaProcess.java
https://jira.talendforge.org/browse/TUP-28612
=> fix(TUP-28612): [TCK] Guess Schema button run the subjob instead of calling discover schema method

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/Action.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/AbstractParameterResolver.java
https://jira.talendforge.org/browse/TCOMP-1757 
=> feat(TCOMP-1757): support context in design time actions

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/Action.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/AbstractParameterResolver.java
https://jira.talendforge.org/browse/TCOMP-1757
=> feat(TCOMP-1757): support context in design time actions (#5220 backport)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
=> feat(TUP-28640):Improve JDBC database support framework to load

main/plugins/org.talend.designer.core.generic/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/EnabletPersonatorAddressBasicSettingTask.java
=> fix(TDQ-18784) add a new migration task

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
=> feat(TUP-28758)Add a warning when we login to a project and if there is

main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml, main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
Missing dependency caused TUJ failure.
Add missing dependency.
=> fix(TDI-44893): added missing dependency

main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
Missing library caused TUJ failure
Add missing library, upgrade soap component
=> fix(TDI-44893): update component, and localprovider

main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_main.javajet
https://jira.talendforge.org/browse/TDI-44997
=> fix(TDI-44997): fix compile error

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveSnapshotJarMigrationTask.java
https://jira.talendforge.org/browse/TUP-28659
Remove snapshot version crypto-utils and slf4j-api-1.7.25.jar
=> fix(TUP-28659): migrate jobs because remove snapshot jars (#5294)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/metadata/RepositoryObjectHelper.java
https://jira.talendforge.org/browse/TUP-28618
=> fix(TUP-28618):[Bug] db type dont show Delta in impact page. (#5275)

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/UnifiedJDBCBean.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/UnifiedJDBCConfigurationBean.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/PropertyTypeController.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/manager/UnifiedComponentsManager.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/UnifiedComponentUtilTest.java
* feat(TUP-28640):Improve JDBC database support framework to load
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
* feat(TUP-28640):Improve JDBC database support framework to load
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
* feat(TUP-28640):Improve JDBC database support framework to load
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
fix(TUP-28746):[Bug] after do "save the property to metadata" studio
will throw error logs.
cf: connection infos with quotes
* feat(TUP-28640):Improve JDBC database support framework to load
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
**What is the current behavior?** (You can also link …
=> feat(TUP-28640):Improve JDBC database support framework to load (#5287)

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
https://jira.talendforge.org/browse/TUP-28952
=> fix(TUP-28952):TOS: NPE when delete items to recycle bin

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
https://jira.talendforge.org/browse/TUP-28952
=> fix(TUP-28952):TOS: NPE when delete items to recycle bin (#5383)

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
=> fix(TESB-30713): Beans folder is missing in routines.jar for route

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
https://jira.talendforge.org/browse/TUP-29022
Compare raw value of jdbc drivers which set in jobsettings
=> fix(TUP-29022): fix jobsettings jdbc change detector

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/AbstractJobSettingsPage.java
https://jira.talendforge.org/browse/TUP-29022
Show change detection popup for jobsettings and items and implicit context changes
=> bugfix(TUP-29022) Fix detection warning popup

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/AbstractJobSettingsPage.java
https://jira.talendforge.org/browse/TUP-29022
Show change detection popup for jobsettings and items and implicit context changes
=> bugfix(TUP-29022) Fix detection warning popup (#5400)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/AbstractJobSettingsPage.java
https://jira.talendforge.org/browse/TUP-29022
https://jira.talendforge.org/browse/TUP-29024
Show changes detection popup correctly for imported projects and project settings
=> fix(TUP-29022):  Fix changes detection for projects

main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
=> update manifest to be same with the jar version in pom

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-28066
Remove lower version of jars based on gavct
=> fix(TUP-28066): remove lower version of jar based on gavct

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-28066
Remove lower version of jars based on gavct
=> fix(TUP-28066): remove the lower jar based on gavct

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-28066
Remove lower version jars based on gavct
=> fix(TUP-28066): remove lower version jars based on gavct

main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_messages.properties, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UncheckTrustAllMigrationTask.java
https://jira.talendforge.org/browse/TDI-44924
=> fix(TDI-44924):tFileFetch should not trust all server by default

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
https://jira.talendforge.org/browse/TDI-45015
=> fix(TDI-45015): tFileInputMail - slow attachments retrieval.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
https://jira.talendforge.org/browse/TDI-45015
Backport of https://github.com/Talend/tdi-studio-se/pull/5399 into "master" branch.
=> fix(TDI-45015): Backport (741) - tFileInputMail retrieves attachments very slow.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
https://jira.talendforge.org/browse/TDI-45015
Backport of https://github.com/Talend/tdi-studio-se/pull/5399/files into "maintenance/7.2" branch
=> fix(TDI-45015): backport fix into "maintenance/7.2" branch

main/plugins/org.talend.designer.components.libs/libs_src/NetSuite_Management/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-ws/pom.xml
https://jira.talendforge.org/browse/TDI-44004
Update cxf for talend-ws and NetSuite_Management lib
=> chore(TDI-44004): update cxf in Netsuite and ws talend libs

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-44004
Update talend-ws lib and it's transitive deps for tWebService component.
Do not merge before build of talend-ws
=> chore(TDI-44004): update talend-ws lib

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet, main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet, main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
Potential NPE pb
resolved, tested on studio, seem to work well => more tests with tuj will be done.
=> TDI-44686 : potential NPE

main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DataBufferCache.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/EnoughDataException.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java, main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/src/main/java/org/talend/msg/utils/MsgMailUtil.java, main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml, main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.excel/build.properties, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-45022
=> chore(TDI-45022): backport Apache POI update to "master"

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
https://jira.talendforge.org/browse/TDI-44087
=> fix(TDI-44087): Update Xstream to 1.4.11.1 version

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
=> fix(TDQ-18826)Set required to true for Dynamic jars

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
=> fix(TDQ-18826) Set required to true for Dynamic jar

main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_main.javajet
https://jira.talendforge.org/browse/TDI-45023
=> fix(TDI-45023): Update tJasper* components to use Apache POI 4.1.2

main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_main.javajet
https://jira.talendforge.org/browse/TDI-45023
Backport of https://github.com/Talend/tdi-studio-se/pull/5426 into "master" branch
=> fix(TDI-45023): Backport - tJasper to use Apache POI 4.1.2

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet, main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet, main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
* TDI-44686 : potential NPE
https://jira.talendforge.org/browse/TDI-44686
=> TDI-44686 : potential NPE (#5164)

i18n/plugins/org.talend.repository.nl/src/main/java/messages_en.properties, main/plugins/org.talend.designer.core/plugin.xml, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/AbstractJobSettingsPage.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UpdateModuleListInComponentsMigrationTask.java, main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/LibraryField.java
* fix(TUP-28978): Add migration
* fix(TUP-28978): show jar for tELMap, show uri for routine/bean dependencies
https://jira.talendforge.org/browse/TUP-28828
https://jira.talendforge.org/browse/TUP-28978
https://jira.talendforge.org/browse/TUP-28979
Replace jar name by maven uri
=> fix(TUP-28978): Add migration (#5422)

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
https://jira.talendforge.org/browse/TDI-45015
Quick fix to remove Input/Output streams declaration outside "try-with-resources", which causes compile error.
=> fix(TDI-45015): removed streams declaration outside try-with-resources

main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.javajet
Reverts Talend/tdi-studio-se#4683
=> Revert "Fix(TDI-44173): Fix for inner element creation in Loop element."

main/plugins/org.talend.designer.components.localprovider/components/tHttpRequest/tHttpRequest_main.javajet
https://jira.talendforge.org/browse/TDI-45098
=> fix(TDI-45098):tHttpRequest accept 2XX as success

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java
https://jira.talendforge.org/browse/TUP-29131
Replace jar name by maven uri for spark jobs
=> bugfix(TUP-29131) Replace jar name by maven uri for spark jobs

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-45054
=> fix(TDI-45054):fix the protected file error.

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.libraries.excel/pom.xml
* fix(TDI-45054):fix the protected file error.
* fix(TDI-45054):update the excel jar in component.
* fix(TDI-45054):update lib version.
https://jira.talendforge.org/browse/TDI-45054
=> fix(TDI-45054):fix the protected file error. (#5428)

main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginFirstTimeStartupActionPage.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-28050
=> Fix TUP-28050 Multi-User: Avoid possible actions that are not supported on shared studio

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
https://jira.talendforge.org/browse/TDI-44994
Upgrade google oauth library to the latest
CVE
=> chore(TDI-44994): bump library version

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
Remove "ROUTE" build type if imported item is job.
=> TESB-30572: [7.1] Job build error

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
Avoid build error by removing property from job design if it's value is "ROUTE".
=> TESB-30572:[7.1] Job build error

main/plugins/org.talend.designer.components.libs/libs_src/filecopy/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/filecopy/src/main/java/org/talend/FileCopy.java, main/plugins/org.talend.designer.components.libs/libs_src/filecopy/src/test/java/org/talend/FileCopyTest.java, main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_java.xml, main/plugins/org.talend.libraries.custom/pom.xml
https://jira.talendforge.org/browse/TDI-45062
=> Pyzhou/tdi 45062 t file copy last modified time 7.3

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
backport to master https://jira.talendforge.org/browse/TDI-44994
=> chore(TDI-44994): bump library version (#5427)

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet, main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
Conflicts:
main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
https://jira.talendforge.org/browse/TPS-4488
https://jira.talendforge.org/browse/TPS-4488
patch
=> fix(TDI-43619): Null Value Treated as <TALEND_NULL> in Subjob (#4488)

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java, test/plugins/org.talend.designer.core.generic.test/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtilsTest.java
https://jira.talendforge.org/browse/TUP-29076
=> feat(TUP-29076):support memsql in studio metadata and components

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java
https://jira.talendforge.org/browse/TUP-29164
Remove duplicated invokes of checkStartNodes
=> fix(TUP-29164): Remove duplicated invokes of checkStartNodes

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java
https://jira.talendforge.org/browse/TUP-29164
Remove duplicated invokes of checkStartNodes
=> fix(TUP-29164): Remove duplicated invokes of checkStartNodes (#5454)

main/plugins/org.talend.designer.codegen/plugin.xml, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsProviderManager.java, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/SharedStudioUserComponentProvider.java, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/UserComponentsProvider.java, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/JetBean.java, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/TalendJETCompiler.java, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/TemplateUtil.java, main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/JetSkeletonManager.java, main/plugins/org.talend.designer.components.exchange/plugin.xml, main/plugins/org.talend.designer.components.exchange/src/main/java/org/talend/designer/components/exchange/ExchangeComponentsProvider.java, main/plugins/org.talend.designer.components.exchange/src/main/java/org/talend/designer/components/exchange/SharedStudioExchangeComponentsProvider.java, main/plugins/org.talend.designer.components.exchange/src/main/java/org/talend/designer/components/exchange/ui/actions/DownloadComponenentsAction.java, main/plugins/org.talend.designer.components.exchange/src/main/java/org/talend/designer/components/exchange/util/ExchangeUtils.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/ComponentBundleToPath.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/CustomComponentSettingPage.java
https://jira.talendforge.org/browse/TUP-28833
=> TUP-28833 Multi-User: support custom javajet component in shared studio

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericWizardService.java, test/plugins/org.talend.designer.core.generic.test/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtilsTest.java
* feat(TUP-29076):support memsql in studio metadata and components
https://jira.talendforge.org/browse/TUP-29076
* feat(TUP-29076):support memsql in studio metadata and components
https://jira.talendforge.org/browse/TUP-29076
fix(TUP-29101):[bug] data viewer failed when export to context
https://jira.talendforge.org/browse/TUP-29101
* feat(TUP-29076):support memsql in studio metadata and components
https://jira.talendforge.org/browse/TUP-29076
**Does …
=> feat(TUP-29076):support memsql in studio metadata and components (#5441)

main/plugins/org.talend.designer.components.libs/libs_src/mdm_services_tomcat/pom.xml
CXF with 3.3.4 version which gets CVE issue
CXF upgrade to 3.3.7
=> TMDM-14904 Update CXF to 3.3.7 due to CVE-2020-1954

main/plugins/org.talend.designer.components.libs/libs_src/NetSuite_Management/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-ws/pom.xml
https://jira.talendforge.org/browse/TDI-44004
=> chore(TDI-44004): update cxf in talend libs

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-44004
=> chore(TDI-44004): update CXF and talend-ws version

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ProcessManager.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ServerManager.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/websocket/WebSocketClient.java, main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ServerManagerTest.java
https://jira.talendforge.org/browse/TUP-28790
=> feat(TUP-28790): Enhance detection of localhost

main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/AbstractTransfer.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/CompleteMultipartDownload.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/Download.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadCallable.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadImpl.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadMonitor.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadPartCallable.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadTaskImpl.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/PersistableDownload.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/TransferCompletionFilter.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/TransferManager.java, main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_messages.properties
https://jira.talendforge.org/browse/TDI-44993
https://jira.talendforge.org/browse/TDI-44993
=> fix(TDI-44993): tS3Get performance issue using multipart target to EFS/NAS

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/tableentry/TableEntryLocation.java
https://jira.talendforge.org/browse/TUP-25235
=> feat(TUP-25235):tELTTeradataMap : allow to rename the alias.

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
=> fix(TESB-30734): Backport from patch 7.2.1

main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/AbstractTransfer.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/CompleteMultipartDownload.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/Download.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadCallable.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadImpl.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadMonitor.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadPartCallable.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/DownloadTaskImpl.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/PersistableDownload.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/TransferCompletionFilter.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/src/main/java/org/talend/aws/TransferManager.java, main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_messages.properties
https://jira.talendforge.org/browse/TDI-44993
https://jira.talendforge.org/browse/TDI-44993
=> fix(TDI-44993): tS3Get performance issue using multipart target to EFS/NAS(#5429)

main/plugins/org.talend.designer.codegen/jet_stub/header.javajet, main/plugins/org.talend.repository/resources/job-rest-template.xml, main/plugins/org.talend.repository/resources/job-template.xml
=> feat(TESB-29949) Pass the data source to a job using a context variable

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/persistence/GenericRepository.java
all the components for jdbc when drag to job.
https://jira.talendforge.org/browse/TUP-28934
=> fix(TUP-28934):JDBC connection created under folder can not generate the

main/plugins/org.talend.designer.core/src/main/java/messages.properties, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/AbstractProcessAction.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/OpenExistVersionProcessAction.java
=> chore(TUP-29273): move to message.properties

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java
https://jira.talendforge.org/browse/TUP-26486
only refresh one time the gui when switch format.
=> feat(TUP-26486) quickly refresh the GUI only one time when switch format.

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java
https://jira.talendforge.org/browse/TUP-26486 
Reverts Talend/tdi-studio-se#5482， will create new pr
=> Revert "feat(TUP-26486) quickly refresh the GUI only one time when switch format."

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java
=> fix(TESB-29553) Publishing a route with cTalendJob from Studio and commandline gives different results

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-45167
=> fix(TDI-45167):Close pre Workbook for tFileOutputExcel

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/ConfigExternalLibPage.java
=> fix(TUP-25925): Cannot add external jar for routines in offline mode

main/plugins/org.talend.designer.components.localprovider/components/tELTMap/tELTMap_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/tJDBCSCDELT_java.xml, main/plugins/org.talend.designer.core.generic/plugin.xml, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/RevertJDBCContextModeMappingFileValueMigrationTask.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/MappingTypeController.java
tELTMap/tJDBCSCDELT from the created metadata
https://jira.talendforge.org/browse/TUP-28699
=> fix(TUP-28699):[Bug] The mapping is wrong after dragging

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
* fix(TUP-29360): Missing log4j2 jar on user routines
* fix(TUP-29360): fix switch log4j level problem
=> fix(TUP-29360): Missing log4j2 jar on user routines (#5529)

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/InputSchemaParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ValueConverter.java, main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameterTest.java
**Support of complete schema definition in Studio**
https://jira.talendforge.org/browse/TCOMP-1761
**Related PR**
- https://github.com/Talend/component-runtime/pull/446
- https://github.com/Talend/tdi-studio-se/pull/5270
=> feat(TCOMP-1761): Support of complete schema definition in Studio

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/InputSchemaParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ValueConverter.java, main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameterTest.java
https://jira.talendforge.org/browse/TCOMP-1761 Backport
=> feat(TCOMP-1761): Support of complete schema definition in Studio BACKPORT

test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/model/parameter/OutputSchemaParameterTest.java
Fix OutputSchemaParameterTest
Fix OutputSchemaParameterTest
=> fix(TUP-29424): OutputSchemaParameterTest

test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/model/parameter/InputSchemaParameterTest.java, test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitorTest.java
Fix junits InputSchemaParameter
Fix junits InputSchemaParameter
=> fix(TUP-29424): fix junit failures related to Parameter change

main/plugins/org.talend.sdk.component.studio-integration/pom.xml, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/AsciidoctorService.java
https://jira.talendforge.org/browse/TDI-45213
The newest ASCII doctor dependency contains the jruby-stdlib version with fixed CVE from SnakeYaml.
CVE fix.
=> chore(TDI-45213): upgrade ascii doctor to prevent snakeyaml CVE

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
https://jira.talendforge.org/browse/TDI-45161
=> TDI-45161 : tFile input delimited correction

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java, test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/utils/DataMapExpressionParserTest.java
https://jira.talendforge.org/browse/TUP-29090
=> fix(TUP-29090):[7.2.1] Extra plus '+' signs in generated SQL

main/plugins/org.talend.designer.components.libs/libs_src/mdm_services_tomcat/src/main/java/mdm_webservice.wsdl, main/plugins/org.talend.designer.components.libs/libs_src/mdm_services_tomcat/src/main/java/org/talend/mdm/webservice/WSTransformerV2.java
https://jira.talendforge.org/browse/TUP-29207
add one field 'withAdminPermissions' to webservice stub class， update the wsdl file.
=> feat(TUP-29207) Add a checkbox Run the process with admin permissions for beforeSaving process

main/plugins/org.talend.designer.components.exchange/src/main/java/org/talend/designer/components/exchange/ui/dialog/ImportExchangeDialog.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractGuessSchemaProcess.java, main/plugins/org.talend.designer.xmlmap/src/main/java/org/talend/designer/xmlmap/editor/actions/ImportTreeFromRepository.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JarBuilder.java
TUP-28891:Shared Studio: Check which functions will write data into
folder "temp" of Studio installation folder from code
https://jira.talendforge.org/browse/TUP-28891
=> Kjwang/feat tup 28891 temp folder (#5465)

main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
https://jira.talendforge.org/browse/TDI-45193
Error if dynamic column and parallele process.
Ok with that
=> TDI-45193 : dynamic col on tFileInputPositional

main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
https://jira.talendforge.org/browse/TDI-45224
=> fix(TDI-45224): Review and update tJasper* dependencies.

main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
https://jira.talendforge.org/browse/TDI-45224
**Other information**: Backport of https://github.com/Talend/tdi-studio-se/pull/5545 into "master" branch.
=> fix(TDI-45224): Backport 7.4.1 - Review and update tJasper* dependencies.

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
https://jira.talendforge.org/browse/TDI-44873
olingo odata bumped to 4.7.1 in tMicrosoftCrmIn/Out
=> feat(TDI-44873) : cve - bump olingo odata to 4.7.1 - maintenance

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.libraries.crm/pom.xml
https://jira.talendforge.org/browse/TDI-44873
olingo odata bump to 4.7.1
=> feat(TDI-44873) : cve - bump olingo odata to 4.7.1 - master

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommand.java, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTDefaultNameMigrationTask.java
https://jira.talendforge.org/browse/TUP-29072
https://jira.talendforge.org/browse/TPS-4519
=> fix(TUP-29072):When renaming link (table) between teltinput and teltmap , the generated SQL query is not updated.

main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataMap/tELTTeradataMap_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_java.xml
https://jira.talendforge.org/browse/TDI-45162
Backport of https://github.com/Talend/tdi-studio-se/pull/5501 into "master" branch. tELTPostgresql* components do not require changes.
=> fix(TDI-45162): Backport 7.4.1 - Rearrange imports in tELTPostgresql* and tELTTeradata components.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml, main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.excel/pom.xml
* use date pattern from studio scheme during parse the date column for event mode
* update version of simpleexcel (the source code of the lib in master branch)
https://jira.talendforge.org/browse/TDI-45089
=> fix(TDI-45089): fix date for excel event mode

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java, test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/utils/DataMapExpressionParserTest.java
https://jira.talendforge.org/browse/TPS-4499
https://jira.talendforge.org/browse/TUP-29090
=> fix(TUP-29090):[7.2.1] Extra plus '+' signs in generated SQL (#5559)

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
https://jira.talendforge.org/browse/TUP-29090
=> fix(TUP-29090):improve since broken some junits .

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/SaveAsProcessWizard.java
https://jira.talendforge.org/browse/TUP-29391
if open a job in the studio and make changes to it then "Save As" to a different job name, the changes are lost and the new job is exactly the same as the original old job(the first time 'Save as' may works).
keep the changes to saved new job.
=> fix(TUP-29391) fix problem that "Save As" loses changes in the studio for such as job, joblet.

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
=> fix(TBD-10285):Add contains predicate to expressions (#4613)

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java
https://jira.talendforge.org/browse/TUP-29572
Update docker.host to jkube.docker.host
=> fix(TUP-29572): fix docker host property name

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommand.java, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTDefaultNameMigrationTask.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommandTest.java
https://jira.talendforge.org/browse/TUP-29072
=> fix(TUP-29072):When renaming link (table) between teltinput and teltmap , the generated SQL query is not updated

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/AliasDialog.java
https://jira.talendforge.org/browse/TUP-29366
=> fix(TUP-29366):[bug] studio can rename alias to an existing name.

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
https://jira.talendforge.org/browse/TDI-45006
=> fix(TDI-45006): Hide "LIKE" operator from CRM-2016 On-Premise setup.

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
https://jira.talendforge.org/browse/TDI-45006
- [X ] The new code does not introduce new technical issues (sonar / eslint)
Backport of https://github.com/Talend/tdi-studio-se/pull/5566 into "master" branch
=> fix(TDI-45006): BP_741: Hide "LIKE" operator CRM-2016 and CRM-2018.

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_main.javajet
https://jira.talendforge.org/browse/TDI-45331
https://jira.talendforge.org/browse/TDI-45331
=> fix(TDI-45331): Exit code for SSH component is not working as expected

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
=> fix(TBD-11724): manually CPing changes from 7.2, TBD-9864

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_main.javajet
https://jira.talendforge.org/browse/TDI-45331
https://jira.talendforge.org/browse/TDI-45331
=> fix(TDI-45331): Exit code for SSH component is not working as expected (#5598)

main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet, main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-45310
https://jira.talendforge.org/browse/TDI-45310
=> fix(TDI-45310): trim the label string when log it to avoid the compiler issue

main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet, main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-45310
https://jira.talendforge.org/browse/TDI-45310
=> fix(TDI-45310): trim the label string when log it to avoid the compiler issue(#5589)

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
=> fix(TBD-11724): manually CPing changes from 7.2, TBD-9864 (#5599)

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
https://jira.talendforge.org/browse/TUP-29432
Regenerate poms for routines after installing required dependency jars
=> fix(TUP-29432): regenerate routine pom after installing jars

main/plugins/org.talend.repository/src/main/java/org/talend/repository/utils/TemplateProcessor.java
=> fix(TESB-31294):move velocity.log to configuration folder

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetDatasetCheckBoxGlobalOption.java
* fix(TBD-11616): parameterize dataset API utilization
* apply migration to only 7.3 and 7.4 studios
* fix for future studio versions
* fix bad merge
=> fix(TBD-11616): parameterize dataset API utilization (#5562)

main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet
https://jira.talendforge.org/browse/TDI-45346
=> fix(TDI-45346):tFileFetch does not accept 202

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeTMatchGroupConfidentWeightTypeTask.java
https://jira.talendforge.org/browse/TDQ-18817
added new migration for tMathGroup
=> fix(TDQ-18817): support context in Confidence Weight on 7.3 and 7.4

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
https://jira.talendforge.org/browse/TUP-29697
Enable profile - packaging-and-assembly for building docker image
=> fix(TUP-29697): fix build docker image from export job

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommand.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTDefaultNameMigrationTask.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommandTest.java
https://jira.talendforge.org/browse/TUP-29072
=> fix(TUP-29072):improve for When renaming link (table) between teltinput and teltmap , the generated SQL query is not updated.

main/plugins/org.talend.designer.components.localprovider/components/tApacheLogInput/tApacheLogInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tExtractPositionalFields/tExtractPositionalFields_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputFullRow/tFileInputFullRow_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml.tmp, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputRegex/tFileInputRegex_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFixedFlowInput/tFixedFlowInput_java.xml, main/plugins/org.talend.libraries.custom/.classpath, main/plugins/org.talend.libraries.custom/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.custom/pom.xml
=> fix(TDI-45260): update components with new library version (#5602)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java
From Database
https://jira.talendforge.org/browse/TUP-28657
=> fix(TUP-29706):"Ingres" "Interbase" "Informix" not support auto fill

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
https://jira.talendforge.org/browse/TDI-45326
old library commons-httpclient was removed and the new org.apache.httpcomponents httpclient library will be used.
https://jira.talendforge.org/browse/TDI-45326
=> chore(TDI-45326): update httpclient

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tCloudStart/tCloudStart_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tCloudStop/tCloudStop_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
https://jira.talendforge.org/browse/TDI-45311
=> fix(TDI-45311):upgrade the version of guava.

main/plugins/org.talend.designer.components.localprovider/components/tGPGDecrypt/tGPGDecrypt_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tGPGDecrypt/tGPGDecrypt_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tGPGDecrypt/tGPGDecrypt_messages.properties, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UncheckUseExtraParameterMigrationTask.java
https://jira.talendforge.org/browse/TDI-45377
=> fix(TDI-45377):tGPGDecrypt fail with gpg2

main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMInput/tVtigerCRMInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMOutput/tVtigerCRMOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
https://jira.talendforge.org/browse/TDI-45366
=> fix(TDI-45366): fix for CVE issue with Apache Axis library.

main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMInput/tVtigerCRMInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMOutput/tVtigerCRMOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
https://jira.talendforge.org/browse/TDI-45366
Backport of https://github.com/Talend/tdi-studio-se/pull/5642 into "master" branch.
=> fix(TDI-45366): BP_741: fix for CVE issue with Apache Axis library. (#5642)

main/plugins/org.talend.repository/resources/osgi-exclude.properties
=> TESB-31188:[7.3] LinkageError when resolving method "javax.xml.soap.SOAPPart.setContent(Ljavax/xml/transform/Source;)V"

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java
https://jira.talendforge.org/browse/TDQ-18757
Support SAP Hana on DQ profiling in Studio
=> feat(TDQ-18757): Support SAP Hana on DQ profiling in Studio

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml, main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
=> chore(TUP-29382): add commons-compress-1.19 for template

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-45404
https://jira.talendforge.org/browse/TDI-45404
=> fix(TDI-45404): tFileOutputExcel component gives The maximum number of cell styles was exceeded error

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
https://jira.talendforge.org/browse/TDI-45385
Backport of https://github.com/Talend/tdi-studio-se/pull/5649 into "master" branch
=> fix(TDI-45385): BP_741: fix CVE for tBonita* components. 

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java
https://jira.talendforge.org/browse/TDQ-18757
support database type SAPHana
=> feat(TDQ-18757): backport on 7.4

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitDependencyService.java
https://jira.talendforge.org/browse/TDI-45225
*Related PR*
- https://github.com/Talend/studio-full-master/pull/574
=> feat(TDI-45225): fix deps svc

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
=> TESB-30792:Upgrade maven plugins

main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/src/main/java/org/talend/fileprocess/delimited/patched/DelimitedDataReader.java, main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/src/main/java/org/talend/fileprocess/delimited/patched/RowParser.java, main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/src/main/java/org/talend/fileprocess/delimited/patched/RowParserByByte.java
=> fix(TDI-45260): save patched version changes on github

main/plugins/org.talend.libraries.crm/pom.xml
For Jira: https://jira.talendforge.org/browse/TDI-45362
=> fix(TDI-45362):update talend-mscrm in crm libraries plugin

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ExecuteSystemCommandCommand.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/color/ColorInfo.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/color/ColorProviderMapper.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/ExpressionBuilderDialogForElt.java
https://jira.talendforge.org/browse/TUP-29782
Draw image on the composite directly instead of using setBackgroundImage() for BigSur.
=> fix(TUP-29782): fixed ELTDBMap display issues on Mac with BigSur.

main/plugins/org.talend.designer.components.localprovider/components/tReplaceList/tReplaceList_main.javajet
https://jira.talendforge.org/browse/TDI-45383
RegExp are not deactivate
RegExp deactivate (except for ignore case)
=> TDI-45383 : replace without regexp

main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/ui/edit/Schema2XMLLinker.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/managers/UIManager.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/MapperUI.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorInfo.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorProviderMapper.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/ui/ExpressionBuilderDialog.java
* fix(TUP-29350): fixed the tMap display issues with Big Sur
* fix(TUP-29350): fixed the tMap display issues with Big Sur
* fix(TUP-29641): fixed tAdvancedFileOutputXML display issues with MacOS BigSur (#5647)
* fix(TUP-29774): fixed scroll display issue with many columns.
* fix(TUP-29767): fixed Expression Builder can't show value and can't edit
* fix(TUP-29766): fixed blank expression issue with Tab key.
https://jira.talendforge.org/browse/TUP-29350
Draw the image on the composite directly instead of using setBackgroundImage() on Big Sur.
**Does this PR introduce a breaking …
=> fix(TUP-29350): fixed the tMap display issues with Big Sur (#5616)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
https://jira.talendforge.org/browse/TUP-29700
1 - Share libraries is disabled by default at startup of studio
2 - User can share libraries manually
3 - When download libraries, does not share library to remote artifact repository if proxy artifact repository is configured.
=> feat(TUP-29700): Don't share libraries during logon studio

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ExecuteSystemCommandCommand.java
https://jira.talendforge.org/browse/TUP-29775
Use CTabFolder instead of TabFolder.
=> fix(TUP-29775): use CTabFolder instead of TabFolder to reslove the display issue in BigSur.

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/color/ColorInfo.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/color/ColorProviderMapper.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/ExpressionBuilderDialogForElt.java
https://jira.talendforge.org/browse/TUP-29782
Fixed ELTDBMap display issues.
=> fix(TUP-29782): fixed ELTDBMap display issues on Mac with BigSur. 

main/plugins/org.talend.designer.components.localprovider/components/tHiveConnection/tHiveConnection_java.xml
=> fix(TBD-10689): deprecate old BD distrib

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
=> TESB-29921:Build/Deploy of a route snapshot with CommandLine has 0 byte

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
https://jira.talendforge.org/browse/TUP-29700
1 - Share libraries is disabled by default at startup of studio
2 - User can share libraries manually
3 - When download libraries, does not share library to remote artifact repository if proxy artifact repository is configured.
=> feat(TUP-29700): Don't share libraries during logon studio (#5660)

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/routines/CreateRoutineAction.java
=> feat(TUP-29943):should not have create routines action when object in

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/WebServiceUI.java, main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/dnd/DropTargetListenerForWebService.java, main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/link/WebServiceTableLiner.java
https://jira.talendforge.org/browse/TUP-29784
Draw the image on the composite directly instead of using setBackgroundImage(). Set all the children's background to transparent.
=> fix(TUP-29784): fix WebService display issues on Mac with BigSur.

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/WebServiceUI.java, main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/dnd/DropTargetListenerForWebService.java, main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ui/link/WebServiceTableLiner.java
https://jira.talendforge.org/browse/TUP-29784
Fixed WebService display issues on Mac with BigSur
=> fix(TUP-29784): fix WebService display issues on Mac with BigSur. (#5720)

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/CodesJarChangeListener.java, main/plugins/org.talend.repository.view.di/plugin.xml, main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/RoutineImportHandler.java, main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/RoutinesJarImportHandler.java, main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/util/ImportHandlerUtil.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/local/ExportItemUtil.java
=> feat(TUP-29943): export codeJar with lib modules, import codeJar with

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
=> fix(TUP-30133):  add directory resource in route template

main/plugins/org.talend.designer.codegen/jet_stub/subprocess_footer.javajet
https://jira.talendforge.org/browse/TDI-32744
Linkto this PR https://github.com/Talend/tbd-studio-ee/pull/2268
Retrieve type with instance name
Retrieve type with type name
=> TDI-32744 : sub process

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
project:import routines.DataQuality cannot be resolved
=> fix(TUP-25649):ERROR when Job in MDM project calling Job in Reference

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
https://jira.talendforge.org/browse/TUP-30170
=> fix(TUP-30170): [7.3.1] tHbaseInput error with R2020-11 or higher java.lang.String cannot be cast to java.util.List

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
=> fix(TESB-31274) jobs containing tRestClient build issues

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_messages.properties, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-45455
Add the possibility to cut exceeding cell length.
=> fix(TDI-45455): excel output exceeding characters

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
=> TESB-31720:[7.4.1]Build a job as OSGi will get a jar with only META-INF

main/plugins/org.talend.repository/resources/osgi-exclude.properties
=> TESB-31657: AWS SQS not able to deploy to Runtime

main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_main.javajet
https://jira.talendforge.org/browse/TDI-29308
Does not work if value is a function that does not return String
Work in that case
=> TDI-29308 - Json

main/plugins/org.talend.designer.components.localprovider/components/tAccessConnection/tAccessConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tAccessInput/tAccessInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tAccessOutput/tAccessOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tAccessRow/tAccessRow_java.xml
https://jira.talendforge.org/browse/TDI-45447
=> fix(TDI-45447): Upgrade bouncycastle

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
https://jira.talendforge.org/browse/TDI-45436
=> fix(TDI-45436):upgrade xstream

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
=> fix(TUP-30179): sync context from ext-resource to resource

main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_messages.properties, main/plugins/org.talend.libraries.excel/pom.xml
=> chore: backport

main/plugins/org.talend.repository.view.di/plugin.xml, main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/CheckCodeJarsDeleteReference.java
=> feat(TUP-29943):add codejar check delete reference

main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/RoutineImportHandler.java, main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/RoutinesJarImportHandler.java, main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/util/ImportHandlerUtil.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/local/ExportItemUtil.java
=> feat(TUP-29943):export and import to deploy libs issue

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeFileInputDynamicFieldLength.java
For JIRA: https://jira.talendforge.org/browse/TDI-45400
=> fix(TDI-45400):Dynamic Schema has default length of 100 even after setting to different amount

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeFileInputDynamicFieldLength.java
For JIRA: https://jira.talendforge.org/browse/TDI-45400
backport master
=> fix(TDI-45400):Dynamic Schema has default length of 100 even after setting to different amount (#5770)

main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileOutputStep2Form.java, main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep2Form.java, main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/JSONToXPathLinker.java, main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/view/JSONTree2SchemaLinker.java
https://jira.talendforge.org/browse/TUP-23477
Fixed TreeToTable connection line issue on Mac with BigSur.
=> fix(TUP-23477):fix TreeToTable connection line issue on Mac with BigSur.

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitDependencyService.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCokitImageUtil.java
https://jira.talendforge.org/browse/TUP-23738
=> fix(TUP-23738):The couchbase icon is not correct when import (#5792)

main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_main.javajet
https://jira.talendforge.org/browse/TDI-30267
=> fix(TDI-30267): adjusting batch insert logic for Oracle DB.

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
=> feat(TBD-10921):Add Spark local 3.0.x

main/plugins/org.talend.sdk.component.studio-integration/messages.properties, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitUpdateService.java
* Fix TUP-29885 ERROR: Some patches are not compatible with current
product
https://jira.talendforge.org/browse/TUP-29885
=> Fix TUP-29885 ERROR: Some patches are not compatible with current product (#5714)

main/plugins/org.talend.designer.core/plugin.xml, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UpdateModuleListInComponents2MigrationTask.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UpdateModuleListInComponentsMigrationTask.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/UpdateMoudleListInComponentsMigrationTest.java
https://jira.talendforge.org/browse/TUP-30186
wrong migration change on hex value during import lower version project.
migration change on hex value during import lower version project, improve the hex value handle during job save
=> fix(TUP-30186) On studio ,java.lang.RuntimeException: Illegal hexadecimal character m at index 0

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/FixUpgradePasswordEncryptionAlg4ItemMigrationTask.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpgradePasswordEncryptionAlg4ItemMigrationTask.java
https://jira.talendforge.org/browse/TUP-29764
Encrypt all of PASSWORD fileds of job with AES algorithms in new format.
=> fix(TUP-29764): encrypt all PASSWORD fields of job in new format (#5760)

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
https://jira.talendforge.org/browse/TUP-29571
=> fix(TUP-29571)Couchbase: items cannot show if parentnode is missing

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetUseLocalTimezone.java
=> fix(TBD-11964): migration task for use local timezone

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
* fix(TDI-45476): Increate tFileOutputMSXML performance
* fix(TDI-45476): Change generic type for list to avoid compile error
* fix(TDI-45476): Store sublist into the resourceMap
* fix(TDI-45476): Fix code compile error
=> fix(TDI-45476): Increate tFileOutputMSXML performance (#5741)

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetUseLocalTimezone.java
* fix(TBD-11964): migration task for use local timezone
* fix(TBD-11964): correct date
=> fix(TBD-11964): migration task for use local timezone (#5802)

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/UpdateMoudleListInComponentsMigrationTest.java
=> fix(TUP-30186) fix unit test failure.

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
Reverts Talend/tdi-studio-se#5821
=> Revert "fix(TDI-45503):Comma missing for tELTMap with multiple inputs, when a…"

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
https://jira.talendforge.org/browse/TUP-30360
Add a preference to disable sharing libraries at startup
=> fix(TUP-30360): add an option to disable sharing libraries

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
https://jira.talendforge.org/browse/TUP-30360
Add a preference to disable sharing libraries at startup
=> fix(TUP-30360): add an option to disable sharing libraries (#5814)

main/plugins/org.talend.designer.components.localprovider/components/tCloudStart/tCloudStart_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tCloudStop/tCloudStop_java.xml
https://github.com/Talend/tdi-studio-se/pull/5804
=> fix(TDI-45529):CVE bouncy castle tcloudXXX

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
=> TESB-32126: Null pointer exception when accessing job properties

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
=> fix(TDI-45476): Remove adding second list

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/jobsettings/JobSettingsManagerTest.java
=> fix(TUP-30373): Implicit Context with field separator tab "\t" doesn't work

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
=> fix(TDI-45476): Remove adding second list (#5838)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/jobsettings/JobSettingsManagerTest.java
…t work (#5825)
* fix(TUP-30373): Implicit Context with field separator tab "\t" doesn't
work anymore
* TUP-30373  code change + add junit
=> fix(TUP-30373): Implicit Context with field separator tab "\t" 

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java, main/plugins/org.talend.designer.rowgenerator/src/main/java/org/talend/designer/rowgenerator/shadow/RowGenProcess.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToDelimitedProcess.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToXmlProcess.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/AnyIntoLogRowProcess.java
=> TBD(11971):Spark joblets keeps defaulting to HDFS

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java, main/plugins/org.talend.designer.rowgenerator/src/main/java/org/talend/designer/rowgenerator/shadow/RowGenProcess.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToDelimitedProcess.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/FileinToXmlProcess.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/AnyIntoLogRowProcess.java
=> fix(TBD-11971): Spark joblets keeps defaulting to HDFS

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/SetupProcessDependenciesRoutinesAction.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/CodesJarChangeListener.java, main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/EditPropertiesAction.java
=> feat(TUP-29943):rename issues

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
https://jira.talendforge.org/browse/TDI-45608
Upgrade Snowflake driver for tCreateTable component
=> chore(TDI-45608): upgrade Snowflake driver version

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
=> feat(TUP-29943):build out job not include inner code items

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
https://jira.talendforge.org/browse/TUP-28836
=> fix(TUP-28836)Can't change JDBC existing driver jar for Implicit Context Load

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemAction.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/routines/AbstractAssignCodesToJarAction.java
=> feat(TUP-29943):disable export action for innercode, and duplicate

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/ElementParameter.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TUP-30273
=> fix(TUP-30273)tDBOutput component compilation error

main/plugins/org.talend.designer.components.libs/libs_src/talendsap/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendsap/src/main/java/org/talend/sap/DocumentExtractor.java, main/plugins/org.talend.designer.components.libs/libs_src/talendsap/src/main/java/org/talend/sap/DocumentHelper.java, main/plugins/org.talend.designer.components.libs/libs_src/talendsap/src/main/java/org/talend/sap/SAPParameterType.java, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SAPBAPIParameterTypeMigrationTask.java
https://jira.talendforge.org/browse/TPS-4677
=> fix(TDI-39084): fail to get sap table parameter for tsapbapi and throw NPE.

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
=> fix(TESB-32252) Ignore "SNAPSHOT" during dependencies comparison

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/InputDataMapTableView.java
=> TUP-30333 tMap with Lookup model Reload at each row freezes Studio

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/InputDataMapTableView.java
…5817)
* TUP-30333 tMap with Lookup model Reload at each row freezes Studio
* TUP-30333 add comments
* TUP-30333 add condition for refresh background
=> fix(TUP-30333) tMap with Lookup model Reload at each row freezes Studio

main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
https://jira.talendforge.org/browse/TDI-45668
=> fix(TDI-45668) CVE ant tfileUnactive

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TDI-45704
*Related PRs*
- https://github.com/Talend/studio-full-master/pull/660
- https://github.com/Talend/tcommon-studio-ee/pull/1767
- https://github.com/Talend/tcommon-studio-se/pull/4090
- https://github.com/Talend/tdi-studio-se/pull/5890
=> feat(TDI-45704): bump component-runtime to 1.30.0

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
https://jira.talendforge.org/browse/TDI-45613
=> fix(TDI-45613):fix the issue in md5.

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
Co-authored-by: qyliu <qyliu@talend.com>
https://jira.talendforge.org/browse/TDI-45561
https://jira.talendforge.org/browse/TDI-45561
=> fix(TDI-45561): Getting Permission denied error in tFileInputExcel

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
contains space
https://jira.talendforge.org/browse/TUP-30548
=> fix(TUP-30548):Debugger does not work in 7.3 if the installation path

main/plugins/org.talend.designer.core/META-INF/MANIFEST.MF, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/NodePart.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/footer/FooterComposite.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/tabs/StyledTextHandler.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/InputDataMapTableView.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/OutputDataMapTableView.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarInputZone.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarOutputZone.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarZone.java
https://jira.talendforge.org/browse/TUP-26185
=> Fix: TUP-26185 Merge GIT branches - Conflict resolution - the "Compare

main/plugins/org.talend.designer.core/META-INF/MANIFEST.MF, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/NodePart.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/footer/FooterComposite.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/tabs/StyledTextHandler.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/InputDataMapTableView.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/OutputDataMapTableView.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarInputZone.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarOutputZone.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarZone.java
https://jira.talendforge.org/browse/TUP-26185
=> Fix: TUP-26185 Merge GIT branches - Conflict resolution - the "Compare (#5876)

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
=> fix(TESB-32028) Remove supported ref Code Projects

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/InputDataMapTableView.java
…5817)
* TUP-30333 tMap with Lookup model Reload at each row freezes Studio
* TUP-30333 add comments
* TUP-30333 add condition for refresh background
=> fix(TUP-30333): tMap with Lookup model Reload at each row freezes Studio 

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TUP-30041
do not show warning message if db type column does not show.
=> fix(TUP-30041) tBigQueryInput Column Type - the Schema's db Type not correct for this components

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TUP-30041
=> fix(TUP-30041) do not show warning message if db type column does not show.

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java, main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/InputDataMapTableView.java
…5817) (#5874)
* TUP-30333 tMap with Lookup model Reload at each row freezes Studio
* TUP-30333 add comments
* TUP-30333 add condition for refresh background
=> TUP-30333 tMap with Lookup model Reload at each row freezes Studio 

main/plugins/org.talend.designer.core/src/main/java/messages.properties, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
https://jira.talendforge.org/browse/TUP-25109
retrieve colums according to sql.
=> fix(TUP-25109): backport TUP-25109

main/plugins/org.talend.designer.core/src/main/java/messages.properties, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
https://jira.talendforge.org/browse/TUP-30526
Guess schema based on sql input
=> fix(TUP-25109): backport TUP-25109 (#5882)

main/plugins/org.talend.designer.dbmap/src/main/java/messages.properties, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/DbMapComponent.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/PropertySetDialog.java, main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTEnableColumnAliasMigrationTask.java, test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/oracle/OracleGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-30043
=> fix(TUP-30043):Add a new option for tELTOracleMap to generate column alias on selection.

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
https://jira.talendforge.org/browse/TUP-25820
backport
=> fix(TUP-25820): backport

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractGuessSchemaProcess.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
=> fix(TUP-30621): Guess schema generate the wrong encoding column name

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
https://jira.talendforge.org/browse/TUP-30250
=> fix(TUP-30250) Not able to share snowflake connection between job and joblet. 

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
https://jira.talendforge.org/browse/TUP-30250
=> fix(TUP-30250) Not able to share snowflake connection between job and joblet.

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
=> feat(TUP-29014): Add only compile code projects function for TDM

main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
https://jira.talendforge.org/browse/TDI-45702
=> fix(TDI-45702):fix the syntax error in eltoutput (#5895)

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveSnapshotJarMigrationTask.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdateDaikonCryptoUtilsMigrationTask.java
https://jira.talendforge.org/browse/TUP-30648
=> TUP-30648 Migration: tRun job cannot run if Install 731 R02 monthly patch plus R03 temp patch

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdateDaikonCryptoUtilsMigrationTask.java
=> fix(TUP-27224)Update Daikon Crypto Utils to 1.15.0

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-30589
=> fix(TUP-30589): Mockito cannot mock this class.

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-30651
=> fix(TUP-30651): Login page won't be refreshed after delete project

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
=> TESB-31465:[7.3.1] Studio ESB build performance issue

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddAndSetDBVersionValueCosmosDB.java
https://jira.talendforge.org/browse/TDI-45590
If this PR contains a breaking change, please describe the impact and migration path for existing applications: 
=> feat(TDI-45590): migration task for CosmosDB

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
=> feat(TBD-11882): update tCollectAndCheck for BD (#5919)

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
runtime with message"[statistics] disconnected"
=> TESB-32453:DemoServiceConsumer/DemoRESTConsumer fail to deploy to

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddAndSetDBVersionValueCosmosDB.java
https://jira.talendforge.org/browse/TDI-45590
Backport of https://github.com/Talend/tdi-studio-se/pull/5861 into patch branch for R2021-03 monthly release.
=> feat(TDI-45590): migration task for CosmosDB (#5861)

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/AddKafkaExtraInfo.java
=> fix(TBD-12011): fix for release branch

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java
https://jira.talendforge.org/browse/TUP-30758
=> fix(TUP-30758):tSingleStoreOutputBulkExec can't work

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveSnapshotJarMigrationTask.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdateDaikonCryptoUtilsMigrationTask.java
https://jira.talendforge.org/browse/TUP-30648
=> TUP-30648 Migration: tRun job cannot run if Install 731 R02 monthly

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java
https://jira.talendforge.org/browse/TUP-30758
=> fix(TUP-30758):tSingleStoreOutputBulkExec can't work (#5964)

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
=> fix(TESB-32507) Correct manifest generation for org.talend.esb.authorization.xacml.rt.pep

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/JavaProcessUtilTest.java
https://jira.talendforge.org/browse/TUP-30522
=> chore(TUP-30522) add test case for version contains 'SNAPSHOT'

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/AddKafkaExtraInfo.java
=> fix(TBD-12011): master fix

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ParallelExecutionUtils.java, main/plugins/org.talend.designer.scd/src/main/java/org/talend/designer/scd/ScdComponentService.java
the job
https://jira.talendforge.org/browse/TUP-30615
=> fix(TUP-30615):Schema Update Detection popping up everytime upon opening

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/CheckLogManagerTest.java
=> fix(TBD-12776): Fix testAddLog4jToModuleList unit test

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeGreenplumDefaultDriverMigrationTask.java
https://jira.talendforge.org/browse/TUP-30381
=> feat(TUP-30381)Support greenplum driver for Greenplum Database in studio metadata

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TDI-45809
**Related PR**:
- https://github.com/Talend/studio-full-master/pull/688
- https://github.com/Talend/tcommon-studio-ee/pull/1823
- https://github.com/Talend/tcommon-studio-se/pull/4145
- https://github.com/Talend/tdi-studio-se/pull/6004
=> feat(TDI-45809): bump component-runtime to 1.31.0

main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinBulkExec/tSalesforceEinsteinBulkExec_java.xml
https://jira.talendforge.org/browse/TDI-45655
=> fix(TDI-45727):CVE jackson-mapper-asl

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
=> TESB-32307 tESBConsumer - wrong header content-type

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
https://jira.talendforge.org/browse/TDI-45246
**Related PR:**
- https://github.com/Talend/tdi-studio-se/pull/6010
=> feat(TDI-45246): do not put in configuration hidden parameters

main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_java.xml
https://jira.talendforge.org/browse/TDI-45834
=> fix(TDI-45834):tFileCopy change module name

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_begin.javajet, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
https://jira.talendforge.org/browse/TUP-30047
Correct classpath for tRunJob for CI, if dynamic job is enabled
=> feat(TUP-30047): Need support of tRunJob with Dynamic Job option enabled on test cases / CI/CD

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
=> fix the backport code conflict

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
=> bugfix(APPINT-32723) Job bundle name is corrected

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/IncomingSchemaEnforcerTest.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java, main/plugins/org.talend.libraries.custom/plugin.xml, main/plugins/org.talend.libraries.custom/pom.xml
https://jira.talendforge.org/browse/TDI-45650
https://jira.talendforge.org/browse/TDI-45650
=> fix(TDI-45650): [7.3.1] tDeltaLakeOutput- not handling the updates when we are using Dynamic schema

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
https://jira.talendforge.org/browse/TUP-30345
Removed the warning message tJDBCRow, tJDBCCommit and derivative components.
=> fix(TUP-30345):remove nooutput warning with tJDBCRow, tJDBCCommit and derivative components.

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
=> bugfix(APPINT-32738) Job execution for Linux is corrected

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
https://jira.talendforge.org/browse/TDI-45815
https://jira.talendforge.org/browse/TDI-45815
=> fix(TDI-45815): CVE: xstream-1.4.15.jar

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml, main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
=> chore(TUP-27039): Update Commons Compress to 1.19 backport to 7.3

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/MultipleThreadDynamicComposite.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
https://jira.talendforge.org/browse/TUP-30793
=> fix(TUP-30793):TCK Datastore on studio Metadata.

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/postgres/PostgresGenerationManager.java, test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
https://jira.talendforge.org/browse/TUP-30731
=> fix(TUP-30731):tELTPostgresqloutput context not work when checked "use update statement without subqueries"

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_main.javajet
https://jira.talendforge.org/browse/TDI-45786
without charset
Use parameter Charset.
=> TDI-45786 - add charset on dynamic

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_main.javajet
* TDI-45786 - add charset on dynamic
=> TDI-45786 - add charset on dynamic (#6027)

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/routinesjar/NewRoutinesJarWizard.java
create custom routine jar/bean jar.
=> fix(TUP-30786):Avoid to click finish button more than once when do

main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateAndDelete.javajet, main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateOnDuplicateKey.javajet
* fix(TDI-45642): Count key columns
* fix(TDI-45642): Fix another regression related to dynamic schema
=> fix(TDI-45642): Count key columns (#6039)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java
=> bugfix(APPINT-32306) Wrong artifact version of the job called by a route

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
=> fix(TUP-30954)CVE_xstream-1.4.15.jar

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/TosTokenCollector.java
https://jira.talendforge.org/browse/TUP-30358
=> feat(TUP-30358) Enhance Data Collector - Route usage details

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
https://jira.talendforge.org/browse/TUP-29033
=> fix(TUP-29033):Fail to run testcase in studio and CI

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java
=> fix(TUP-30625): update maven project after convert jobscript to job

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/java/TalendJavaCompletionProcessor.java
https://jira.talendforge.org/browse/TUP-29284
Do not show proposals for disabled categories(proposal kinds).
=> fix(TUP-29284): only show proposals for enabled categories(proposal kinds).

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-30849
=> fix(TUP-30849):Improve build Job performance

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/LibraryField.java
https://jira.talendforge.org/browse/TUP-30458
=> fix(TUP-30458):Studio throw Unhandled event loop exception when click in blank of the panel in "Import External Library".

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Reverts Talend/tdi-studio-se#5987
=> Revert "feat(TDI-45746): fix date context variable"

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/SetupProcessDependenciesRoutinesAction.java
fix(TUP-30791): remove setup code dependencies action for testcase
=> fix(TUP-30586):Routine/Bean custom jars dependency management issues left todo

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/DataSourceConfig.java
=> APPINT-32688:R2021-03 issue with tDB*** using datasource

main/plugins/org.talend.designer.core/META-INF/MANIFEST.MF, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractTableController.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ColumnListController.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/AbstractPropertiesTableEditorView.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java, main/plugins/org.talend.sdk.component.studio-integration/META-INF/MANIFEST.MF, main/plugins/org.talend.sdk.component.studio-integration/plugin.xml, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/tableeditor/TaCoKitPropertiesTableEditorView.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/AbstractActionParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/Action.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TableActionParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TableElementParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ValueSelectionParameter.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/AbstractParameterResolver.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/controller/SuggestableTableController.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/controller/TaCoKitTableController.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/generator/TaCoKitTableGenerator.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
https://jira.talendforge.org/browse/TUP-30291
=> feat(TUP-30291):Add Suggestable support for Table options (List<Row>) in Studio.

main/features/org.talend.rcp.branding.tos.test.feature/feature.xml
=> fix(TUP-30992)CVE: junit-4.11,4.13

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java
=> bugfix(APPINT-32288) Propagate "bundleVersion" option

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/java/TalendJavaCompletionProcessor.java
https://jira.talendforge.org/browse/TUP-29284
Do not show proposals for disabled categories
=> fix(TUP-29284): only show proposals for enabled categories (#6070)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
https://jira.talendforge.org/browse/TUP-30992
fix(TUP-29033):Fail to run testcase in studio and CI
https://jira.talendforge.org/browse/TUP-29033
=> fix(TUP-30992):CVE: junit-4.11,4.13

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
https://jira.talendforge.org/browse/TUP-30992
=> fix(TUP-30992):CVE: junit-4.11,4.13 (#6110)

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/IncomingSchemaEnforcerTest.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java, main/plugins/org.talend.libraries.custom/plugin.xml, main/plugins/org.talend.libraries.custom/pom.xml
https://jira.talendforge.org/browse/TDI-45577
https://jira.talendforge.org/browse/TDI-45577
=> fix(TDI-45577): Job using snowflake dynamic schema fails with special char(#6095)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
https://jira.talendforge.org/browse/TUP-30992
Fix junit version
=> chore(TUP-30992): fix junits

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
https://jira.talendforge.org/browse/TUP-30793
=> fix(TUP-30793):to fix the password problem of RabbitMQ.

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
https://jira.talendforge.org/browse/TUP-30992
=> fix(TUP-30992):CVE: junit-4.11,4.12,4.13

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/TaCoKitCache.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCokitImageUtil.java
* TUP-21090 Support connection component for tacokit (Fix command line
load image error)
https://jira.talendforge.org/browse/TUP-21090
=> Kjwang/fix tup 21090 fix command line load image error p73 (#6125)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/TaCoKitCache.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCokitImageUtil.java
load image error)
https://jira.talendforge.org/browse/TUP-21090
TUP-21090 Support connection component for tacokit (Fix command line load image error)
https://jira.talendforge.org/browse/TUP-21090
=> TUP-21090 Support connection component for tacokit (Fix command line

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
=> chore: bump to tck:1.32.0

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java
Backport of https://jira.talendforge.org/browse/TDI-45551
=> fix(TDI-45551): SingleStore fix blob type processing (#6084)

main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/BranchesSelectionDialog.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-25494
Provide branch search and memory from launcher.
=> feat(TUP-25494): provide branch search and memory from launcher.

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
TUP-31096 Could not find or load main class error on the jobs created on
the Feature Branch which has #
https://jira.talendforge.org/browse/TUP-31096
=> TUP-31096 Could not find or load main class error on the jobs created on the Feature Branch which has # 

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
https://jira.talendforge.org/browse/TDI-45879
=> fix(TDI-45879): save initial value of NB_LINE to globalMap.

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
https://jira.talendforge.org/browse/TDI-45879
Backport of https://github.com/Talend/tdi-studio-se/pull/6076 into "master" branch
=> fix(TDI-45879): BP_741: save initial value of NB_LINE to globalMap.

main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/BranchesSelectionDialog.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-25494
Provide branch search and memory from launcher.
=> feat(TUP-25494): provide branch search and memory from launcher. (#6138)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
https://jira.talendforge.org/browse/TUP-21425
=> fix(TUP-21425)Job built in 7.0.1 not working in 7.1.1 (#3106) (#3115)

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
Reverts Talend/tdi-studio-se#6151 Because it bring in https://jira.talendforge.org/browse/TUP-31376
=> Revert "TUP-31096 Could not find or load main class error on the jobs created on the Feature Branch which has # "

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
Reverts Talend/tdi-studio-se#6082 Because it bring in https://jira.talendforge.org/browse/TUP-31376
=> Revert "TUP-31096 Could not find or load main class error on the jobs created on the Feature Branch which has #"

main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
Remove wrong-brought code 7.4 from 7.3 branch
=> fix(TDI-45642): Fix codegen error for Greenplum

main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
* fix(TDI-45642): Fix codegen error for Greenplum
* chore(TDI-45642): Add missing empty line
=> fix(TDI-45642): Fix codegen error for Greenplum (#6102)

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
=> APPINT-32905: Issue with Rest service flow

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
https://jira.talendforge.org/browse/TUP-30413
=> fix(TUP-30413):Comma missing for tELTMap with multiple inputs, when aliases are used.

main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> fix/TBD-12115: CVE: derby-10.11.1.1.jar

main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> fix(TBD-12115): master merge

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-31346
Set selected branch
=> fix(TUP-31346): add default branch for remote uninitialized git repo

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/util/GenericContextUtil.java
Metadata Connection with a Snowflake password that has a slash character
https://jira.talendforge.org/browse/TUP-31237
=> fix(TUP-31237):Invalid username or password when creating a Snowflake

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
Fix TUP-31096 Could not find or load main class error on the jobs created on the Feature Branch which has #
https://jira.talendforge.org/browse/TUP-31096
=> Fix TUP-31096 Could not find or load main class error on the jobs created on the Feature Branch which has #

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/GeneralProjectSettingPage.java
https://jira.talendforge.org/browse/TUP-31429
=> Fix:TUP-31429 Fail to add reference project

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
Reverts Talend/tdi-studio-se#6171
=> Revert "APPINT-32905: Issue with Rest service flow"

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
Fix TUP-31096 Could not find or load main class error on the jobs created on the Feature Branch which has #
https://jira.talendforge.org/browse/TUP-31096
=> Fix TUP-31096 Could not find or load main class error on the jobs

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/GeneralProjectSettingPage.java
Fix:TUP-31429 Fail to add reference project
https://jira.talendforge.org/browse/TUP-31429
=> Fix:TUP-31429 Fail to add reference project (#6183)

main/plugins/org.talend.designer.components.localprovider/components/tEXistConnection/tEXistConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tEXistDelete/tEXistDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tEXistGet/tEXistGet_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tEXistList/tEXistList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tEXistPut/tEXistPut_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tEXistXQuery/tEXistXQuery_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tEXistXUpdate/tEXistXUpdate_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml
https://jira.talendforge.org/browse/TDI-46004
=> fix(TDI-46004): tEXist components and tXMLRPCInput dependency import.

main/plugins/org.talend.designer.components.localprovider/components/tREST/tREST_java.xml
=> fix(TDI-45824): Bump jersey for tRest

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloCheckElements/tPaloCheckElements_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloConnection/tPaloConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloCube/tPaloCube_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloCubeList/tPaloCubeList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloDatabase/tPaloDatabase_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloDatabaseList/tPaloDatabaseList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloDimension/tPaloDimension_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloDimensionList/tPaloDimensionList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloInputMulti/tPaloInputMulti_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloOutputMulti/tPaloOutputMulti_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloRule/tPaloRule_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPaloRuleList/tPaloRuleList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tServiceNowInput/tServiceNowInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
https://jira.talendforge.org/browse/TDI-46005
=> fix(TDI-46005): cve bump httpclient to 4.5.13

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-45882
Bump CXF to 3.3.10 version
=> chore(TDI-45882): bump cxf 3 3 10

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.libraries.crm/pom.xml
https://jira.talendforge.org/browse/TDI-45929
talend-mscrm has a new version of junit and it's declared as test dependency.
=> chore(TDI-45929): cve junit

main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
=> fix(TDI-45910):Jakarta-ORO imported

main/plugins/org.talend.designer.components.localprovider/components/tGoogleDataprocManage/tGoogleDataprocManage_java.xml
https://jira.talendforge.org/browse/TDI-45968
https://github.com/Talend/tdi-studio-se/pull/6136
=> fix(TDI-45968): fix commons-codec module name (#6136)

main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> fix(TBD-12142): CVE: jersey-core-1.4 and jersey-1.9

main/plugins/org.talend.repository/src/main/java/messages.properties
https://jira.talendforge.org/browse/TUP-25494
Correct dialog title.
=> TUP-25494:Correct dialog title.

main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> fix(TBD-12358): CVE: Update CXF to 3.3.10

main/plugins/org.talend.designer.components.libs/libs_src/mdm_services_tomcat/pom.xml
=> chore(TDQ-19297): Upgrade 'cxf' to 3.3.10

main/plugins/org.talend.designer.components.libs/libs_src/mdm_services_tomcat/pom.xml
=> chore(TDQ-19297):Upgrade 'cxf' to 3.3.10 for security

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/subjobcontainer/SubjobContainer.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/subjobcontainer/SubjobContainerFigure.java
https://jira.talendforge.org/browse/TUP-26747
=> feat(TUP-26747):improve outline for joblet and subjob. 

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/subjobcontainer/SubjobContainer.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/subjobcontainer/SubjobContainerFigure.java
https://jira.talendforge.org/browse/TUP-26747
=> feat(TUP-26747):improve Outline for joblet and subjob.

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
=> APPINT-32987: Fix dublicate variable

main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
* fix(TDI-45910):Jakarta-ORO imported
* fix(TDI-45910):Jakarta-ORO updated the mvn GAV and required
=> fix(TDI-45910):Jakarta-ORO imported (#6166)

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
=> fix(APPINT-32995) Root poms installed in CI mode

main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> fix(TBD-12358): cfx lib change

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
=> fix(TDI-46060): Fix compile error for tFTPFileList

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
=> fix(TDI-46060): Fix compile error for tFTPFileList (#6219)

main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> fix(TBD-12358): cfx lib change (#6228)

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
=> fix(APPINT-32953) Routelets are built before Route

main/features/org.talend.tos.libraries.feature/feature.xml, main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> chore(TUP-29079): remove some urlpath

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
=> chore(APPINT-32953) fix the NPE when using DI license

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/TaCoKitGuessSchemaProcess.java
subjob can't work
https://jira.talendforge.org/browse/TUP-31213
=> fix(TUP-31213)tNetSuiteV2019Input failed to guess schema because preview

main/plugins/org.talend.repository/resources/osgi-exclude.properties
=> APPINT-32843 Fix error while deploying a route with tAzureStorageQueue

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
kar file without a first run in Studio
https://jira.talendforge.org/browse/APPINT-32953
=> fix(APPINT-32953):[7.3.1 patch] Route+routelet will not build as osgi

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
=> bugfix(APPINT-33067) Backport fix for NPE

main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
=> chore: backport to 7.2

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_end.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_process_records_end.javajet, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
* handle specific metakey
* extract metadata in javajet
https://jira.talendforge.org/browse/TCOMP-705
https://jira.talendforge.org/browse/TDI-45963
This PR can be merged only after 
1. [Component-runtime-part:467](https://github.com/Talend/component-runtime/pull/467)
2. Bump of the version component runtime in the Studio. New code uses classes (annotation) from the new related PR.
=> feat(TDI-45963): after variables

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_end.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_process_records_end.javajet, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
* handle specific metakey
* feature uses metadata endpoint in the framework
* extract metadata in javajet
https://jira.talendforge.org/browse/TDI-45963
port from maintenance/7.3
=> feat(TDI-45963): after variables (#5933)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java
=> fix(TUP-31164)Guess schema button on the informix tDBinput component

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/TRunjobUtil.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java, main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java
https://jira.talendforge.org/browse/TUP-31117
=> feat(TUP-31117):Improve performances related to recursive jobs

main/plugins/org.talend.repository/resources/osgi-exclude.properties
=> APPINT-32699 Fix error while deploying a route with tAzureStorageQueue

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/TaCoKitGuessSchemaProcess.java
Token-based login type
https://jira.talendforge.org/browse/TUP-31228
=> fix(TUP-31228)Netsuite tck guess schema when use existing connection and

main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/local/ExportItemUtil.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemAction.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizardPage.java
https://jira.talendforge.org/browse/TUP-30343
have the "Export Dependencies" option checked by default.
=> feat(TUP-30343):have the "Export Dependencies" option checked by default.

main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/local/ExportItemUtil.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemAction.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizardPage.java
https://jira.talendforge.org/browse/TUP-30343
have the "Export Dependencies" option checked by default.
=> feat(TUP-30343):have the "Export Dependencies" option checked by default.(#6273)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
directory method
https://jira.talendforge.org/browse/TUP-31316
=> fix(TUP-31316):Error connecting to Azure SQL database with Azure Active

main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.excel/build.properties, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TUP-31617
Remove commons-compress-1.18.jar
=> chore(TUP-31617): remove commons-compress-1.18

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/HadoopJarSetupController.java
https://jira.talendforge.org/browse/TUP-31553
=> fix(TUP-31553):Hadoop Metadata Wizard when using custom distro dialog box doesnt pop up to import dependencies.

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
* Add reuse connection support to standalone connectors
=> fix(TDI-46100): connection support

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
* fix(TDI-46100): connection support
* Add reuse connection support to standalone connectors
* fix(TDI-46100): connection support
* Add comment explaining reflection
Co-authored-by: Dmytro Chmyga <dmytro.chmyga@globallogic.com>
=> fix(TDI-46100): connection support (#6253)

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
=> APPINT-33068: Fix variable duplication

main/plugins/org.talend.repository/META-INF/MANIFEST.MF
https://jira.talendforge.org/browse/TUP-30834
=> feat(TUP-30834) add missing comma of require bundle

main/plugins/org.talend.sdk.component.studio-integration/pom.xml, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/AsciidoctorService.java
https://jira.talendforge.org/browse/TDI-46053
=> chore(TDI-46053): upgrade snakeyaml to 1.26

main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/build.properties
https://jira.talendforge.org/browse/TDI-45979
https://jira.talendforge.org/browse/TDI-45979
=> fix(TDI-45979): commons-compress-1.18.jar to 1.19

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TDI-46215
*Related PR*
- https://github.com/Talend/tdi-studio-se/pull/6294
- https://github.com/Talend/tcommon-studio-se/pull/4338
- https://github.com/Talend/tcommon-studio-ee/pull/1955
- https://github.com/Talend/studio-full-master/pull/780
=> feat(TDI-46215): bump component-runtime to 1.33.1

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
=> APPINT-32851 Fix cSplitter with JSonPath is not working as expected

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
=> APPINT-32851 Fix enum class resolve

main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/pom.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-46016
https://jira.talendforge.org/browse/TDI-46016
=> fix(TDI-46016): FTPS issue with JAVA Open JDK - 1.8.0_282-b08

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
https://jira.talendforge.org/browse/TDI-46109
=> fix(TDI-46109): update XStream to 1.4.17

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
Co-authored-by: jillyan <yan955599@gmail.com>
APPINT-32940
compare mavenUri to confirm if is selected by user in de
=> Fix/jill/APPINT-32940 (master) (#6286)

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
https://jira.talendforge.org/browse/TDI-46109
Backport of https://github.com/Talend/tdi-studio-se/pull/6283 into "master" branch
=> fix(TDI-46109): BP_741: update XStream to 1.4.17 (#6283)

main/plugins/org.talend.designer.components.localprovider/components/tHiveClose/tHiveClose_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tHiveConnection/tHiveConnection_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tHiveIn/tHiveIn_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_main.javajet
https://jira.talendforge.org/browse/TDI-44917
=> fix(TDI-44917):Fix Compile Error

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
=> APPINT-33200 update pom_job_template.xml

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
=> APPINT-33200 update the pom_job_template.xml

main/plugins/org.talend.designer.components.localprovider/components/templates/googleStorageConnection.javajet
https://jira.talendforge.org/browse/TDI-46248
=> fix(TDI-46248): fix compile error when dieOnError is checked

main/plugins/org.talend.designer.components.localprovider/components/templates/googleStorageConnection.javajet
https://jira.talendforge.org/browse/TDI-46248
It's port from maintenance/7.3 to master branch
https://github.com/Talend/tdi-studio-se/pull/6308
=> fix(TDI-46248): fix compile error when dieOnError is checked (#6308)

main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tCloudStart/tCloudStart_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tIngresBulkExec/tIngresBulkExec_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tParAccelBulkExec/tParAccelBulkExec_begin.javajet
https://jira.talendforge.org/browse/TDI-44917
=> fix(TDI-44917):error message compile error

main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_end.javajet
https://jira.talendforge.org/browse/TDI-46218
https://jira.talendforge.org/browse/TDI-46218
=> fix(TDI-46218): tRedshiftOutput data loss when insert size matches the input size

main/features/org.talend.designer.business.feature/feature.xml, main/features/org.talend.gmf.feature/.project, main/features/org.talend.gmf.feature/build.properties, main/features/org.talend.gmf.feature/feature.xml, main/features/org.talend.gmf.feature/pom.xml, pom.xml
=> feat(TUP-31484) fix issue found with junit execution

main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
=> fix(TDI-46128): Remove duplicated declaration for variables

main/plugins/org.talend.designer.components.libs/libs_src/adal4j/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
* bump commons-lang3 to 3.10 in studio-se libs to align between all
components
=> chore(TDI-46067): Bump commons-lang3

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/ConnectionCreateAction.java
https://jira.talendforge.org/browse/TUP-31608
=> fix(TUP-31608):Output link from one tELTMSSqlMap to another tELTMSSqlMap is not saved after we remove once.

main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSetProxy/tSetProxy_java.xml, main/plugins/org.talend.designer.components.localprovider/pom.xml, main/plugins/org.talend.libraries.excel/pom.xml
* chore(TDI-46067): Bump commons-lang3
* bump commons-lang3 to 3.10 in studio-se to align between all
components
* chore(TDI-46067): Bump commons-lang3
* clean up unused UrlPath
* chore(TDI-46067): Bump commons-lang3
* updated talend-mscrm lib version after rebase
=> chore(TDI-46067): Bump commons-lang3 (#6227)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ComboController.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/FileController.java
https://jira.talendforge.org/browse/TUP-31218
=> fix(TUP-31218):Medata for salesforce:UI show issue when enable Mutual authenticaiton

main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-46016
https://jira.talendforge.org/browse/TDI-46016
=> fix(TDI-46016): fix the groupid

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
=> fix(APPINT-33088) bundle resources cleaning is skipped in CI mode

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
=> feat(TBD-10185):Support Datasets API in tMap - Spark Batch - Inner|Left Join / Match model: Unique match

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/FixProjectResourceLink.java
org.talend.repository.items.importexport.handlers.cache.RepositoryObjectCache.initialize
=> fix(TUP-31904)java.lang.NullPointerException at (#6359)

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
=> fix(TUP-31997): Commandline fails start studio with error 'Could not load SWT library' on Ubuntu 18 LTS without UI

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
=> fix(TUP-32024): fix module gorup not retrieved in TBD

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
https://jira.talendforge.org/browse/TUP-32024
=> fix(TUP-32024): Module groups are not loaded anymore on Talend 7.4 build

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/ComponentIconLoading.java, main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/resources/ComponentIconLoading.java
=> fix(TUP-31997): Commandline fails start studio with error 'Could not load SWT library' on Ubuntu 18 LTS without UI 

main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_begin.javajet
https://jira.talendforge.org/browse/TDI-46329
https://jira.talendforge.org/browse/TDI-46329
=> fix(TDI-46329): tS3List NullPointerException in R2021-05

main/plugins/org.talend.repository/src/main/java/messages.properties, main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/GeneralProjectSettingPage.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/GitProviderUtil.java
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
Conflicts:
main/plugins/org.talend.repository/src/main/java/messages.properties
**What kind of change does this …
=> feat(TUP-23337):Option to disable Job's screenshot creation. (#6317)

main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForOutput.javajet, main/plugins/org.talend.designer.components.localprovider/components/templates/createTableFromDynamicInBulkExec.javajet
https://jira.talendforge.org/browse/TDI-46251
https://jira.talendforge.org/browse/TDI-46251
=> fix(TDI-46251): [7.3.1] MsSQL row named "column" results in code generation error on dynamic table create

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdateDaikonCryptoUtilsMigrationTask.java
https://jira.talendforge.org/browse/TUP-31163
upgrade daikon to 0.31.12
=> chore(TUP-31163): upgrade daikon to 0.31.12

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/NodeParamsHelper.java
=> Chore(APPINT-33291) add getIntParam method in NodeParamsHelper

main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java
from repository
https://jira.talendforge.org/browse/TUP-27695
=> fix(TUP-37695)Studio tMap can't update schema timely when set schema

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
https://jira.talendforge.org/browse/TUP-31871
=> fix(TUP-31871) update the driver with user selected but not always the default driver.

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/DataSourceConfig.java
[APPINT-33364] org.talend.utils.json.JSONObject$Null cannot be cast to java.lang.String - Talend Open Integration Solution
Check  if is JSONOjbect.NULL before convert to String.
=> check if JSONObject.NULL before convert

main/plugins/org.talend.expressionbuilder/src/main/java/messages.properties, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/ui/BatchCategoryComposite.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/ui/BatchExpressionBuilderDialog.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/ui/BatchExpressionComposite.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/ui/CategoryComposite.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/ui/ExpressionBuilderDialog.java, main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/ui/ExpressionComposite.java
https://jira.talendforge.org/browse/TUP-31736
List out all of functions in custom routine jars
=> fix(TUP-31736): add warning message (#6378)

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_main.javajet
https://jira.talendforge.org/browse/TDI-46321
https://jira.talendforge.org/browse/TDI-46321
=> fix(TDI-46321): tFileOutputExcel outputs 1 less number in NB_LINE global varaible

main/plugins/org.talend.designer.components.libs/libs_src/azure-utils/pom.xml
https://jira.talendforge.org/browse/TDI-46266
=> fix(TDI-46266):CVE Oauth2

test/plugins/org.talend.repository.test/src/org/talend/repository/demo/imports/DemosImportTest.java, test/plugins/org.talend.repository.test/src/org/talend/repository/demo/imports/MdmEeDemoImportTest.java
https://jira.talendforge.org/browse/TUP-31482
=> fix(TUP-31482) fix unit test failure.

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/odata/QueryOptionConfig.java
https://jira.talendforge.org/browse/TDI-46392
tck/dynamics work well with talend-mscrm:3.8-20210707
=> fix(TDI-46392): mscrm expand list not null

main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
* feat(TDI-46167):improve contaionsSpaces for column.
* feat(TDI-46167):reverse the changes to JDBC and ODBC.
* feat(TDI-46167):keep the minimal changes.
https://jira.talendforge.org/browse/TDI-46167
=> Vyu/tdi 46167 modify containsspace for column (#6392)

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java
https://jira.talendforge.org/browse/TUP-31869
=> fix(TUP-31869) show table header/columns in "Advanced settings" tab.

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java
https://jira.talendforge.org/browse/TUP-31869
=> fix(TUP-31869) Studio, TCK components: Table element issues in "Advanced settings" tab..

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet
https://jira.talendforge.org/browse/TDI-45907
=> fix(TDI-45907): single insert Bigdecimal

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
https://jira.talendforge.org/browse/TDI-46398
Use of talend-mscrm:3.8-20210707 lib
=> feat(TDI-46398): bump tMSCrmInOut to talend-mscrm:3.8-20210707

main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_messages.properties
for jira: https://jira.talendforge.org/browse/TDI-46081
=> fix(TDI-46081):Oracle BLOB data not ingesting in table when using Dynamic schema

main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-46393
https://jira.talendforge.org/browse/TDI-46393
=> fix(TDI-46393): runtime log log the password field for tcompv0 as we don't filter HIDDEN_TEXT type field

main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_messages.properties
for jira: https://jira.talendforge.org/browse/TDI-46081
backport master
=> fix(TDI-46081):Oracle BLOB data not ingesting in table when using Dynamic schema (#6421)

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UncheckBson2JsonTask.java
https://jira.talendforge.org/browse/TDI-46340
=> fix(TDI-46340):tMongoDB convert bson to string migration

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
https://jira.talendforge.org/browse/TDI-46395
**Related PR**
- https://github.com/Talend/studio-full-master/pull/834
- https://github.com/Talend/tcommon-studio-se/pull/4423
- https://github.com/Talend/tcommon-studio-ee/pull/2029
- https://github.com/Talend/tdi-studio-se/pull/6422
=> chore(studio731): bump component-runtime to 1.34.1

main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
https://jira.talendforge.org/browse/TDI-46393
https://jira.talendforge.org/browse/TDI-46393
=> fix(TDI-46393): runtime log log the password field for tcompv0 as we don't filter HIDDEN_TEXT type field (#6410)

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet
=> fix(TDI-46165): backport to 7.2

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet
=> fix(TDI-46165): bigqueryinput deletes token file

main/plugins/org.talend.designer.components.localprovider/plugin.xml
=> fix(TBD-12218): zookeeper cleanup

main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
https://jira.talendforge.org/browse/TDI-46396
https://jira.talendforge.org/browse/TDI-46396
=> fix(TDI-46396): align net.minidev:accessors-smart and org.ow2.asm:asm:jar for studio 

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
https://jira.talendforge.org/browse/TUP-31858
Can load drivers for implicit context
=> fix(TUP-31858): set items value

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPClose/tFTPClose_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_end.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_end.javajet
* A bit reduce code duplication
=> fix(TDI-46355): Add logout for ftp and ftps before disconnect

main/plugins/org.talend.designer.components.libs/build.properties, main/plugins/org.talend.designer.tutorials/build.properties, main/plugins/org.talend.libraries.excel/build.properties, main/plugins/org.talend.presentation.onboarding.resource/build.properties, main/plugins/org.talend.sdk.component.studio-integration/build.properties
build failed, files not existing in build.properties
edit build.properties, remove un-existing files
=> feat(TUP-32149): fix buid

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
=> fix(APPINT-32880) Missing WSDL is added (CI usage)

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/mvn/Mvn.java
https://jira.talendforge.org/browse/TCOMP-1983
=> feat(TCOMP-1983): fix module inclusion in dependencies.txt when build is java9+

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
=> chore(TDI-46132): Update adal4j in tMicrosoftCrm

main/plugins/org.talend.repository/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
log4j1
https://jira.talendforge.org/browse/TUP-31794
=> fix(TUP-31794)jar slf4j-log4j12-1.7.25.jar pop up when build job with

main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
* workitem(TUP-28063): Improve studio bundles reloading logic
https://jira.talendforge.org/browse/TUP-28063
* workitem(TUP-28063): Improve studio bundles reloading logic
https://jira.talendforge.org/browse/TUP-28063
* workitem(TUP-28063): Improve studio bundles reloading logic
https://jira.talendforge.org/browse/TUP-28063
Conflicts:
main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java …
=> Cmeng/patch/7.3/tup 28063 improve start (#5092)

main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jDBConnUtil.javajet
=> fix(TDI-47951): Don't set null passw for sso auth

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/close/close_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/connection/connection_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet, main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_begin.javajet
https://jira.talendforge.org/browse/TDI-47694
https://jira.talendforge.org/browse/TDI-47694
=> fix(TDI-47694): [JDBC TCK]: Inject runtime context for tck connector runtime

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGeneratorService.java
fix(TUP-31721):Not clear studio index cache in normal case.
https://jira.talendforge.org/browse/TUP-31721
=> fix(TUP-31721):Not clear studio index cache in normal case.

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
https://jira.talendforge.org/browse/TUP-36653
Correct connection id for generic connection.
=> fix(TUP-36653):Schema Update Detection popping up everytime upon opening the job.

main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
https://jira.talendforge.org/browse/TDI-48675
=> feat(TDI-48675):JDBC ELT components can not handle Japanese table,schama,alias name for insert/update/delete

main/plugins/org.talend.sdk.component.studio-integration/pom.xml, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/PatternValidator.java
This reverts commit babf58784b06cd7203a2a18c9597e70d70e5fd32.
=> Revert "feat(TDI-48644): bump component-runtime to 1.50 (#8132)"

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
https://jira.talendforge.org/browse/TUP-36122
=> feat(TUP-36122):hide tNetSuiteV2019Connection/Input/Output.

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/UserComponentsTokenCollector.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/CustomComponentSettingPage.java
https://jira.talendforge.org/browse/TUP-29016
=> fix(TUP-29016) hide tTaCoKitGuessSchema in shared component and exclude from user data token collection.

main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/src/main/java/org/talend/fileprocess/delimited/RowParser.java, main/plugins/org.talend.designer.components.localprovider/components/tApacheLogInput/tApacheLogInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tExtractPositionalFields/tExtractPositionalFields_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputFullRow/tFileInputFullRow_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml.tmp, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputRegex/tFileInputRegex_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFixedFlowInput/tFixedFlowInput_java.xml, main/plugins/org.talend.libraries.custom/.classpath, main/plugins/org.talend.libraries.custom/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.custom/pom.xml
* fix the behavior when it reaches end of file
https://jira.talendforge.org/browse/TDI-49284
=> fix(TDI-49284): talend file enhanced

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
* in tCreateTable for java 9+ libraries
https://jira.talendforge.org/browse/TDI-49336
=> fix(TDI-49336): required if for hsqldb

main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet, main/plugins/org.talend.designer.components.localprovider/components/tELTPostgresqlOutput/tELTPostgresqlOutput_main.javajet, main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- In case of useUpdateStatement Update query will be generated inside GenerationManager that is used in tELTMap_main.javajet
- add some comments
- populate fix on tELTPostgres, tELTMSSql
=> fix(TDI-49267): Update sql fail for tELTOutput when have two ELTMap and two WHERE clause

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
* for date cell use pattern from dynamic column
=> fix(TDI-32442): FileInputExcel pattern for dynamic

main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet, main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml, main/plugins/org.talend.libraries.excel/.classpath, main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-47390
=> feat(TDI-47390): tFileInputExcel support 1904 time

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
=> APPINT-35307 correct build type

main/plugins/org.talend.libraries.css/build.properties, main/plugins/org.talend.libraries.css/plugin.xml, main/plugins/org.talend.libraries.edifact/plugin.xml, main/plugins/org.talend.libraries.hadoop.mapr.5.0.0/plugin.xml, main/plugins/org.talend.libraries.salesforce/plugin.xml, main/plugins/org.talend.libraries.sqlbuilder/plugin.xml, main/plugins/org.talend.repository/plugin.xml
=> chore(TUP-37430) cleanup default groupid org.talend.libraries

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSDelimited/tFileOutputMSDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tInformixOutputBulk/tInformixOutputBulk_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tNormalize/tNormalize_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tPivotToColumnsDelimited/tPivotToColumnsDelimited_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSocketInput/tSocketInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSocketOutput/tSocketOutput_java.xml
master:
https://github.com/Talend/tcommon-studio-se/pull/5927
8.0:
https://github.com/Talend/tcommon-studio-se/pull/5926
master:
https://github.com/Talend/tdi-studio-se/pull/8389
8.0:
https://github.com/Talend/tdi-studio-se/pull/8390
=> fix(TDI-31777): bump library talendcsv

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet, main/plugins/org.talend.designer.codegen/jet_stub/iterate_subprocess_header.javajet, main/plugins/org.talend.designer.codegen/jet_stub/subprocess_header.javajet
=> fix(TDI-49434): copy MDC to subprocess

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateContextParameterCommand.java
https://jira.talendforge.org/browse/TUP-38173
=> fix(TUP-38173) upload context link when context changed

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
https://jira.talendforge.org/browse/TDI-49483
https://jira.talendforge.org/browse/TDI-49483
=> fix(TDI-49483): Denial Of Service (DoS) in Talend/connectors-se (master)-FileUpload

main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinBulkExec/tSalesforceEinsteinBulkExec_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinOutputBulkExec/tSalesforceEinsteinOutputBulkExec_java.xml
https://jira.talendforge.org/browse/TDI-49791
=> feat(TDI-49791):upgrade salesfroce driver and support latest endpoint.

main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/APIParam.java
tRestRequest query parameters get wrong names when importing an API
=> tdi-studio-se Jill/m80/appint-35629

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/BigDataJobUtil.java
=> feat(TBD-15036): Beta - Universal Spark 3.1 for HDInsight 5.0

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java, main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/IncomingSchemaEnforcerTest.java, main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java, main/plugins/org.talend.libraries.custom/plugin.xml, main/plugins/org.talend.libraries.custom/pom.xml
* revert the changes of "fix(TDI-49305): dynamic schema length (#8651)"
https://jira.talendforge.org/browse/TDI-49856
=> fix(TDI-49856): snowflake create table fail

main/plugins/org.talend.designer.core/plugin.xml, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/migration/AddDistributionForDIItemMigrationTask.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/migration/AddDistributionForDIItemMigrationTaskTest.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/process/ProcessTest.java
Studio - missing distribution entry in .item
=> fix(TUP-38590): CI/CD Pipeline generating different code compared to

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/nodes/NodeTest.java
https://jira.talendforge.org/browse/TUP-38296
=> fix(TUP-38296) Input connections order changes keeps in order

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
https://jira.talendforge.org/browse/TUP-41057
=> fix(TUP-41057) refactor

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/OutputConnectorCreator.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/ProcessorConnectorCreator.java
https://jira.talendforge.org/browse/TUP-41047
=> fix(TUP-41047):looup on the Reject line working in the non-flow way.

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/OutputConnectorCreator.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/ProcessorConnectorCreator.java
https://jira.talendforge.org/browse/TUP-41047
=> fix(TUP-41047):looup on the Reject line working in the non-flow way

main/plugins/org.talend.designer.components.localprovider/plugin.xml
https://jira.talendforge.org/browse/TDI-50450
=> fix(TDI-50450):cve upgrade snappy-java to 1.1.10.5

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java
https://jira.talendforge.org/browse/TUP-40985
=> fix(TUP-40985):The table column in tFixflowInput is editable but can't save the changes.

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/JetSkeletonManager.java
https://jira.talendforge.org/browse/TUP-40457
just do what the method means
=> chore(TUP-40457) exception log in CommandLine log file

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
https://jira.talendforge.org/browse/TDI-50634
https://jira.talendforge.org/browse/TDI-50634
=> fix(TDI-50634): check tck null config values

main/features/org.talend.designer.feature/feature.xml
https://jira.talendforge.org/browse/TUP-40272
Remove m2e ui
=> feat(TUP-40272): Try to find way to avoid m2e.core.ui issue

main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
https://jira.talendforge.org/browse/TDI-50271
https://jira.talendforge.org/browse/TDI-50271
=> fix(TDI-50271): Denial Of Service (DoS) Memory And CPU Consumption in Talend/connectors-lib-se (main)

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java, main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SuggestableEnumParameter.java
https://jira.talendforge.org/browse/TCOMP-2167
=> feat(TCOMP-2167): tck enum suggestible

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java, test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/oracle/OracleGenerationManagerTest.java
spaces present
https://jira.talendforge.org/browse/TUP-41316
=> fix(TUP-41316):tELTOracleMap generates incorrect column names when

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java, test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/process/ProcessTest.java
execution to fail
https://jira.talendforge.org/browse/TUP-41180
=> fix(TUP-41180):the generated code is different which caused the job

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/ContextParameterWizard.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/NewProcessWizard.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/SaveAsProcessWizard.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/SaveAsRoutineWizard.java, main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/SaveAsSQLPatternWizard.java, main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/wizards/GenerateDocAsHTMLWizard.java, main/plugins/org.talend.repository.bigquery/src/org/talend/repository/bigquery/ui/wizards/BigQueryConnectionWizard.java, main/plugins/org.talend.repository.bigquery/src/org/talend/repository/bigquery/ui/wizards/bigquerytable/BigQueryTableWizard.java, main/plugins/org.talend.repository.ftp/plugin.xml, main/plugins/org.talend.repository.ftp/src/org/talend/repository/ftp/ui/wizards/FTPWizard.java, main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizard.java, main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONWizard.java, main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/ui/wizards/NewRouteResourceWizard.java, main/plugins/org.talend.repository.view.di/plugin.xml, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importproject/ImportDemoProjectItemsWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importproject/ImportDemoProjectWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/ConfigExternalLibWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/ImportProjectAsWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/NewProjectWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendImportExportWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendZipFileExportWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendZipFileExportWizard2.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/routines/NewRoutineWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/routinesjar/NewRoutinesJarWizard.java, main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/sqlpattern/NewSqlpatternWizard.java
=> chore(TUP-41038)Remove repository wizard icon

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMomMessageIdList/tMomMessageIdList_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
https://jira.talendforge.org/browse/TDI-50768
=> fix(TDI-50768):clean org.talend.libraries

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetGlobalTimestampOptionForPreviousVersions.java
=> fix(TBD-16015): remove input components from date pattern migration task

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
https://github.com/Talend/tdi-studio-se/pull/9507
=> fix(TUP-41606) Compile error when using tJDBCInput with comment has line break

main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_begin.javajet
=> fix(TDI-50610): fix tAmazonOracleOutput NPE additional columns

main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_begin.javajet
=> Mhryb/tdi 50610 fix t amazon oracle output additional columns 8.0

main/plugins/org.talend.designer.runprocess/resources/templates/Job_run_template.bat
https://jira.talendforge.org/browse/TDI-50677
=> fix(TDI-50677): change bat run template

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
=> fix(TDI-50769): jets3t GAV cleaning

main/plugins/org.talend.designer.components.localprovider/components/tRSSInput/tRSSInput_java.xml
=> fix(TDI-50737): feed4j change GAV

main/plugins/org.talend.designer.components.localprovider/components/tJMSInput/tJMSInput_java.xml, main/plugins/org.talend.designer.components.localprovider/components/tJMSOutput/tJMSOutput_java.xml
https://jira.talendforge.org/browse/TDI-50771
=> fix(TDI-50771): tJMS clean org.talend.libraries

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/dialog/ProjectSettingsPreferenceDialog.java
restart
https://jira.talendforge.org/browse/TUP-41080
=> fix(TUP-41080):Active/Deactive features will cause commit window after
