main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java

convert separator from "\" to "/" make it is work on the windows

fixed bug TDQ-9942 tdqReportRun component exist compile error on the 6.0

---

main/plugins/org.talend.designer.components.localprovider/plugin.xml

Impala components throw ClassNotFoundException when CDH 5.4 is the selected distribution. This commit fixes that issue.

[TBD-1931] Add hive-exec dependency into Impala components for CDH 5.4

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java

This property was mandatory in order to display some fields inside the tPigLoad. But it was restricted to two parameter. I need it in twenty parameters, so I need a softer rule.
The line "tPigLoad".equals(node.getComponent().getName(), will assure that it will not impact any other component.

[TBD-2458] Allow to use the "INCOMING_LINK_TYPE" property on every variable inside the tPigLoad

---

main/plugins/org.talend.designer.components.localprovider/plugin.xml

This pull request is basically a backport on 5.6 of what we already did to fix TBD-1931.
Don't worry about the great number of addition/deletions on plugin.xml, my editor just deleted useless trailing spaces or tabulations at the end of the lines when possible.
The real change is just the addition of the hive-exec dependency for Impala on CDH 5.4.

[TBD-2623] Backport of TBD-1931 on maintenance/5.6

---

main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_main.javajet

(We use to save a string with the pointer to the object,
now we save the byte as a String.)

[TBD-3244] Correctly output bytes.

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java

Daikon 0.8.0 changed the interface for widget to use isHidden instead of isVisible.

Change isVisible to !isHidden for the usual reasons.

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet

Changed connections fetching for Output components to input connections - earlier we were fetching output connectors for Output components, while we needed to fetch input connectors, as the connection is input for output component(data flows into component, not out of it).
Comments were added for discussion and better understanding of my thoughts. They will be removed if everything in my logic and the code is correct.

TUP-4531: Fixed connections fetching for Output components.

---

main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet

without 'die on error' on the component
https://jira.talendforge.org/browse/TDI-35892

TDI-35892 : globalMap.get("tMysqlOutput_1_ERROR_MESSAGE") return null

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java

switch property type between built-in and repository.

TDI-36044: 'Enable parallel execution' shouldn't been enabled when

---

main/plugins/org.talend.designer.components.localprovider/plugin.xml

Cherry-pick of the commit included in pull-request #532

[TBD-3774] Rename HDP 2.3 assembly to fix path length on Windows

---

main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_begin.javajet

'Newer email first' selected and 'Number of emails to retrieve' equals
the total mail number.
https://jira.talendforge.org/browse/TDI-36790

bugfix/6.2.2/TDI-36790 : tPOP rise ArrayIndexOutOfBoundsException when

---

main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/actions/AbstractPublishJobAction.java

TDI-27409: Unable to export a job via TIS Studio with statistics enable--for fixing publishJob from both Studio and CommandLine

TDI-27409: Unable to export a job via TIS Studio with statistics enable

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/ActiveProcessTracker.java

now show unhandle error when switch pages

TUP-6195:Should better restore the jobsetting view after close a job,

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/PropertyTypeController.java

Just disable the save metadata to HDFS button since the component only take Row Seperator and Field Seperator from HDFS connection.

TUP-15922: BD batch job:there is error when click "Save the property to Metadata" of tFileOutputDelimited

---

main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet

* TDI-35416 : replace the last system.err.print with log4j witch I
forgot.
Conflicts:
main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet

TDI-37774 : backport to 5.6. Add getNextException to show more error message (#764)

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet

When a job is undeployed in Runtime, corresponding thread receives interruption request from Karaf, and job controller treats the request as an indicator that the job is undeployed,  otherwise it tries to restart the job (probably as a sort of failure recovery).
When job multi thread execution is turned on, corresponding interruption request is sent to one of the subthreads, but not to the thread that is monitored by job controller, which leads to infnite attempts to restart the job and unlimited growth of logs.
Proposed fix sends interruption request to the thread, monitored by job controller in case if one of the subthreads receives interruption request.

[TESB-18057] Fix

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet

To be merged when the studio is using components 0.17.0-SNAPSHOT
(It looks like the non-javajet code has already been updated for the version bump: https://github.com/Talend/tdi-studio-se/blob/master/main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java)

TCOMP-275 Specify the DI execution engine for component runtimes.

---

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet

https://jira.talendforge.org/browse/TDI-38131

TDI-38131:error message for tRunjob is not complete in tLogCatcher's output

---

main/plugins/org.talend.designer.runprocess/schema/runprocess_manager.exsd
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/IESBRunContainerService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessPlugin.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/TargetExecComposite.java

Hi,
This is the studio-se part to support the ESB runtime server display in target exec tab. PLease consider the merget with another part together, https://github.com/Talend/tdi-studio-ee/pull/316
Regards,
Yi

TESB-18750: Add ESB runtime server in target exec tab

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java

This is for https://jira.talendforge.org/browse/TDI-38056.
The modification based on what we have done for 6.3 in https://jira.talendforge.org/browse/TCOMP-229
1. Any component can have outgoing iterate connector
2. Only Standalone and Input components can have incoming iterate connector
We also provide transformer component interface, but we didn't created this kind of component.
So here we ignore this situation.

fix(TDI-38056):add iterator line for new framework components in 6.2

---

main/plugins/org.talend.designer.components.localprovider/components/tContextDump/tContextDump_begin.javajet

* Remove duplicate code in tContextDump which appears in this PR: https://github.com/Talend/tdi-studio-se/pull/1059 (context.propertyNames() contains paramTypes for all params, one more checking is out of date)

fix(TDI-38369): Refactoring

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
main/plugins/org.talend.designer.codegen/jet_stub/header.javajet

* Runtime instance of a component properties are stored in globalMap in order to be refercned by other components
* Implemented lookup of referenced properties in globalMap

fix(TDI-38559): Fixed initialization of ComponentReferenceProperties

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml

For jira: https://jira.talendforge.org/browse/TDI-38613
Fix issues:
- The entitySet of MicrosoftCRM can't refresh with V2016(odata) when the entity of other API Version is customentityset
- The schema of MicrosoftCRM's column isn't empty with customentityset when when the entity of other API Version isn't customentityset

fix(TDI-38613):the entitySet of MicrosoftCRM can't refresh with V2016(odata)

---

main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_java.xml

For jira: https://jira.talendforge.org/browse/TDI-38334
Make `MAX_NUMBER_MESSAGES` always showed in tSQSInput

fix(TDI-38334):MaxNumberOfMessages for tSQSInput should displayed always

---

main/plugins/org.talend.libraries.jboss/META-INF/MANIFEST.MF

Reverts Talend/tdi-studio-se#1165

Revert "TDQ-13464: fix running the match analysis with "Store on disk" option"

---

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.javajet

This is for : 
https://jira.talendforge.org/browse/TDI-38519
We can't cache the xml element order because it's not a fix order and it's may change in branch
by caching the order we get bas insert position for the element causing IndexOutOfBoundsException.
this will revert the solution implemented here : 
https://jira.talendforge.org/browse/TDI-34433

fix(TDI-38519): revert the order caching in the tFileOutputMSXML

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_begin_odata.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_begin_odata.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_main_odata.javajet

For jiras: 
* tMicrosoftCRMXX can't pass the custom entity correctly with V2016
https://jira.talendforge.org/browse/TDI-38648
* tMicrosoftCRMOutput can't support 'lookup type mapping'
https://jira.talendforge.org/browse/TDI-38639

fix(TDI-38639):tMicrosoftCRMOutput can't support 'lookup type mapping'

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobJavaScriptsWSManager.java

fix(TUP-17123): Build as War will miss wsdd and wsdl folder if studio patch include blank
https://jira.talendforge.org/browse/TUP-17123

fix(TUP-17123): Build as War will miss wsdd and wsdl folder if

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddFailOnErrorOnTFileCopyTDI38441.java

* tFileCopy will have failOn set to true even if copydir was absent before

fix(TDI-38441): Fix migration task

---

main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet

For https://jira.talendforge.org/browse/TDI-38009
When use context expression on port field and active log4j, it would got compile in generated code.

fix(TDI-38009):compile error on tSSH component if use context expression on port field

---

main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.inc.javajet
main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_main.javajet

For https://jira.talendforge.org/browse/TDI-38801
Avoid NPE when append xml file node included all elements defined in the xml tree.

fix(TDI-38801):tAdvancedFileOutputXML throws null pointer if there is more then one component in a flow and one appends the xml file

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java

fix(TUP-17869): routines dependencies cannot be added to newly created job automatically even tick the checkbox
https://jira.talendforge.org/browse/TUP-17869

fix(TUP-17869): routines dependencies cannot be added to newly created job automatically even tick the checkbox

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

When an error is detected in BigQueryBulkExec, a component is not reported.
https://jira.talendforge.org/browse/TBD-5111
Error is reported correctly

bug(TBD-5111/components): tBigQueryBulkExec component does not report error when failures happen - fixed

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_begin_odata.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_main_odata.javajet

For https://jira.talendforge.org/browse/TDI-39045
**Problem**： When tMicrosoftCRMOutput use update with no key column in the schema. The code generate would get compiler error.
**Solution**: Avoid the compiler error. and throw a runtime exception when the schema is not set a key column for update.
And put the check in begin part and before connection for performance.

fix(TDI-39045) improve the error message when when used the tMicrosoftCRMOutput to do the update without key column is set

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

When job contains jar in it's bundle class path that contains log4j classes in it, log4j classes for the job are getting resolved with classes from inside the bundle but not pax-logging classes, which leads to completely broken logging in the bundle. 
This fix adds Require-Bundle manifest entry to job's manifest which enforces resolution of log4j classes from pax-logging.

[TESB-18845] DI service  used JMS and ActiveMQ does not produce log output

---

main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet
main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/DecodeURIInTFileFetch.java

* Incorrect uri would become correct in the job using URI.toASCIIString method
* No changes for ftp and smb protocol due to they should work OK with special characters
* Already correct uri become incorrect-encoded in properties (migration task)

fix(TDI-39089): Add uri encoding in tFileFetch

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_main.javajet

For https://jira.talendforge.org/browse/TDI-39051
Fix the issue:
When **SELECT** SQL before a **INSERT/UPDATE/DELETE**/... SQL in a  stored procedure, if **INSERT/UPDATE/DELETE**/... SQL have some error, the error can't be throw by our tMSSqlSP component.

fix(TDI-39051): tMSSqlSP doesn't always return execution error

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java

fix(TUP-18213): set correct connection bean if logon studio using parameters instead of logon dialog
https://jira.talendforge.org/browse/TUP-18213

fix(TUP-18213): set correct connection bean if logon studio using parameters instead of logon dialog

---

main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jDBConnUtil.javajet

Cann't run job that use joblet use existing connection for tHiveInput 
https://jira.talendforge.org/browse/TBD-4416
Joblet with tHiveInput using existing connection runs succesfully

fix(TBD-4416/components): Cann't run job that use joblet use existing connection for tHiveInput - fixed

---

main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveGet/tGoogleDriveGet_begin.javajet

https://jira.talendforge.org/browse/TDI-39101
When the tGoogleDriveGet try to retreive an undownloadable file (maps, form, site, ...) the outputSchema.content was null or take the value of the previous file.
No row send to the output flow

fix(TDI-39101) : Don't send null for rejected

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
test/plugins/org.talend.designer.core.generic.test/src/main/java/org/talend/designer/core/generic/model/ComponentTest.java
test/plugins/org.talend.designer.core.generic.test/src/main/java/org/talend/designer/core/generic/utils/TestProperties.java

**What is the problem this Pull Request is trying to solve?**
during the code generation of tcomp components, those that use the daikon ReferenceProperties class do not compile because of the field *referenceDefinitionName* not escaped with quotes
**What is the chosen solution to this problem?**
escape the string value for *referenceDefinitionName* of ReferenceProperties
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TUP-18440
**Please check if the Pull Request fulfills these requirements**
**[ ] This Pull Request introduces a breaking change**

fix(TUP-18440):added quotes to ReferenceProperties object during code generation

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BDJobReArchieveCreator.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JarBuilder.java

Add the contexts properties files inside the job jar so these contexts are usable in Yarn cluster mode

Fix(TBD-5655) Can't use contexts in Spark Yarn cluster mode

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/odata/DynamicsCRMClient.java
main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/test/java/org/talend/ms/crm/odata/DynamicsCRMClientTest.java
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_main_odata.javajet

https://jira.talendforge.org/browse/TDI-39571
Navigation links can be set to null. 
The advanced parameter 'Empty Lookup to null' is effective.

fix(TDI-39571): Set navigation link to null

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.libraries.crm/pom.xml

https://jira.talendforge.org/browse/TDI-39642
talend-mscrm-3.1-20170825.jar should become talend-mscrm-3.2-201701107

fix(TDI39642) : MSCRM lib version to 3.2-201701107

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.libraries.crm/pom.xml

https://jira.talendforge.org/browse/TDI-39642
talend-mscrm-3.1-20170825.jar should become talend-mscrm-3.2-20171107 and not talend-mscrm-3.2-2017*0*1107

fix(TDI39642) : MSCRM lib version to 3.2-20171107

---

main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_main.javajet

For https://jira.talendforge.org/browse/TDI-39662
`log4jSb_<%=cid%>` declear is removed TDI-28637
I found that we can avoid the compiler error by using another variable(`sb_<%=cid%>`)

fix(TDI-39662):"log4jSb_tGreenplumGPLoad_1" cannot be resolved

---

main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet

https://jira.talendforge.org/browse/TDI-39447
The cookie is saved if __SAVE_COOKIE__ is checked, even if there is HTTP error.

fix(TDI-39447) : Save cookie even if there is HTTP error.

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet

Related to https://jira.talendforge.org/browse/TCOMP-291
Small chore to avoid repeating dynamic properties where it's not necessary.
Assuming that if a property can reference another one (w/ ComponentReferenceProperties), it's not a real dynamic variable that has to be evaluated on each iteration.

chore(TCOMP-291): remove dynamic tags for referenced properties

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml

https://jira.talendforge.org/browse/TDI-39770
LIKE operator is no more available for ODATA (online/premise crm 2016)

fix(TDI-39770) : LIKE operator disabled for ODATA.

---

main/plugins/org.talend.designer.codegen/jet_stub/subprocess_header.javajet

This code change prevents throwing an Exception only to get the method name even in the case we do not need that because no resuming is running.
We have figured out, these Exceptions have serious impact to the performance of jobs in case of using DI jobs in services.

fix(TDI-39566): prevent throwing an Exception all the time we do not need it.

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet

https://jira.talendforge.org/browse/TDI-39475
When connectorTopology is NONE, a class implementing `ComponentDriverInitialization<ComponentProperties>` is used but the codegen doesn't handle it correctly. It works as if a flow is connected (This leads to a NPE).
When we're using a ComponentDriverInitialization runtime, no need to handle the flow.
The return values are also handled correctly by ComponentDriverInitialization class.
If this PR contains a breaking change, please describe the impact and migration path for existing …

fix(TDI-39475): manage codegen when ConnectorTopology is NONE

---

main/plugins/org.talend.designer.components.libs/libs_src/adal4j/pom.xml

Linked to this PR : https://github.com/Talend/tdi-studio-se/pull/1794
It was missing nexus deployment information for new library ADL4J. Its deployment on Nexus failed.
The deployment succeeded.

feat(TDI-39306) : Add nexus deployment information

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml

Change jar for http version to avoid conflicts. 
Tests done on a job with tBigQueryOutput and another one tBigQueryOutputBulk + tBigQueryOutputExec.

fix(TBD-6075): change jar http version on tbigQuery Component

---

main/plugins/org.talend.designer.components.localprovider/components/tHiveIn/tHiveIn_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/GetDataprocConnection.javajet

Field separator are inconsistent : "\t" in the Studio and "," in GCP.
Google Storage path is not set when an existing connection in not used.
Fields are consistent and set to "\t" (not "," because "\t" is already used for HDi behavior).
Google Storage path is set when no existing connection is used.

fix(TBD-5317): consistent field separator

---

main/plugins/org.talend.designer.components.localprovider/components/tOracleInput/tOracleInput_begin.javajet

The fix handles the situation when Apache Commons DBCP is used to create connection pool for Oracle DB.

[TESB-20919] Issue with Apache DBCP connection pools

---

main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet

https://jira.talendforge.org/browse/TDI-39754
If the redirect url doesn't start by 'http' then it is a relative URL. Then, we get the protocol of the origin url and its port to complete the url.

fix(TDI-39754) : Retrieve protocol and port from origin

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml

For https://jira.talendforge.org/browse/TDI-39827
After upgrade CXF, this thow some wrong dependency of jar.
Provide download those jars.

fix(TDI-39827): some jars can't be imported or download after cxf upgrade

---

main/plugins/org.talend.designer.components.localprovider/components/tLDAPAttributesInput/tLDAPAttributesInput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tLDAPClose/tLDAPClose_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tLDAPConnection/ldapconnect.javajet
main/plugins/org.talend.designer.components.localprovider/components/tLDAPInput/tLDAPInput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tLDAPOutput/tLDAPOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tLDAPRenameEntry/tLDAPRenameEntry_end.javajet

For https://jira.talendforge.org/browse/TDI-39932
- Close TLS connection in LDAP components.
**NOTE:
This PR would merge after support validate the unoffical patch..**

fix(TDI-39932): tLDAPXX components does not close TLS connection

---

.github/PULL_REQUEST_TEMPLATE.md

https://jira.talendforge.org/browse/TDI-39981
When a PR is created, the default template is used as description.

feat(TDI-39981) : Add template for github PR comments

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet

SharedConnectionPool code (which is required for TCOMP component) is generated for the job where there is TaCoKit component, but there is no TCOMP component, because they both have GENERIC type
Code is not generated when there is no TCOMP component in the job

fix(TCOMP-681): remove unrelated code when tacokit component is used

---

main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddSchemaDatePatternUseForImpalaTask.java

tImpalaOutput use hard coded date pattern set to "yyyy-MM-dd" but has been modified to use the schema date pattern in [TBD-6195](https://github.com/Talend/tbd-studio-se/pull/669)
Migration Task for older jobs having a date pattern in the schema different from the hard coded one.

fix(TBD-6388): Add Migration Task for tImpalaOutput

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

At this moment generated Routines package does not have Beans inside. The reason is - Beans and Routines are generated now as separate projects with different "target" location. There are few different ways to resolve issue: 
1. Include Beans as separate library to generated Route;
2. Copy Beans classes to Routines package to make it consistent with previous behaviour (before moving to single maven build);
Current fix contains implementation of approach № 2.

TESB-21298 Missing Beans are added to Routines pkg

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

At this moment we have NPE during invocation of "JavaCamelJobScriptsExportWSAction" from "BundleJavaProcessor".
The reason of NPE is   "repositoryNode" (from BundleJavaProcessor) is null because of Eclipse somehow refreshes TreeView after finishing of Workspace operation only. And imported element can not be retrived from TreeView before Import operation is finished. Current fix is just workaround for such situation. It will be necessary to review this code when propagation of Build Type will be fully implemented (we must avoid using BundleJavaProcessor for imported Routes).

TESB-21304 NPE during importing of Route is fixed

---

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet

https://jira.talendforge.org/browse/TDI-40026
All the stacktrace of a subjob exception where logged.
Only the exception class and its message are logged (as if it was a normal job).

bug(TDI-40026) : Get only exception msg from subjob

---

main/plugins/org.talend.designer.components.localprovider/components/tCloudStart/tCloudStart_begin.javajet

tCloudStart does not start an existing EC2 instance but creates a new one.
https://jira.talendforge.org/browse/TDI-40110
https://jira.talendforge.org/browse/TDI-40112
If the requested instance count is set to 1, we should 
* start this instance if it's suspended.
* do nothing if it's already running.
* create a new one if it's terminated (deleted). The newly created instance will use the `instanceName` as base name.
Otherwise, we'll create _n_ instances using the `instanceName` as base name.
After merge, need to be backported to  `maintenance/6.4` and `maintenance/6.5`.
**Does this …

fix(TDI-40112): tCloudStart doesn't start an existing EC2 instance

---

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/NodesSubTree.java

https://jira.talendforge.org/browse/TDI-40106
Now returning a copy of the `List<INode>` instead of the original reference.
This avoids the exception due to the `modCount` changes during iterations on the reference.
Need to be backported to 6.4 and 6.5.

fix(TDI-40106): avoid ConcurrentModificationException

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java

At this moment we have NPE during importing of Route (or during saving of new Route). It happends due to missing compillation logs (it is expected because of Route was not compiled previously). 
Verification for "null" condition is added.

TESB-21314 NPE during Routes import is corrected

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/JobSettingsView.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java

At this moment "Deployment" tab is not shown for new or imported Routes (it is shown in case of Route / Job is opened in Editor only). 
Current fix makes "Deployment" tab available. But content will be shown in "Read Only" mode (because of it will not possible to save changes in any case).

TESB-20833 Missing "Deployment" tab is added

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java

Remote project creation without user & password -> HTTP 500 error
Check url button would only be active if user are filled

fix(TUP-19131):Remote project creation without user & password -> HTTP 500 error

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java

Maven need change to online manually.
Change Maven to online mode when build to OSGi type

TESB-20833: Change maven to online when build OSGi type

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewMarkLogicMigrationTask.java

* Remain cmd mode of marklogic bulkload in jobs migrated from javajet
Extend marklogic migration task to set 'use external mlcp' to true after migration
Migration task for
https://github.com/Talend/components/pull/1164

fix(TDI-40071): Expand migration task

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobJavaScriptsManager.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java

Old type of export was partially disabled since DI part doesn't use it.
However MDM is still using it for the deploy of jobs

fix(TUP-19688) fix the old export job still used for mdm

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

When import ESB demo project, it will meet a endless loop exception and failed.
As it is related with  TUP-19688 Job deployed to MDM not work, so I just move the implements into ESB manager to avoide the generate code on ESB side.

TESB-21489: Avoid to generate code in JobJavaScriptOSGIForESBManager

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/GenerateJobPomMigrationTask.java

The generation of pom was done 2 times during the process (migration
task + task at the end of import.
Disable the generation of pom here to have it only at the end of the
migration only. (means enable it only during the logon project)

fix(TUP-19687) fix import issue

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet

tFTPFileList in FTP and FTPS modes doesn't work with windows path separators
tFTPFileList works the same as all another FTP components

fix(TDI-40197): Replace wrong fileseparators in tftpfileList

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet

For JIRA: https://jira.talendforge.org/browse/TDI-40217
When Avro convert to DI for dynamic, the bigdecimal type didn't have correct mapping.
It map to String type.
Add correct mapping for bigdecimal type

fix(TDI-40217) tMSSqlOutput component fails while writing exponential notation data using Dynamic Schema

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java

**What is the current behavior?** 
When attemp to check for build errors is made on the "last main job", when there is no last main job available, an NPE is thrown.
Added null pointer check to avoid the NPE

[TESB-21378] Issues publishing artifacts with Studio commandline

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java

* Use REJECT connector name for reject schemas
Reject schema is not set for reject connectors, due to difference of connector name for reject schema and and existing REJECT connector name.
Reject schema connector name is always set to REJECT
Schema was not set to configuration for processor components.

fix: fix reject schema name

---

main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml

https://jira.talendforge.org/browse/TMDM-11916
- Using xmlschema-core of version 2.2.2
- Using neethi of version 3.1.0
- Using CXF of version 3.2.1
- Upgrade xmlschema-core from 2.2.2 to 2.2.3
- Upgrade neethi from 3.1.0 to 3.1.1
- Upgrade CXF from 3.2.1 to 3.2.2

TMDM-11916 Can't download required jars(xmlschema-core-2.2.2.jar, neethi-3.1.0.jar) when run mdm demo jobs

---

main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/sap_hana.javajet
main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/tJDBCSCDELT_begin.javajet

Adding support for SAP Hana.
Amended the begin template to conditionally include SAP Hana specific template if the appropriate mapping is selected.
Added a SAP HANA specific javajet template,
When HANA mapping is selected the component generates SQL that is incompatible with SAP HANA.
See - TDI-40170
Adding support for SAP Hana.
Amended the begin template to conditionally include SAP Hana specific template if the appropriate mapping is selected.
Added a SAP HANA specific javajet template,
When HANA is selected as mapping the correct SQL is generated. 
- [ x] Bugfix
**Does this PR …

fix(TDI-40170): Add HANA support to tJDBCSCDELT

---

main/plugins/org.talend.designer.components.localprovider/pom.xml
main/plugins/org.talend.libraries.crm/pom.xml

https://jira.talendforge.org/browse/TUP-19810
When building with tycho, these warning shows up : 
<snip>[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-clean-plugin is missing. </snip>
no more warning
- [*] No

TUP-19810 : Tycho fix

---

main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_main.javajet

Attribute values are not added to output if value is set for the element.
Do not set type of the element automatically if custom attributes are added

fix(TDI-35080): tWriteJsonField renders strings

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java

Unzip done for nothing in every build, while we need it only in some special cases (classpath.jar)
Execute the unzip only if needed

fix(TUP-19848) improve build performances

---

main/plugins/org.talend.repository/resources/osgi-exclude.properties

At this moment we have ClassCastException in Runtime  because of "camel-talendjob" package is included to generatd OSGi bundle (Runtime has this library also)

TESB-21702 Excluding camel-talendjob from OSGi pkg

---

main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHBulkExec/tSQLDWHBulkExec_begin.javajet

For JIRA: https://jira.talendforge.org/browse/TDI-40321
The query clause, externalTableRejectOptions, is always generated even reject options is not checked
Ungenerated those code when `externalTableRejectOptions` unchecked

fix(TDI-40321): The query clause, externalTableRejectOptions, is always generated even reject options is not checked

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java

MR Required flag is not set for every module for now, only some.
The order doesn't set them especially as first (it might have some esb definition module without MR Required)
Simply apply MR Required flag to other modules with the same name, to ensure to have the correct flag.

fix(TUP-19921) set correctly MR Required flags

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

NPE when publish OSGi type with TSC_BDRT license
Fixed by checking beans exists.

TESB-21726: NPE when publish OSGi type with TSC_BDRT license

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

Job build wizard displays ESB microservice as a possibility to build the
jobs. Build as microservice won't work in TOS for ESB version.
This removes Microservice from build type combo box when product is TOS.
- [ x] Bugfix
- [x ] No

TESB-21825 TOS for ESB should not allow building jobs as microservice

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java

"Sync columns" button pushed for FLOW schema also updates REJECT schema which correct for javaject and TCOMP components, but is not correct for Tacokit components.
"Sync columns" button pushed for FLOW schema doesn't updates REJECT schema for Tacokit components. For javajet and TCOMP components behavior remains the same.
https://jira.talendforge.org/browse/TCOMP-755

fix(TCOMP-755): fix sync columns issue

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java

* Change marker dependency for beam components
Search for apache beam dependencies to find out if it is beam component.
Search for component-runtime-beam dependency, which will be added as a dependency on server side if beam is active on the server.
This will work after https://github.com/Talend/component-runtime/pull/223 is merged and the new(0.0.10) version of component-runtime is used in studio.

feat: additional dependencies for beam components

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java

* Add converting value to string
@ActiveIfs annotation doesn't work for several conditions
ActiveIfs work corectly

fix(TCOMP-783): activeifs doesnt work

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/IESBRunContainerService.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java

Local runtime for Studio job/routes execution should not be used in some
cases: build type has to be checked to define the best execution
processor. As execution processor must change when build type is updated
in deployment tab, processor can not be persisted anymore.
Persisted "processor" class variable was returned in getProcessor method. But "processor" instance was sometimes unappropriate as build type can be changed in deployment tab without closing & reopening process editor.
Now processor is (re)calculated at each getProcessor call.
- [ x] Bugfix
- [x ] No

TESB-21832 Problems with job/route exec. with local runtime in Studio

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java

* Clean controls map
When one enum is shown dependently on another enum's value, there might be an error after disposal of one of enums.
No error appears.

fix(TCOMP-792): ActiveIf for enums

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/build/StandardJobOSGiBundleBuildProvider.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

Kar file run failed in ESB Runtime for the camel-alldeps libraries are confilct
Filter out camel-alldeps in MANIFEST for OSGi type export

TESB-21804: Filter out camel-alldeps in MANIFEST for OSGi type export

---

main/plugins/org.talend.designer.components.localprovider/components/tServiceNowInput/tServiceNowInput_main.javajet

with more than one result, tServicenownput returns bad data for resolved_at and closed_at fields
https://jira.talendforge.org/browse/TDI-40464

fix(TDI-40464): fix column mapping in servicenowInput component.

---

main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/models/FeaturesModel.java

Read access to the bundles included in a feature is required in order to determine which dependency modules are bundles and should therefore not be physically included in the route bundle.
TESB-22036
get accessor added

fix(TESB-22036): Add read access to list of bundles in FeaturesModel.

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewMarketoMigrationTask.java

https://jira.talendforge.org/browse/TDI-40495
avoid NPE when LEAD_SELECTOR does not exist

fix(TDI-40495): avoid NPE when LEAD_SELECTOR does not exist

---

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet

Wrong CREATE TABLE query generated for NUMERIC type in postgesql type
Bug fixed
Should be merged with https://github.com/Talend/tcommon-studio-se/pull/1656

fix(TDI-32027): Fix CreatesqlQuery generation for postgres

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet

Job with tFTPProperties doesn't compile when fileName property is complex (2 or more concatenated strings)
Job with tFTPProperties compiles when fileName property is complex (2 or more concatenated strings)

fix(TDI-40513): Fix compile error for concated strings in FileName

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/ConfigExternalLib/LibraryField.java

The present fix enables selection of the "required" state of bean libraries in the corresponding dialog.
Bean dependencies are always handled as required
Enable setting of required state

fix(TESB-22034): Fix handling of non-required bean deps in routes.

---

main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_main.javajet

https://jira.talendforge.org/browse/TMDM-12258
After WSPutItemWithReport added 3 attributes, the generated webservice stub changed.
There are 3 parameters for the constructor before, now is 6, so we get the compile error.
Use default constructor with no parameters, and set the attributes by setXXX methods.

TMDM-12258 tMDMOutput get compile issue

---

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ws/wsdlutil/ServiceDiscoveryHelper.java
main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ws/wsdlutil/WSDLLocatorImpl.java
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/ServiceDiscoveryHelperTest.java
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/TestService.wsdl
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/TestServiceBinding.wsdl
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/TestServiceJmsBinding.wsdl

TESB-22183 Circular WSDL imports cause endless recursion
Issue is fixed

 fix(TESB-22183): Add support for circular WSDL imports to WSDL loading. 

---

main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ws/wsdlutil/ServiceDiscoveryHelper.java
main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ws/wsdlutil/WSDLLocatorImpl.java
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/ServiceDiscoveryHelperTest.java
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/TestService.wsdl
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/TestServiceBinding.wsdl
test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/TestServiceJmsBinding.wsdl

TESB-22183 Circular WSDL imports cause endless recursion
Issue is fixed

 fix(TESB-22183): Add support for circular WSDL imports to WSDL loading.

---

main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_java.xml

Components use old version of json-lib
Components will use patched version of json-lib to avoid dependency conflict
**SHOULD BE MERGED ONLY AFTER NEXT PRs** 
https://github.com/Talend/tdi-studio-se/pull/2358
https://github.com/Talend/tcommon-studio-se/pull/1693

fix(TDI-40526): Update json-lib dependency

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
main/plugins/org.talend.designer.maven.job/resources/templates/standalone/assembly_job_template.xml
main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java

rules in src/main/resources. they will be in jar/zip when build the
maven job
**What is the current behavior?** ( https://jira.talendforge.org/browse/TDQ-15215 )
- 

fix(TDQ-15215): No need to run 'include-survivorship-rules' sice the

---

main/plugins/org.talend.designer.runtime.visualization.tools/plugin.xml

https://jira.talendforge.org/browse/TUP-20007
'Tools' peference page is now located in the 'Talend' category

fix (TUP-20007) : set a correct category

---

main/plugins/org.talend.designer.components.localprovider/components/tSCPGet/tSCPGet_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tSCPGet/tSCPGet_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSCPGet/tSCPGet_messages.properties

https://jira.talendforge.org/browse/TDI-40674
With new property it is possible to download files from directory with '\' in name

fix(TDI-40674): Add property to avoid windows-separator replacement

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml

deploying ESB as OSGI to nexus used wrong groupId

fix(TESB-22695) : use the correct groupId from project.

---

main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_begin.javajet

* Avoid ArrayIndexOfBoundsException when schema is empty
When schema is empty unclear codegen error appears
Code generates successfully, error at runtime

fix(TDI-32435): VerticaBulkExec codegen error

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/AbstractConnectorCreator.java

com.sun import is not accessible using openJdk and not used in the class.
https://jira.talendforge.org/browse/TESB-22210

fix(TESB-22210) Remove unnecessary com.sun import

---

main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet

This change improves the log4j code.
For the open studio it prevents the creation of useless Byte65335Limit classes.
For the enterprise studio it improves the performance and decrease the memory allocation of jobs.

TDI-39567 improve performance in log4j code

---

main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
main/plugins/org.talend.libraries.xml/pom.xml

https://jira.talendforge.org/browse/TDI-40722
After discuss with Pierre, we will not provide xstream.jar in our product any more.

fix(TDI-40722):remove xstream1.2.2 in bonita component.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/build/StandardJobStandaloneBuildProvider.java

Rest service provider job pom still be generated as standalone type pom file.
Avoid to generate standalone pom for service provider

fix(TESB-22825): Avoid to generate standalone pom for service provider

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java

Current issue is triggered by this comit https://github.com/Talend/tdi-studio-se/commit/d2f57c48f9731fe1a02e4b138624d6d327a0dd30.
if (exportType == null) {
exportType = itemProperty.getAdditionalProperties().get(TalendProcessArgumentConstant.ARG_BUILD_TYPE);
}
**so, previously export type was null for child jobs but now it has value "ROUTE"
this is why incorrect Job pom creator is selected**
**Current fix excludes assigning of exportType for Jobs**

TESB-22594 Error occurred when build a route with ctalendjob to runtime

---

main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet

For https://jira.talendforge.org/browse/TDI-40824
Fix some bug caused by db unify

fix(TDI-40824):tRedshiftOutputBulkExec compile error since generic components name when use 'encrypt'

---

main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHOutput/tSQLDWHOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/tMSSql/_tMSSqlConnection.javajet

https://jira.talendforge.org/browse/TDI-40855
isEnableDatasource was useless filter. It was deleted

fix(TDI-40855): remove duplicated filter for datasource

---

main/plugins/org.talend.designer.components.localprovider/components/tSCPFileList/tSCPFileList_java.xml

Default command separator is ":"
Default command separator is ";"
https://jira.talendforge.org/browse/TDI-32740

fix(TDI-32740): Change default command separator

---

main/plugins/org.talend.designer.components.localprovider/components/tAccessConnection/tAccessConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAccessInput/tAccessInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAccessOutput/tAccessOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tAccessRow/tAccessRow_java.xml

- bouncycastle/bcprov-jdk15on/1.51
- jackcess/2.1.0
- jackcess-encrypt/2.1.0
With incompatibility between bouncycastle & jackcess to decrypt db access file in 4.2 version.
- bouncycastle/bcprov-jdk15on/1.51
- jackcess/2.1.0
- jackcess-encrypt/2.1.0

feat(TDI-40900) : Update libs versions

---

main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet

SOCKS Proxy with auth doesn't work for ftp components
SOCKS Proxy with auth works

fix(TDI-40927): Set default Authenticator for ftp socks proxy

---

main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java

https://jira.talendforge.org/browse/TDI-40875
Currently, the incomingEnforcer only contains the columns defined in the outgoing schema.
So, if a component needs the incoming values there're not passed to writer until they are defined in the outgoing schema. 
Now, we give to the writer all incoming columns even if there're not in the component's schema.
This allows to use incoming values for anything like querying and not polluting the outgoing schema.
If this PR contains a breaking change, please describe the impact and migration path for …

feat(TDI-40875): give to writer all incoming columns

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/ComponentSettingsView.java

Current implementation has an issue. MissingSettingsMultiThreadDynamicComposite() contstructor is called in any case. It creates the whole composite using javajet-specific algorithms. 
Then Tacokit-specific composite is created too. It constructs one more composite.
However, javajet composite already exists and attached to parent composite. Also this composite is shown to user.
Now, only one composite is created.
**Other …

fix(TCOMP-1056): fix refresh problem on advanced component tab

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java

Guess schema button is created only for schema which is not present on layout (basic or advanced). However, it is not created for if schema is present on layout.
Guess schema button is created regardless it is present or not on layout
https://jira.talendforge.org/browse/TCOMP-1078

fix(TCOMP-1078): fix guess schema button visibility

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/migration/TaCoKitMigrationManager.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/TaCoKitConfigurationModel.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TextElementParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/VersionParameter.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/resolver/HealthCheckResolver.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitConfigurationWizard.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitCreateWizard.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitEditWizard.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/page/TaCoKitConfigurationWizardPage.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java

https://jira.talendforge.org/browse/TCOMP-996
I have added the configuration version to the serialized properties.
**What is missing :** 
* path adaptation of the configuration. root configuration need to be passed to migration without the configuration prefix to respect the migration handler expectation. only component migration handler expect the configuration prefix as defined in component constructor.
* ElementParameter value need to be updated after the migration and synchronized with the connection properties which hold the node data

Metadata migration fix and default values and diplayName for test connection

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java

Hides Edit Schema widget from repository dialog
https://jira.talendforge.org/browse/TCOMP-1105

fix(TCOMP-1105): hide Edit Schema widget in repository dialog

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ListPropertyNode.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java

* Add support for OptionsOrder/GridLayout for SomeClass used as List<SomeClass> option in Studio
studio integration plugin ignores OptionsOrder/GridLayout for tables and columns are sorted in alphabetical order
Columns are ordered as set in OptionsOrder/GridLayout
https://jira.talendforge.org/browse/TCOMP-925

fix(TCOMP-925): columns order in tcompv1 tables

---

main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/APIParam.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/EParamKind.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/EParamType.java
main/plugins/org.talend.designer.oas/src/org/talend/designer/oas/external/RestAPIMapping.java

When using an API definition from metadata for tRESTRequest component,
operation parameters (path, query & header parameters) are now
automatically created.

TESB-23238 API definitions parameters import in tRESTRequest

---

main/plugins/org.talend.designer.components.localprovider/components/tContextLoad/tContextLoad_main.javajet

Added a check for tContextLoad is not null prior to use so the HPE
Fortify security scanner won't raise a flag (the flag prevent the job to
be used in a bank environment)

fix(TBD-7334) check tContexLoad is not null prior to use

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java

**What is the current behavior?** 
At this moment we have issue with incorrect manifest generation for child Jobs TESB-23870 which was provoked by https://github.com/Talend/tdi-studio-se/commit/34d92b92c9e45cf32bfb5a7f645fed16713c708f
The problem is - manifest from child Jobs does not have required dependencies because of manifest creator can not find required dependencies due to missing generated classes. So, it is necessary to compile child subjobs before manifest is calculated. Besides, it is not possible to avoid creation of maven nature for child job project (otherwise project with child Job can not be compiled) 
**What is the new behavior?** 
Current change suppose creation of maven nature and compillation of  child Jobs during creation of OSGi Routes with child Jobs (referenced by …

TESB-23870 Camel dependencies are not included to manifest of route's child jobs

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/service/ResourcesDependenciesService.java
main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/ui/wizards/EditRouteResourcePropertiesWizard.java

job first after change the resources item
https://jira.talendforge.org/browse/TUP-20913

fix(TUP-20913)Remote project:job run use old data if not run the child

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java

* fix(TUP-21039): "Apply context to children jobs" does not work for
"grand son" job if Studio not restarted
https://jira.talendforge.org/browse/TUP-21039
* fix(TUP-21039): "Apply context to children jobs" does not work for
"grand son" job if Studio not restarted
https://jira.talendforge.org/browse/TUP-21039

fix(TUP-21039): "Apply context to children jobs" does not work for "grand son" job if Studio not restarted (#2848)

---

main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton

* fix(TDI-41276): Use correct SQLType for null Time
* fix(TDI-41276): Fix codegen error
Backport of https://jira.talendforge.org/browse/TDI-41276 to 7.1 branch

fix(TDI-41276): Use correct SQLType for null Time (#2852)

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet

Wrong NULL-handle behavior for Talend Date and SQL TIME in SingleInsertQuery
Same as for plain insert

fix(TDI-41330): Use sql TIME in setNull for SIQ

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet

Backport of https://github.com/Talend/tdi-studio-se/pull/2927

fix(TDI-41330): Use sql TIME in setNull for SIQ (#2927)

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ListPropertyNode.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java

This fix allows subclasses to provide its own Set of children names in case there is no GridLayout or OptionsOrder
https://jira.talendforge.org/browse/TUP-21122

fix(TUP-21122): fix missing Table rows

---

main/plugins/org.talend.designer.components.localprovider/components/tSVNLogInput/tSVNLogInput_java.xml

No date pattern in default component schema -> warning appeared
Set default date pattern for new tSVNLogInput components added to jobs

fix(TDI-31328): Add default datePattern to SVNLogInput locked schema

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java

Map components and is not separated with string concat from SQL code
- [* ] Bugfix
- [* ] No

bugfix(TUP-21041):ELT Maps generate incorrect SQL when sql contains schema.table.column1 + schema.table.column2

---

main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/HelpClass.javajet

Codegen trying to find Hive username variable which does not exist
Preventing codegen to seek this variable when not needed

fix(TBD-8089): Hive requiring user when not needed

---

main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/src/main/java/org/talend/archive/IntegrityUtil.java
main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
main/plugins/org.talend.libraries.custom/pom.xml

* fix(TDI-41469): tFileUnarchive zip64 format error
* Use apache commons compress in checkArchive lib
* fix(TDI-41469): tFileUnarchive zip64 format error
* Remove unused method

fix(TDI-41469): backport to 7.1

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java

What is the current behavior? (You can also link to an open issue here)
https://jira.talendforge.org/browse/TUP-21356
What is the new behavior?
https://jira.talendforge.org/browse/TUP-21356

fix(TUP-21356):talend-bigdata-launcher-1.2.0-20170410.jar not found when spark job launched from standard job by jobserver.

---

main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/src/main/java/org/talend/archive/IntegrityUtil.java
main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
main/plugins/org.talend.libraries.custom/pom.xml

* fix(TDI-41469): tFileUnarchive zip64 format error
* Use apache commons compress in checkArchive lib
* fix(TDI-41469): tFileUnarchive zip64 format error
* Remove unused method

fix(TDI-41469): backport to 7.0

---

main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java

https://jira.talendforge.org/browse/TUP-9814

fix(TUP-9814):SCD component add a warning message if the source key is empty.

---

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_begin.javajet

https://jira.talendforge.org/browse/TDI-41556
driver name for Redshift driver was changed. It used outdated name.
Also for tPostgreSQLConnection was updated list with Redshift driver names to avoid conflict when both DBs in one job.

fix(TDI-41556): Redshift driver name was changed

---

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet

https://jira.talendforge.org/browse/TDI-41581
tCreateTable for MySQL when use exist connection now define database name rightly.

fix(TDI-41581): change MySQL db name recognition

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTestHelper.java

* bugfix(TUP-21164):Context is not recognized as context variable in ELT
Map components and is not separated with string concat from SQL code
- [* ] Bugfix
- [ *] No

Hwang/tup 21164 (#3004) (#3011)

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet

Just add a <%cid%> to prevent a compile error when more using more than
one tBigQueryInput
- [x ] The new code does not introduce new technical issues (sonar / eslint)
- [x ] Bugfix
- [ x] No

fix(TBD-8102): tBigQueryInput compile error

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

Add a <%cid%> to prevent a compile error when using more than one
tBigQueryOuput

fix(TBD-8299): tBigQueryOutput compile error

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

At this moment xmlMapping is not propagated to Jobs OSGi Bundle.
Unfortunatelly we can not just backport existing bugfix for 6.4 https://github.com/Talend/tdi-studio-se/pull/2360/files because of artifacts propagation in 7.1/7.2 has some differences (it is necessary also to extend corresponding template to make propagation of xmlMappings complete).
xmlMapping become propagated to Jobs OSGi Bundle
See corresponding PR for 6.4 …

TESB-22085:Dynamic schema column type is always String in Runtime

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

At this moment xmlMapping is not propagated to Jobs OSGi Bundle.
Unfortunatelly we can not just backport existing bugfix for 6.4 https://github.com/Talend/tdi-studio-se/pull/2360/files because of artifacts propagation in 7.1/7.2 has some differences (it is necessary also to extend corresponding template to make propagation of xmlMappings complete).
xmlMapping become propagated to Jobs OSGi Bundle
See corresponding PR for 6.4 …

TESB-22085 Dynamic schema column type is always String in Runtime

---

main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/read_by_jsonpath_process.javajet
main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/read_by_xpath_process.javajet

Compile error on tExtractJSONField when byte[] field is extracting
No compile error, same behavior for tExtractJSONField as for tFileInputJSON

fix(TDI-31429): Avoid compile error for byte array

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet

https://jira.talendforge.org/browse/TBD-7153?filter=-1
Short, Long, Double and Character are transferred as String. 
Any date column is saved as a timestamp.
Added mappings for Short, Long, Double and Character.
Changed the way "DATE" datatype is treated. Now, a table in BigQuery is created with datatype according to Studio pattern. If a pattern is missing or it is an empty string, a column will be created as DATE and formatted in a way that is only acceptable by BigQuery.
If this PR contains a breaking change, please describe the impact …

fix(TBD-7153): Fixed missing mappings for BigQuery

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java

Jobs containing tRESTClient or tESBConsumer components cannot be built as Docker Image whereas user can build Job standalone. Last fix introduced a bug not allowing the user to finnish the wizard while all docker parameters are correct.
Error management is improved and wizard can finnish when Docker params are correct.

TESB-25045 Authorize Docker Build for job with tRESTClient

---

main/plugins/org.talend.designer.components.localprovider/components/tSPSSOutput/tSPSSOutput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_begin.javajet

* Use text escape method usage in SPSOutput and SalesforceWaveBulkExec components

fix(TDI-41951): special chars in column comment

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

At this moment we have NPE in Runtime which is provoked by conflict which happends due to multiple version of "javax.annotation" in Runtime:
karaf@trun()> exports |grep javax.annotation
javax.annotation.processing                                           │ 1.0.0          │ 0   │ org.eclipse.osgi
javax.annotation.security                                                │ 1.2.0          │ 0   │ org.eclipse.osgi
javax.annotation.security                                                │ 1.3.0          │ 8   │ javax.annotation-api
javax.annotation.sql                                                        │ 1.2.0          │ 0   │ org.eclipse.osgi
javax.annotation.sql                                                        │ 1.3.0          │ 8   │ javax.annotation-api
javax.annotation …

TESB-24730 Services no longer accessible ( NPE) after route deployment

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaElementParameter.java

no way to get int or any type =! string in the schema at runtime
it works

TUP-22648 ensure colulmns types are not lost

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java

Studio tries to display an error message dialog from inside a Job. This causes an InvalidThreadAccess.
Code now synchronize with UI thread to display the error message and user can get the real error message.

TESB-25472 Avoid InvalidThreadAccess to get the real error

---

test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/ConnectionManagerTest.java

job in studio
https://jira.talendforge.org/browse/TUP-22620
Since my new added test testCheckCircle is the first one to execute, it
used common variable node broke other test balance. Modify to use it own
private variable.

fix(TUP-22620)java.lang.StackOverflowError exception when opening the

---

main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_begin.javajet

(See TESB-24851) in case of Failover mode on tMomConnection component, deploy the job into Runtime OSGi container, and the AMQ 61616 is not available, the Connection has no chance to be closed and keep running to re-connect for ever even the job got undeployed from container.
The fix is putting the connection_tMomConnection_1 earlier into the Map before it is starting, so that it is able to be closed in the destroy() method when uninstalled.
If this PR contains a breaking change, please describe the impact and migration path for existing …

TESB-24851, fix the Connection leak in case of Failover mode and OSGi deployment

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/WidgetTypeMapper.java
main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/ComponentModelTest.java

date/time inputs have no dedicated widget
components can use "time"/"date"/"datetime"/"zoneddatetime" widgets in their declaration.
this PR maps them all to DATE widget - i'll open a ticket to refine them.
IMPORTANT: this PR upgraded the plugin to Talend Component Kit 1.1.10-SNAPSHOT, this is mainly because a change in the model but is not required, feel free to revert that version in the plugin pom or do the upgrade in tcommon se/ee to ensure it works properly
Edit: relative PR to complete this work: https://jira.talendforge.org/browse/TUP-23326
**Does this PR introduce a breaking …

basic date support (coming Talend Component Kit 1.1.10)

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java

does not exist throw when I rename a folder.
- [* ] Bugfix
- [* ] No

bugfix(TUP-21693):Error log like Resource '/AA/poms/jobs/process/test1'

---

main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/JavaRoutineSynchronizer.java

another user will hang on in "User operation is waiting" page after
click refresh.
- [* ] Bugfix
- [* ] No

bugfix(TUP-23400):Collaborative work in SVN: one user delete a job,

---

main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet

* Fix basic auth when server allows different auth mechanisms
When proxy server has several authentication mechanisms and ntlm has the highest priority, tFileFetch component tries using ntlm mechanism, even if the checkbox "Enable NTLM Credentials" is not checked.
If the checkbox "Enable NTLM Credentials" is not checked, tFileFetch would try using BASIC authentication mechanism.

fix(TDI-42536): tFileFetch NTLM PROXY issues

---

main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml

https://jira.talendforge.org/browse/TDI-42436
tAmazonRedshiftManage and tRedshiftUnload was added to Cloud/Amazon/Redshift family folder

fix(TDI-42436): copy Redshift components to cloud folder

---

main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/actions/AbstractPublishJobAction.java

Published data service artifacts are missing context files: when a dataservice job is published for the first time and was never build from Studio before, published artifact is missing the context files.
Context files are included even when job was not built before.

TESB-26086 Adding missing context files to published artifacts

---

main/plugins/org.talend.designer.components.libs/libs_src/soap/src/main/java/org/talend/soap/SOAPUtil.java

param 'action' optional and  should not be empty
it will be added in case when not empty. 
- [ X] No

bugfix(TDI-42581): tSOAP doesn't support SOAPActions for Soap 1.2

---

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_begin.javajet

the output directory may not exist. So files cannot be saved.
output directory is created when it not exists

fix(TDI-42634): create output directory if not exists

---

main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/util/JSONTokener.java
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/util/JSONUtils.java
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/test/java/net/sf/json/TestJSONObject.java
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/test/java/net/sf/json/sample/BeanD.java
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/test/java/net/sf/json/util/TestJSONBuilder.java
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/test/java/net/sf/json/util/TestJSONStringer.java
main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_java.xml

https://jira.talendforge.org/browse/TDI-42689
BigDecimal is used instead of float & double to avoid lose of decimal precision.

fix(TDI-42689) : prefer BigDecimal for float&double

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

osgi-exclude.properties resource fileis included in org.talend.repository bundle and by this cannot be updated. In some rare case, user need to add an exclusion entry.
This dev adds the opportunity to externalise osgi-exclude.properties
resource file from org.talend.repository bundle better than using the
one included in org.talend.repository budle jar file.

TESB-26772 Adds a way to externalise osgi-exclude.properties file

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitorTest.java

https://jira.talendforge.org/browse/TUP-20950
https://jira.talendforge.org/browse/TUP-20950

fix(TUP-20950):When Configuration/Datastore class is empty it is displayed in Studio as a Text field.

---

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet

* Fix multivalue body mail part processing
"Multivalue" checkbox does not work for body mail part
Multivalue checkbox is used to process multipart mail body.

fix(TDI-42549): tFileInputMail multipart body

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

Original issue: beans package from referenced project become empty (does not have any classes inside) during Studio startup with main project. 
Issue is not reproduced in case of I put one break point in debug mode for this line (and wait 1 sec) https://github.com/Talend/tdi-studio-se/blob/7d8653fbf967826c046b02c16f1f7c6f329df20e/main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java#L843
Original code works in this way:
- build Routines from referenced project
- remove routines referenced project from workspace
- build PigUDFs from referenced project
- remove PigUDFs referenced project from workspace
- build Beans from referenced project
- remove Beans referenced project from workspace
I see that removing of Routines project …

TESB-26789 Bean called in routelet not found by main route

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java

* TESB-23600 : do not open dialog anymore when checking errors
* TESB-23600 : refactor/cleanup
Conflicts:
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
Conflicts:
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
When route is built, it shows twice an error dialog.
Do not display dialog on error check …

TESB-26300: disable message dialog when checking build errors (#3654)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/local/ExportItemUtil.java

turning into a reference to the default 6.0.0-SNAPSHOT version
- [ *] Bugfix
- [ *] No

bugfix(TUP-24563):Specifying a custom MVN URI in a Bean still ends up

---

main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet

At this moment content handlers (com.sun.mail.handlers.*) can not be found by classloader because of they are not present in import section of generated bundles manifest. It leads to ClassNotFoundError in Runtime.
Current fix resolves this issue (codegenerator will find and add "import com.sun.mail.handlers.*; " to generated code and corresponding dependency to import section of bundles MANIFEST).

TESB-27110 Missing tSendMail dependencies are added

---

main/plugins/org.talend.designer.core/src/main/java/messages.properties
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobContextLoadComponent.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java

* feat(TUP-25035)Implicit tContextLoad feature (with selection from file)
uses a hardcoded encoding of ISO-8859-15
* bugfix(TUP-25035)Implicit tContextLoad feature (with selection from
file) uses a hardcoded encoding of ISO-8859-15
* bugfix(TUP-25035)Implicit tContextLoad feature (with selection from
file) uses a hardcoded encoding of ISO-8859-15
* bugfix(TUP-25035)Implicit tContextLoad feature (with selection from
file) uses a hardcoded encoding of ISO-8859-15
* bugfix(TUP-25035)Implicit tContextLoad feature (with selection from
file) uses a hardcoded encoding of ISO-8859-15
**Does …

Hengzhao/bugfix/tup 25035 (#4157)

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java

https://jira.talendforge.org/browse/TDI-43212
When the query String contains ending semicolon in newer version of tJDBC component compile error appears. (Starting from Studio 7.0)
Remove the last semicolon that is present in query string.

fix(TDI-43212): improve code generation for query string

---

test/plugins/org.talend.repository.test/src/org/talend/repository/handler/BuildJobHandlerTest.java

caused by org.eclipse.emf.ecore.resource.Resource$IOWrappedException:
The object 'testauto@talend.com' is not contained in a resource

Fix junits failure

---

main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java

fix(TUP-24148): tNetsuiteInput throws cast error when switching from use tNetsuiteConnection to use this component
https://jira.talendforge.org/browse/TUP-24148

fix(TUP-24148): tNetsuiteInput throws cast error when switching from use tNetsuiteConnection to use this component

---

main/plugins/org.talend.designer.core/plugin.xml
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/NumberLimitTextController.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/generator/NumberLimitTextGenerator.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/generator/TextGenerator.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java

Text filed on component view can input every thing. But for our threshold of tMatchGroup component. If the threshold is bigger than six decimal places then it will get exception result.
https://jira.talendforge.org/browse/TDQ-17709
Create a new text controller NumberLimitTextController and make sure it is working for table.
And the new text field can input number and dot only. 
we add a limit to keep six decimal places on here
If this PR contains a breaking change, please describe the impact and migration path for existing applications: …

fix(TDQ-17709): create number limit text controller

---

main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileOutputPositional/tFileOutputPositional_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileOutputPositional/tFileOutputPositional_main.javajet

tFileOutputDelimited in iterate parallel execution is working syncronic even when write occurs in different files
Lock changed to the target filename

fix(TDI-43222): Lock write operation by filename in parallel

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

Backport for patch 7.1.1 (#4045)
* fix(TESB-27030): Avoid to add activemq-all lib in OSGi bundle
* fix(TESB-27030): Exclude jms library when it is used from tRunJob
Conflicts:
main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

fix(TESB-27030): Exclude jms library when it is used from tRunJob

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobFactory.java

Dataservices are always published as OSGI bundles without taking care of the Job defined build type. 
With this fix, DS with build type "Microservice" will be built and published with the appropriate format.

TESB-27989 Fix publish DS to cloud as MS

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet

https://jira.talendforge.org/browse/TDI-43632
Static pattern cut fraction seconds.
Use user-defined pattern instead of static one.

fix(TDI-43632): use defined pattern by user instead of static value

---

main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/util/JSONUtils.java
main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/test/java/net/sf/json/util/TestJSONUtils.java
main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_java.xml

https://jira.talendforge.org/browse/TDI-43610
A decimal value in a json with non-significant 0, keep at least one non-significant 0 to keep the double type "10.0000" -> "10.0"

fix(TDI-43610) : jsonutil keep decimal if any

---

main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_end.javajet

https://jira.talendforge.org/browse/TDI-33414
before the change of TDI-32991, the input message will be moved to the backout queue when the 3rd message reaches the message queue. But after the change, the input message will be moved to the backout queue once the 2nd message reaches the message queue.
It was fixed with right backout order.

fix(TDI-33414): change tMomInput backout behavior

---

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tELTMysqlMap/tELTMysqlMap_java.xml

* update driver and remove MYSQL_4
for https://jira.talendforge.org/browse/TDI-43510 
update mysql driver for tCreateTable/tELTMysqlMap and remvoe mysql4

feat(TDI-43510):Upgrade mysql driver for tCreateTable/tELTMysqlMap

---

main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton

Use setNString method for NVARCHAR and NCHAR columns
Method setString il always used to set the value of a string column
Code now checks if the column is a NVARCHAR or NCHAR type and then use setString or setNString accordingly
- [X ] Bugfix
- [ X] No

TDI-43764 : MsSQL NVARCHAR

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet

set correct configuration value for non String context item
For tacokit components, when using a context item that is not a String type, there's compilation error due to the fact the type do not match the Map<String, String> for component's configuration.

fix(TCOMP-1677): correct configuration value for non String context item

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/ServiceAccountBigQueryHelper.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_end.javajet

https://jira.talendforge.org/browse/TDI-42951
The component tBigQueryInput in case of Authentication Mode - Service Account & Result Size - Auto -> executes a query always as for large results. Auto result size uses when the volume of the query result is not certain. So we we use much more resources than we need during Auto result size.
Now during Auto result size, component will try to perform small, in case of error - large
If this PR contains a breaking change, please describe the impact and migration path for existing applications: …

fix(TDI-42951): Improved query execution for Result size Auto

---

main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastExport/tTeradataFastExport_messages.properties

https://jira.talendforge.org/browse/TDI-44002
Necessary rename "Die When Unnormal Terminated" to "Die on abnormal termination" in tTeradataFastExport
Property already renamed

fix(TDI-44002): Rename DIE_WHEN_UNNORMAL_TERMINATED.NAME property

---

main/plugins/org.talend.designer.components.localprovider/components/tBoxList/tBoxList_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBoxList/tBoxList_end.javajet
main/plugins/org.talend.designer.components.localprovider/resources/box/header_additional_box.javajet

https://jira.talendforge.org/browse/TDI-43995
The component tBoxList lists files from parent folder. When you pass the path to the file, component displays siblings folder on the same base path. When you pass path that does not exist displaying content of the root folder.
Supported listing any path.
If the path is a file, only list the file.

fix(TDI-43995): Support listing any path and file

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_end.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_end.javajet

https://jira.talendforge.org/browse/TDI-44010
NB_Line is null when there are not entries for iteration for Input and Output components
Now NB_Line is add to globalMap in the ending javajet by default

fix(TDI-44010): Fix adding NBLine to globalMap

---

main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java
main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/util/GenericContextUtil.java

Names is not reflected on the Connection for Snowflake
https://jira.talendforge.org/browse/TUP-26639

fix(TUP-26639):Talend Cloud studio Issue -Changes to Context Parameter

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet

https://jira.talendforge.org/browse/TDI-44093
Syntax error when use query for tCosmosDBSQLAPIInput. Because strings with quotes were not processed correctly
Currently strings with quoted values process as expected.

fix(TDI-44093): Fix processing of quoted strings

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
main/plugins/org.talend.designer.codegen/jet_stub/header.javajet

* fix(TDI-43619): Null Value Treated as <TALEND_NULL> in Subjob
* fix(TDI-43619): fix for all types to avoid the parse warn log or message
when null
* fix the compiler issue for password field
https://jira.talendforge.org/browse/TPS-3976
https://jira.talendforge.org/browse/TPS-3976

fix(TDI-43619): Null Value Treated as <TALEND_NULL> in Subjob (#4488)

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet

https://jira.talendforge.org/browse/TDI-44147
The job with "Create the table if it doesn't exist" can be run several times without failing, and create the table at the first execution.

fix(TDI-44147) : BigQuery create table only if needed

---

main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_java.xml

https://jira.talendforge.org/browse/TDI-44191 : wrong behavior in MDM deployment.
Same in studio & "job build".
Just MODULE name in xml description that strip version.

fix(TDI-44191) : change module for tfilecopy

---

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet

- this fixes the case when run as independent job is checked and the `m2.repository` automatically defaults to user's m2 in exported job.
- issue on singleton will be fix by component-runtime upgrade.
https://jira.talendforge.org/browse/TDI-44174

fix(TDI-44174): Component manager is not thread safe

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java

https://jira.talendforge.org/browse/TUP-27588

fix(TUP-27588)tCreateTable data types mapping in the schema editor is always Mysql after dragging and dropping from database Metadata

---

main/plugins/org.talend.libraries.excel/pom.xml

This task is to update Commons Compress to at least version 1.19 to pick up some CVE fixes (https://commons.apache.org/proper/commons-compress/security-reports.html#Apache_Commons_Compress_Security_Vulnerabilities)

TDI-44140 - Update Commons Compress to 1.19

---

main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet

In tFileInputMail, when parsing a mail and requesting for a header field that is not present, the "getHeader" function will return a null value witch is the expected behavior.
In the case the "Multi Value" option is checked for a field, the previous code wasn't checking for null value before trying to loop on the field, witch was causing a java.lang.NullPointerException when trying to get the length of the array.
a null pointer exception occurs
no more null pointer exception
If this PR contains a breaking change, please describe the …

tFileInputMail_MIME.javajet : avoid a java.lang.NullPointerException

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_main.javajet

https://jira.talendforge.org/browse/TDI-44342
DateTime columns are not correctly read from BigQuery. This is because BigQuery stores date with a microsecond precision while Java can only hanlde to milliseconds.
The datetime string is cut to remove the last three digits to conform to java Date precision.
- [x ] Bugfix
- [x ] No

TDI-44342 : Ignore microseconds in BigQuery datetime

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java

fix(TUP-26197)needn't force to log4j2 when import old project which is

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java

This fix includes fixes for TESB-27081 and TESB-27583 handling missing SOAP Action due to missing WSDL and TESB-2960 ensuring the WSDL is present for properly configuring the SOAP 1.2 binding.
https://jira.talendforge.org/browse/TESB-27081
https://jira.talendforge.org/browse/TESB-27583
https://jira.talendforge.org/browse/TESB-29690
The WSDL document is added as resource to jobs which are web service consumer, ensuring proper web service calls.
If this PR contains a breaking change, please describe the impact and migration path for …

TESB-29690 Ensure WSDL is included in WS consumer build.

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

If the job's deployment "Custom Version" is different than that of the job's item version, then the job's bundle uses the job's item version instead of "Custom Version". This PR is to make bundle use "Custom Version"

TESB-29647 Bundle version does not use 'Custom Version' for jobs

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

To fix this issue we can use '/' instead of empty endpoint. Then we can access service with this URL http://localhost:8040/services

TESB-29664 Random port will be used when REST Engpoint in tRESTRequest is empty

---

main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet

https://jira.talendforge.org/browse/TDI-44202
The component tCreateTable in case of Database Type - Sybase can't create table and fails with SQLException.
After fix tCreateTable component works as expected.

fix(TDI-44202): tCreateTable add support of Sybase

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java

Currently if we are building Job (parent) as microservice and the Job contains child Job, 
this child Jobs also will be automatically build as microservice, even if it supports only OSGI or Standalone build type. This PR adds additional check to make sure that only Job which has microservice build type will be build as microservice.

TESB-29285, TESB-29284 Error occurred when execute a microservice jar which is built by a tresrequest job with embedded trestclient job

---

main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java

This fix corrects TESB-27081 and TESB-27583 ensuring SOAP Action is set from binding definition in WSDL, and TESB-2960 ensuring the WSDL is present for properly configuring the SOAP 1.2 binding. This fix is identical with the temporarily reverted fix from pull request #4926.
Due to missing WSDL resource WS clients configure default values which may be incompatible with the server side.
Inclusion of the WSDL in WS clients built as OSGi bundles is ensured.
If this PR contains a breaking change, please describe the impact and migration path …

TESB-27583 TESB-29690 Ensure WSDL is included in WS consumer build.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java

always Mysql after dragging and dropping from database Metadata

fix(TUP-27588)tCreateTable data types mapping in the schema editor is

---

main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/extraction/ExtractionLoopWithJSONXPathEditorView.java

https://jira.talendforge.org/browse/TUP-28130
'Loop limit' does not limit the number of loop
Remove loop limit column for json type meta data.

TUP-28130 Remove Loop limit column for target schema's path loop expression table, for json type meta data.

---

main/plugins/org.talend.designer.components.libs/libs_src/mdm_transaction/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-webservice-input/pom.xml
main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
main/plugins/org.talend.designer.components.localprovider/pom.xml

* remove commons-logging library from mdm_transaction and webservice-input libraries
* bump version for talend-webservice-input [1.0.0-20170301]->[1.0.2]
* declare explicit version of maven-jar-plugin in talend-webservice-input dependency
* change group id of mdm_transaction
* update version of mdm_transaction [1]->[1.2.0]
* change import in javajet xml due to convension for the talend-webservice-input to [1.0.2/6.0.0]
TDI-44362
If this PR contains a breaking change, please describe the impact and migration path for existing applications: …

chore(TDI-44362): CVE. Remove commons logging

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/prefs/RunProcessPreferenceInitializer.java
main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/utils/JobVMArgumentsUtil.java

https://jira.talendforge.org/browse/TUP-27374
Get default jvm arguments if studio can not load it from preference store.

fix(TUP-27374): Get default jvm arguments

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

https://jira.talendforge.org/browse/TESB-29664- Random port will be used when REST Endpoint in tRESTRequest is empty
The default value is a service path "/&lt;artifact-name&gt;"

TESB-29664 Produce a more unique default value on empty endpoint URI.

---

main/plugins/org.talend.designer.components.localprovider/components/tOracleInput/tOracleInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_java.xml

* remove interfere SPECIFY_DATASOURCE_ALIAS from the import condition of the tOracle components
https://jira.talendforge.org/browse/TDI-31162
It doesn't add an ojdbc driver into the classpath of the job if the SPECIFY_DATASOURCE_ALIAS checkbox is selected
It will add it.
- [ x The commit message follows Talend standard
Shouldn't.

fix(TDI-31162): remove interfere condition

---

main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/src/main/java/org/talend/ftp/SSLSessionReuseFTPSClient.java
main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
main/plugins/org.talend.designer.components.localprovider/pom.xml

* add info message about nullity of the ssl session context
* update version of commons-net-ftps-proxy [3.6.1-talend-20190819] -> [3.6.1-talend-20200902]
* update version of 'commons-net-ftps-proxy' in javajet ftp's components
* remove slf4j-log4j12 dependency
https://jira.talendforge.org/browse/TDI-44654

fix(TDI-44654): fixed NPE for tFTP (#5071)

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/PropertyValidator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ValidationListener.java

* Don't show validation results for hidden parameters
* Revalidate parameters on show/hide property change

fix(TCOMP-1749): validation with ActiveIf broken

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/PropertyValidator.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ValidationListener.java

* Don't show validation results for hidden parameters
* Revalidate parameters on show/hide property change
Co-authored-by: Dmytro Chmyga <dmytro.chmyga@synapse.com>

fix(TCOMP-1749): validation with ActiveIf broken (#5121)

---

main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml

* remove guava:13.0 dependency use 20.0 instead of it
https://jira.talendforge.org/browse/TDI-44765
It's a port from maintenance/7.3

chore(TDI-44765): remove guava:13.0

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

https://jira.talendforge.org/browse/TCOMP-1770
https://jira.talendforge.org/browse/TDI-44874
**Related PR**
- https://github.com/Talend/studio-full-master/pull/439
- https://github.com/Talend/tcommon-studio-ee/pull/1522
- https://github.com/Talend/tcommon-studio-se/pull/3637
- https://github.com/Talend/tdi-studio-se/pull/5201

fix(TCOMP-1770): bump component-runtime to 1.1.25

---

main/plugins/org.talend.designer.components.libs/libs_src/mdm_transaction/pom.xml

https://jira.talendforge.org/browse/TMDM-14794
We should update Commons Codec to 1.13+ due to a medium level CVE reported by Veracode.
Removed Commons Codec in pom file as it wasn't imported in source code.

TMDM-14794 Update Commons Codec to 1.13+ in mdm_transaction

---

main/plugins/org.talend.designer.components.libs/libs_src/mdm_taskloadclient/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/mdm_taskloadclient/src/main/java/org/talend/datastewardship/server/task/creation/TaskLoadClient.java

https://jira.talendforge.org/browse/TMDM-14845
We should update Commons Codec to 1.13+ due to a medium level CVE reported by Veracode. 
Removed Commons Codec and used java.util.Base64.

TMDM-14845 Update Commons Codec to 1.13+ in mdm_taskloadclient

---

main/plugins/org.talend.repository/src/main/java/messages.properties

https://jira.talendforge.org/browse/TUP-28773

Fix: TUP-28773 Dialog title is incorrect when using 'Import an existing project'

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java

https://jira.talendforge.org/browse/TESB-30623 - Data service job bundles built via CI contain empty routines library jar.
The internal jar "lib/routines.jar" contains the expected routine classes.

TESB-30623 Ensure routine classes are compiled before the routines library is created.

---

main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/soap/src/main/java/org/talend/soap/SOAPUtil.java
main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
main/plugins/org.talend.designer.components.localprovider/pom.xml

https://jira.talendforge.org/browse/TDI-44893
Upgraded libraries:
- saaj-impl - 1.5.2: the main fix of the Jira.
- commons-codec - 1.14: as in tSOAP_java.xml
- stax-ex-1.8.3: comes as compile dependency for saaj-impl
- jakarta.xml.soap-api-1.4.2: comes as compile dependency for saaj-impl
Removed libraries:
- jdom - 1.1: old version, replaced with newer **org.dom4j**
- javax.activation: comes as **com.sun.activation:jakarta.activation:jar** as provided jar
- jaxqname: replaced with **xml-apis**
- jaxpapi: replaced with **xml-apis**
- jaxpri: replaced with **xercesImpl**
- saajapi: removed as no relation to newest saaj-impl
**What …

fix(TDI-44893): upgrade libraries, update code, remove old libs

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java

https://jira.talendforge.org/browse/TUP-28778
"java.lang.ClassCastException" thrown in error log when d&d Input/Output/Trigger Input/Trigger Output from Palette into joblet
NO "ClassCastException" thrown in error log and Searchable Stitch connectors works as before.

TUP-28778 Add 'if' judgment  before type conversion.

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/sdk/OnlineAuthenticationPolicy.java
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.libraries.crm/pom.xml

https://jira.talendforge.org/browse/TDI-44866
tMicrosoftCrmInput/Output configured on-premise + v2011 generate a ClassNotFoundException if executed within java 11.
The not found exception has been chnage by another one.

fix(TDI-44866) : mscrm 11 not java11 compatible

---

main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
main/plugins/org.talend.libraries.crm/pom.xml

https://jira.talendforge.org/browse/TDI-44866
tMicrosoftCrmInput/Output configured on-premise + v2011 generate a ClassNotFoundException if executed within java 11.
The not found exception has been change by another one. In maintenance branch, only change the lib version to use the one from master 3.4-20200923.

fix(TDI-44866) : mscrm 11 not java11 compatible - maintenance

---

main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleRow/tAmazonOracleRow_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tOracleRow/tOracleRow_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/AbstractDBInputBegin.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jDBConnUtil.javajet

* make query expression idempotent in the generated code
* store the expression in the variable and then read it again
https://jira.talendforge.org/browse/TDI-44935
the query is idempotent for logger
It's a backport from maintenance/7.3

fix(TDI-44935): reuse custom query expression

---

main/plugins/org.talend.designer.components.libs/libs_src/neo4j-talend-component/pom.xml

Fixing ticket https://jira.talendforge.org/browse/TDI-42384. We don't need neo4j repo as all the required deps can be downloaded from central.

chore(TDI-42384): remove old neo4j repo from pom

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java

* fix(TUP-29131): Replace jar name by uri for spark job
* fix(TUP-29131): Replace jar name by maven uri for spark jobs
https://jira.talendforge.org/browse/TUP-29131
Replace jar name by maven uri for spark jobs

bugfix(TUP-29131) Replace jar name by maven uri for spark jobs (#5444)

---

main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet

https://jira.talendforge.org/browse/TDI-45161
Fileinputdelimited does not work with dynamic & parallel
Affect object without copy, then, rebuild values. So, threads shared mutable & modified list.
Work
Affect a copy of Dynamic object, only immutable shema is preserved. So, each threads treats its own values.
(As first code recreate values list each time, there are no performance pb)

TDI-45161 : tFile input delimited correction

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitWizardComposite.java

https://jira.talendforge.org/browse/TUP-26486
https://jira.talendforge.org/browse/TUP-29355
Netsuite/tck: in Metadata credentials fields are not changed based on Auth type selected

fix(TUP-26486, TUP-29355): fix problem that 'Netsuite/tck: in Metadata credentials fields are not changed based on Auth type selected'.

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java

https://jira.talendforge.org/browse/TUP-29224
ELTMAP generate wrong SQL When dragging multiple columns at the same time, because the column was always added into same index, so the order is opposite.
auto increment the index according the added columns numvers.

fix(TUP-29224):auto increment the index according to the drag/drop column numbers.

---

main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java

https://jira.talendforge.org/browse/TUP-29224
ELTMAP generate wrong SQL When dragging multiple columns at the same time, because the column was always added into same index, so the order is opposite.
auto increment the index according to the drag/drop column numbers.

fix(TUP-29224) auto increment the index according to the drag/drop column numbers.

---

main/plugins/org.talend.designer.core/plugin.xml
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/FixModuleListInBDJDBCMigrationTask.java
main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UpdateModuleListInComponentsMigrationTask.java

https://jira.talendforge.org/browse/TUP-29693
When to migrate jarname to maven uri, do not replace jarname if jarname contains context.

fix(TUP-29693): Do not replace maven uri for context inside jarname

---

main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/src/main/java/org/talend/fileprocess/delimited/RowParser.java

https://jira.talendforge.org/browse/TDI-45260
CR issue, CRLF row separator low performance with Scanner
Fixed problem with CR for LF row separator, increased performance for CRLF.

fix(TDI-45260): fix cr issue, improve crlf row separator performance

---

main/plugins/org.talend.designer.components.localprovider/components/tApacheLogInput/tApacheLogInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tExtractPositionalFields/tExtractPositionalFields_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputFullRow/tFileInputFullRow_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml.tmp
main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileInputRegex/tFileInputRegex_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFixedFlowInput/tFixedFlowInput_java.xml
main/plugins/org.talend.libraries.custom/.classpath
main/plugins/org.talend.libraries.custom/META-INF/MANIFEST.MF
main/plugins/org.talend.libraries.custom/pom.xml

CR treated as row separator, even though it's not ("\n" case)
Handle CR character, improve performance for "\r\n".

fix(TDI-45260): update components with new library version

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/MainComposite.java

https://jira.talendforge.org/browse/TUP-29550
after rename job name,version, old job items still in pom file.
update pom file according job property change, align with edit job property.

fix(TUP-29550) fix problem that "rename" Job in property sheet page duplicates item in Pom file

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

https://jira.talendforge.org/browse/TDI-45530
*Related PR*
- https://github.com/Talend/studio-full-master/pull/618
- https://github.com/Talend/tcommon-studio-se/pull/4036
- https://github.com/Talend/tcommon-studio-ee/pull/1742
- https://github.com/Talend/tdi-studio-se/pull/5803

feat(TDI-45530): bump component-runtime to 1.29.1 for bouncycastle CVE

---

main/features/org.talend.tos.libraries.feature/feature.xml

https://jira.talendforge.org/browse/TUP-30230
Remove org.talend.libraries.apache.batik

chore(TUP-30230): Remove org.talend.libraries.apache.batik

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/Log4jSettingPage.java

https://jira.talendforge.org/browse/TUP-30109
resolved problem that after restore default value the preference changes cannot be saved on log4j preference page.

fix(TUP-30109) [7.3.1] Log4J preferences does not save

---

main/plugins/org.talend.sdk.component.studio-integration/pom.xml

* clean cached libs during clean phase for studio-integration plugin
* help to avoid using the out-to-date version of jars in plugin
https://jira.talendforge.org/browse/TCOMP-1877

feat(TCOMP-1877): clean cached libs studio-integration

---

main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet

* fix the logic of passing date variable to sub jobs
https://jira.talendforge.org/browse/TDI-45746
the date context variables converting via string not via second as it was before

feat(TDI-45746): fix date context variable

---

main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java

https://jira.talendforge.org/browse/TUP-25417
generate classpath using relative path for building parent job(whose child job contains esb cxf components) on jdk11

fix(TUP-25417) JDK11: run a job call a child job use twebservice meet error.

---

main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_begin.javajet

https://jira.talendforge.org/browse/TDI-45772
unarchiv component try to update creation date of extracted file by build file as "new File(repo + name);"
so, if repo doesn't terminate with path separator (/), File doesn't point to the right file, so, operation has no effect.
Java file is build with "new File(repo, name);" (File(String, String) constructor)).
So, whatever the end of repo, it's good.

TDI-45772 : unarchiv correction

---

main/plugins/org.talend.designer.components.localprovider/components/tMap/tMap_main.inc.javajet

* extend try-block that includes "Input tables (lookups)"
https://jira.talendforge.org/browse/TDI-45732
covered with try-catch Table Input (lookups) area in tMap component

feat(TDI-45732): extend not dieoneerror area

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/TaCoKitGuessSchemaProcess.java

TUP-31145 TCK:Guess schema use an exist connection will overwrite the parameters of component tNetSuiteV2019Input
https://jira.talendforge.org/browse/TUP-31145

TUP-31145 TCK:Guess schema use an exist connection will overwrite the parameters of component tNetSuiteV2019Input

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet

fix(TDI-43931): convert long as date from context args
* update file root to be up to date
* implement fix for tRunJob
* mention string parse exception in log warn
https://jira.talendforge.org/browse/TDI-45924
https://jira.talendforge.org/browse/TDI-43931

fix(TDI-43931) pass full date to independand child job

---

main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java

https://jira.talendforge.org/browse/TDI-45551
java.lang.UnsupportedOperationException: Unrecognized type id_byte[]
Added processing for id_byte[]

fix(TDI-45551): SingleStore fix blob type processing

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/GeneralProjectSettingPage.java

Feat:TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting.
https://jira.talendforge.org/browse/TUP-30377

Feat:TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/GeneralProjectSettingPage.java

Feat:TUP-30377 Move the "Allow specific characters (UTF8,...) preference setting to project setting.
https://jira.talendforge.org/browse/TUP-30377

Feat:TUP-30377 Move the "Allow specific characters (UTF8,...)" (#6139)

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_begin.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_end.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_finally.javajet
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/enums/ETaCoKitComponentType.java

* Integrate TCK Standalone connectors to studio
We don't have Standalone connectors support in studio
Add the TCK standalone connectors support to studio code.
https://jira.talendforge.org/browse/TDI-45836
Do not merge before https://github.com/Talend/component-runtime/pull/475 is merged. Should be integrated together with according component-runtime version.

feat(TDI-45836): Standalone connectors support

---

main/plugins/org.talend.designer.components.libs/libs_src/filecopy/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/filecopy/src/main/java/org/talend/FileCopy.java
main/plugins/org.talend.designer.components.libs/libs_src/filecopy/src/test/java/org/talend/FileCopyTest.java
main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_main.javajet
main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_messages.properties
main/plugins/org.talend.libraries.custom/pom.xml
main/plugins/org.talend.repository/plugin.xml
main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SetForceCopyFortFileCopy.java

* Add force copy parameter
* Copy and delete file instead of moving
If the file is being moved between filesystems the process might fail
In case 'Force copy instead of move' parameter is checked we will copy the file and delete it
https://jira.talendforge.org/browse/TDI-45859

fix(TDI-45859): tFileCopy with different fs

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtilTest.java

https://jira.talendforge.org/browse/TUP-30430
Clone the connection's UNIQUE_NAME for some links instead of generating a new one in joblet node container.

fix(TUP-30430): Clone the connection's UNIQUE_NAME for some links instead of generating a new one in joblet node container.

---

main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtilTest.java

https://jira.talendforge.org/browse/TUP-30430
Clone the connection's UNIQUE_NAME for some links  instead of generating a new one in joblet node container. 

fix(TUP-30430): Clone the connection's UNIQUE_NAME for some links  instead of generating a new one in joblet node container. (#6194)

---

main/plugins/org.talend.designer.components.localprovider/pom.xml

for https://jira.talendforge.org/browse/TDI-44893 wrong backport missing artifactId update

fix(TDI-46346): wrong soap lib artifactId in 7.2 localprovider

---

main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet

https://jira.talendforge.org/browse/APPINT-32340
Context variable will correctly get the default value even if some context are overriden

APPINT-32340 NullPointerException if context variable is not provided

---

main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet

* fix(TDI-45907): single insert Bigdecimal
* Set scale for bigdecimals
* fix(TDI-45907): fix indents
* fix(TDI-45907): consider precision is not set
Co-authored-by: Dmytro Chmyga <dmytro.chmyga@globallogic.com>
https://jira.talendforge.org/browse/TDI-45907

fix(TDI-45907): single insert Bigdecimal (#6384)

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_end.javajet
main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_process_records_end.javajet

* TCK studio-integration
* method stop should be invoked after the method flush for producers (outputs)
(cherry picked from commit 54b17eea2c4d714d613d78d01c7ddd829f52a03a)
https://jira.talendforge.org/browse/TDI-47222
Related pr
https://github.com/Talend/tdi-studio-se/pull/6985

fix(TDI-47222): invoke stop after flush (#6985)

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java

https://jira.talendforge.org/browse/TDQ-19623
support export TDQ reference project items when do build job and the job contains tDqReportRun

fix(TDQ-19623): make sure tdqReportRun can support reference project out of stdio

---

main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet

https://jira.talendforge.org/browse/TCOMP-2122
https://jira.talendforge.org/browse/TCOMP-2122

fix(TCOMP-2122): [JDBC TCK]: can't get user defined schema info in tck runtime in studio when no data outut line

---

main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_begin.javajet

https://jira.talendforge.org/browse/TDI-48418
This includes the following fixes:
- fix(TCOMP-2182): pass version to tck guess schema
***Related PR***
**master**
- https://github.com/Talend/studio-se-master/pull/679
- https://github.com/Talend/tcommon-studio-se/pull/5592
- https://github.com/Talend/tdi-studio-se/pull/7987
**maintenance/8.0**
- https://github.com/Talend/studio-se-master/pull/681
- https://github.com/Talend/tcommon-studio-se/pull/5593
- https://github.com/Talend/tdi-studio-se/pull/7988

feat(TDI-48418): Bump component-runtime to 1.48

---

main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/ActiveIfListener.java

https://jira.talendforge.org/browse/TUP-36717
https://jira.talendforge.org/browse/TUP-36717

fix(TUP-36717): Avoid error log and NPE after after a connector use TCOMP-2230 allow a "ui.scope" target for the tck ActiveIf json metadata info

---

main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java

Fix TUP-36781 If do not select "ask me at startup" on login project page, next time studio will popup "Branches has been changed! Please check and logon manually" dialog
https://jira.talendforge.org/browse/TUP-36781

Fix TUP-36781 If do not select "ask me at startup" on login project

---

main/plugins/org.talend.designer.components.libs/libs_src/talendssl/pom.xml
main/plugins/org.talend.designer.components.libs/libs_src/talendssl/src/main/java/talend/ssl/Truster.java
main/plugins/org.talend.designer.components.localprovider/META-INF/MANIFEST.MF
main/plugins/org.talend.designer.components.localprovider/components/tLDAPAttributesInput/tLDAPAttributesInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tLDAPConnection/tLDAPConnection_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tLDAPInput/tLDAPInput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tLDAPOutput/tLDAPOutput_java.xml
main/plugins/org.talend.designer.components.localprovider/components/tLDAPRenameEntry/tLDAPRenameEntry_java.xml
main/plugins/org.talend.designer.components.localprovider/pom.xml

https://jira.talendforge.org/browse/TUP-41020
Initialize default trust manager if specified cacerts not found

fix(TUP-41020): LDAP Metadata : Check Authentication fails when Encryption method = LDAPS(SSL) even with correct credentials. 
