- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaSampleCodeFactory.java
Update code to generate code for tJavaRow components in BD Spark Batch and Streaming.
> [TBD-1999] Update code to generate code for tJavaRow components in BD Spark Batch and Streaming.

- main/plugins/org.talend.designer.components.localprovider/components/tMDMBulkLoad/tMDMBulkLoad_finally.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMBulkLoad/tMDMBulkLoad_main.javajet
In order to fix TMDM-8949, I need to enhance tMDMBulkLoad by adding a finally clause to it and clean resources used in the main part of the component.
> TMDM-8949 add a finally part to tMDMBulkLoad, to clean InputStreamMerger

- main/plugins/org.talend.designer.components.localprovider/plugin.xml
Reuse the module group in TDI to manage Kafka libraries for TBD.
> TBD-2639: Add kafka libraries to plugin.xml.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
regardless the presence of a "USE_EXISTING_COMPONENT" or not.
> [TBD-2773] Empty "COMPONENT_LIST" element are now displaying an error,

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
The job failed when run tDQReportRun job with git remote
> bug fixed TDQ-11338

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
> TESB-16985:tESBConsumer using default SOAPAction header when there is no SOAPAction defined

- main/plugins/org.talend.component.core/src/main/java/org/talend/component/core/model/Component.java
- main/plugins/org.talend.component.core/src/main/java/org/talend/component/core/model/GenericElementParameter.java
- main/plugins/org.talend.component.core/src/main/java/org/talend/component/core/model/migration/ChangeSalesforceComponentsParametersToSerializedMigrationTask.java
- main/plugins/org.talend.component.core/src/main/java/org/talend/component/core/utils/ComponentsUtils.java
- main/plugins/org.talend.component.ui.wizard/src/main/java/org/talend/component/ui/wizard/ui/GenericConnPropertiesWizard.java
- main/plugins/org.talend.component.ui.wizard/src/main/java/org/talend/component/ui/wizard/ui/dnd/GenericDragAndDropHandler.java
- main/plugins/org.talend.component.ui.wizard/src/main/java/org/talend/component/ui/wizard/util/GenericContextUtil.java
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
Please @ycbai can you review it but do not merge it yet.
The merge must be done after the Component framework branch is merged : https://github.com/Talend/components/tree/make_ComponentProperties_a_Property
> update Generic Component set/getValue after Framework change

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
[Need modify code out of "components" repository]
https://jira.talendforge.org/browse/TDI-35107
> TDI-35107: New Salesforce components "Use this connection" doesn't work

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/dnd/GenericDragAndDropHandler.java
Code Pull request : 
Before i only based on the temp branch : bugfix/6.2/TUP_4141_fixStudioOrComponentIssues , now it had be merged ,then can create the pull request .
> TUP-4177:Throw error when dropping tSalesforceInputNew on the designer.

- main/plugins/org.talend.designer.core.generic/plugin.xml
Code Pull request : 
Before i only based on the temp branch : bugfix/6.2/TUP_4141_fixStudioOrComponentIssues , now it had be merged ,then can create the pull request .
> TUP-4170:TCOMP : NPE when dropping tSalesforceOutputNew on the designer(TUP-4010)

- main/plugins/org.talend.designer.core.generic/META-INF/MANIFEST.MF
- main/plugins/org.talend.repository.generic/META-INF/MANIFEST.MF
- test/plugins/org.talend.repository.generic.test/META-INF/MANIFEST.MF
TUP-3843:remove execution environment in new plugin setup(TUP-4010)
> TUP-3843:remove execution environment in new plugin setup(TUP-4010)

- pom.xml
need update the pom.xml file for the new plugin  .
> TUP-3843:update the pom.xml file for the new plugin(TUP-4010)

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
> TBD-3174:add parameters to distinguish different job types and

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/StandAloneTalendJavaEditor.java
https://jira.talendforge.org/browse/TDI-35280
> TDI-35280 bug: Talend stores te content of a bean to the wrong file!

- main/plugins/org.talend.designer.components.localprovider/components/tSAPConnection/tSAPConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSAPConnection/tSAPConnection_messages.properties
https://jira.talendforge.org/browse/TDI-35391
> TDI-35391 : Remove the option 'sap jco 2.*' from tSAPConnection

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericElementParameter.java
Note: you have to wait the fix of TCOMP-99 before test this bug.
>  TUP-4163: add long running when invoking callXXX methods of component

- main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
https://jira.talendforge.org/browse/TDI-35262
> TDI-35262 : security issues: Oracle password in plain text

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
https://jira.talendforge.org/browse/TUP-4248
> [TUP-4248] fixed bugs for type convert

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
Set BundleID="" attribute for CXF dependencies, as them causes CCE during feature install
> TIPAAS-8133: MDM jobs failed on TIC1.5

- main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
TUP-4200: tOracleBulkExec returning wrong NB_LINE_* value with DIRECT
path mode
https://jira.talendforge.org/browse/TUP-4200
Note: Changed the algorithm to read the right line of the generated log
file.
> TUP-4200: tOracleBulkExec returning wrong NB_LINE_* value with DIRECT path mode

- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_begin.javajet
https://jira.talendforge.org/browse/TDI-35602
> TDI-35602 : issue when setting escape char as "" for tVerticaBulkExec

- main/plugins/org.talend.designer.components.localprovider/components/tGroovy/tGroovy_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGroovy/tGroovy_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tGroovyFile/tGroovyFile_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGroovyFile/tGroovyFile_java.xml
Changes is related only to tGroovy/tGroovyFile components.
> TDI-33821: update tGroovy and tGroovyFile components to groovy version 2.4.6

- main/plugins/org.talend.componentdesigner/src/org/talend/componentdesigner/ui/action/provider/PushToPaletteActionProvider.java
> TDI-35131：'Push components to Palette' doesnt update the files correctly

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java
test case and job stops building
> TUP-4222:Change in context value does not get updated in the job and

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/AbstractMultiPageTalendEditor.java
> TDI-35456：MapReduce job:Progress bar is lost when I go to jobscript tab

- main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml
https://jira.talendforge.org/browse/TDI-35468
> TDI-35468 : WebSphere 8.0 and Active 5.13+ for tMomXXXX and tJMS

- main/plugins/org.talend.designer.codegen/jet_stub/footer_java.skeleton
'Multi thread execution' on the job
https://jira.talendforge.org/browse/TDI-35706
> TDI-35706 : Code generation errors in Talend 5.5/6.1.1 after enabling

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
value is wrong when the project is git remote project
> TUP-3922:TalendDesignerPrefConstants.COMP_DEFAULT_PROJECT_DIR's default

- main/features/org.talend.rcp.branding.tos.test.feature/feature.xml
- main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ws/wsdlutil/ComponentBuilder.java
- pom.xml
- test/plugins/org.talend.designer.webservice.test/.classpath
- test/plugins/org.talend.designer.webservice.test/.project
- test/plugins/org.talend.designer.webservice.test/META-INF/MANIFEST.MF
- test/plugins/org.talend.designer.webservice.test/build.properties
- test/plugins/org.talend.designer.webservice.test/pom.xml
- test/plugins/org.talend.designer.webservice.test/src/org/talend/designer/webservice/test/ComponentBuilderTest.java
1. fix TDI-35536 tWebService - parameters are not seen on output mapping
2. Add junit test for TDI-35536 tWebService - parameters are not seen on output mapping
> Bug fix/tdi 35536 t web service parameters output

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
chars
https://jira.talendforge.org/browse/TUP-4336
> TUP : tFileInputMail issue with attachment filename containing non ASCII

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet
output
https://jira.talendforge.org/browse/TUP-4480
> TUP-4480: fix the javajet for bulkexec and outputbulkexec without any

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewSalesforceMigrationTask.properties
https://jira.talendforge.org/browse/TUP-4480
> TUP-4480: fix the migratask for the table

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
> TESB-17314:NPE error in error log when open a route

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
https://jira.talendforge.org/browse/TUP-4480
> TUP-4480: fix the compile issue for table usage

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/ExportProcessorHelper.java
> TDI-35506:[6.0.1] Studio distant run missing trace information with

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
component(tsalesforcebulkexec)
https://jira.talendforge.org/browse/TUP-4547
> TUP-4547: support reject line for input

- main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/models/BaseModel.java
- main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/models/BundleModel.java
- main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/models/FeatureModel.java
- main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/models/FeaturesModel.java
Please help to check and merge, thanks.
> TESB-17150: Fixed to deploy snapshot version artifact to repository

- main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_messages.properties
- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SetDefaultValueForNewerEmailFirstOfTDI35976.java
https://jira.talendforge.org/browse/TDI-35976
> TDI-35976 : tpop retrieves emails from the oldest time stamp first

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
> TESB-17310:SoapAction is set to empty in Runtime when tEsbConsumer is invoked from a Joblet

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ProcessController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
> TDI-34538:trunjob's "context param" parameter can't be set when use "use

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
> TUP-4563：[TestCase][Di][Spark][SparkStreaming] You cannot open a test

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceVarcharArrayWithVarcharIssueTDI35719.java
Migration task is dedicated to change "['****']" values for ERRORTABLE1, ERRORTABLE2, WORKTABLE attributes to "****". It will be added to 6.2.1. As the fix of the bug was added to 6.2.0, the migrated tasks should be available for import to 6.2.0.
> TDI-35719: added migration task.

- main/plugins/org.talend.designer.core/plugin.xml
> TMDM-9573 : tMDMRestInput & Query Text : context variable or globalmap variable not allowed.

- main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/actions/AbstractPublishJobAction.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java
> TDI-35608:Publish standalone job with compilation error finished

- main/plugins/org.talend.designer.components.localprovider/components/tTeradataTPTExec/tTeradataTPTExec_main.javajet
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceVarcharArrayWithVarcharIssueTDI35719.java
Replaced code for update and load operators as it was the same for both of them. Fixed code for table names - removed adding database name before the table names.
> TDI-35719: fixed code for table names; replaced code for update and load operators.

- main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_main.javajet
Moved values formatting to a method, used this method to apply the same formatting for default values. Changed formatting of byte[] arrays to use FormatterUtils.
> TDI-29308: added formatting for default values.

- main/features/org.talend.rcp.branding.tos.test.feature/feature.xml
For bug : no bean and duplicate job script
> TUP-4797: Add test fragement to test feature

- main/plugins/org.talend.designer.components.localprovider/components/tFilterRow/tFilterRow_main.javajet
Used String.valueOf() to create a valid String after ternary operator expression.
> TDI-35603: fixed creation os String passed to ParserUtils

- main/plugins/org.talend.designer.components.localprovider/components/tAggregateOut/tAggregateOut_begin.javajet
Fix for issue
https://jira.talendforge.org/browse/TUP-3977
> TUP-3977 Changed type of map from HashMap to LinkedHashMap

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
> TDI-35007:positioning of drag and drop objects on designer space in

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/JobSettingsView.java
TUP-4345: can't focus on what you click, and will do refresh
> TUP-4345: can't focus on what you click, and will do refresh

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/NameAndLabelsReferenceController.java
Widget.WidgetType.NAME_SELECTION_REFERENCE
> [TUP-4450] fixed the problem when the component has one more

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
tSAPInfoObjectOutput can't get schema from repository.
> TDI-36473: Drag SAP InfoObject to a job as a component

- main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
We will encrypt only parameters with type "password" from context. Also, if context password parameters are mentioned in "Context param" table in component properties they will also be encrypted for log. But they won't be encrypted for passing to the tRunJob component.
> TDI-35425: Added new List to log context parameters.

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
Talend6IncomingSchemaEnforcer in javajet part
https://jira.talendforge.org/browse/TUP-4570
> TUP-4570: use the DiIncomingSchemaEnforcer instead of

- main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_java.xml
invisible
https://jira.talendforge.org/browse/TDI-35717
> bugfix/6.2/TDI-35717 : tOracleBulkExec's action on table still used when

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet
https://jira.talendforge.org/browse/TDI-36651
> TDI-36651: fix the runtime part for the return property

- main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_main.javajet
https://jira.talendforge.org/browse/TDI-36251
> bugfix/6.2/TDI-36251 : [6.1.1] Vertica components with Vertica 7.1

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
https://jira.talendforge.org/browse/TUP-4910
> TUP-4910: Fixed salesforce extendInsert missing output data

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_finally.javajet
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
https://jira.talendforge.org/browse/TCOMP-219
> TCOMP-219: add the finally part for generic components.

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ComponentListController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java
for Component List and Context Parameter List fields.
> TDI-35251: won't select the first one by default 

- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputPositional/tFileOutputPositional_end.javajet
file" not working with tMap
https://jira.talendforge.org/browse/TDI-35360
> bugfix/6.2/TDI-35360 : tFileOutputPositional + "Don't generate empty

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
https://jira.talendforge.org/browse/TUP-4570
> TUP-4570: fix some i18 issue for the return property

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet
https://jira.talendforge.org/browse/TUP-4570
> TUP-4570: fix the new return property.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/IDbMapDesignerService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionCreateCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
- main/plugins/org.talend.designer.dbmap/plugin.xml
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/command/UpdateELTMapComponentCommand.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/service/DbMapDesignerService.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/command/UpdateELTMapComponentCommandTest.java
> TDI-35297: tELTPostgressqlMap not functioning on other schemas apart

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
checked depends on the commit level
https://jira.talendforge.org/browse/TUP-4943
> TUP-4943: tsalesforceOutput:output is not correct when Extend Insert is

- main/plugins/org.talend.designer.components.localprovider/plugin.xml
Add missing jars for Secure Hbase with Kerberos
> [TBD-3745] Update missing jars for secure Hbase

- main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
component
https://jira.talendforge.org/browse/TDI-35931
> bugfix/6.2/TDI-35931 : Number format with toracleoutputbulkexec

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TDI-36772
> TDI-36772 fix: No response when click restart button when I start studio with cutom workspace

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
TDI-36731: sometimes can't retrieve remote project on login page
> TDI-36731: sometimes can't retrieve remote project on login page

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet
https://jira.talendforge.org/browse/TUP-4964
> TUP-4964: New framework dynamic long to date convert issue

- main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/actions/AbstractPublishJobAction.java
> TDI-36773:Studio always publish latest job version even if you select a

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
dataset
https://jira.talendforge.org/browse/TDI-36822
> TDI-36822: NPE in tDatasetOutput when performing a full run on a live

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
TUP-4998:Git:There is error when logon branch
> TUP-4998:Git:There is error when logon branch

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ProcessController.java
https://jira.talendforge.org/browse/TDI-35811
> TDI-35811 fix: Studio throw NPE error if you delete a job in referrence project and try to open the job by trunjob in main project.

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReviseInvalidContextNamesMigrationTask.java
> TUP-5009: [6.1.1] Export Context on Metadata Hadoop Connection erroneous

- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet
tMSSqlInput_3Process(Map<String,Object>) is exceeding the 65535 bytes
limit
https://jira.talendforge.org/browse/TUP-4925
> bugfix/6.2.2/TUP-4925 : The code of method

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/PasswordController.java
context.password+context.token
https://jira.talendforge.org/browse/TUP-5010
> TUP-5010 fix: Password field show *** when using

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/ImportExportPreferencePage.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizardPage.java
> TUP-4175:Export with dependencies fails to select (and export)

- main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/content/doc/DocumentationContentProvider.java
not show under documentation node.
> TDI-36887:After do view documentation for job, the job/joblet node do

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/ComponentHit.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/TalendEditorPaletteFactoryTest.java
https://jira.talendforge.org/browse/TUP-3675
> Bug fix/6.3.0/tup 3675 components search

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/cmd/QueryGuessCommandTest.java
> TDI-36897:Auto Generated Query isn't correct after Drag teradata schema

- main/plugins/org.talend.designer.core/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/Connection.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateViewerHelper.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/connections/ConnectionTest.java
> TDI-36886: Update a context parameter will make the studio blocked on a

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/SqlMemoController.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/actions/EditQueriesAction.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/actions/ReadQueriesAction.java
https://jira.talendforge.org/browse/TBD-3827
> TBD-3827 fix: Cann't edit query for Impala

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
TDI-27409:Unable to export a job via TIS Studio with statistics enable
> TDI-27409:Unable to export a job via TIS Studio with statistics enable

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateContextParameterCommand.java
> TUP-5136: Importing context group doesn't propagate changes to the jobs

- main/plugins/org.talend.designer.hl7/src/org/talend/designer/hl7/managers/HL7OutputManager.java
Element" for tHL7Output
https://jira.talendforge.org/browse/TDI-37034
> TDI-37034 fix: can't save successfully after set "Set As Repeatable

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
> TUP-5161:Studio connecting to Last Used Remote Connection can cause

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/metadata/DetecteViewImpactAction.java
"detect dependencies" do not work correctly.
> TDI-36036: For columns under schemas, the r-click menu "read schema" and

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/assembly_job_template.xml
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendProcessJavaProject.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java
for review first.
Need to check some other parts first on commandline
> TDI-36930: Improve performances during the build

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java
> TDI-37120: Edit schema which used in job, will hang on "Progress

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractRepositoryController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ControllerRepositoryValueHander.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ValidationRuleTypeController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/DynamicPropertyGenerator.java
the util class to reuse by the compare editor
> TUP-5205: do some refactor to move the display value calculate code to

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-5221
> TUP-5221 fix: shouldn't do update when logon local mode project

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
https://jira.talendforge.org/browse/TDI-37055
> TDI-37055 fix: Job versions do not show in order in the build job page.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java
missing when hbase connection has more schemas
> TBD-3988:Only 612 studio:Drag hbase schema to job, column family is

- main/plugins/org.talend.designer.publish.core/src/org/talend/designer/publish/core/actions/AbstractPublishJobAction.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
> TDI-36420: "apply context to children" doesn't work for the published

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
> TDI-36859: Refresh the forms before any generation to ensure it has the

- main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_begin.javajet
'Newer email first' selected and 'Number of emails to retrieve' equals
the total mail number.
https://jira.talendforge.org/browse/TDI-36790
> bugfix/6.3.1/TDI-36790 : tPOP rise ArrayIndexOutOfBoundsException when

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
the modification from the joblet it generated.
> TUP-5942: Pop up update detection when save job which already propagate

- main/plugins/org.talend.designer.core.generic/plugin.xml
- main/plugins/org.talend.designer.core.generic/src/main/java/messages.properties
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ButtonController.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/JsonTableController.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/generator/JsonTableGenerator.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/ui/JsonFieldModel.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/ui/JsonTableHandler.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/ui/JsonTableVO.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/ui/JsonTableView.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/CheckController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ComboController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/FileController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TextController.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/DynamicComposite.java
- test/plugins/org.talend.designer.core.generic.test/src/main/java/org/talend/designer/core/generic/ui/JsonTableHandlerTest.java
And fix the layout problem of Text, Combo, Checkbox, File, Table
controllers in the wizard at the same time.
> TUP-5252: add JSON_TABLE controller which is a table with json input.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/HadoopJarSetupController.java
cluster
https://jira.talendforge.org/browse/TBD-3987
> TBD-3987 fix: Impala:Cann't check successfully when I use custom hadoop

- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveOutputBulkExec/tSalesforceWaveOutputBulkExec_java.xml
https://jira.talendforge.org/browse/TDI-37028
> TDI-37028 : Upgrade Salesforce API with latest one(should be >=37.0).

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/subjobcontainer/SubjobContainerPart.java
> TUP-15846:Spark streaming joblet:joblet style is not same as it opend in

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
> TUP-541:[Studio] MS SQL Server: Azure SQL (2016) support and 2014

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/IconSelectionController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateCheckResult.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateContentProvider.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateLabelProvider.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateViewerModel.java
> TUP-15844:spark/spark ss: on the recently used palette, icon is not

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java
Add export only default type for TESB-17856
> TESB-17856: ESB Microservice can be exported only with Default context

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/SetupProcessDependenciesRoutinesAction.java
> TUP-15841:Spark/Spark ss joblet:on R-click option don't have setup

- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_main.javajet
Fixed the way we get parameters number to retrieve the value from call result.
> TDI-37285: fixed issues with getting out parameters from result.

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/JsonTableController.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericElementParameter.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/FileController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/MultipleThreadDynamicComposite.java
- main/plugins/org.talend.repository.generic/plugin.xml
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/model/migration/NewDelimitedFileWizardMigrationTask.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/model/migration/NewDelimitedFileWizardMigrationTask.properties
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/DynamicComposite.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizardPage.java
1) Add migration task for old delimited file metadatas;
2) Improve UI.
> TUP-15819: Set the new wizard from the new framework for File Delimited

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
> TUP-15870:NPE shows when drag Big Data schema to Spark/Spark Streaming

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
> TUP-15880: "Guess schema" throwing ClassNotFoundException when

- main/plugins/org.talend.designer.webservice/src/main/java/org/talend/designer/webservice/ws/wsdlutil/ComponentBuilder.java
> TUP-15975:Get NPE when click refresh on tWebService wizard with specific

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/CheckController.java
> TUP-15923:Git merge: parameter "Active" can be edited but can not be

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-15939
> TUP-15939 fix> GIT: Cannot Switch to Offline Mode if tag is selected in Remote Connection list

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet
https://jira.talendforge.org/browse/TDI-37525
> TDI-37525: Add support document type in new framework

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
> TUP-15996:Guess Schema for tJDBCInput/tSAPHanaInput does not work for

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeMappingFileMigrationTask.java
> TUP-15833: [6.2.1] General JDBC metadata connection cannot use SAPHana

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
> TDQ-7446: fix TDQ-7348 pattern list in tMultiPatternCheck show more than

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java
> TUP-16060 fix:!!!SchemaController.schemaOf!!! display on Guess schema

- main/plugins/org.talend.designer.core.generic/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
https://jira.talendforge.org/browse/TDI-37519
> TDI-37519: fix the import

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/DeleteNodeContainerCommand.java
> TUP-16066：when delete a componet for spark job that used joblet, line is

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionReconnectCommand.java
> TUP-16059:tSAPTableInput: Repository schema is changed to built-in when

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-5155
> TUP-5155 fix> GIT: Offline Mode: Logon Branch is always master instead of previous logged branch

- main/plugins/org.talend.designer.components.localprovider/components/tHiveConnection/tHiveConnection_jdbc.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/GetConnection.javajet
> [TBD-3936] : Support new Mapr tickets API

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeMSSQLDBVersionMigrationTask.java
> TUP-16114：MSSQL：value of "JDBC Privoder" not correct after import lower

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
> TUP-15990:FileDelimited:Schema layout shouldn't be in same row of

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importexport/ExportItemWizardPage.java
items, in export page the salesforce connection is not selected.
> TUP-15865：For columns under salesforce schemas, when select to export

- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLBuilderDialog.java
> TUP-16084:need to restart studio if not download the jar when expand

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_finally.javajet
https://jira.talendforge.org/browse/TDI-37658
> TDI-37658: fix the runtime issue

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeMappingFileMigrationTask.java
logon a new created svn project.
> TUP-16135: Have en error about projectname/.setting don't exist when

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
> TUP-5737 fix: improved -- can't re-create the link between tMap after

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
> TUP-16104:[6.2.1] Get error in the tRedshiftInput when Guess Schema

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
in schema of tFileInputExcel when reading .xls (97-2003) format.
https://jira.talendforge.org/browse/TDI-37592
> TDI-37592 : Date Pattern doesn't take effect when set Type as 'Dynamic'

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/MemoController.java
PropertyType is from repository
> TUP-15459 fix: tLDAPInput: Filter is shouldn't be enabled if

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
https://jira.talendforge.org/browse/TUP-7147
> TUP-7147 Fix:[5.6.1] Special characters when used within a component cause job to dont open properly

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
> TUP-5269：All the components use the new framework will lost the value if

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
https://jira.talendforge.org/browse/TUP-16216
> TUP-16216 fix> Git: can't switch to remote mode

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java
https://jira.talendforge.org/browse/TUP-16139
> TUP-16139 Fix: Layout is not proper for tsalesforce component

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/palette/TalendCombinedTemplateCreationEntry.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
be deleted from the referencing project
> TUP-15926：Joblet with the same name as in the referenced project cannot

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/OpenExistVersionProcessWizard.java
> TUP-16215:Can't export dependencies when job version is created by "open

- main/plugins/org.talend.designer.components.localprovider/components/tHttpRequest/tHttpRequest_main.javajet
https://jira.talendforge.org/browse/TDI-37725
> TDI-37725 : tHttpRequest add error massage to global map

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
to stand, name will changed " to _
> TUP-16152：Convert joblet: when schema have ", change it type from spark

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
https://jira.talendforge.org/browse/TDI-37787
I also test Boolean, Boolean_Formula, String_Formula,  Label, error, error_Formula. I think it is unnecessary to add them.
> TDI-37787 : Add code to support Number Formula and Date Formula.

- main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_begin.javajet
https://jira.talendforge.org/browse/TDI-37735
tS3connection will only create the instance of connection object, but won't connect to S3. So tS3connection will always success. So I add this code to connect to S3.
> TDI-37735 : S3 Job throw errors but does complete successfully.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/MainComposite.java
> TUP-16022:job/joblet "description" field should extend to match the "job view" size

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java
<value> of line <#> is not existed in column
https://jira.talendforge.org/browse/TUP-16183
> TUP-16183 Fix: Component tRunJob has warnings of "The context name

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java
https://jira.talendforge.org/browse/TUP-16169
> TUP-16169  Improve: Sometimes cannot run job

- main/plugins/org.talend.designer.xmlmap/src/main/java/org/talend/designer/xmlmap/editor/actions/ImportTreeFromRepository.java
> TUP-16319:tXMLMAp with GIT remote connection : option "import from

- main/plugins/org.talend.designer.components.localprovider/components/tConvertType/tConvertType_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMap/default_auto_convert_function.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMap/tMap_commons.skeleton
https://jira.talendforge.org/browse/TDI-37741
> TDI-37741: Automatic Type Conversion from Object to byte/short/int/long/..... issue

- main/plugins/org.talend.designer.components.localprovider/components/tDB2BulkExec/tDB2BulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Connection/tDB2Connection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Input/tDB2Input_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Row/tDB2Row_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2SCD/tDB2SCD_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2SCDELT/tDB2SCDELT_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tDB2SP/tDB2SP_java.xml
Related to https://jira.talendforge.org/browse/TDI-37694
> fix(TDI-37694): fix maven url for db2jcc4 driver in DB2 components

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/MainComposite.java
by spark job with test case to Spark back.
> TUP-15118：A wrong warning shown when convert MR job which is converted

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/JobSettingsView.java
https://jira.talendforge.org/browse/TUP-5203
> TUP-5203 fix: Can not load job properties when repeat switch from Extra to main in jobsettings.

- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLBuilderDialog.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/util/UIUtils.java
> TUP-16127: no context group selection window pop up when click .. button

- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet
displays the SQLException.getMessage in addition to the java error message
https://jira.talendforge.org/browse/TDI-35416
> TDI-35416: Add getNextException to show more error message

- main/plugins/org.talend.designer.components.localprovider/components/tEXAConnection/tEXAConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAInput/tEXAInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXARow/tEXARow_java.xml
https://jira.talendforge.org/browse/TDI-37116
> TDI-37116 : Upgrade exajdbc-5.0.12.jar to exajdbc-5.0.13.jar

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/Connection.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/connections/ConnectionTest.java
> TUP-16281:Job with tDataprepinput with parallelisation enabled does not

- main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml
https://jira.talendforge.org/browse/TDI-37837
> TDI-37837: ClassNotFoundException: org.springframework.aop.interceptor.AsyncUncaughtExceptionHandler

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/constants/IGenericConstants.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
https://jira.talendforge.org/browse/TDI-37454
> TDI-37454: Upgrade of tSalesforceInput -with Manual input of SOQL query-broken in 6.2.1

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
> TUP-5737 fix: can't re-create the link between tMap after it's deleted

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ColumnListController.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/properties/controllers/ColumnListControllerTest.java
> TUP-5658 fix:Error when run job trowgenerator to tlogrow with check and

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMondrianInput/tMondrianInput_java.xml
Related to https://jira.talendforge.org/browse/TDI-37846
> fix(TDI-37846): upgrade db2 driver for tCreatetable and tMondrianInput

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/dialog/RepositoryReviewDialog.java
https://jira.talendforge.org/browse/TUP-6142
> TUP-6142 fix: main project can add context variable to ref project

- main/plugins/org.talend.designer.components.libs/libs_src/talend-marketo-rest/src/main/java/org/talend/marketo/MarketoRestClient.java
https://jira.talendforge.org/browse/TDI-36713
414 will be returned when the URI of a GET request exceeds 8KiB.  To avoid it, check against the length of your query string to see if it exceeds this limit.
If does it will be divided into smaller requests.
> TDI-36713 : TMarketoInput can not handle large input to match data

- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet
* TDI-35416 : replace the last system.err.print with log4j witch I
forgot.
Conflicts:
main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet
> TDI-37774 : backport to 5.5. Add getNextException to show more error message (#764)

- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet
* TDI-35416 : replace the last system.err.print with log4j witch I forgot.
> TDI-37774 : backport to 6.0. Add getNextException to show more error message (#764)

- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet
* TDI-35416 : replace the last system.err.print with log4j witch I forgot.
> TDI-37774 : backport to 6.1. Add getNextException to show more error message (#764)

- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet
* TDI-35416 : replace the last system.err.print with log4j witch I forgot.
> TDI-37774 : backport to 6.2. Add getNextException to show more error message (#764)

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
This preserves the compatibility to newer Apache-POI releases.
I have tested it with Talend studio release 6.1.1, 6.2.1 and 6.3.0
> Using the correct Workbook methods to iterate over the sheets. 

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-37879
> TDI-37879:tMySqlOutput generates invalid create statement when DOUBLE

- main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
https://jira.talendforge.org/browse/TDI-37934
> TDI-37934: tExtractJSONFIelds: no Getter for field scale in class BigDecimal

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
TUP-16458 projects not retrieved correctly when do refresh on logon window
https://jira.talendforge.org/browse/TUP-16458
> TUP-16458 projects not retrieved correctly when do refresh on logon window

- main/plugins/org.talend.designer.components.localprovider/components/tMDMInput/tMDMInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- Remove StrictAnd and Exactly from predicates list
> TMDM-10262 [tMDMInput] Unsupported predicates found in tMDMInput.

- main/plugins/org.talend.designer.components.localprovider/components/tREST/tREST_begin.javajet
https://jira.talendforge.org/browse/TDI-37949
getEntity Throws: UniformInterfaceException - if the response status is 204 (No Content).
> TDI-37949 : tRest is throwing exception on HTTP response code 204

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/assembly_job_template.xml
- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
Hi,
please help to merge it Talend master. Thank you.
> TDQ-12474 add a profiler "include-survivorship-rules" to export

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/assembly_job_template.xml
- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
Hi,
please help to merge it Talend 6.3.1. Thank you.
> TDQ-12474 add a profiler "include-survivorship-rules" to export survivorship rules. it only execute when the "include-items" not be added.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java
tRuleSurvivorship node when export job.
> TDQ-13026 consider the sub-job and joblet dependecies wherether include

- main/plugins/org.talend.designer.components.localprovider/components/tXSDValidator/tXSDValidator_main.javajet
https://jira.talendforge.org/browse/TDI-37968
> TDI-37968:tXSDValidatoris not containing all the expected fields.

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/oracle/OracleGenerationManagerTest.java
> bugfix recheck: TUP-14431 ELT Map queries : compilation error with

- main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_main.javajet
https://jira.talendforge.org/browse/TDI-38006
> TDI-38006:Global Variable on tFileArchive miss a letter.

- main/plugins/org.talend.designer.codegen/jet_stub/subprocess_footer.javajet
> TESB-17960:Exceptions of DI jobs embedded in service jobs are not logged

- main/features/org.talend.rcp.branding.tos.feature/feature.xml
Reverts Talend/tdi-studio-se#888
> Revert "TMDM-10190: remove mdm webservice ce plugin from feature list."

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
TUP-16553 Logon Project：Focous switch from git project to svn project each time do "refresh" on branch option
https://jira.talendforge.org/browse/TUP-16553
> TUP-16553 Logon Project：Focous switch from git project to svn project each time do "refresh" on branch option

- main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_main.javajet
https://jira.talendforge.org/browse/TDI-38006
> TDI-38006:Batter way to fix it.

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/imports/ImportItemUtil.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeXmiSerialization.java
TUP-14737 too slowly when import items using overwrite to svn/git project
https://jira.talendforge.org/browse/TUP-14737
> TUP-14737 too slowly when import items using overwrite to svn/git project

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
password when logon svn project
> TUP-5760:only password filling window pop up if no svn user name and

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/ComponentSearcher.java
TUP-15678 Job icon and style is displayed as standard when I use find components for Map reduce job components
https://jira.talendforge.org/browse/TUP-15678
> TUP-15678 Job icon and style is displayed as standard when I use find components for Map reduce job components

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
https://jira.talendforge.org/browse/TUP-16616
> TUP-16616 fix: Error "java.util.ConcurrentModificationException" when connecting to studio

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateContextParameterCommand.java
> TUP-16671:AMC database repository connect doesn't grab all context

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/QueryGuessCommand.java
> bug fixed TDQ-12896 support get dbname or schema from exist connection

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/prefs/RunProcessPreferenceInitializer.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/JobVMArgumentsComposite.java
- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ResetVMArgumentMigrationTask.java
- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/ui/JobVMArgumentsCompositeTest.java
escape character works [MacOS]
> TUP-16584：Job run Tab >> Advanced Settings >> Add JVM argument - No

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
> TESB-18147:java.lang.NoSuchMethodError: org.springframework.core.MethodParameter.getContainingClass()

- main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
https://jira.talendforge.org/browse/TDI-38048
> TDI-38048: Add setCharset method.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java
> TUP-16724：Drag joblet to job, there is no corresponding context in job

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/shadow/ShadowProcess.java
> TUP-16746: Excel file metadata : Error "Unable to recognize OLE stream"

- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_main_AXIS.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_main_CXF.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_messages.properties
- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddNewIgnoreNullSettingForTMicrosoftCrmOutputTask.java
* Add "Ignore null" property
* Add ignoring null values code
* Add fix for NPE when set primitive value from null(Online 2011 API)
> fix(TDI-37987): tMicrosoftCrmOutput has NullPointerException

- main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_main.javajet
https://jira.talendforge.org/browse/TDI-37833
> TDI-37833:tEXAOutput component does not support dynamic schema

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/StatusManagerSettingPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/VersionManagementPage.java
Designs" on the left, only show standard job on the right
> TUP-16196:For status management and version management, if check "Job

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/GEFDeleteAction.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/GEFPasteAction.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/MultiplePasteCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/NodesPasteCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletContainerPart.java
joblet component (input/output)
> TUP-16108:joblet in job , not support copy/paste if joblet contain

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/GenericHiddenTextController.java
> TUP-16318:Password field in connection components should not mask global

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
difference found in schema editor
> TUP-17048:Warning about schema attached to tUnite component while no

- CONTRIBUTORS.md
- main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_begin.javajet
https://jira.talendforge.org/browse/TDI-38166
> TDI-38166 : tPOP component throws an exception when deleting emails using imap

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/JobVMArgumentsComposite.java
escape character works [MacOS]
> TUP-16584:Job run Tab >> Advanced Settings >> Add JVM argument - No

- main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
https://jira.talendforge.org/browse/TDI-38154
> TDI-38154:tOracleBulkExec Error in the CTL file generated

- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
https://jira.talendforge.org/browse/TDI-38177
> TDI-38177:tFileDelimitedOutput compile error if split every is empty.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
> TUP-17091：Unexpected Warning with tOracleOutput when Parallel Execution

- main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_main.javajet
https://jira.talendforge.org/browse/TDI-38197
> TDI-38197: Performance issue for tMssqlOutput.

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
Related to https://jira.talendforge.org/browse/TCOMP-230
> feat(TCOMP-230): add flow varibles support

- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.javajet
this is for [https://jira.talendforge.org/browse/TDI-38232 ](https://jira.talendforge.org/browse/TDI-38232 )
> fix(TDI-38232): fix index out of bounds exception in the tfileoutputmsxml

- main/plugins/org.talend.designer.components.localprovider/components/tPivotToColumnsDelimited/tPivotToColumnsDelimited_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPivotToColumnsDelimited/tPivotToColumnsDelimited_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tPivotToColumnsDelimited/tPivotToColumnsDelimited_main.javajet
* Substitute groupKeys List with groupKeys LinkedHashSet
* Add iterators
> fix(TDI-38213): poor performance of tPivotToColumnsDelimited

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/MSCRMClient.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/sdk/OperationProcessor.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/sdk/OperationProcessorsFactory.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/sdk/OrganizationServiceStubWrapper.java
* Add wrapper for OrganizationServiceStub
* Implement automatic token renewal
* Increment talend-mscrm lib version
> feat(TDI-35388): handle ExpiredSecurityTokenException

- main/plugins/org.talend.designer.components.libs/libs_src/tWebServiceInput/org/talend/DynamicInvoker.java
https://jira.talendforge.org/browse/TDI-38212
> TDI-38212:tWebServiceInput returning empty result

- main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-marketo-rest/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-ucanaccess-utils/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talendsap/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/thashfile/pom.xml
> update the pom to adapter the new talend maven nexus repository(or only

- pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [patch/6.0.1s/TPS-1373]

- pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [patch/6.0.1]

- main/plugins/org.talend.designer.components.libs/libs_src/talend-marketo-rest/pom.xml
- pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1_TPS-1357]

- main/plugins/org.talend.designer.components.libs/libs_src/talend-marketo-rest/pom.xml
- pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1]

- main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-marketo-rest/pom.xml
- pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.2]

- main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-marketo-rest/pom.xml
- pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [patch/6.2.1]

- main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-marketo-rest/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/thashfile/pom.xml
- pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [patch/6.3.1]

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/language/java/JavaLanguage.java
- test/plugins/org.talend.designer.mapper.test/src/org/talend/designer/mapper/language/java/JavaLanguageTest.java
> TUP-17185:"Auto-Conversion of Types" does not work with columns in

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/jobletcontainer/JobletUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
> TUP-17201:Upgrade issue with Jobs referencing joblets from a reference

- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.libraries.crm/pom.xml
about jira: https://jira.talendforge.org/browse/TDI-38351
> fix(TDI-38351): fix tMicrosoftInput failing with Timeout

- main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAConnection/tEXAConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAInput/tEXAInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXARow/tEXARow_java.xml
https://jira.talendforge.org/browse/TDI-37831
> TDI-37831:Add Support for ExaSol 6

- main/plugins/org.talend.designer.components.localprovider/components/tContextLoad/tContextLoad_main.javajet
* Before print load-logs to the console component now checks the type
* If type is Password - replace all symbols with '*'
> fix(TDI-38348): Add context variables typechecking before printing

- main/plugins/org.talend.designer.rowgenerator/src/main/java/org/talend/designer/rowgenerator/ui/editor/MetadataTableEditorViewExt.java
- main/plugins/org.talend.designer.xmlmap/src/main/java/org/talend/designer/xmlmap/ui/tabs/table/XmlCellModifier.java
TUP-6549 tFixFlowInput on the Ubuntu job:show an error when I click add button before add schema
https://jira.talendforge.org/browse/TUP-6549
> TUP-6549 tFixFlowInput on the Ubuntu job:show an error when I click add button before add schema

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
make the field visiable when select "builtin"
> TDQ-11688 make pattern-regex visiable when built-in

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
* Update all axis2 lib dependencies in the talend-mscrm/pom.xml
* Set talend-mscrm lib version to 2.0-20170314
> fix(TDI-38351): update talend-mscrm version

- main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAConnection/tEXAConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAInput/tEXAInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tEXARow/tEXARow_java.xml
https://jira.talendforge.org/browse/TDI-38429
> TDI-38429:Correct the wrong jar name.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
Repository pattern type get error dialog, job can not run--on windows
> TDQ-13484 open job with tPatternCheck and tPatternExtract which select

- main/plugins/org.talend.designer.runprocess/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/IESBRunContainerService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessPlugin.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/JobJvmComposite.java
Hello, I have fixed the same with the master TESB-19082 for M2, please merge it.
Regards,
Yi
> TESB-19082: Fixed NPE when create "Target Exec" in Run job view

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ProcessConvertServiceImpl.java
Reverts Talend/tdi-studio-se#1054
> Revert "Bug/tbd 4639 t hive output sp to ss convert"

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/managers/MapperManager.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/utils/MapperHelper.java
- test/plugins/org.talend.designer.mapper.test/src/org/talend/designer/mapper/utils/MapperHelperTest.java
> TUP-17326: fix tMap for bigdata, since it should not be as virtual

- main/plugins/org.talend.designer.components.libs/libs_src/thashfile/org/talend/designer/components/hashfile/common/MapHashFile.java
- main/plugins/org.talend.designer.components.libs/libs_src/thashfile/pom.xml
* Make changes in the thashfile lib
* clearChildCache method in MapHashFile class now delete used keys from keyMap (fix performance leak)
* Fix artifactName, source folder in the pom.xml
> fix(TDI-37068): Increase performance of tHashcomponents

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/RadioController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/AdvancedContextComposite.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/DesignerUtilities.java
Simple re-use the old code to find the related radio buttons to the same
group, and set the value to false. (moved code to util class)
> TUP-17268: fix radio button

- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_main.javajet
https://jira.talendforge.org/browse/TDI-38464
> TDI-38464: handle Error in code generation.

- main/plugins/org.talend.designer.components.localprovider/components/tFileDelete/tFileDelete_main.javajet
* Add throwing RuntimeException for case when deleting wasn't successfull
* Fix log-levels for errors (new level now is "error" instead of "info")
> fix(TDI-38442): tFileDelete doesnt trigger errors (on Component Error/on Subjob error)

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/MSCRMClient.java
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.libraries.crm/pom.xml
* Fix wrong talend-mscrm lib version, it should be 2.1, not 2.0 for tos6.4
> fix(TDI-38351): set correct talend-mscrm version

- main/plugins/org.talend.designer.components.localprovider/components/tELTJDBCOutput/tELTJDBCOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tELTJDBCOutput/tELTJDBCOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForELT.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-38244
> fix(TDI-38244): For Teradata, the create statement is wrong in the tELTJDBCOutput

- main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_messages_en.properties
* Create new checkbox property for tFileCopy component (default value - false)
* Create en message for it
* Change logic for component - it now trows RuntimeException if failOn is enabled
> fix(TDI-38441): add failOn error to tFileCopy

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-38466
> TDI-38466:Problem with writing time field with nulls to Exasol

- main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
* Make the checking for table existing the same as in the tTeradataOutput component
* Remove previous fix
> bug(TDI-38421): Refix

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm-odata/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm-odata/src/main/java/org/talend/mscrm/ClientConfiguration.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm-odata/src/main/java/org/talend/mscrm/ConditionOperator.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm-odata/src/main/java/org/talend/mscrm/DynamicsCRMClient.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm-odata/src/main/java/org/talend/mscrm/LogicalOperator.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm-odata/src/main/java/org/talend/mscrm/QueryFilterUtil.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm-odata/src/main/java/org/talend/mscrm/QueryOptionConfig.java
For feature: https://jira.talendforge.org/browse/TDI-38091
Add the client api source code to build automatically.
- retrieve records for input component
- create/update/delete for output component
Need to review and merge ASAP, So that we can let DEVOPS Team add this jar can be build automatically.
> feat(TDI-38091):add Microsoft CRM online 365/2016  odata client api

- main/plugins/org.talend.designer.components.localprovider/components/tSAPConnection/tSAPConnection_java.xml
https://jira.talendforge.org/browse/TDI-37648
> fix(TDI-37648): add the slf4j dependency

- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveOutputBulkExec/tSalesforceWaveOutputBulkExec_java.xml
For feature: https://jira.talendforge.org/browse/TDI-38098
upgrade Salesforce API from 37 to 39
> fix(TDI-38098): upgrade Salesforce API to 39

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
https://jira.talendforge.org/browse/TDI-38105
> TDI-38105:Update Excel components to support Excel 2016/next version

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-17460
> fix(TUP-17460): can't retrieve projects by default

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TextController.java
load>From Database>Query Condition is red (Value is invalid)
> TUP-17428:File>Edit Project properties>Job Settings>Implicit Context

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddApiModeToMarketoComponentsMigrationTask.java
If OK, should be merged to
* maintenance/6.1
* maintenance/6.2
* maintenance/6.3
> feature(TDI-38596): Add API properties to Marketo jobs created pre 6.1

- main/plugins/org.talend.designer.runprocess/schema/runprocess_manager.exsd
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/IESBRunContainerService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessPlugin.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/jmx/JMXPerformanceChangeListener.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/jmx/JMXRunStatManager.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/TargetExecComposite.java
Hi, please review my PR, this change will only impact route running in ESB runtime server, 
thanks,
> TESB-19257: Add JMX listener and add to run process context

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/ExportModelJavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/ExportProcessorHelper.java
TUP-17412 Remote Runs from Studio Display Project Setting Log4jLevel
https://jira.talendforge.org/browse/TUP-17412
> TUP-17412 Remote Runs from Studio Display Project Setting Log4jLevel

- main/plugins/org.talend.libraries.jboss/META-INF/MANIFEST.MF
> TDQ-13464: fix running the match analysis with "Store on disk" option

- main/plugins/org.talend.designer.core.generic/plugin.xml
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewComponentFrameworkMigrationTask.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewNetsuiteMigrationTask.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewNetsuiteMigrationTask.properties
* Refactored NewComponentMigrationTask to facilitate processing of element params
* Implemented migration task for NetSuite components
> fix(TDI-38345): Implement migration task for NetSuite components

- main/features/org.talend.tos.libraries.feature/feature.xml
Reverts Talend/tdi-studio-se#1168
> Revert "TDQ-13464:rename org.talend.libraries.persist.lookup"

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/ComponentSettingsView.java
> TUP-17454:Generation Error When using tFileInputPositional with Reject

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
https://jira.talendforge.org/browse/TUP-17396
> bug(TUP-17396): saved job changes are lost when studio crashes

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewMarketoMigrationTask.java
https://jira.talendforge.org/browse/TDI-38653
Corrects typo in tMarketoInput's operation since 563.
> Correct typo in tMarketoInput's operation since 563

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml
- main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-37924
> TDI-37924:revert the commit of change localprovider pom.

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/managers/MapperSettingsManager.java
*add a if judge in initCurrentModel() method
https://jira.talendforge.org/browse/TUP-17050
> bugfix(TUP-17050):tmap looses setting for Die on error

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
Hi, I fix a blueprint template loading issue for ESB runtime server feature.
> TESB-19405: Fixed to load blueprint template for local runtime server

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
> fix(TUP-17538):"The connected components in a job must not form a closed

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-38627
> TDI-38627:NUMERIC format problem on tAS400Output

- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.libraries.crm/pom.xml
For https://jira.talendforge.org/browse/TDI-38625
> fix(TDI-38625):update tMicrosoftCRM odata client api version

- main/plugins/org.talend.designer.components.libs/libs_src/talend-mscrm/src/main/java/org/talend/ms/crm/odata/DynamicsCRMClient.java
* Fix the connection release before the error exception is handled.
> fix(TDI-38625): fix tMicrosoftCRMOutput handle exception issue

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/jmx/JMXRunStatManager.java
Hello, please merge this PR for ESB artifact running information display issue, thanks.
> TESB-19381: Fixed JMX connection number calculate problem

- main/plugins/org.talend.designer.mapper/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.mapper/model/mapper.ecore
- main/plugins/org.talend.designer.mapper/model/mapper.genmodel
- main/plugins/org.talend.designer.mapper/plugin.xml
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponent.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/MapperComponentDocumentation.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/external/converter/ExternalDataConverter.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/external/data/ExternalMapperTable.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/emf/mapper/AbstractInOutTable.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/emf/mapper/MapperPackage.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/emf/mapper/impl/AbstractInOutTableImpl.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/emf/mapper/impl/MapperFactoryImpl.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/emf/mapper/impl/MapperPackageImpl.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/emf/mapper/util/MapperResourceFactoryImpl.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/table/AbstractInOutTable.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/utils/MapperHelper.java
Need take care of the class MapperResourceFactoryImpl.java , not sure why remove all the resource default options by emf generated.
> TUP-17465:tMap filter : enable status not save after reopen map editor.

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
Avoid remote resolution when resolve needed jars for the components of the new framework
> fix(TUP-17521): avoid maven remote resolve

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/jmx/JMXRunStatManager.java
Hi, please review this PR for fixing a ESB runtime log and connection number display issue.
Thanks,
Yi
> TESB-19437: ESB Studio with local runtime does not show logs

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetSparkDataframeAlphabeticalSortOrder.java
Add Spark Dataframe column order migration job
> TBD-4486 : Add Spark Dataframe column order migration job

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetSparkDataframeAlphabeticalSortOrder.java
Add Spark Dataframe column order migration job
> TBD-4486 : Add Spark Dataframe column order migration job - maintenance/6.1

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetSparkDataframeAlphabeticalSortOrder.java
Add Spark Dataframe column order migration job
> TBD-4486 : Add Spark Dataframe column order migration job - maintenance/6.2

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/SetSparkDataframeAlphabeticalSortOrder.java
Add Spark Dataframe column order migration job
> TBD-4486 : Add Spark Dataframe column order migration job - maintenance/6.3 

- main/plugins/org.talend.designer.business.diagram/src/org/talend/designer/business/model/business/diagram/part/BusinessDiagramEditor.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/StandAloneTalendJavaEditor.java
Create a Routine(Sql Template,Pig UDF,bean, business models) can't show
the version at the editor title
https://jira.talendforge.org/browse/TUP-17209
> (bugfix)TUP-17209

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java
build, green progress bar does not change
> TUP-5694:In Studio 6.1.1 when you right click on a job and click on

- main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_messages.properties
* return FailOn property name which was deleted by babili
> bug(TDI-38441): Add missing property name

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateJobletNodeCommand.java
> fix(TUP-17600):Label on lookup from joblet to another joblet is removed

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/OpentRunJobComponentAction.java
Component" of a Spark subjob in a standard job
> TUP-17011:Some components are missing when context click "Open tRunJob

- main/plugins/org.talend.presentation.onboarding.resource.tos/resources/onboarding.json
*change page size to fit all resolution for Windows
*Its about resolution, not Windows version
https://jira.talendforge.org/browse/TUP-17621
> fix(TUP-17621):Studio quick tour page size problem

- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_begin.javajet
For https://jira.talendforge.org/browse/TDI-36331
Avoid password code generated when the parameter is hidden.
> fix(TDI-36331):avoid password code generate when parameter is hidden in twebservice

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewMarketoMigrationTask.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewMarketoMigrationTask.properties
For https://jira.talendforge.org/browse/TDI-38770.
> fixed migration for tMarketoListOperation connectors

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/internal/service/GenericWizardInternalService.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/AbstractBuildJobHandler.java
- test/plugins/org.talend.repository.test/src/org/talend/repository/handler/BuildJobHandlerTest.java
* disable the junits for maven build
* enhance the generic type
* fix the problem for BuildHandler
* add maven debug parameter
> test(TUP-17687): enhance the junits

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
> fix(TUP-17586):Warning message when use joblet in a job as a lookup to a

- main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSAPConnection/tSAPConnection_java.xml
For https://jira.talendforge.org/browse/TDI-38749
I found the dependency `slf4j` have been update to `1.7.13`
Because of out update site don't have this version.
So I use a newer one `slf4j-api-1.7.16`
> fix(TDI-38749):AMQ 5.14.5 Upgrade for tMOM, SAP RFC server

- main/plugins/org.talend.designer.components.localprovider/components/tFirebirdOutput/tFirebirdOutput_begin.javajet
For https://jira.talendforge.org/browse/TDI-33784
When firebird db jdbc connection set autocommit, then should not call commit() manually.
So this modification avoid call commit()
> fix(TDI-33784):tFirebirdOutput can't create table with use an exist connection when tFirebirdConnection check Auto commit

- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDataprocManage/tGoogleDataprocManage_java.xml
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/AbstractJobSettingsPage.java
fix(TUP-17642):6.3.1 studio takes about 25 mins to update project settings for about 200 jobs in the GIT project.
https://jira.talendforge.org/browse/TUP-17642
> fix(TUP-17642):6.3.1 studio takes about 25 mins to update project

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/DesignerCoreUIService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/AbstractProcessProvider.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
Streaming job which are both converted from Spark job for the first time
> fix(TUP-17591)：Cannot drag the Spark Streaming joblet to the Spark

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/external/data/ExternalDbMapTable.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/external/data/ExternalMapperTable.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/model/emf/mapper/impl/AbstractDataMapTableImpl.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/external/data/ExternalDbMapDataTest.java
- test/plugins/org.talend.designer.mapper.test/src/org/talend/designer/mapper/external/data/ExternalMapperDataTest.java
> fix(TUP-17556):Changes to a tmap in an expanded joblet from a job does

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/handler/IContextHandler.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/DynamicComposite.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizard.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizardPage.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/common/GenericWizardPage.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/context/handler/GenericContextHandler.java
Setup again the listener in the dynamic composite, when the component is
setup from the wizard.
> fix(TUP-17365): fix refresh status of name

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java
"ITEM" of a "TABLE" parameeter
> fix（TUP-17508）：SHOW_IF/NOT_SHOW_IF can't work as expect when use it in

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
> fix(TUP-17889):Snowflake Component-JsonParseException: Unexpected

- main/plugins/org.talend.designer.runprocess/src/main/java/messages.properties
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
This reverts commit db90f45ce1739e146f522e0919954783f2f09154.
> Revert "fix(TUP-17863):Use routine in job, could build job successfully even (#1298)"

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
https://jira.talendforge.org/browse/TUP-17720
> fix(TUP-17720)useless component should not visible in studio palette

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
TESB-19575 Configuration file with OIDC configuration is copied to classpath before Job/Route execution with tREST/tRESTClient/cREST in Studio.
> TESB-19575 Dynamic update of OIDC configuration for Studio is added

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
> TDQ-13685-tMultiPatternCheck: fix but about refresh when deleted

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
fix(TUP-17707): an error happened during login in Talend-Studio-20170510_1410-V6.4.0EP
https://jira.talendforge.org/browse/TUP-17707
> fix(TUP-17707): an error happened during login in Talend-Studio-20170510_1410-V6.4.0EP

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
> TESB-19643:RouteBuilder - cConfig Install button active and creation of 6.0.0-SNAPSHOT Versions

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/DesignerCoreService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
> fix(TUP-17890):tRunJob takes 1 minute to display the component tab

- main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/HTMLDocGenerator.java
- main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/wizards/GenerateDocAsHTMLWizardPage.java
> fix(TUP-17900):"Export all projects documentation" does not create the

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
fix(TUP-17766): unable to rollback git version with routine dependencies setting
https://jira.talendforge.org/browse/TUP-17766
> fix(TUP-17766): unable to rollback git version with routine dependencies setting

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TableController.java
> TESB-19538:Fail to add Dependencies in "Bundle ClassPath" for cConfig component

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/PropertyTypeController.java
build-in mode dialog select "ok", Regex Pattern field can not show.
> TDQ-13705 run tPatternCheck/tPatternExtract job, on pop up change to

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/jobsettings/tabs/DeploymentComposite.java
Hi, I'm wokring with @zwxue to add a fix only for ESB data service job, I disabled the deployment tab settings for this kind of job because this job only can be publish with the linked services. PLease help to merge if it's OK.
Yi
> TESB-19577: Disable the deployment tab for SOAP data service type job

- main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_messages.properties
For https://jira.talendforge.org/browse/TDI-38854
Change "Max number of message to return (from 1 to 10)"  to "Max number of message to return **per request** (from 1 to 10)"
> chore(TDI-38854):tSQSInput parameter rename

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveConnection/tGoogleDriveConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveCopy/tGoogleDriveCopy_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveCreate/tGoogleDriveCreate_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveDelete/tGoogleDriveDelete_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveGet/tGoogleDriveGet_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveList/tGoogleDriveList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDrivePut/tGoogleDrivePut_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tHiveIn/tHiveIn_main.javajet
https://jira.talendforge.org/browse/TDI-38110
> feat(TDI-38110):eliminate the job name and job version.

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/assist/TalendEditorComponentCreationUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendDndHelper.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ValidationRulesUtil.java
- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/dnd/GenericDragAndDropHandler.java
- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/dnd/JSONDragAndDropHandler.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddFamilyFieldProjectMigrationTask.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeComponentSettingNameMigrationTask.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/palettesettings/PaletteItemHelper.java
- test/plugins/org.talend.designer.components.localprovider.test/src/main/java/org/talend/designer/components/localprovider/test/TestComponentsAction.java
fix(TUP-17983): random issue when logon remote project error pop up
https://jira.talendforge.org/browse/TUP-17983
> fix(TUP-17983): random issue when logon remote project error pop up

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/wizards/JSONFileStep1Form.java
fix(TUP-18012): ui problem for json wizard
https://jira.talendforge.org/browse/TUP-18012
> fix(TUP-18012): ui problem for json wizard

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/dialog/PropertySetDialog.java
https://jira.talendforge.org/browse/TUP-17971
> fix(TUP-17971)tMap Temp data directory path get doublequote for Contexts

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UnifyPasswordEncryption4ContextMigrationTask.java
> fix(TUP-18017)：Password not encrypt after import a context contain

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
fix(TUP-5461):AmazonAurora components can't select existing connection from joblet
https://jira.talendforge.org/browse/TUP-5461
> fix(TUP-5461):AmazonAurora components can't select existing connection

- main/plugins/org.talend.designer.alfrescooutput/src/main/java/org/talend/designer/alfrescooutput/AlfrescoOutputManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/ConnectionCreateAction.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableByRowEditorView.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/macrowidgets/tableeditor/PropertiesTableEditorView.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateJobletNodeCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateNodeParameterCommand.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/DesignerMapperService.java
TUP-17701 Can't setup / reopen tMap if component is not existing (D&D tmap from palette to Job)
https://jira.talendforge.org/browse/TUP-17701
> TUP-17701 Can't setup / reopen tMap if component is not existing (D&D tmap from palette to Job)

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/action/JobExportAction.java
> fix(TUP-18025)：Misleading Task Publisher Status when Job has compilation

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
fix(TUP-18027): can't get git project branch with "listProject -b" command
https://jira.talendforge.org/browse/TUP-18027
> fix(TUP-18027): can't get git project branch with "listProject -b" command

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewNetsuiteMigrationTask.java
* Fixed migration of search conditions
JIRA issue: https://jira.talendforge.org/browse/TDI-38997
> fix(TDI-38997): Fix migration of search conditions.

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericElementParameter.java
fix(TUP-16516): after change context group under repository re-import the whole project again will get error
https://jira.talendforge.org/browse/TUP-16516
> fix(TUP-16516): after change context group under repository re-import the whole project again will get error

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
For https://jira.talendforge.org/browse/TDI-38772
Upgrade CXF from 3.1.4 to 3.1.11 for
tWebService
tMicrosoftCrmXX
tMDMXX
And add dependency jars to talend update for download.
> feat(TDI-38772): Upgrade to CXF 3.1.11

- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHConnection/tSQLDWHConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHInput/tSQLDWHInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHOutput/tSQLDWHOutput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHRow/tSQLDWHRow_begin.javajet
For https://jira.talendforge.org/browse/TDI-38890
1) Replace `appName` with `applicationName` and set the value to `Talend`
2) Replace `<%@ include file="../templates/tMSSql/_tMSSqlConnection.javajet"%>` with it's content to separator it with tMSSQLXXX components
> feat(TDI-38890):Add parameter "applicationName=Talend;" for tSQLDWHXXX components

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_messages.properties
https://jira.talendforge.org/browse/TDI-32344
> fix(TDI-32344):add the missing name.

- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
https://jira.talendforge.org/browse/TDI-32438
> fix(TDI-32438):add verification to the current_path in tFTPfileList.

- main/plugins/org.talend.designer.components.localprovider/components/tReplaceList/tReplaceList_main.javajet
Correct component's behavior with empty cells 
(String.valueOf(null) return "null", and it cause problems when using tReplaceList)
> fix(TDI-38143): Process null data in tReplaceList correctly

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
NullPointerException occured when the component's flow connector is not shown.
Avoid nullPointerException when the component's flow connector is not shown.
> fix(TBD-4990): Avoid NullPointerException when the component's flow connector is not shown

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
Bugfix of TBD-5111 for maintenance/6.3 branch
> TBD-5111/6.3

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/composites/MissingSettingsMultiThreadDynamicComposite.java
> fix(TUP-17731):UI issue after MySQL jar has been installed via "Install

- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/hive/HiveGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java
fix(TUP-17996):When Deploying one customer's job in CI, the build failed with error: constant string too long
https://jira.talendforge.org/browse/TUP-17996
> fix(TUP-17996):When Deploying one customer's job in CI, the build failed with error: constant string too long

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
> fix(TUP-17916):Improve propagation behavior when multiple output schemas

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/process/ProcessTest.java
> fix(TUP-17540):Campaign label value is lost after reopenning job when it

- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-31454
> fix(TDI-31454):eliminate useless code in MSSQLManager

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/views/properties/MultipleThreadDynamicComposite.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/AdvanceSettingComposite.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
*add scroll bar for Spark Configuration, Advanced Setting, Basic Run
view
https://jira.talendforge.org/browse/TUP-17832
> fix(TUP-17832)Spark Configuration UI not good for smaller screens

- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
Related to https://jira.talendforge.org/browse/TDI-37213
> chore(TDI-37213): bump version to 0.17.0

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/action/OpenJobAction.java
https://jira.talendforge.org/browse/TUP-4739
> fix(TUP-4739)No search in Routes

- main/plugins/org.talend.designer.components.localprovider/components/tReplaceList/tReplaceList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tReplaceList/tReplaceList_main.javajet
https://jira.talendforge.org/browse/TDI-39037
> fix(TDI-39037):Handle NPE for tReplaceList.

- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
https://jira.talendforge.org/browse/TDI-30685
> fix(TDI-30685):eliminate duplicate log.

- main/plugins/org.talend.designer.components.localprovider/components/tFirebirdOutput/tFirebirdOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tIngresOutput/tIngresOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tInterbaseOutput/tInterbaseOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tParAccelOutput/tParAccelOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQLiteOutput/tSQLiteOutput_java.xml
https://jira.talendforge.org/browse/TDI-33531
> fix(TDI-33531):hide batch size when update or insert.

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java
https://jira.talendforge.org/browse/TUP-17755
> fix(TUP-17755)Hover text for column filter icon make no sense in tMap

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlInput/tAmazonMysqlInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCInput/tJDBCInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMysqlInput/tMysqlInput_begin.javajet
https://jira.talendforge.org/browse/TDI-39098
> TDI-39098:handle ClassCastException and remove useless code.

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/xpath.javajet
https://jira.talendforge.org/browse/TDI-34905
> fix(TDI-34905):add stream support for tFileinputJason JSONpath

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/cmd/UpdateNodeParameterCommand.java
show the job name of tMultiPatternCheck as others --fixed
> TDQ-13899 when save pattern, on the "Update Detection" dialog can not

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet
- main/plugins/org.talend.libraries.custom/pom.xml
Related to https://jira.talendforge.org/browse/TDI-37213
Depends on https://github.com/Talend/tdi-studio-se/pull/1447
> igonchar/tdi 37213 call codegen-utils library in codegen instead of calling daikon

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/DesignerCoreService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PerformancePreferencePage.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
fix(TUP-18152): when the first time create tag,always met the issue "connect server timeout"
https://jira.talendforge.org/browse/TUP-18152
> fix(TUP-18152): when the first time create tag,always met the issue "connect server timeout"

- main/plugins/org.talend.repository.json/src/org/talend/repository/json/node/JSONRepositoryContentHandler.java
fix(TUP-18184):Read schema on JSON Metadata throw NPE
https://jira.talendforge.org/browse/TUP-18184
> fix(TUP-18184):Read schema on JSON Metadata throw NPE

- main/plugins/org.talend.designer.runtime.visualization.tools/src/org/talend/designer/runtime/visualization/internal/tools/ToolsPreferencePage.java
fix(TUP-18199)The tools preference page can't work well on mac OS.
https://jira.talendforge.org/browse/TUP-18199
> fix(TUP-18199)The tools preference page can't work well on mac OS.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/ReconcilerViewer.java
fix(TUP-18210):Inconsistencies of keyboard shortcut commands in Talend
https://jira.talendforge.org/browse/TUP-18210
> Kjwang/fix(tup 18210)inconsistencies of keyboard shortcut commands in talend studio on mac os

- main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
https://jira.talendforge.org/browse/TDI-39135
> fix(TDI-39135):Handle duplicate variable in tOracleBlukOutput.

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet
https://jira.talendforge.org/browse/TDI-34905
When jasonPath without loop and use url was selected , thers's a compile error.
> fix(TDI-34905):fix the compile error.

- main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
Add ?w=1 to URL line to see changes without white-spaces.
> fix(TDI-35112): Add supporting MySQL YEAR(4) type in tMysqlOutput

- main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
> fix(TUP-18217):Testcase for tWriteJSONFiled gives junitGlobalMap cannot

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet
https://jira.talendforge.org/browse/TDI-34905
> fix(TDI-34905):tackle stupid mistake.

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/constants/IGenericConstants.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
https://jira.talendforge.org/browse/TUP-18087
> fix(TUP-18087)The visibility of Property Type of tNetsuiteInput/Output

- main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
- main/plugins/org.talend.libraries.excel/.classpath
- main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
- main/plugins/org.talend.libraries.excel/lib/.gitignore
- main/plugins/org.talend.libraries.excel/pom.xml
For jira: https://jira.talendforge.org/browse/TDI-39079
- Issue:
When tFileInput excel use event mode to read an excel which created by tFileOutputExcel.
If the created excel only have one sheet and you fill position to **1** (max position is **0**)
This should throw an error to notice that the position is out of range.
Fixed the issue to check position works.
> fix(TDI-39174):tFileInputExcel can't check sheet position in some situation.

- main/plugins/org.talend.designer.components.localprovider/components/tMysqlSCD/tMysqlSCD_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/slowly_change_dimension.skeleton
https://jira.talendforge.org/browse/TDI-38127
> fix(TDI-38127):SCD components type0 cannot work with other type

- main/plugins/org.talend.designer.components.localprovider/components/tMysqlInput/tMysqlInput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/AbstractDBInputBegin.javajet
* Move calling generateYearResultSet method from abstract javajet to mysql one
* Fix problems which were caused by PR https://github.com/Talend/tdi-studio-se/pull/1529
> fix(TDI-39175): Revert unsafe changes, move it into mysql component

- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputLDIF/tFileOutputLDIF_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputLDIF/tFileOutputLDIF_main.javajet
* Fixed handling of base64 encoded LDIF entries
JIRA: https://jira.talendforge.org/browse/TDI-37942
> fix(TDI-37942): Fix handling of base64 encoded LDIF entry

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateDetectionDialog.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/update/UpdateManagerUtils.java
> fix(TUP-18270):Propogation problems when change contexts in a joblet

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/dialog/RepositoryReviewDialog.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/processor/MultiTypesProcessor.java
https://jira.talendforge.org/browse/TUP-17378
> fix(TUP-17378)Should not show CDH 5.8 Spark 2 distribution in MR job

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_java.xml
stream input
https://jira.talendforge.org/browse/TDI-38195
> fix(TDI-38195):make footer invisible and throw an exception for the

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/dialog/RepositoryReviewDialog.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/processor/MultiTypesProcessor.java
Reverts Talend/tdi-studio-se#1545
> Revert "fix(TUP-17378)Should not show CDH 5.8 Spark 2 distribution in MR job"

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/GenericHiddenTextController.java
call the variable when enter password
> fix(TUP-4834):New framework components can't use keyboard shortcuts to

- main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWriteJSONFieldIn/tWriteJSONFieldIn_main.javajet
https://jira.talendforge.org/browse/TDI-38923
Change library for parsing json from xml.
Now it uses [org.json](https://github.com/stleary/JSON-java).
> fix(TDI-38923): change library for generating json from xml

- main/plugins/org.talend.repository/resources/job-rest-template.xml
> TESB-19960:ESB Infrastrcuture Service - Spring-dm replacement

- main/plugins/org.talend.designer.components.localprovider/components/templates/slowly_change_dimension.skeleton
https://jira.talendforge.org/browse/TDI-38127
> fix(TDI-38127):amend type0 on memory save mode.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
move component to expanded joblet
> fix(TUP-17937):Joblet: Joblets category will disappear in palette when

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UpdateParameterUtils.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/UpdateParameterUtilsTest.java
fix(TUP-17627): can't data viewer for HDFS schema when HDFS is HA
https://jira.talendforge.org/browse/TUP-17627
> fix(TUP-17627): can't data viewer for HDFS schema when HDFS is HA

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
* Improved handling of value parsing related errors
JIRA: https://jira.talendforge.org/browse/TDI-37182
> fix(TDI-37182): Improve handling of parsing related errors.

- main/plugins/org.talend.designer.components.localprovider/components/tXMLMap/tXMLMap_lookup.inc.javajet
* Fixed lookup in tXMLMap when lookup source is document
JIRA issue: https://jira.talendforge.org/browse/TDI-39229
> fix(TDI-39229): Fix lookup in tXMLMap when lookup source is document.

- main/plugins/org.talend.designer.rowgenerator/src/main/java/org/talend/designer/rowgenerator/ui/editor/MetadataTableEditorViewExt.java
https://jira.talendforge.org/browse/TUP-18325
> fix(TUP-18325)Interface of Row line component display deformation

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
tsalesforceinput when select a repository salesforce which convert to
context will show pop up error.
> fix(TUP-5432):Component Framework :Salesforce: For component

- main/plugins/org.talend.designer.components.localprovider/components/tXMLMap/tXMLMap_lookup.inc.javajet
Back-port TDI-39229 to 6.3
See: https://jira.talendforge.org/browse/TDI-39229
> fix(TDI-39301): Back-port TDI-39229 to 6.3

- main/plugins/org.talend.designer.components.localprovider/components/tXMLMap/tXMLMap_lookup.inc.javajet
Back-port TDI-39229 to 6.4
See: https://jira.talendforge.org/browse/TDI-39229
> fix(TDI-39301): Back-port TDI-39229 to 6.4

- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveList/tGoogleDriveList_begin.javajet
* Add a parenthesis in generated code
> fix(TDI-39105) : Fix after QA message

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
* Add definition registry injection to post-deserialization process
> feat(TDKN-127): add searchable definitions

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
- main/plugins/org.talend.repository/resources/job-rest-template.xml
- main/plugins/org.talend.repository/resources/job-template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
> TESB-20243: SAM Custom properties not work for tRESTClient component

- main/plugins/org.talend.designer.components.localprovider/components/tXMLMap/tXMLMap_lookup.inc.javajet
Reverts Talend/tdi-studio-se#1584
> Revert "fix(TDI-39301): Back-port TDI-39229 to 6.3"

- main/plugins/org.talend.designer.components.localprovider/components/tXMLMap/tXMLMap_lookup.inc.javajet
Reverts Talend/tdi-studio-se#1585
> Revert "fix(TDI-39301): Back-port TDI-39229 to 6.4"

- main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jDBConnUtil.javajet
… connection for tHiveInput - fixed (#1540)
> fix(TBD-4416): backport into maintenance/6.4

- main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/ui/FOXUI.java
*add colors for table since mac does not support row separater line
*adjust "y" coordinate of end point of line on mac
https://jira.talendforge.org/browse/TUP-18404
> fix(TUP-18404)Link Target Issue

- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/MDM/TimeoutUtil.javajet
Move MDM#getWSClientTimeout to TimeoutUtil.javajet to avoid depending on routines.MDM
> TMDM-9923 Ability to control the timeout or start/end date of the transaction in MDM components (remove dependency of routines.MDM)

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_begin.javajet
Backport TMDM-11214
See: https://github.com/Talend/tdi-studio-se/pull/1577
> TMDM-11385	[tMDMConnection] "OnComponentError" and "On SubjobError" not triggered when an error occurs

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_begin.javajet
For https://jira.talendforge.org/browse/TDI-39350
- fix performance issue which caused by TDI-27307
> fix(TDI-39350): Performance decline for tFileInputXML compared to 5.3.1

- main/plugins/org.talend.designer.components.localprovider/components/tELTJDBCMap/tELTJDBCMap_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tELTJDBCOutput/tELTJDBCOutput_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
For https://jira.talendforge.org/browse/TDI-39289
- Support tELTJDBCMap can use connection from tSnowflakeConnection component
- Make table action work in tELTJDBCOutput for snowflake.
> fix(TDI-39289) : support tSnowflakeConnection in ELTJDBC

- main/plugins/org.talend.designer.components.localprovider/components/tOracleInput/tOracleInput_java.xml
https://jira.talendforge.org/browse/TDI-39376
> fix(TDI-39376):Import the jar to eliminate compile error.

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java
- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/OutputDataMapTableView.java
https://jira.talendforge.org/browse/TUP-17199
> fix(TUP-17199)tMap Column name filter always can't save modification

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/ConfigureConnParamDialog.java
left empty in tverticaconnection
> feat(TUP-18510):Guess schema doesn't work in tverticaInput if schema is

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
https://jira.talendforge.org/browse/TDI-39432
> fix(TDI-39432):Correct the wrong mvn path.

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
https://jira.talendforge.org/browse/TDI-39423
> fix(TDI-39423):Amend the escape method.

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/ModuleListController.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/uidialog/InstallModuleDialog.java
> fix(TUP-18489):tLibraryLoad doesn't display the jars available in local

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/extrachecker/AbstractJobNodeChecker.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/extrachecker/LimitRESTRequestJobChecker.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManagerFactory.java
> TESB-20333:Data Services (REST) as Microservice

- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_end.javajet
For issue:
https://jira.talendforge.org/browse/TDI-39333
Reduce the log level when local file not generated or no content.
> fix(TDI-39333):tRedshiftOutputBulk log issue

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
https://jira.talendforge.org/browse/TUP-18466
fix a bug when managing connection in login dialog
> fix(TUP-18466): complete URL Pop-up with LDAP SSH Git Authentication

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
Fixed export microservice option
> TESB-20466: Fixed export microservice as Zip option

- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/tJDBCSCDELT_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tJDBCSCDELT/vertica.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
https://jira.talendforge.org/browse/TDI-39477?focusedCommentId=505589
> Pyzhou/tdi 39527 implement t jdbcscdelt with vertica 7.1

- main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
- main/plugins/org.talend.libraries.excel/pom.xml
For issue: https://jira.talendforge.org/browse/TDI-39562
Fix issue:
When append sheet row content is empty(no style also)
This kind of excel would show the default row height in excel tools.
After write with our component the excel tools would can't show default row height.
Even we set "keep cell format"
> fix(TDI-39562):tFileOutputExcel "Keep existing cell format" doesn't work in some situation

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
> TESB-20466:Data Services (REST) as Microservice - Part II

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/EInternalTemplate.java
Hi, I added a new template type for microservice.
Thanks,
Yi
> TESB-20466: Add micorservice launcher template name

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
Revert Talend/tdi-studio-se#1667
https://jira.talendforge.org/browse/TDI-39423
> Revert "fix(TDI-39423):Amend the escape method."

- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java
* When component has avro byte with Object class flag - enforcer will propagate data further
> feat(TDI-39466): Process marklogicOutput Objects

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewMarketoMigrationTask.java
https://jira.talendforge.org/browse/TDI-39319
> fix(TDI-39319): correct include/exclude types in REST API

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManager.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/JobScriptsManagerFactory.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptMicroServiceForESBManager.java
> TESB-20462:tRestRequest job is built to microservice with unexpected suffix when select lastest version

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/xpath.javajet
https://jira.talendforge.org/browse/TDI-39641
> Pyzhou/tdi 39641 backport tdi 34905 to 6.5

- main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_begin.javajet
https://jira.talendforge.org/browse/TDI-37322
> fix(TDI-37322):tFileInputXML incorrectly counts NB_LINE value.

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
* TDQ-14308 include some drools file for tRulesurvivorhsip.
* TDQ-14308 move the code of copy drools file to 'ProcesssorUtilites.java'
> TDQ-14308 include some drools file for tRulesurvivorhsip. (#1638)

- main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tHiveRow/tHiveRow_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/AbstractDBInputBegin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/SetQueryName.javajet
TBD Cherry-picks for 6.5 release
* feat(TBD-4197): set hive job name for tracking
> chore(TBD-5936): TBD 6.5 cherry-picks

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
Please check my fix for TESB-20767.
> TESB-20767: Fixed microservice should not be display with TDI license

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/assist/TalendEditorComponentCreationAssist.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/assist/TalendEditorComponentProposalProvider.java
fix(TUP-18018):Can put the joblet exclusive component to job
https://jira.talendforge.org/browse/TUP-18018
> fix(TUP-18018):Can put the joblet exclusive component to job

- main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
- main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
- main/plugins/org.talend.libraries.excel/.classpath
- main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
- main/plugins/org.talend.libraries.excel/lib/.gitignore
- main/plugins/org.talend.libraries.excel/pom.xml
https://jira.talendforge.org/browse/TDI-39190
> fix(TDI-39190):Sheet name is not case sensitive.

- main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_begin.javajet
https://jira.talendforge.org/browse/TDI-34625
> fix(TDI-34625):restore the origin behavior.

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewSalesforceMigrationTask.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/Salesforce620Migration.java
https://jira.talendforge.org/browse/TDI-39711
> fix(TDI-39711):remove \r|\n|\r\n of module name.

- main/plugins/org.talend.rcp.branding.tos/content/root.xhtml
https://jira.talendforge.org/browse/TUP-18946
depend on https://github.com/Talend/tcommon-studio-se/pull/1294
> feat(TUP-18946): add advertisement for Cloud product

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/AbstractComponent.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/ComponentFilesNaming.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobContextLoadComponent.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/AbstractStatsLogsComponent.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/TalendEditorPaletteFactoryTest.java
* Unify jet filenames calculation
This PR Depends on PR https://github.com/Talend/tcommon-studio-se/pull/1296
Those PRs should be merged together.
> feat(TCOMP-683): tacokit runtime integration

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
> fix(TUP-19019):TUJ broken since TUP-18265 tELTSAPMAP component does not

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
* MDM components
* CRM components
* tWebService
For issue https://jira.talendforge.org/browse/TDI-39718
> feat(TDI-39718): Upgrade to CXF 3.1.14

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/SQSClient.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Amazon/EMRClient.javajet
This commit totally depends on https://github.com/Talend/tcommon-studio-se/pull/1303, see more details there.
> feat(TBD-5415) Insert user agent for GCS in jets3t http client

- main/plugins/org.talend.designer.core.generic/plugin.xml
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/Dataprep701MigrationTask.java
https://jira.talendforge.org/browse/TDI-37747
> fix(TDI-37747):tDatasetOutput cannot retrieve Dataset name.

- main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_main.javajet
https://jira.talendforge.org/browse/TDI-39732
> fix(TDI-39732):deactivate system.out when log4j enabled.

- main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet
https://jira.talendforge.org/browse/TDI-39761
If the server return 202 HTTP code, it doesn't generate exception anymore.
> fix(TDI-39761) : SC_ACCEPTED doesn't generate exception anymore.

- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java
TUP-19013 Studio hangs/freezes after clicking cancel while job is being built
https://jira.talendforge.org/browse/TUP-19013
> TUP-19013 Studio hangs/freezes after clicking cancel while job is being

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
* Fix password deserialization for tacokit components
Warning! this is a hack and must be fixed in a correct way in future releases!
> feat(TCOMP-683): runtime integration

- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
https://jira.talendforge.org/browse/TDI-33014
> fix(TDI-33014):remove the urlpath of two missing jar tWebService.

- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputRaw/tFileOutputRaw_main.javajet
https://jira.talendforge.org/browse/TDI-33511
> fix(TDI-33511):tFileOutputRow handle types other than string stream.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
> TDQ-14232 Always ask user to change the "Property" to built-in mode of

- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveCreate/tGoogleDriveCreate_main.javajet
https://jira.talendforge.org/browse/TDI-39808
Sub folder can be  created in any folder.
> fix(TDI-39808) : Sub-folder can be created in any folder.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/assist/TalendEditorComponentProposalProvider.java
TUP-18989 Components quick find from job designer is not working
https://jira.talendforge.org/browse/TUP-18989
> TUP-18989 Components quick find from job designer is not working

- main/plugins/org.talend.designer.core/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractGuessSchemaProcess.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
https://jira.talendforge.org/browse/TCOMP-691
> task(TCOMP-691): create context menu for Tacokit node in repository

- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
https://jira.talendforge.org/browse/TDI-39480
> feat(TDI-39480):AWS tS3put support stream upload.

- main/plugins/org.talend.designer.components.localprovider/components/tExtractRegexFields/tExtractRegexFields_main.javajet
https://jira.talendforge.org/browse/TDI-31109
> fix(TDI-31109):Exception info appears in wrong component.

- main/plugins/org.talend.designer.components.localprovider/components/tGoogleDriveCreate/tGoogleDriveCreate_main.javajet
https://jira.talendforge.org/browse/TDI-39808
Sub folder can be  created in any folder.
> fix(TDI-39808):  tGoogleDriveCreate create subfolder in root

- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
https://jira.talendforge.org/browse/TDI-39841
> fix(TDI-39841):tS3put should only evaluated Key once.

- main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_java.xml
https://jira.talendforge.org/browse/TDI-39212
> fix(TDI-39212):fix the issue of missing jar.

- main/plugins/org.talend.repository/src/main/java/messages.properties
https://jira.talendforge.org/browse/TUP-19188
> fix(TUP-19188): Improve English messages on the "Network Issue Occured" dialog

- main/plugins/org.talend.repository/src/main/java/messages.properties
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java
https://jira.talendforge.org/browse/TUP-19123
> feat(TUP-19123): Manage connections: improvements (2)

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionCreateCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionDeleteCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionReconnectCommand.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/DeleteNodeContainerCommand.java
TUP-18826 Need a notification mecanism when a connection between components is added/removed
https://jira.talendforge.org/browse/TUP-18826
> Kjwang/feat(tup 18826)need a notification mecanism when a connection between components is added/removed 2

- main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_java.xml
https://jira.talendforge.org/browse/TDI-39872
> fix(TDI-39872):Upgrade the aws-java-sdk.jar tSQSQueueAttribute

- main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
This reverts commit 11ff8135b4fcc1c16d53e6e328277e8230a3b3d7.
https://jira.talendforge.org/browse/TDI-39423
> Revert "fix(TDI-39423):Amend the escape method. (#1630)"

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
> fix(TBD-6075): change jar http versions (#1840) on 6.5

- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
Cherry-pick from change on 6.4
> fix(TBD-6075): change jar http versions (#1840) on master

- main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet
https://jira.talendforge.org/browse/TDI-39876
Upload a file using HTTP/POST with 'using redirection' option disabled display an exception if 202 status code is returned.
the behavior is the same as 200 status code.
> fix(TDI-39876) : report the TDI39761 correction when no redirection

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/ComponentsFactory.java
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/components/model/UserComponentsProvider.java
- main/plugins/org.talend.designer.components.exchange/src/main/java/org/talend/designer/components/exchange/ExchangeComponentsProvider.java
* Implement methods required for guess schema feature
Depends on https://github.com/Talend/tcommon-studio-se/pull/1369
> feat(TCOMP-683): Guess schema

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
> feat(TDQ-14297): modify code to make dynchornized comboList support

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_process_data_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_process_data_end.javajet
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java
- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/flowvariables/runtime/FlowVariablesWriter.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
- main/plugins/org.talend.libraries.custom/pom.xml
https://jira.talendforge.org/browse/TDI-39741
Related PR :
* tcommon-studio-se : https://github.com/Talend/tcommon-studio-se/pull/1350
* components: https://github.com/Talend/components/pull/1107
> feat(TDI-39741): add data process parts to codegen

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_begin.javajet
https://jira.talendforge.org/browse/TDI-36358
> fix(TDI-36358):tAmazonEMRManage has no error info when terminated with error

- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/dbstructure/SessionTreeNodeUtils.java
- main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/repository/utility/EMFRepositoryNodeManager.java
> feat(TUP-18755):fix TUP-19241 can't use SQL Builder to execute sql queries

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/TextController.java
depends on https://github.com/Talend/tcommon-studio-se/pull/1381
> adding IAdvancedElementParameter support in Text controller

- main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
For JIRA: https://jira.talendforge.org/browse/TDI-39900
- support expression context/globalMap/.. for `DIRECT`.
- `DIRECT` boolean value can be surrounded by `""`
> fix(TDI-39900): add context support on the tOracleBulkExec on the load option

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
fix(TUP-19162)error pop up when open the HL7 job exported from lower version
https://jira.talendforge.org/browse/TUP-19162
> fix(TUP-19162)error pop up when open the HL7 job exported from lower

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
Upgrade to CXF 3.2.1 for JIRA:
https://jira.talendforge.org/browse/TDI-39827
> feat(TDI-39827): Upgrade to CXF 3.2.1

- main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
* Use correct method from new library to change working directory
* User correct method from new library to get currect directory
> fix(TDI-39937): Fix compile errors ftpGet and ftpPut

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tHiveIn/tHiveIn_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/SQSClient.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Amazon/EMRClient.javajet
https://jira.talendforge.org/browse/TDI-39602
> feat(TDI-39602):Use the new tracker implementation for AWS / google

- main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
https://jira.talendforge.org/browse/TDI-39602
> fix(TDI-39602):fix the generate error tGSCopy

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRListInstances/tAmazonEMRListInstances_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRResize/tAmazonEMRResize_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/tSQSConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageChangeVisibility/tSQSMessageChangeVisibility_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageDelete/tSQSMessageDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueCreate/tSQSQueueCreate_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueDelete/tSQSQueueDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueList/tSQSQueueList_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSQSQueuePurge/tSQSQueuePurge_java.xml
https://jira.talendforge.org/browse/TDI-37863
> feat(TDI-37863):Upgrade aws-java-driver to 269.

- main/plugins/org.talend.designer.components.localprovider/components/tHiveIn/tHiveIn_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Hive/GetDataprocConnection.javajet
[#1881](https://github.com/Talend/tdi-studio-se/pull/1881)
> fix(TBD-5317): consistent field separator

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
Use the JAR existing on https://talend-update.talend.com/nexus instead of local studio folder.
> TMDM-11782 Can't download jars when run mdm demo jobs

- main/plugins/org.talend.designer.components.localprovider/components/tNetezzaNzLoad/tNetezzaNzLoad_begin.javajet
https://jira.talendforge.org/browse/TDI-39395
> fix(TDI-39395): tNetezzaNZload. Fix actualLogFilePath variable for context or global values

- main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet
* In every ftp component with 'move to dir' property add additional check
* Throw an exception when remote dir doesn't exist or cwd failed for any reason
* Fix nb line for ftps in ftpRename
> fix(TDI-39961): Add check if remote directory exist ftps

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_begin.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_end.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_process_data_begin.javajet
https://jira.talendforge.org/browse/TDI-39957
> fix(TDI-39957): fix variables redeclaration

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/app_mapping.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_java.xml
https://jira.talendforge.org/browse/TDI-38023
> fix(TDI-38023):compile error when setting applications with list.

- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_main.javajet
* Add possibility to check files in another directories
> fix(TDI-39963): Fix wrong result of tFileExist for ftps file

- main/plugins/org.talend.designer.components.libs/libs_src/adal4j/src/samples/public-client-app-sample/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/adal4j/src/samples/web-app-samples-for-adal4j/pom.xml
https://jira.talendforge.org/browse/TDI-39975
pom.xml are valid
> fix(TDI-39975) : fix invalid pom.xml in adal4j sample

- main/plugins/org.talend.designer.components.localprovider/components/tSybaseIQBulkExec/tSybaseIQBulkExec_begin_Load.javajet
https://jira.talendforge.org/browse/TDI-38647
Is checkbox not cheked, the file must be accessible by the server "FROM '/path/to/file..'"
If checked send the file throught the netework "USING CLIENT FILE '/path/to/file....'"
> fix(TDI-39915) : React to isClientFile checkbox

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewComponentFrameworkMigrationTask.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewJDBCMigrationTask.java
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java
using repository metadata after migration
> fix(TUP-19306):[bug] migration: all fields are writable for tJDBCInput

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
https://jira.talendforge.org/browse/TUP-3237
> fix(TUP-3237)Clear button too small

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java
fix(TUP-19272):If did not set the schema at the first time,can't set schema for output of tmap
https://jira.talendforge.org/browse/TUP-19272
> fix(TUP-19272):If did not set the schema at the first time,can't set

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
- main/plugins/org.talend.designer.maven.job/src/main/java/org/talend/designer/maven/job/setting/project/initializer/MavenJobScriptsProjectSettingInitializer.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendProcessJavaProject.java
> TESB-20453:Changes for Single Maven Build: Routes

- main/plugins/org.talend.designer.dbmap/src/main/java/messages.properties
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/postgres/PostgresGenerationManager.java
- main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/problems/ProblemsAnalyser.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
- test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/postgres/PostgresGenerationManagerTest.java
> fix(TUP-19338):[TBD] Hive basic 8 (child 2) TUJ does not work properly

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildJobHandler.java
> fix(TUP-17555):Relevant Error Code Line Numbers

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_begin.javajet
https://jira.talendforge.org/browse/TDI-39999
> fix(TDI-39999):tAmazonEMRManager cannot customize AMI version.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/process/jobsettings/JobSettingsManagerTest.java
https://jira.talendforge.org/browse/TUP-19342
https://jira.talendforge.org/browse/TUP-19342
> fix(TUP-19342)Implicit context load from file behavior change

- main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jDBConnUtil.javajet
- main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet
https://jira.talendforge.org/browse/TDI-39968
> fix(TDI-39968):split the string in log.

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewComponentFrameworkMigrationTask.java
fix the NPE when import the jobs
NPE
> fix(TUP-19306): fix the NPE when import jobs

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SnowflakeConvertToUpperCaseMigrationTask.java
* Migration task for uncheck of convert to upper case property in
SnowflakeOutput component
> feat(TDI-39983): Case sensitivity SnowflakeOutput

- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_messages.properties
India region is absent from DI S3 components
India region is added and is in sync with Spark jobs available regions
> fix(TBD-6412): India Region in DI components

- main/plugins/org.talend.repository/plugin.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddSchemaDatePatternUseForImpalaTask.java
https://github.com/Talend/tdi-studio-se/pull/1955
> fix(TBD-6388): Add Migration Task for tImpalaOutput (#1955)

- main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet
In case of not-critical exception ftpclient doesn't enter passive mode
Even if exception occurs, ftpclient will still try to enter passive mode
https://jira.talendforge.org/browse/TDI-39923
> fix(TDI-39923): Enter passive mode after connection created

- main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_begin.javajet
https://jira.talendforge.org/browse/TDI-40057
> fix(TDI-40057):tAmazonEMRManager fails when enable debug.

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendProcessJavaProject.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
> fix(TUP-19494):Problem of synchronization of build job.

- main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
- main/plugins/org.talend.libraries.custom/pom.xml
> feat(TDI-40061): upgrade the daikon version

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
Export osgi bundle name is ***-jar-with-dependencies.jar
Export osgi bundle name is ***-bundle.jar
> TESB-20833: Improvement for OSGi bundle templates and target name

- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/AbstractComponentsUnifier.java
> fix(TUP-19443):Db unified throw exception when the studio path is in

- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/manager/UnifiedComponentsManager.java
> fix(TUP-19346):Remove tDBCDC, tDBCDCOuput, tDBInvaidRows and

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddSchemaDatePatternUseForImpalaTask.java
https://github.com/Talend/tdi-studio-se/pull/1955
> fix(TBD-6388): Add Migration Task for tImpalaOutput

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/OpenExistVersionProcessWizard.java
dependencies
https://jira.talendforge.org/browse/TUP-18925
Fixed the test cases didn't change version when their parent job changed
version in studio.
> fix(TUP-18925)ChangeVersion command doesn't upgrade the version of

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendWizardProjectsImportPage.java
https://jira.talendforge.org/browse/TUP-19372
https://jira.talendforge.org/browse/TUP-19372
> TUP-19372 Studio crashed after importing projects

- main/plugins/org.talend.designer.components.localprovider/components/tLDAPInput/tLDAPInput_begin.javajet
https://jira.talendforge.org/browse/TDI-39879
> fix(TDI-39879): change adding of binary attribute to context

- main/plugins/org.talend.designer.components.localprovider/components/tNetezzaNzLoad/tNetezzaNzLoad_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_java.xml
https://jira.talendforge.org/browse/TDI-39307
Add "required if" condition for import jars
> fix(TDI-39307): add 'required if' for jars import

- main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_main.javajet
https://jira.talendforge.org/browse/TDI-39285
Now temp table drop in finally block. 
> fix(TDI-39285): move dropping temp table to finally block

- main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
- main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
- main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
- main/plugins/org.talend.libraries.excel/pom.xml
* Remove main method
* Update deprecated method calls
* Add commons-lang
> fix(TDI-40125): Update talend excel library

- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommand.java
- test/plugins/org.talend.designer.unifiedcomponent.test/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommandTest.java
> fix(TUP-19475):Cannot select a repository schema on a tJDBCInput

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/JobErrorsChecker.java
At this moment we have NPE during Route generation in some cases. It leads to Route generation with missing classes.
> TESB-20453 NPE during Routes generation is fixed

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/utils/JobVersionUtils.java
the correct Artifact information in publish page.
> xlwang/fix(TUP-19547)Select job' old version to publish will not show

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/GenericTableUtils.java
> fix(TUP-19553):Can't use custom URI module to check JDBC conection

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendProcessJavaProject.java
TUP-19534
log4j level can work while building standard job.
> fix(TUP-19534):log4j level does not work as expected while building standard job.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/StatsAndLogsManager.java
https://jira.talendforge.org/browse/TDI-40155
https://jira.talendforge.org/browse/TDI-40155
> fix(TDI-40155): Stats&Log:can`t get correct data from stats&log tables when use JDBC

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importproject/ImportProjectHelper.java
https://jira.talendforge.org/browse/TUP-19402
> fix(TUP-19402)Can not import in project folder items.

- main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/dialog/PropertySetDialog.java
> fix(TUP-19619):new Automap function should be EE only

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/GenericProcessProvider.java
https://jira.talendforge.org/browse/TUP-19615
> fix(TUP-19615): Libraries cache is not recreated during Studio startup in case of path to Studio contains special symbols (for example, "!")

- main/plugins/org.talend.repository/plugin.xml
https://jira.talendforge.org/browse/TDI-34082
> fix(TDI-34082):correct mistake in plugin.xml

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/action/GenericNodeActionProvier.java
> fix(TUP-19446):SNOWFLAKE connection in metadata repository

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewJDBCMigrationTask.properties
https://jira.talendforge.org/browse/TDI-40183
https://jira.talendforge.org/browse/TDI-40183
> fix(TDI-40183): Migration for tJDBCOutput:the value for field option in advance setting is wrong

- main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/read_by_jsonpath_process.javajet
https://jira.talendforge.org/browse/TDI-34082
> fix(TDI-34082):use Node instead of Iprocess.

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/utils/ComponentsUtils.java
> fix(TUP-19661):tJDBCInput Guess Query not work well when use oracle

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
> Don't popup dialog for junit since it will block the junit

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JavaJobScriptsExportWSWizardPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/handler/BuildOSGiBundleHandler.java
TESB-21445 NPE error when request a service with saml
Fixed by adding context in service with saml.
> TESB-21445 NPE error when request a service with saml

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
- test/plugins/org.talend.designer.unifiedcomponent.test/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommandTest.java
> fix(TUP-19682):tJDBC --> Can't switch to Snowflake database.

- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveOutputBulkExec/tSalesforceWaveOutputBulkExec_java.xml
https://jira.talendforge.org/browse/TDI-40177
Upgrade salesforce API version
Upgrade api to latest one 42.0
> feat(TDI-40177): Update salesforce API to latest version 42

- main/plugins/org.talend.designer.maven.job/resources/templates/osgi/pom_job_template.xml
TESB-21454: Updated maven-bundle-plugin version for OSGi type export
To fix OSGi type with maven offline issue.
> TESB-21454: Updated maven-bundle-plugin version for OSGi type export

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
main class commonpro.tjava_0_1.tjava
https://jira.talendforge.org/browse/TUP-19695
> fix(TUP-19695)run task failed with error :Error: Could not find or load

- main/plugins/org.talend.designer.components.localprovider/components/tNetezzaNzLoad/tNetezzaNzLoad_begin.javajet
Control file not working due to wrong command line argument
Command line argument fixed
> fix(TDI-38944): Fix wrong control file argument

- main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
https://jira.talendforge.org/browse/TDI-40206
tFTPFileProperties enter binary mode
> fix(TDI-40206): Enter binary mode ftps ftpFileProperties

- main/plugins/org.talend.designer.core/src/main/java/messages.properties
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/AbstractJobSettingsPage.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> fix(TUP-19692):Bad performance when do updating stats&logs setting to

- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
For https://jira.talendforge.org/browse/TDI-40129
Upgrade CXF version 
Upgrade CXF from 3.2.1 to 3.2.2
> feat(TDI-40129) Upgrade to CXF 3.2.2

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
> fix(TUP-19758) generate code even if the jars are missing

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
Match Rule key table is not support filter function by now.
Make it support filter function
It is a Feature.
No
> feat(TDQ-14700): Support filter on Survivorship function column of match rule key table

- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/set_kms.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
https://jira.talendforge.org/browse/TDI-40201
https://jira.talendforge.org/browse/TDI-40201
> fix(TDI-40201): ts3put is slower than expected

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/OutputConnectorCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/PartitionMapperConnectorCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/ProcessorConnectorCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/StandAloneConnectorCreator.java
sets input/output connector type correctly
> fix: set explicitly connector type by setInput() method

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java
> fix(TUP-19421):Missing connection info when D&D tJDBCSCDELT and

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet
For JIRA: https://jira.talendforge.org/browse/TDI-40217
wrong code caused compiler error
Fix the issue
> fix(TDI-40217) tMSSqlOutput component fails while writing exponential

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/ui/GenericConnWizard.java
> fix(TUP-19743):TDS Connection settings in metadata : export as context

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendGridLayer.java
https://jira.talendforge.org/browse/TUP-19064
> TUP-19064 Studio consuming CPU after opening a Job (no other activity)

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
https://jira.talendforge.org/browse/TMDM-11903
- CXF using 3.2.1
- WSS4J using 2.2.0
- CXF from 3.2.1 to 3.2.2 
- WSS4J from 2.2.0 to 2.2.1 
> TMDM-11903 Upgrade CXF to 3.2.2, WSS4J to 2.2.1 for MDM components

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/Locales.java
> fix: add locales class used by help

- main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_messages.properties
- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_messages.properties
to the CMK
https://jira.talendforge.org/browse/TDI-40233
> fix(TDI-40233):Change the property name of "Server side encryption ID"

- test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/java/TalendProcessJavaProjectTest.java
https://jira.talendforge.org/browse/TUP-19803
> TUP-19803 Fix the the junits on master

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/migration/TaCoKitMigrationManager.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
https://jira.talendforge.org/browse/TUP-19738
> item(TUP-19738): Tacokit migration API not wired into the studio

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java
> upgrade TaCoKit version to 0.0.3

- main/plugins/org.talend.designer.components.localprovider/components/tWaitForFile/tWaitForFile_begin.javajet
https://jira.talendforge.org/browse/TDI-40157
Component trigger action on delete mode
> fix(TDI-40157): remove overwriting of origin files list

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/BuildJobManager.java
tests"
https://jira.talendforge.org/browse/TUP-19726
> fix(TUP-19726)publish job with testcase failed if check on "execute

- main/plugins/org.talend.designer.components.localprovider/pom.xml
https://jira.talendforge.org/browse/TDI-39302
> fix(TDI-39302):Eliminate useless plugin in pom of localprovider.

- main/plugins/org.talend.designer.components.localprovider/components/tMDMBulkLoad/tMDMBulkLoad_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_main.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_begin.javajet
https://jira.talendforge.org/browse/TPS-2299
> TPS-2299 [6.4.1] transaction does not commit when multiple tMDMOutput used in same subjob (TMDM-11629)

- main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/action/GenericAction.java
> fix(TUP-5360):Retrieve Salesforce Modules option is missing

- main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_begin.javajet
- main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_end.javajet
https://jira.talendforge.org/browse/TDI-33063
> fix(TDI-33063):Wrong cid when tMonConnection exist.

- main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_begin.javajet
https://jira.talendforge.org/browse/TDI-32006
> fix(TDI-32006): GlobalMap variable was not put sometime.

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/build/TestProcessor.java
> fix(TUP-19687) improve perf of gen pom

- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHOutput/tSQLDWHOutput_begin.javajet
https://jira.talendforge.org/browse/TDI-40137
> fix(TDI-30137):tSQLDWHOutput cannot create table.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/wizards/OpenExistVersionProcessWizard.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AbstractVersionManagementProjectSettingPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/VersionManagementPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
> fix(TUP-19694):testcase version changed when open job as another version

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/MavenJavaProcessor.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> fix(TUP-19687): fix testcase issue.

- main/plugins/org.talend.designer.components.localprovider/components/tWaitForFile/tWaitForFile_begin.javajet
https://jira.talendforge.org/browse/TDI-40157
The component was updated. Now it's work well when file created with same names (https://jira.talendforge.org/browse/TDI-35382)
> fix(TDI-40157): problems with same name files

- main/plugins/org.talend.designer.codegen/jet_stub/generic/component_util_indexedrecord_to_rowstruct.javajet
> fix(TUP-19526):Dynamic schema with generic JDBCconnection fails when job

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/ImportProjectAsWizardPage.java
- main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendWizardProjectsImportPage.java
> fix(TUP-19419) fix project import on mac

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
> fix a NPE problem

- main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ButtonController.java
button with no any input  connection parameters
> fit(TUP-19789):NPE error occurred in error log when check "Test connect"

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/maven/listener/ProcessChangeListener.java
> fix(TESB-21577): add compatible options.

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/NodeQueryCheckUtil.java
https://jira.talendforge.org/browse/TUP-19691 java.lang.StackOverflowException when job is run
Job can run if sql query too long now
> fix(TUP-19691):java.lang.StackOverflowException when job is run.

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
Don't use the adjuster to create the pom file
> fix(TUP-18552) fix classpath adjuster

- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet
- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin.javajet
- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/mvn/Mvn.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/ComponentService.java
side note: will require to upgrade tacokit to v0.0.4 (in snapshot for now)
> starting to wire beam into the studio

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/build/StandardJobStandaloneBuildProvider.java
No relation for service, the stand zip type should not be shown in the deployment tab
Add realtion for service
> TESB-21507: Add realtion for service

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java
> upgrade tacokit version to 0.0.4

- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/assembly_job_template.xml
- main/plugins/org.talend.designer.maven.job/resources/templates/standalone/pom_job_template.xml
> TESB-21528 Missing config folder is added

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeValuesFromRepository.java
> fix(TUP-19788):The JDBC connection info cannot be sync to tSqoop*

- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHInput/tSQLDWHInput_java.xml
https://jira.talendforge.org/browse/TDI-40276
https://jira.talendforge.org/browse/TDI-40276
> fix(TDI-40276): Missing talend_DB_mssqlUtil.jar in 651, 652, 701

- main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_begin_for_processor.javajet
- main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_end.javajet
- main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_end_body.javajet
- main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_end_head.javajet
- main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_end_tail.javajet
- main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_finally.javajet
- main/plugins/org.talend.sdk.component.studio-integration/components/tTaCoKitGuessSchema/tTaCoKitGuessSchema_main.javajet
- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin.javajet
- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_inputs.javajet
- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_outputs.javajet
- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_end_head.javajet
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/enums/ETaCoKitComponentType.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/model/ComponentModelSpy.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/OutputConnectorCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/PartitionMapperConnectorCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/ProcessorConnectorCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/StandAloneConnectorCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/TaCoKitNodeConnector.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingsCreator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/TaCoKitElementParameter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/GuessSchemaRunnable.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/GuessSchemaSelectionAdapter.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/TaCoKitGuessSchemaProcess.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/wizard/TaCoKitConfigurationWizard.java
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
https://jira.talendforge.org/browse/TUP-19734
> item(TUP-19734): Support tacokit multischema auto fill

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/TalendJavaProjectManager.java
https://jira.talendforge.org/browse/TUP-19782
> feat(TUP-19782)Add filter on the pom synchronization

- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenInit.java
- main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendJavaEditor.java
Full synchronization of codegen was done at every start of studio (and commandline)
Editor was also not linked at the good time to the file.
Right now the codegen will not be done at all in studio mode (to only generate the code of files we need).
Same change might be done also in commandline (but too big change for commandline just before a release)
> fix(TUP-19045) Fix issues of codegen and editor

- main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
> fix: fix process init for beam processors

- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
For https://jira.talendforge.org/browse/TDI-40129
Upgrade to CXF 3.2.3
> (TDI-40129) Upgrade to CXF 3.2.4

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
routines were not added as dependency if shade was not used (not same as old code)
Add back the routine in the libjars as long as shade is not used (since shade contains the routines)
> fix(TUP-19888) add routines if shade is not used

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/IUnifiedComponentService.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/UnifiedComponentUtil.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/unifiedcomponent/unifier/AbstractComponentsUnifier.java
- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/unifiedcomponent/unifier/IComponentsUnifier.java
- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/UnifiedComponentService.java
- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/component/UnifiedObject.java
- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommand.java
- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/manager/UnifiedComponentsManager.java
- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/jdbc/unifier.json
- main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/snowflake/unifier.json
- test/plugins/org.talend.designer.unifiedcomponent.test/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommandTest.java
> fix(TUP-19802):For DB Unified, Fixed schema for database error is added

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/GuessSchemaSelectionAdapter.java
> fix guess schema propagation for tacokit

- main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
https://jira.talendforge.org/browse/TUP-19800
> fix(TUP-19800)tNetezzaNZload --> "Data file" doesn't work on 701

- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/listener/PatternValidator.java
- main/plugins/org.talend.sdk.component.studio-integration/src/test/java/org/talend/sdk/component/studio/model/parameter/listener/PatternValidatorTest.java
patterns are validated with java regex in properties
patterns are validated with js regex to unify the API with the web (where it is hard to use java style today)
> chore(tacokit) ensure to use a unified regex syntax between the web and the studio for tacokit

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
fix to avoid the issue TPSVC-4826
> fix(TUP-19904) fix jobserver issue for MR HDI

- main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ProjectRefSettingPage.java
https://jira.talendforge.org/browse/TUP-19913
> fix(TUP-19913)NPE pop up if first do action on Project

- main/plugins/org.talend.designer.components.localprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.localprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
https://jira.talendforge.org/browse/TMDM-11860
Upgrade CXF to 3.2.4
> TMDM-11860 Upgrade to CXF 3.2.4

- main/plugins/org.talend.sdk.component.studio-integration/pom.xml
- main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/GAV.java
tacokit 0.0.4 is used
tacokit 0.0.5 is active
To be merges also : 
https://github.com/Talend/tcommon-studio-se/pull/1583
https://github.com/Talend/tcommon-studio-ee/pull/662
> chore(tacokit) upgrading tacokit to 0.0.5

- main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
https://jira.talendforge.org/browse/TDI-40254
> fix(TDI-40254):clean the buffer of tS3put.

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJobUtil.java
ESB Studio Unit test fails with an NPE
Unit test pass
- [*] The commit message follows Talend standard
- [*] Bugfix
- [*] Code style update (formatting, local variables)
- [*] No
the only change is line 153 , others are formatting.
> fix(TESB-21700) : fixed NPE that cause test to fail

- main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHBulkExec/tSQLDWHBulkExec_begin.javajet
For JIRA: https://jira.talendforge.org/browse/TDI-40333
- password should be encrypted during code generate
- remove some code when `isEnabledExtTableOptions` is false
> fix(TDI-40333): For tSQLDWHBulkExec, the password field is not encrypted in the generated java code

- test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/TalendEditorPaletteFactoryTest.java
update junit for TalendEditorPaletteFactory
> update junit for TalendEditorPaletteFactory

- main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
Routines "myroutine" has compile errors.
> fix(TUP-19945):first generate failed with error:ProcessorException:
